Description of cat
Home > GISMO > core > dev > @NewCorrelation > cat.m
cat
PURPOSE
c = cat(c1,c2,c3,...)
SYNOPSIS
function c = cat(varargin)
DESCRIPTION
 c = cat(c1,c2,c3,...)
 Concatenate the traces in two or more correlation objects. c1,c2,c3,...
 will be combined in the order listed. Only the four data descriptor
 fields (TRIG,START,WAVES,FS) will be filled in the output object. There
 is not enough information to fill in the CORRELATION, LAG, STAT, LINK, or
 CLUSTER fields. These fields will be empty. Data in c1,c2,c3,... must
 have the same number of samples and sampling frequency.
CROSS-REFERENCE INFORMATION
This function calls:
cat c = cat(c1,c2,c3,...)
NewCorrelation
cat c = cat(c1,c2,c3,...)
This function is called by:
dd_collate dd_collate('event.dat')
dd_make_scp DD_MAKE_SCP Create a draft control file for the correlation process
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
ie_readchans IE_READCHANS Read and parse station/channel list from file
antelope READ_CATALOG.ANTELOPE load events from a CSS3.0 database using Antelope.
cat c = cat(c1,c2,c3,...)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
interferogram C = INTERFEROGRAM(C)
getval Function to extract a cell array from an
NewCorrelation
cat c = cat(c1,c2,c3,...)
getval Function to extract a cell array from an
interferogram C = INTERFEROGRAM(C)
SUBFUNCTIONS
function c = ensureType(c)
SOURCE CODE
function c = cat(varargin)
   % c = cat(c1,c2,c3,...)
   % Concatenate the traces in two or more correlation objects. c1,c2,c3,...
   % will be combined in the order listed. Only the four data descriptor
   % fields (TRIG,START,WAVES,FS) will be filled in the output object. There
   % is not enough information to fill in the CORRELATION, LAG, STAT, LINK, or
   % CLUSTER fields. These fields will be empty. Data in c1,c2,c3,... must
   % have the same number of samples and sampling frequency.
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   narginchk(2,inf);
   varargin{1} = ensureType(varargin{1});
   expectedSamplerate = varargin{1}.samplerate;
   expectedDatalength = varargin{1}.data_length;
   % make sure that the inputs are compatible
   for i = 2:nargin
      varargin{i} = ensureType(varargin{i});
      assert(varargin{i}.samplerate == expectedSamplerate,...
         'All inputs must have the same sampling frequency');
      assert(varargin{i}.data_length == expectedDatalength,...
         'All inputs must have the same trace length');
   end
   c = varargin{1};
   c.corrmatrix = [];
   c.lags = [];
   c.stat = [];
   c.link = [];
   c.clust = [];
   for i = 2:nargin
      cin = varargin{i};
      c.traces = cat(1,c.traces,cin.traces);
      c.trig = cat(1,c.trig,cin.trig);
   end
end
function c = ensureType(c)
   if ~isa(c,'NewCorrelation')
      c = NewCorrelation(c); % c must be a correlation or be convertable into one.
   end
end