Description of corrplot
Home > GISMO > core > dev > @NewCorrelation > corrplot.m
corrplot
PURPOSE
corrplot plot the correlation matrix
SYNOPSIS
function corrplot(c)
DESCRIPTION
corrplot   plot the correlation matrix
 Called internally by correlation/plot to plot correlation matrix.
CROSS-REFERENCE INFORMATION
This function calls:
colormap C = COLORMAP(C)
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
load Purpose:
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
get GET Get waveform properties
set SET Set properties for waveform object(s)
colormap colormap apply a colormap to the cross-correlation
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function corrplot(c)
   %corrplot   plot the correlation matrix
   % Called internally by correlation/plot to plot correlation matrix.
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   % PREP PLOT
   figure('Color','w','Position',[50 50 600 500]);
   set(gcf,'DefaultAxesFontSize',14);
   imagesc(c.corrmatrix);
   title('Maximum correlation coefficient');
   % ADD DATES TO AXES
   n = length(c.trig);
   ticvalues = 1:round(n/25):n;
   set(gca,'XTick',ticvalues);
   set(gca,'YTick',ticvalues);
   yt = get(gca,'YTick');
   set(gca,'YTickLabel',datestr(c.trig(yt),'yyyy-mm-dd HH:MM'),'FontSize',6);
   % DRESS UP THE FIGURE
   caxis([0 1]);
   cmap = load('colormap_corr.txt');
   colormap(cmap);
   colorbar;
   xlabel('Event number');
   ylabel('Event date');
   %PRINT OUT FIGURE
   set(gcf, 'paperorientation', 'portrait');
   set(gcf, 'paperposition', [1.25 2.5 6 6] );
end