Description of eventplot
Home > GISMO > core > dev > @NewCorrelation > eventplot.m
eventplot
PURPOSE
Private method. See ../plot for details.
SYNOPSIS
function eventplot(c,scale,howmany)
DESCRIPTION
 Private method. See ../plot for details.
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
subset CATALOG.SUBSET Create a new catalogObject by subsetting based
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
stack c = STACK(c)
subset c = SUBSET(c,INDEX)
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
min MIN Smallest value of a waveform.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
stack STACK stacks data from array of waveforms
NewCorrelation
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
stack c = STACK(c)
subset c = SUBSET(c,INDEX)
plot plot plots a SeismicTrace
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function eventplot(c,scale,howmany)
   % Private method. See ../plot for details.
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   % if isempty(get(c,'LINK'))
   %     error('LINK field must be filled in input object');
   % end;
   if isempty(c.corrmatrix)
      error('CORR field must be filled in input object');
   end;
   if isempty(c.clust)
      error('CLUST field must be filled in input object');
   end;
   if ~isempty(c.lags)
      warning('Time corrections from LAG field have not been applied to traces. ADJUSTTRIG may be necessary');
   end;
   % TEST FOR NUMBER OF CLUSTERS
   if (howmany > max(c.clust))
      error(['There are only ' num2str(max(c.clust)) ' clusters in this set of traces']);
   end
   % FIND CLUSTERS AND STACK TRACES
   c1 = NewCorrelation;   % get new correlation object without correlation info
   c1.traces = c.traces;
   c1.trig = c.trig;
   for i = howmany: -1 : 1
      index{i} = find(c,'CLU',i);
      ntraces(i) = length(index{i});
      c1 = stack(c1,index{i});
   end
   % MAKE PLOT OF STACKS
   c1 = subset(c1, (length(c1.trig)-howmany+1):length(c1.trig) );
   plot(c1,'wig',scale);
   set(gcf,'Position',[50 500 850 300]);
   Xlim = get(gca,'Xlim');
   for i = 1:length(index)
      text(Xlim(1),i-0.3,['  #' num2str(i) ' (' num2str(ntraces(i)) ' traces)'],'HorizontalAlignment','Left');
   end
   % PLOT EVENTS VS. DATE
   figure('Color','w','Position',[50 92 850 250]);
   xleft = min(c.trig) - 0.05*(max(c.trig)-min(c.trig));
   xright = max(c.trig) + 0.05*(max(c.trig)-min(c.trig));
   box on; hold on;
   for i = 1:length(ntraces)
      plot([xleft xright],[i i],'k:');
      plot(c.trig(index{i}),i*ones(size(index{i})),'ko','MarkerFaceColor',[.5 .5 1]);
      text(xleft,i-0.3,['  #' num2str(i)],'HorizontalAlignment','Left');
   end
   set(gca,'YTick',[]);
   set(gca,'YDir','reverse');
   xlabel('Date');
   ylabel('Cluster');
   datetick('x');
   axis([xleft xright 0 length(ntraces)+1]);
   %PRINT OUT FIGURE
   set(gcf, 'paperorientation', 'portrait');
   set(gcf, 'paperposition', [.25 .25 8 10.5] );
   % print(gcf, '-depsc2', 'FIG.ps')
end