Description of getval
Home > GISMO > core > dev > @NewCorrelation > getval.m
getval
PURPOSE
Function to extract a cell array from an
SYNOPSIS
function A = getval(OBJ,PROP)
DESCRIPTION
 Function to extract a cell array from an
 object and convert it into an array of values.
 Basically it applies the {} operator to all
 values in the array.
 NOTE: This routine is only valid for properties that returns a single
 value per waveform.
CROSS-REFERENCE INFORMATION
This function calls:
cat c = cat(c1,c2,c3,...)
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
cat c = cat(c1,c2,c3,...)
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
NewCorrelation
SOURCE CODE
function A = getval(OBJ,PROP)
   % Function to extract a cell array from an
   % object and convert it into an array of values.
   % Basically it applies the {} operator to all
   % values in the array.
   %
   % NOTE: This routine is only valid for properties that returns a single
   % value per waveform.
   %
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   A = [];
   Ao = get(OBJ,PROP);
   for i = 1:length(Ao)
      A = cat(1,A,Ao{i});
   end;
   %A = A';
end