Description of hilbert
Home > GISMO > core > dev > @NewCorrelation > hilbert.m
hilbert
PURPOSE
HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
SYNOPSIS
function c = hilbert(c,n)
DESCRIPTION
HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
   waveform = hilbert(waveform)
   waveform = hilbert(waveform, N);
 This function does not return the complete (complex) hilbert transform,
 but rather the absolutely value of the transform typically used in
 seismology. To keep the imaginary values, use the built-in hilbert
 transform.
 Be careful if cross correlating the hilbert transforms of waveforms.
 Becuase the nilbert transformed data is not oscillatory around zero in
 the traditional waveform sense, unexpected behaviors can result.
 Caveat Emptor!
 See HILBERT for the meaning of "N"
CROSS-REFERENCE INFORMATION
This function calls:
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
This function is called by:
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
NewCorrelation
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
TraceData
testWaveform
SOURCE CODE
function c = hilbert(c,n)
   %HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
   %   waveform = hilbert(waveform)
   %   waveform = hilbert(waveform, N);
   %
   % This function does not return the complete (complex) hilbert transform,
   % but rather the absolutely value of the transform typically used in
   % seismology. To keep the imaginary values, use the built-in hilbert
   % transform.
   %
   % Be careful if cross correlating the hilbert transforms of waveforms.
   % Becuase the nilbert transformed data is not oscillatory around zero in
   % the traditional waveform sense, unexpected behaviors can result.
   % Caveat Emptor!
   %
   % See HILBERT for the meaning of "N"
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   if exist('n','var'),
      c.traces = hilbert(c.traces,n);
   else
      c.traces = hilbert(c.traces);
   end
end