Description of statplot
Home > GISMO > core > dev > @NewCorrelation > statplot.m
statplot
PURPOSE
Private method. See ../plot for details.
SYNOPSIS
function statplot(c)
DESCRIPTION
 Private method. See ../plot for details.
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
abs ABS Absolute value for the waveform object
max MIN Largest value of a waveform.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
plot plot plots a SeismicTrace
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function statplot(c)
   % Private method. See ../plot for details.
   % Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   Rmean  = c.stat(:,1);
   Rrmshi = c.stat(:,2);
   Rrmslo = c.stat(:,3);
   T      = c.stat(:,4);
   Trms   = c.stat(:,5);
   % PLOT RESULTS
   figure('Color','w','Position',[50 50 1000 600]);
   set(gcf,'DefaultLineLineWidth',1);
   set(gcf,'DefaultAxesFontSize',14);
   subplot(2,1,1);
   hold on; grid on; box on;
   ylabel('Time (s)');
   title('Best fit delay time and 1\sigma error');
   xfill = [ [1:length(T)]' ; [length(T):-1:1]' ];
   yfill = [T+Trms ; flipud(T-Trms)];
   fill(xfill,yfill,[.9 .9 .9]);
   plot(c.lags','b.','MarkerSize',5);
   plot(T,'ko-','LineWidth',2);
   xlim([1 length(T)]);
   maxval = 1.05*max(max(abs(c.lags)));
   ylim([-1*maxval maxval]);
   subplot(2,1,2);
   hold on; grid on; box on;
   xfill = [ [1:length(T)]' ; [length(T):-1:1]' ];
   yfill = [Rrmshi ; flipud(Rrmslo)];
   fill(xfill,yfill,[.9 .9 .9]);
   plot(Rmean,'ko-','LineWidth',2);
   xlabel('Trace no.');
   ylabel('Mean R');
   title('Mean max correlation and 1\sigma error');
   xlim([1 length(T)]);
   ylim([0 1]);
   % PREP PRINT OUT
   set(gcf, 'paperorientation', 'landscape');
   set(gcf, 'paperposition', [1 3 9 4] );
   print(gcf, '-depsc2', 'FIG_stat.ps');
end