Description of unifytracelengths
Home > GISMO > core > dev > @NewCorrelation > unifytracelengths.m
unifytracelengths
PURPOSE
unifytracelengths make all traces the same length (mode length)
SYNOPSIS
function c = unifytracelengths(c)
DESCRIPTION
unifytracelengths   make all traces the same length (mode length)
   C = unifytracelengths(C) if traces are of unequal lengths, then they
   are either trimmed or zero-padded to the same size.  The final length
   will be the mode length of the original set of traces.
   See also mode
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
This function is called by:
NewCorrelation
align align resample traces so that a sample falls exactly on trigger time.
conv conv convolve all traces with the final trace
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
stack c = STACK(c)
SOURCE CODE
function c = unifytracelengths(c)
   %unifytracelengths   make all traces the same length (mode length)
   %   C = unifytracelengths(C) if traces are of unequal lengths, then they
   %   are either trimmed or zero-padded to the same size.  The final length
   %   will be the mode length of the original set of traces.
   %
   %   See also mode
   if isempty(c.traces)
      return
   end
   lengths = [c.traces.nsamples];
   ideal = mode(lengths);
   tooShort = lengths < ideal;
   tooLong = lengths > ideal;
   for i = 1:numel(lengths)
      if tooShort(i)
         c.traces(i).data(ideal) = 0;
      elseif tooLong(i)
         c.traces(i).data = c.traces(i).data(1:ideal);
      end
   end
end