Description of display
Home > GISMO > core > @scnlobject > display.m
display
PURPOSE
DISPLAY - scnlobject display overloaded operator
SYNOPSIS
function display(scnl)
DESCRIPTION
DISPLAY - scnlobject display overloaded operator
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
get GET - Get correlation properties
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
disp DISP - scnl disp overloaded operator
get GET for the scnl object
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
This function is called by:
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
cookbook % The SCNLOBJECT cookbook
cookbook % Correlation object cookbook
drumplot DRUMPLOT the blueprint for drumplot objects in GISMO
testWaveform
SOURCE CODE
function display(scnl)
%DISPLAY - scnlobject display overloaded operator
% VERSION: 1.0 of scnlobject
% AUTHOR: Celso Reyes
% LASTUPDATE: 1/30/2007
if isequal(get(0,'FormatSpacing'),'compact')
    disp([inputname(1) ' =']);
    disp(scnl);
else
    disp(' ');
    disp([inputname(1) ' =']);
    disp(' ');
    disp(scnl);
end