Description of scnlobject
Home > GISMO > core > @scnlobject > scnlobject.m
scnlobject
PURPOSE
scnl (deprecated) : object that holds the stations, channel, network, and location for
SYNOPSIS
function SCNLs = scnlobject(stations, channels, networks, locations)
DESCRIPTION
 scnl (deprecated) : object that holds the stations, channel, network, and location for
 a seismic trace.  This object is used by the datasource object.
 SCNLOBJECT has been replaced by CHANNELTAG
 scnlobject is now just a backwards-compatibility wrapper for ChannelTag
 see ChannelTag
CROSS-REFERENCE INFORMATION
This function calls:
ChannelTag
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
This function is called by:
incomplete OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
stream2waveform OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
stream_matfile2waveform OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
demo_plutons
response_get_from_db RESPONSE_GET_FROM_DB Get instrument response from database.
response_get_from_polezero RESPONSE_GET_FROM_POLEZERO Create response structure from poles/zeros
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
arrivals2waveforms ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
cookbook % The SCNLOBJECT cookbook
query_file QUERY_FILE retrieves scnl, starttime and endtime information for all
getwaveform rsam.getwaveform() Get the waveform corresponding to the RSAM data
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
get GET Get waveform properties
sac2waveform SAC2WAVEFORM fill a waveform object from a sac header
sacload SACLOAD Load SAC files into MATLAB as waveform objects
testScnlobject
testWaveform
test_waveform_constructor test waveform creation
trloadcss_test % Main function to generate tests
waveform_antelope_test % Main function to generate tests
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
SUBFUNCTIONS
function scnl = singleSCNL(sta, cha, net, loc)
SOURCE CODE
function SCNLs = scnlobject(stations, channels, networks, locations)
   % scnl (deprecated) : object that holds the stations, channel, network, and location for
   % a seismic trace.  This object is used by the datasource object.
   % SCNLOBJECT has been replaced by CHANNELTAG
   %
   % scnlobject is now just a backwards-compatibility wrapper for ChannelTag
   %
   % see ChannelTag
   switch (nargin)
      case 0 %default
      case 4 %stations, channel, network, location
      case 3 %stations, channel, network
      case 2 %stations, channel
      case 1 %
         switch class(stations)
            case 'ChannelTag'
               for i = numel(stations): -1 : 1
                  SCNLs(i).tag = stations(i);
               end
               SCNLs = class(SCNLs,'scnlobject');
               return
            case 'scnlobject'
               SCNLs = stations;
               return
            otherwise
               tags = ChannelTag.array(stations);
               for i = numel(tags) : -1 : 1
                  SCNLs(i).tag = tags(i);
               end
               SCNLs = class(SCNLs,'scnlobject');
               return
         end
   end
   % initialize defaults
   defaultStation = '';
   defaultChannel = '';
   defaultNetwork = ''; %changed default from '--'
   defaultLocation = '';%changed default from '--'
   % assign default if it seems appropriate
   if ~exist('stations','var') || isempty(stations)
      stations = defaultStation;
   end
   if ~exist('channels','var') || isempty(channels)
      channels = defaultChannel;
   end
   if ~exist('networks','var') || isempty(networks)
      networks = defaultNetwork;
   end
   if ~exist('locations','var') || isempty(locations)
      locations = defaultLocation;
   end
   if  any(cellfun(@iscell,{networks,stations,locations,channels}))
      % we're building an array of SCNLs pass work off to ChannelTag
      all_tags = ChannelTag.array(networks,stations,locations,channels);
      for i = numel(all_tags) : -1 : 1
         SCNLs(i).tag = all_tags(i);
      end
      SCNLs = class(SCNLs,'scnlobject');
   else
      SCNLs = singleSCNL(stations, channels, networks, locations);
   end
end
function scnl = singleSCNL(sta, cha, net, loc)
   scnl.tag = ChannelTag(net, sta, loc, cha);
   scnl = class(scnl,'scnlobject');
end