Description of unique
Home > GISMO > core > @scnlobject > unique.m
unique
PURPOSE
UNIQUE return set of unique scnlobjects from an array
SYNOPSIS
function [B,I,J] = unique(A)
DESCRIPTION
UNIQUE return set of unique scnlobjects from an array
 [B I J] = unique(scnlobjectList)
   B is the unique (non duplicated) set of scnls
   I is the index, such that B = A(I) and A = B(J)
 see also UNIQUE
CROSS-REFERENCE INFORMATION
This function calls:
unique UNIQUE return set of unique scnlobjects from an array
This function is called by:
iceweb
ReadMSEEDFast ReadMSEEDFast(fileName)
station_meta station_meta adds station metadata to a waveform
dmc_station_meta DMC_STATION_META adds station metadata to a waveform
dd_make_scp DD_MAKE_SCP Create a draft control file for the correlation process
ie_readchans IE_READCHANS Read and parse station/channel list from file
dbload DBLOAD extracts travel times from a database
antelope READ_CATALOG.ANTELOPE load events from a CSS3.0 database using Antelope.
dbget_closest_sites DBGET_CLOSEST_SITES Get closest sites from an Antelop database to a given [lon, lat]
listMiniseedFiles LISTMINISEEDFILES retrieve a list of the Miniseed files referenced by a datasource, ChannelTag object and start/end times.
cookbook % The SCNLOBJECT cookbook
eventrate CATALOG.EVENTRATE
EventRate
cluster c = CLUSTER(c,CUTOFF) cuts the "branches" of the linkage tree to create
disp DISP Datasource disp overloaded operator
subdivide_files_by_date SUBDIVIDE_FILES_BY_DATE given a datasource and daterange return list of files
unique UNIQUE return set of unique scnlobjects from an array
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
legend legend creates a legend for a waveform graph
plot PLOT plots a waveform object
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_from_datasource load_from_datasource
antelopesource
cluster cluster Construct agglomerative clusters from linkage for Seismic Traces
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
SeismicTrace
legend legend Create a legend for the graph of a trace.
plot plot plots a SeismicTrace
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
SOURCE CODE
function [B,I,J] = unique(A)
%UNIQUE return set of unique scnlobjects from an array
% [B I J] = unique(scnlobjectList)
%   B is the unique (non duplicated) set of scnls
%   I is the index, such that B = A(I) and A = B(J)
%
%
% see also UNIQUE
[B, I, J] = unique([A.tag]);