Description of arrival_histogram
Home > GISMO > contributed_antelope > traveltime_and_ray_coverage > +ttimes > arrival_histogram.m
arrival_histogram
PURPOSE
ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
SYNOPSIS
function arrival_histogram(dbName)
DESCRIPTION
ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
 ARRIVAL_HISTOGRAM(dbName) creates plot comparing the number of P and S
 phase arrivals at each station.
 see also ttimes.dbload
CROSS-REFERENCE INFORMATION
This function calls:
hist HIST plot histograms of magnitude distribution, depth
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
get GET Get waveform properties
legend legend creates a legend for a waveform graph
set SET Set properties for waveform object(s)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
set SET Set properties for correlation object
legend legend Create a legend for the graph of a trace.
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function arrival_histogram(dbName)
%ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
% ARRIVAL_HISTOGRAM(dbName) creates plot comparing the number of P and S
% phase arrivals at each station.
%
% see also ttimes.dbload
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% LOAD DATABASE
[origin,site,arrival,ray] = ttimes.dbload(dbName);
% ADD STATION NUMBERS
site.stationNum = 1:numel(site.sta);
for n = 1:numel(site.stationNum)
    f = find(strcmp(site.sta(n),arrival.sta));
   arrival.stationNum(f) = site.stationNum(n);
end
arrival.stationNum =  arrival.stationNum';
% ARRIVAL HISTOGRAMS
figure('Position',[0 0 1100 850],'Color','w');
set(gcf,'DefaultAxesFontSize',14);
set(gcf,'DefaultAxesLineWidth',0.25);
%
f = find(strcmp(arrival.iphase,'P'));
nP = hist(arrival.stationNum(f),site.stationNum);
f = find(strcmp(arrival.iphase,'S'));
nS = hist(arrival.stationNum(f),site.stationNum);
h = bar(site.stationNum,[nP' nS'],1.8)
set(h(1),'FaceColor','r');
set(h(2),'FaceColor',[0.7 0.7 0.7]);
legend('P wave arrivals','S wave arrivals')
%xlabel('Station name');
ylabel('No. of phase arrivals');
% place rotated x-axis labels
set(gca,'XTick',1:12,'XTickLabel','')
xAxisHandle = get(gca,'XLabel');
set(xAxisHandle,'Units','data');
pos = get(xAxisHandle,'Position');
y = pos(2);
for n = 1:size(site.sta,1)
t(n) = text(site.stationNum(n),y,site.sta(n,:));
end
set(t,'Rotation',90,'HorizontalAlignment','right')
set(gcf, 'paperorientation', 'landscape');
set(gcf, 'paperposition', [.5 .5 10 6.5]);
print(gcf, '-dpsc2', 'FIG_arrival_histogram.ps');