Description of stream2waveform
Home > GISMO > contributed > +obspy > stream2waveform.m
stream2waveform
PURPOSE
OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
SYNOPSIS
function [w,scnl]=obspy.stream2waveform(path_to_python, path_to_converter, path_to_data)
DESCRIPTION
OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
 into a waveform object. Also return a scnlobject.
 Example:
  [w,scnl]=obspy.stream2waveform('/Users/glennthompson/anaconda/bin/python', ...
       '/Users/glennthompson/obspy_stream2matfile.py', ...
       'https://examples.obspy.org/BW.BGLD..EH.D.2010.037')
  plot(w)
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
waveform WAVEFORM Extract a waveform object.
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
load Purpose:
disp DISP - scnl disp overloaded operator
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
disp DISP Waveform disp overloaded operator
waveform WAVEFORM Waveform Class constructor
disp CORRELATION/DISPLAY Command window display of a correlation object
waveform WAVEFORM Extract a waveform object.
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
SOURCE CODE
function [w,scnl]=obspy.stream2waveform(path_to_python, path_to_converter, path_to_data)
%OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
% into a waveform object. Also return a scnlobject.
% Example:
%  [w,scnl]=obspy.stream2waveform('/Users/glennthompson/anaconda/bin/python', ...
%       '/Users/glennthompson/obspy_stream2matfile.py', ...
%       'https://examples.obspy.org/BW.BGLD..EH.D.2010.037')
%  plot(w)
    commandstr=sprintf('%s %s "%s"',path_to_python, path_to_converter, path_to_data);
    system(commandstr);
    clear commandstr fname
    d=dir('obspy.stream.*.mat');
    disp(sprintf('%d trace matfiles found\n',length(d)))
    for c=1:length(d)
        tr=load(d(c).name);
        disp(sprintf('Loaded trace %d',c))
        scnl(c)=scnlobject(tr.station, tr.channel, tr.network, tr.location);
        snum=(tr.starttime.timestamp/86400)+datenum(1970,1,1);
        w(c)=waveform(scnl, tr.sampling_rate, snum, tr.data);
        delete(d(c).name);
    end
end