Description of stream_matfile2waveform
Home > GISMO > contributed > +obspy > stream_matfile2waveform.m
stream_matfile2waveform
PURPOSE
OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
SYNOPSIS
function [w,scnl]=stream_matfile2waveform(matfilepath)
DESCRIPTION
OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
 into a waveform object. Also return a scnlobject.
 Example:
  [w,scnl]=obspy.stream_matfile2waveform(matfilepath)
CROSS-REFERENCE INFORMATION
This function calls:
waveform WAVEFORM Extract a waveform object.
load Purpose:
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
waveform WAVEFORM Get waveforms from a threecomp object
waveform WAVEFORM Waveform Class constructor
waveform WAVEFORM Extract a waveform object.
This function is called by:
SOURCE CODE
function [w,scnl]=stream_matfile2waveform(matfilepath)
%OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
% into a waveform object. Also return a scnlobject.
% Example:
%  [w,scnl]=obspy.stream_matfile2waveform(matfilepath)
    tr=load(matfilepath)
    scnl=scnlobject(tr.station, tr.channel, tr.network, tr.location);
    %snum=(tr.starttime.timestamp/86400)+datenum(1970,1,1);
    snum=datenum('2007-08-28T00:00:00','yyyy-mm-ddTHH:MM:SS');
    w=waveform(scnl, tr.sampling_rate, snum, tr.data);
end