Description of get_channeltags_active
Home > GISMO > applications > +iceweb > get_channeltags_active.m
get_channeltags_active
PURPOSE
sites active for this day
SYNOPSIS
function goodsites = get_channeltags_active(sites, snum)
DESCRIPTION
 sites active for this day
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
disp DISP Waveform disp overloaded operator
disp CORRELATION/DISPLAY Command window display of a correlation object
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
iceweb
SOURCE CODE
function goodsites = get_channeltags_active(sites, snum)
    % sites active for this day
    k=0;
    %goodsites = [];
    for c=1:numel(sites)
        if sites(c).ondnum <= snum+1 && sites(c).offdnum >= snum
            k = k + 1;
            goodsites(k) = sites(c);
            disp(sprintf('Keeping %s',sites(c).channeltag.string()));
        else
            %datestr(snum+1),datestr(sites(c).ondnum)
            %datestr(snum),datestr(sites(c).offdnum)
            disp(sprintf('Rejecting %s',sites(c).channeltag.string()));
        end
    end
    if k==0
        goodsites = [];
    end
end