Description of makespectrogramthumbnails
Home > GISMO > applications > +iceweb > makespectrogramthumbnails.m
makespectrogramthumbnails
PURPOSE
SYNOPSIS
function makespectrogramthumbnails(spectrogramFilename, spectrogramFraction)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
calculatePanelPositions
saveImageFile saveImageFile(IMGDIR, fname, res);
map MAP plot a map of ray coverage.
printfunctionstack PRINTFUNCTIONSTACK print the list of functions in the stack
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
get GET Get waveform properties
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
iceweb
SOURCE CODE
function makespectrogramthumbnails(spectrogramFilename, spectrogramFraction)
import debug.*
printfunctionstack('>');
%print_debug('> makespectrogramthumbnails', 2);
% figure 1 should be a large spectrogram with traces, cropped nicely. Now remove labels and maximise panels.
ax=get(gcf, 'Children');
% Work out number of channels
pos1 = get(ax(1),'position'); % top trace
pos2 = get(ax(2),'position'); % top sgram
height_per_channel = pos1(4) + pos2(4);
numchannels = 0.95 / height_per_channel;
numpanels = numchannels * 2;
new_height_per_channel = 1 / numchannels;
% Remove all axes, tickmarks, labels, and axis boxes and title from view
for c=1:numpanels
    set(ax(c), 'Visible', 'off')
end
% Move panels
for channelNum = 1:numchannels
    [spectrogramPosition, tracePosition] = calculatePanelPositions(numchannels, numchannels - channelNum + 1, spectrogramFraction, 0.0, 0.0, 1, 1);
    set(ax(channelNum*2 - 1), 'position', tracePosition);
    set(ax(channelNum*2), 'position', spectrogramPosition);
end
% we need a name for the labelless large spectrogram
[tmppath, tmpbase, tmpext] = fileparts(spectrogramFilename);
tmpfile = sprintf('%s/%s_labelless%s',tmppath,tmpbase,tmpext);
% print large labelless PNG
saveImageFile(tmpfile, 72);
% load then delete temporary file
I = imread(tmpfile);
delete(tmpfile)
% Resize the image (aspect ratio 16:21 same as 576:756) and convert it to an indexed image with 256 colors
% (Note: we were originally creating 150x96, which is far off the aspect ratio of large spectrograms)
%[X,map] = rgb2ind(imresize(I, [126 96]), 256);
%thumbnailfile = sprintf('%s/smallest_%s%s',tmppath, tmpbase, tmpext);
%imwrite(X,map,thumbnailfile,'PNG');
%[X,map] = rgb2ind(imresize(I, [147 112]), 256);
%thumbnailfile = sprintf('%s/smaller_%s%s',tmppath, tmpbase, tmpext);
%imwrite(X,map,thumbnailfile,'PNG');
[X,map] = rgb2ind(imresize(I, [198 151]), 256);
thumbnailfile = sprintf('%s/small_%s%s',tmppath, tmpbase, tmpext);
imwrite(X,map,thumbnailfile,'PNG');
close;
printfunctionstack('<');