Description of waveform_remove_empty
Home > GISMO > applications > +iceweb > waveform_remove_empty.m
waveform_remove_empty
PURPOSE
WAVEFORM_REMOVE_EMPTY remove empty waveform objects from a vector of waveform objects
SYNOPSIS
function w2 = waveform_remove_empty(w);
DESCRIPTION
WAVEFORM_REMOVE_EMPTY remove empty waveform objects from a vector of waveform objects
   Note that the opposite function, of expanding empty waveform objects can largely
   be achieved with waveform/pad
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
iceweb
SOURCE CODE
function w2 = waveform_remove_empty(w);
%WAVEFORM_REMOVE_EMPTY remove empty waveform objects from a vector of waveform objects
%   Note that the opposite function, of expanding empty waveform objects can largely
%   be achieved with waveform/pad
%   Glenn Thompson
    e = 1;
    for c=1:length(w)
            nsamp = get(w(c), 'data_length');
            if nsamp > 1 % 0 means blank waveform object, 1 means corrupt waveform object
                    w2(e) = w(c);
                    e = e + 1;
            end
    end
    if e==1
            w2 = [];
    end
end