Description of wf_fftplot
Home > GISMO > deprecated > fft_tools > wf_fftplot.m
wf_fftplot
PURPOSE
WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
SYNOPSIS
function wf_fftplot(w);
DESCRIPTION
 WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
Fs
plot RSAM/PLOT plot rsam data
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
mean MEAN Average or mean value of waveform's data.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
plot plot plots a SeismicTrace
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
SOURCE CODE
function wf_fftplot(w);
% WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% TODO: written pretty hastily and inefficiently - MEW 6/18/2007
admin.deprecated(mfilename,'wf_fft.plot');
% CHECK ARGUMENTS
if ~strcmpi(class(w),'waveform')
    error('First input must be a waveform object');
end
Fs = round(get(w,'Fs'));
if ~isempty(find(Fs-mean(Fs)))
   error('Waveforms must have the same sample rate');
end
%if ~isfield(w,'FFT_AMP')
%    error('waveform must contain FFT fields. Run WF_FFT first');
%end;
% MAKE LOG PLOT
figure('Color','w','Position',[50 200 800 600]);
set(gcf,'DefaultAxesFontSize',14);
hold on; box on; grid on;
cmap = lines;
for n = 1:numel(w)
    col = round(size(cmap,1)*rand(1));
    col = cmap(col,:);
    plot( get(w(n),'FFT_FREQ') ,  get(w(n),'FFT_AMP') , 'Color' , col );
end;
set(gca,'XScale','log');
%set(gca,'YScale','log');
xlabel('Frequency (Hz)');
ylabel('Amplitude');