Description of separating_tremor_and_events
Home > GISMO > training > separating_tremor_and_events.m
separating_tremor_and_events
PURPOSE
Tremor range is 1-5 Hz
SYNOPSIS
This is a script file.
DESCRIPTION
 Tremor range is 1-5 Hz
 Swarm events are 0.5-15 Hz
CROSS-REFERENCE INFORMATION
This function calls:
filterobject FILTEROBJECT constructor for a filter object
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
waveform2rsam WAVEFORM2RSAM create an RSAM-like object from a waveform object
This function is called by:
SOURCE CODE
% Tremor range is 1-5 Hz
% Swarm events are 0.5-15 Hz
fobj = filterobject('b', [1 5], 2);
wtremor = filtfilt(fobj, w);
wevents = w - wtremor;
cobj = Detect.sta_lta(wevents, 'edp', event_detection_params)
% RSAM
rsam_tremor = waveform2rsam(wtremor, 'method', 'median')
rsam_events = waveform2rsam(wevents, 'method', 'max')