Description of demo_plutons
Home > GISMO > contributed > instrument_response > demo_plutons.m
demo_plutons
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
response_plot RESPONSE_PLOT plot an instrument response
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
correlation
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
waveform WAVEFORM Extract a waveform object.
datasource DATASOURCE constructor for a datasource object.
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
filterobject FILTEROBJECT constructor for a filter object
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
get GET - Get filterobject properties
load Purpose:
plot RSAM/PLOT plot rsam data
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
get GET for the scnl object
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
plot PLOT plots a threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
get GET Get waveform properties
plot PLOT plots a waveform object
waveform WAVEFORM Waveform Class constructor
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
waveform WAVEFORM Extract a waveform object.
plot plot plots a SeismicTrace
get GET: Get helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
SOURCE CODE
%
dbName = '/home/admin/databases/PLUTONS/wf/plutons';
ds = datasource('antelope',dbName);
%t1 = datenum('2010/2/27 6:35');
%t2 = datenum('2010/2/27 6:55');
%filterObj = filterobject('b',[0.033 0.2],3);
%stachan = {
% 'UTLO'   'BHZ'
% 'UTKH'   'BHZ'
% 'UTSA'   'BHZ'
% 'UTQU'   'BHZ'
% 'UTLV'   'BHZ'
% 'UTSM'   'BHZ'
% 'UTLL'   'SHZ'
% 'UTSS'   'SHZ'
% 'UTLA2'  'SHZ'
% 'UTSW'   'SHZ'
% 'UTMK'   'SHZ'
% 'UTCM'   'SHZ'
% 'UTCA'   'SHZ'
% 'UTZN'   'SHZ'
% 'UTTM'   'SHZ'}
%t1 = datenum('2009/9/22 22:47:10');
%t2 = datenum('2009/9/22 22:47:30');
t1 = datenum('2010/02/27 22:47:10');
t2 = datenum('2010/02/27 22:47:30');
filterObj = filterobject('b',[0.5 10],2);
stachan = {
'UTSM'   'BHZ'
'UTQU'   'BHZ'
'UTTM'   'SHZ'
'UTLA2'  'SHZ'
'UTCA'   'SHZ'
'UTLV'   'BHZ'
'UTCM'   'SHZ'
'UTSW'   'SHZ'
'UTSA'   'BHZ'
'UTZN'   'SHZ'
'UTSS'   'SHZ'
'UTMK'   'SHZ'
'UTLO'   'BHZ'
'UTLL'   'SHZ'
'UTKH'   'BHZ'
}
for n = 1:size(stachan,1)
    scnl = scnlobject(stachan(n,1),stachan(n,2),'','');
    try
        w(n) = waveform(ds,scnl,t1,t2);
    catch
        w(n) = waveform;
    end
end
f = find(get(w,'DATA_LENGTH')~=0);
w = w(f);
% APPLY RESPONSES TO ORIGINAL WAVEFORMS (SHORT PERIOD)
wFilt = filtfilt(filterObj,w);
wNew = response_apply(wFilt,filterObj,'antelope',dbName);
% for n =1:numel(w)
%     n
%     wFilt(n) = filtfilt(filterObj,w(n));
%     wNew(n) = response_apply(wFilt(n),filterObj,dbName);
% end
save
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% check one channel
n = 3;
figure
plot(wFilt(n),'r');
hold on;
plot(wNew(n),'b');
response_plot(get(wNew(n),'RESPONSE'),[0.01 50])
load
% compare all channels
cNew = correlation(wNew);
%cNew = xcorr(cNew);
%cNew = adjusttrig(cNew);
plot(cNew,'wig',0.6)
title('Filtered and corrected for instrument response','FontSize',16);
%print(gcf,'-dpsc2','demo_corrected.ps');
cFilt = correlation(wFilt);
plot(cFilt,'wig',.6)
title('Filtered only (30.5 - 10 Hz)','FontSize',16);
%print(gcf,'-dpsc2','demo_filtered.ps');
c = correlation(w);
plot(c,'wig',.6)
title('Raw','FontSize',16);
%print(gcf,'-dpsc2','demo_raw.ps');
%
% % compare all channels
% cNew = correlation(wNew);
% cNew = crop(cNew,[0 600]);
% cNew = xcorr(cNew,[100 300]);
% cNew = adjusttrig(cNew);
% plot(cNew,'wig',0.6)
% title('Filtered and corrected for instrument response','FontSize',16);
% print(gcf,'-dpsc2','demo_corrected.ps');
%
% cFilt = correlation(wFilt);
% cNew = crop(cFilt,[0 600]);
% plot(cFilt,'wig',.6)
% title('Filtered only (30-5 s)','FontSize',16);
% print(gcf,'-dpsc2','demo_filtered.ps');
%
% c = correlation(w);
% cNew = crop(c,[0 600]);
% plot(c,'wig',.6)
% title('Raw','FontSize',16);
% print(gcf,'-dpsc2','demo_raw.ps');
%
%