Description of response_demo_waveforms
Home > GISMO > contributed > instrument_response > response_demo_waveforms.m
response_demo_waveforms
PURPOSE
RESPONSE_DEMO_WAVEFORMS returns the absolute path to the demo database
SYNOPSIS
function w = response_demo_waveforms
DESCRIPTION
RESPONSE_DEMO_WAVEFORMS returns the absolute path to the demo database
  W = RESPONSE_DEMO_WAVEFORMS
CROSS-REFERENCE INFORMATION
This function calls:
which WHICH manage and switch between multiple GISMO archives
load Purpose:
This function is called by:
response_cookbook % Instrument response cookbook
SOURCE CODE
function w = response_demo_waveforms
%RESPONSE_DEMO_WAVEFORMS returns the absolute path to the demo database
%  W = RESPONSE_DEMO_WAVEFORMS
file = which('response_cookbook');
path = fileparts(file);
if ~exist([path '/demo'])
    error('response_demo_waveforms: demo waveforms not found');
else
    load([path '/demo/plutons_waveforms.mat']);
end