Description of isunassigned
Home > GISMO > core > @datasource > isunassigned.m
isunassigned
PURPOSE
ISUNASSIGNED is true when no data source is associated with this object
SYNOPSIS
function val = isunassigned(ds)
DESCRIPTION
ISUNASSIGNED is true when no data source is associated with this object
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
uispecgram UISPECGRAM M-file for uispecgram.fig
disp DISP Datasource disp overloaded operator
SOURCE CODE
function val = isunassigned(ds)
   %ISUNASSIGNED is true when no data source is associated with this object
   val = true(size(ds));
   for n=1:numel(ds)
      val(n) = strcmp(get(ds,'type'),'none');
   end
end