Description of query_file
Home > GISMO > core > @datasource > query_file.m
query_file
PURPOSE
QUERY_FILE retrieves scnl, starttime and endtime information for all
SYNOPSIS
function [scnls starttimes endtimes] = query_file(ds, filename)
DESCRIPTION
 QUERY_FILE retrieves scnl, starttime and endtime information for all
 objects of intrest with a file
 [scnls starttimes endtimes] = query_file(datasource, filename);
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
requires_file ISFILEDEPENDENT
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
SOURCE CODE
function [scnls starttimes endtimes] = query_file(ds, filename)
   % QUERY_FILE retrieves scnl, starttime and endtime information for all
   % objects of intrest with a file
   % [scnls starttimes endtimes] = query_file(datasource, filename);
   if ~requires_file(ds)
      warning('irrelevent request, no filenames associated with this datasource');
      scnls = scnlobject;
      return
   end
   if isa(filename,'cell')
      filename = filename{1};
   end;
   if ~exist(filename,'file')
      warning('file does not exist');
      scnls =  scnlobject;
      return
   end
   obj = ds.interpreter(filename);
   scnls = get(obj,'scnlobject');
   starttimes = get(obj,'start');
   endtimes = get(obj,'end');
   %interpret file
   %keep scnls only
end