Description of mep2dep
Home > gismotools > GISMO > classes > @waveform > private > mep2dep.m
mep2dep
PURPOSE
convert a matlab date to an epoch date
SYNOPSIS
function n = mep2dep(n)
DESCRIPTION
 convert a matlab date to an epoch date
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
load_antelope load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
SOURCE CODE
function n = mep2dep(n)
   % convert a matlab date to an epoch date
   n = (n - 719529) * 86400;
end