Description of fft
Home > GISMO > core > @spectralobject > fft.m
fft
PURPOSE
FFT Discrete Fourier transform. OVERLOADED for waveform & Spectralobject
SYNOPSIS
function [varargout] = fft(s, w)
DESCRIPTION
FFT Discrete Fourier transform.  OVERLOADED for waveform & Spectralobject
   USAGE
       v = fft(s, w);      % get the fft only
       [v, f] = fft(s,w);  % get the fft & assoc. frequencies
       [v, f, Pyy] = fft(s,w); % get fft, frequencies, and Power Spectrum
   See also SPECTRALOBJECT/IFFT, FFT, FFT2, FFTN, FFTSHIFT, FFTW, IFFT2, IFFTN, WAVEFORM/FILLGAPS.
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
conv c = CONV(c) convolves all traces with the final trace. By default the new
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
DEPRICATED_xcorr1xr This function performs cross correlations in sets by correlating one
DEPRICATED_xcorrcxc This function performs cross correlations of one correlation object
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
specgram SPECGRAM - plots spectrogram of waveforms
plot_spectrum add_spectral_data Simple method to compute frequency
conv conv convolve all traces with the final trace
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
amplitude_spectrum amplitude_spectrum Simple method to compute amplitude
specgram specgram - plots spectrogram of traces
compute COMPUTE calculates the fast fourier transform of a waveform object
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
SOURCE CODE
function [varargout] = fft(s, w)
%FFT Discrete Fourier transform.  OVERLOADED for waveform & Spectralobject
%   USAGE
%       v = fft(s, w);      % get the fft only
%       [v, f] = fft(s,w);  % get the fft & assoc. frequencies
%       [v, f, Pyy] = fft(s,w); % get fft, frequencies, and Power Spectrum
%
%   See also SPECTRALOBJECT/IFFT, FFT, FFT2, FFTN, FFTSHIFT, FFTW, IFFT2, IFFTN, WAVEFORM/FILLGAPS.
% AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
if nargin < 2
    error('Spectralobject:fft:insufficientArguments',...
        'Not enough input arguments. [out]=fft(spectralobject, waveform)');
end
if ~isscalar(w)
    error('Spectralobject:fft:nonScalarWaveform',...
        'waveform must be scalar (1x1)');
end
if ~isa(w,'waveform')
    error('Spectralobject:fft:invalidArgument',...
        'second argument expected to be WAVEFORM, but was [%s]', class(w));
end
if any(isnan(double(w)))
    warning('Spectralobject:fft:nanValue',...
        ['This waveform has at least one NaN value, which returns NaN ',...
        'results. Remove NaN values by either splitting up the ',...
        'waveform into non-NaN sections or by using waveform/fillgaps',...
        ' to replace the NaN values.']);
end
varargout{1} = builtin('fft', double(w));
varargout{2} = get(w,'fs') * (0:fix(get(s,'nfft')./2)) / get(s,'nfft');
varargout{3} = varargout{1}.* conj(varargout{1}) / get(s,'nfft');
varargout{3} = varargout{3}(1:length(varargout{2}));