Description of ifft
Home > GISMO > core > @spectralobject > ifft.m
ifft
PURPOSE
IFFT Inverse discrete Fourier transform. OVERLOADED FOR Spectralobject
SYNOPSIS
function [varargout] = ifft(s, w)
DESCRIPTION
IFFT Inverse discrete Fourier transform.  OVERLOADED FOR Spectralobject
   IFFT(spectralobject, X) is the N-point inverse discrete Fourier
   transform of X, using the spectralobject's NFFT value for N.
   See also SPECTRALOBJECT/FFT, FFT, FFT2, FFTN, FFTSHIFT, FFTW, IFFT2, IFFTN.
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
conv c = CONV(c) convolves all traces with the final trace. By default the new
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
DEPRICATED_xcorr1xr This function performs cross correlations in sets by correlating one
DEPRICATED_xcorrcxc This function performs cross correlations of one correlation object
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
conv conv convolve all traces with the final trace
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
SOURCE CODE
function [varargout] = ifft(s, w)
%IFFT Inverse discrete Fourier transform.  OVERLOADED FOR Spectralobject
%   IFFT(spectralobject, X) is the N-point inverse discrete Fourier
%   transform of X, using the spectralobject's NFFT value for N.
%
%   See also SPECTRALOBJECT/FFT, FFT, FFT2, FFTN, FFTSHIFT, FFTW, IFFT2, IFFTN.
%   Copyright 1984-2003 The MathWorks, Inc.
%   $Revision$  $Date$
% AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
if nargin < 2
    error('Spectralobject:ifft:insufficientArguments',...
        'Not enough input arguments. [out]=ifft(spectralobject, waveform)');
end
if ~isscalar(w)
    error('Spectralobject:ifft:nonScalarWaveform',...
        'waveform must be scalar (1x1)');
end
if ~isa(w,'waveform')
    error('Spectralobject:ifft:invalidArgument',...
        'second argument expected to be WAVEFORM, but was [%s]', class(w));
end
if nargout == 0
  builtin('ifft', double(w), get(s,'nfft'));
else
  [varargout{1:nargout}] = builtin('ifft', double(w), get(s,'nfft'));
end