Description of ideas2waveform
Home > GISMO > uaf_internal > IDEAS_format > ideas2waveform.m
ideas2waveform
PURPOSE
OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
SYNOPSIS
function w = ideas2waveform(fileName)
DESCRIPTION
OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
 [W] = OPEN_INFRASOUND(FILENAME) opens a file in the UAF/GI infrasound
 format. FILENAME should be quoted and be in .mat format. The contents of
 the infrasound data are then parsed into a waveform object.
   Example:
       w = open_infrasound('FAI200908205.mat')
CROSS-REFERENCE INFORMATION
This function calls:
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
set SET: Set drumplot properties
set SET - Set filterobject properties
load Purpose:
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
set SET inserts properties for threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
addfield ADDFIELD add fields and values to waveform object(s) V1.1
set SET Set properties for waveform object(s)
waveform WAVEFORM Waveform Class constructor
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function w = ideas2waveform(fileName)
%OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
% [W] = OPEN_INFRASOUND(FILENAME) opens a file in the UAF/GI infrasound
% format. FILENAME should be quoted and be in .mat format. The contents of
% the infrasound data are then parsed into a waveform object.
%   Example:
%       w = open_infrasound('FAI200908205.mat')
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
if ~exist(fileName)
    error(['file ' fileName ' does not exist.']);
end
load(fileName);
w = waveform;
for n = 1:size(data,2)
    startTime = datenum([micHeader(n).date ' ' micHeader(n).time]);
    w(n) = waveform( micHeader(n).station , micHeader(n).channel , micHeader(n).Hz , startTime , CSS.calib(n)*data(:,n) );
    w(n) = set(w(n),'UNITS','Pa');
    w(n) = addfield(w(n),'LAT',CSS.lat(n));
    w(n) = addfield(w(n),'LON',CSS.lon(n));
    w(n) = addfield(w(n),'DNORTH',CSS.dnorth(n));
    w(n) = addfield(w(n),'DEAST',CSS.deast(n));
    w(n) = addfield(w(n),'ELEV',CSS.elev(n));
    w(n) = addfield(w(n),'DESCRIP',CSS.descrip(n,:));
    w(n) = addfield(w(n),'STANAME',CSS.staname(n,:));
    w(n) = addfield(w(n),'EDEPTH',CSS.edepth(n));
    w(n) = addfield(w(n),'REFSTA',CSS.refsta(n,:));
    w(n) = addfield(w(n),'CALIB',CSS.calib(n));
    w(n) = addfield(w(n),'ONDATE',CSS.ondate(n));
    w(n) = addfield(w(n),'OFFDATE',CSS.offdate(n));
end