Description of getproperty
Home > GISMO > core > @threecomp > private > getproperty.m
getproperty
PURPOSE
GETPROPERTY returns a property value from a property list, or a default
SYNOPSIS
function [isfound, foundvalue, properties] = getproperty(desiredproperty,properties,defaultvalue)
DESCRIPTION
GETPROPERTY returns a property value from a property list, or a default
  value if none is available
[isfound, foundvalue, properties] =
      getproperty(desiredproperty,properties,defaultvalue)
 returns a property value (if found) from a property list, removing that
 property pair from the list.  only removes the first encountered property
 name.
see also waveform/private/parseargs, waveform/private/property2varargin
CROSS-REFERENCE INFORMATION
This function calls:
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
This function is called by:
specgram SPECGRAM - plots spectrogram of waveforms
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
plot PLOT plots a threecomp object
plot PLOT plots a waveform object
SOURCE CODE
function [isfound, foundvalue, properties] = getproperty(desiredproperty,properties,defaultvalue)
%GETPROPERTY returns a property value from a property list, or a default
%  value if none is available
%[isfound, foundvalue, properties] =
%      getproperty(desiredproperty,properties,defaultvalue)
%
% returns a property value (if found) from a property list, removing that
% property pair from the list.  only removes the first encountered property
% name.
%
%see also waveform/private/parseargs, waveform/private/property2varargin
pmask = strcmpi(desiredproperty,properties.name);
isfound = any(pmask);
if isfound
  foundlist = find(pmask);
  foundidx = foundlist(1);
  foundvalue = properties.val{foundidx};
  properties.name(foundidx) = [];
  properties.val(foundidx) = [];
else
  if exist('defaultvalue','var')
    foundvalue = defaultvalue;
  else
    foundvalue = [];
  end
  % do nothing to properties...
end