Description of property2varargin
Home > GISMO > core > @threecomp > private > property2varargin.m
property2varargin
PURPOSE
PROPERTY2VARARGIN makes a cell array from properties
SYNOPSIS
function c = property2varargin(properties)
DESCRIPTION
PROPERTY2VARARGIN makes a cell array from properties
  c = property2varargin(properties)
 properties is a structure with fields "name" and "val"
see also waveform/private/getproperty, waveform/private/parseargs
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
specgram SPECGRAM - plots spectrogram of waveforms
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
plot PLOT plots a threecomp object
plot PLOT plots a waveform object
SOURCE CODE
function c = property2varargin(properties)
%PROPERTY2VARARGIN makes a cell array from properties
%  c = property2varargin(properties)
%
% properties is a structure with fields "name" and "val"
%
%see also waveform/private/getproperty, waveform/private/parseargs
c = {};
c(1:2:numel(properties.name)*2) = properties.name;
c(2:2:numel(properties.name)*2) = properties.val;