Description of sacsource
Home > GISMO > core > dev > +dataretrieval > sacsource.m
sacsource
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
sacsource
spatiotemporal_file
This function is called by:
sacsource
SUBFUNCTIONS
function data = retrieve(obj, where_, from_ , until_)
SOURCE CODE
classdef sacsource < spatiotemporal_file
   %UNTITLED2 Summary of this class goes here
   %   Detailed explanation goes here
   properties
   end
   methods
      function data = retrieve(obj, where_, from_ , until_)
         error('unimplemented SAC source');
      end
   end
end