Description of arrivals2waveforms
Home > GISMO > core > +antelope > arrivals2waveforms.m
arrivals2waveforms
PURPOSE
ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
SYNOPSIS
function w = arrivals2waveforms(dbpath, arrivals, pretrig, posttrig, taper_seconds, nwaveforms)
DESCRIPTION
 ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
    w = ARRIVALS2WAVEFORMS(dbpath, arrivals, pretrig, posttrig, taper_seconds, maxNumberOfWaveforms)
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
waveform WAVEFORM Extract a waveform object.
datasource DATASOURCE constructor for a datasource object.
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
disp DISP Waveform disp overloaded operator
min MIN Smallest value of a waveform.
waveform WAVEFORM Waveform Class constructor
disp CORRELATION/DISPLAY Command window display of a correlation object
waveform WAVEFORM Extract a waveform object.
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
epoch2datenum TIME = EPOCH2DATENUM(EPOCH) translates Unix epoch date format into Matlab
This function is called by:
SOURCE CODE
function w = arrivals2waveforms(dbpath, arrivals, pretrig, posttrig, taper_seconds, nwaveforms)
% ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
%    w = ARRIVALS2WAVEFORMS(dbpath, arrivals, pretrig, posttrig, taper_seconds, maxNumberOfWaveforms)
    w = waveform(); % Initialize output
    % Check input variables.
    if nargin<4
        disp('Incorrect number of input variables')
        return
    end
    % Create datasource
    ds = datasource('antelope', dbpath);
    % Loop over arrivals structure
    for i=1:min([nwaveforms numel(arrivals.arid)])
        scnl = scnlobject(arrivals.sta{i}, arrivals.chan{i});
        snum = epoch2datenum(arrivals.time(i) - pretrig - taper_seconds);
        enum = epoch2datenum(arrivals.time(i) + posttrig + taper_seconds);
        try
            thisw = waveform(ds, scnl, snum, enum);
        end
        if numel(thisw)==1
            w(i) = thisw;
        else
            w(i)=waveform();
        end
    end
end