Description of as_channeltag
Home > GISMO > core > @waveform > private > as_channeltag.m
as_channeltag
PURPOSE
SYNOPSIS
function obj = as_channeltag(obj)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ChannelTag
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
waveform WAVEFORM Waveform Class constructor
SOURCE CODE
function obj = as_channeltag(obj)
   switch(class(obj))
      case 'ChannelTag' %good. do nothing.
      case 'scnlobject'
         obj = get(obj, 'channeltag');
      otherwise
         obj = ChannelTag(obj); %attempt natural conversion
         % should be able to handle 'N.S.L.C'
   end
end