Description of filter_by_time
Home > GISMO > core > @waveform > private > filter_by_time.m
filter_by_time
PURPOSE
filter_by_time
SYNOPSIS
function w = filter_by_time(w, myStartTime, myEndTime)
DESCRIPTION
 filter_by_time
 w = filter_by_time(w, startTime, endTime)
CROSS-REFERENCE INFORMATION
This function calls:
extract EXTRACT extract matches to the master waveform
extract
extract EXTRACT particle motion parameters from a threecomp object
extract EXTRACT creates a waveform with a subset of another's data.
gettimerange GETTIMERANGE returns the list of start and end times from a waveform array
This function is called by:
load_from_datasource load_from_datasource
SOURCE CODE
function w = filter_by_time(w, myStartTime, myEndTime)
   % filter_by_time
   % w = filter_by_time(w, startTime, endTime)
   % subset and consolidate
   [wstarts, wends] = gettimerange(w);
   wavesWithinWindow = wstarts < myEndTime & wends > myStartTime;
   if any(wavesWithinWindow)
      w = extract(w(wavesWithinWindow),'time',myStartTime,myEndTime);
   else
      w(:)=[]; %return an empty waveform
   end
end