Description of get_load_routine
Home > GISMO > core > @waveform > private > get_load_routine.m
get_load_routine
PURPOSE
determine the load function based upon the datasource's type
SYNOPSIS
function myLoadRoutine = get_load_routine(ds, use_wkaround)
DESCRIPTION
 determine the load function based upon the datasource's type
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
load_antelope load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_matfile LOAD_FILE
load_miniseed LOAD_MINISEED loads a waveform from MINISEED files
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
load_sac LOAD_SAC loads a waveform from SAC files
load_seisan LOAD_SEISAN loads a waveform from SEISAN files
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
load_antelope load a waveform from antelope
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
load_from_datasource load_from_datasource
SOURCE CODE
function myLoadRoutine = get_load_routine(ds, use_wkaround)
      % determine the load function based upon the datasource's type
   switch lower(get(ds,'type'))
      case 'sac'
         myLoadRoutine = @load_sac;
      case 'matfile'
         myLoadRoutine = @load_matfile;
      case 'obspy'
         myLoadRoutine = @load_obspy;
      case 'file'
         myLoadRoutine = @load_matfile; %same as type 'matfile'
      case 'antelope'
         if use_wkaround
            myLoadRoutine = @load_antelope_workaround;
         else
            myLoadRoutine = @load_antelope;
         end
      case 'irisdmcws'
         myLoadRoutine = @load_irisdmcws;
      case 'winston'
         myLoadRoutine = @load_winston;
      case 'seisan'
         myLoadRoutine = @load_seisan;
      case 'ah'
         myLoadRoutine = @load_ah;
       case 'miniseed' % added by Glenn 2016/05/25
           myLoadRoutine = @load_miniseed;
      otherwise
            error('Waveform:waveform:noDatasourceInterpreter',...
               'user defined datasources should be associated with an interpreter');
   end
end