Description of load_obspy
Home > GISMO > core > @waveform > private > load_obspy.m
load_obspy
PURPOSE
LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
SYNOPSIS
function w = load_obspy(request)
DESCRIPTION
LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
 it expects one waveform per file, with variables stored individually, not
 as a struct.
 uses the DATASOURCE class
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
ChannelTag
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
disp DISP Datasource disp overloaded operator
load_objects_from_file grab all the variables in a matlab file, and flip through them, returning
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
set SET - Set filterobject properties
load Purpose:
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
disp DISP - scnl disp overloaded operator
ismember ISMEMBER for scnlobjects
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
set SET - Set properties for spectralobject
disp DISP Display threecomp object
set SET inserts properties for threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
addfield ADDFIELD add fields and values to waveform object(s) V1.1
disp DISP Waveform disp overloaded operator
ismember ISMEMBER waveform implementation of ismember
unpackDataRequest
set SET Set properties for waveform object(s)
waveform WAVEFORM Waveform Class constructor
disp CORRELATION/DISPLAY Command window display of a correlation object
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
set SET: Set helicorder properties
This function is called by:
get_load_routine determine the load function based upon the datasource's type
SOURCE CODE
function w = load_obspy(request)
   %LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
   % it expects one waveform per file, with variables stored individually, not
   % as a struct.
   %
   % uses the DATASOURCE class
   % request.combineWaves is ignored
   w = waveform; w = w();
   if isstruct(request)
      [ds, chanInfo, startTimes, endTimes, ~]  = unpackDataRequest(request);
      w = load_objects_from_file(ds, 'waveform', chanInfo, startTimes, endTimes);
      w = w(:);
   else
      filen = request;
      if ~exist(filen,'file')
         disp(['unable to find file: ', filen]);
         return
      end
      %find out which variables exist within the file...
      fcontents = whos('-file',filen);
      %if this is an obspy generated .mat file, then it will have the following
      %fields:
      if ~all(ismember({'data','network','station','channel','location','sampling_rate','starttime','calib','mseed'},{fcontents.name}))
         return
      end
      stuff =load(filen);
      chanInfo = ChannelTag(stuff.network, stuff.station, stuff.location, stuff.channel);
      w = set(w,...
         'channelinfo',chanInfo,...
         'data',stuff.data,...
         'freq',str2double(stuff.sampling_rate),...
         'start',[stuff.starttime(1:10),' ',stuff.starttime(12:end-1)],...
         'units','UNKNOWN');
      w = addfield(w,'calib',stuff.calib);
      w = addfield(w,'mseed_info',stuff.mseed);
   end
end