Description of load_miniseed
Home > GISMO > core > @waveform > private > load_miniseed.m
load_miniseed
PURPOSE
LOAD_MINISEED loads a waveform from MINISEED files
SYNOPSIS
function w = load_miniseed(request)
DESCRIPTION
LOAD_MINISEED loads a waveform from MINISEED files
 combineWaves isn't currently used!
CROSS-REFERENCE INFORMATION
This function calls:
ReadMSEEDFast ReadMSEEDFast(fileName)
extract EXTRACT extract matches to the master waveform
ChannelTag
waveform WAVEFORM Extract a waveform object.
getfilename GETFILENAME returns a filename that is associated with a single SCNL
extract
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
extract EXTRACT particle motion parameters from a threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
extract EXTRACT creates a waveform with a subset of another's data.
unpackDataRequest
waveform WAVEFORM Waveform Class constructor
waveform WAVEFORM Extract a waveform object.
epoch2datenum TIME = EPOCH2DATENUM(EPOCH) translates Unix epoch date format into Matlab
This function is called by:
get_load_routine determine the load function based upon the datasource's type
SUBFUNCTIONS
function w = mseedfilename2waveform(thisfilename, snum, enum)
SOURCE CODE
function w = load_miniseed(request)
   %LOAD_MINISEED loads a waveform from MINISEED files
   % combineWaves isn't currently used!
   % Glenn Thompson 2016/05/25 based on load_sac
   % request.combineWaves is ignored
   if isstruct(request)
      [thisSource, chanInfo, startTimes, endTimes, ~] = unpackDataRequest(request);
      for i=1:numel(chanInfo)
         for j=1:numel(startTimes)
            thisfilename = getfilename(thisSource,chanInfo(i),startTimes(j));
            w(i,j) = mseedfilename2waveform(thisfilename{1}, startTimes(j), endTimes(j));
         end
      end
      w = w(:);
   else
      %request should be a filename
      thisFilename = request;
      if exist(thisFilename, 'file')
        w = mseedfilename2waveform(thisFilename);
      else
          w = waveform();
          warning(sprintf('File %s does not exist',thisFilename));
      end
   end
end
function w = mseedfilename2waveform(thisfilename, snum, enum)
    s = ReadMSEEDFast(thisfilename); % written by Martin Mityska
    w = waveform();
    w.data = s.data;
    w.start = epoch2datenum(s.startTime);
    w.Fs = s.sampleRate;
    w.cha_tag = ChannelTag(s.network, s.station, s.location, s.channel);
    w = extract(w, 'time', snum, enum);
end