Description of load_from_datasource
Home > GISMO > core > @waveform > private > load_from_datasource.m
load_from_datasource
PURPOSE
load_from_datasource
SYNOPSIS
function w = load_from_datasource(ds, chans, startt, endt, combine_waves, usewkaround)
DESCRIPTION
load_from_datasource
 w = load_from_datasource(ds, chans, startt, endt, combine_waves)
CROSS-REFERENCE INFORMATION
This function calls:
combine CATALOG.COMBINE combine two Catalog objects
get GET - Get correlation properties
waveform WAVEFORM Extract a waveform object.
get
getfilename GETFILENAME returns a filename that is associated with a single SCNL
setinterpreter SETINTERPRETER changes the associated interpreter function
subdivide_files_by_date SUBDIVIDE_FILES_BY_DATE given a datasource and daterange return list of files
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
unique UNIQUE return set of unique scnlobjects from an array
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
waveform WAVEFORM Get waveforms from a threecomp object
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
get GET Get waveform properties
filter_by_time filter_by_time
get_load_routine determine the load function based upon the datasource's type
load_from_file load waveforms from a file using myLoadfunc
packDataRequest packDataRequest - encapsulate the request, allowing single structure to be passed around.
waveform WAVEFORM Waveform Class constructor
get GET - Get correlation properties
waveform WAVEFORM Extract a waveform object.
get GET: Get helicorder properties
This function is called by:
waveform WAVEFORM Waveform Class constructor
SUBFUNCTIONS
function tf = isVoidInterpreter(ds)
SOURCE CODE
function w = load_from_datasource(ds, chans, startt, endt, combine_waves, usewkaround)
   %load_from_datasource
   %
   % w = load_from_datasource(ds, chans, startt, endt, combine_waves)
   % determine the load function based upon the datasource's type
   if isVoidInterpreter(ds)
      ds = setinterpreter(ds, get_load_routine(ds, usewkaround));
   end
   request = packDataRequest(ds, chans, startt, endt, combine_waves);
   getter = get(ds,'interpreter');
   %w = getter(request, combine_waves);
   w = getter(request);
   % TODO: Trim waveform to request
   % maybe we're already done?
   return
   % -------------------------------------------------------------------
   % if the datasource is file based, or if it requires a user-defined
   % intepreter function, then do what follows.  Otherwise, we're done
   if ~isVoidInterpreter(ds)
      myLoadFunc = get(ds,'interpreter');
      %user_defined datasource
      ALLOW_MULTIPLE = true;
      ERROR_ON_EMPTY = true;
      for j = 1:numel(startt)
         myStartTime = startt(j);
         myEndTime = endt(j);
         % grab all files for date range, discarding duplicates
         fn = getfilename(ds, chans,subdivide_files_by_date(ds,myStartTime, myEndTime));
         fn = unique(fn);
         %load all waveforms for these files
         clear somew
         for i=1:numel(fn)
            w = load_from_file(myLoadFunc,fn{i},ALLOW_MULTIPLE, ERROR_ON_EMPTY);
            %w = w(ismember([w.cha_tag],[chans])); %keep only appropriate station/chan
            ct = w.cha_tag;
            w = w(ct.matching(chans)); %Not 100% sure about this one
            w = filter_by_time(w, myStartTime, myEndTime);
            if numel(w) > 0
               somew(i) = {w};
            end
         end %for fn
         if ~exist('somew','var')
            w = waveform; w = w([]);
         else
            if combine_waves,
               w = combine([somew{:}]);
            else
               w = [somew{:}];
            end
         end
         allw(j) = {w};
      end %each start time
      w = [allw{:}];
   end %~isVoidInterpreter
end
function tf = isVoidInterpreter(ds)
   tf = strcmpi(func2str(get(ds,'interpreter')),'void_interpreter');
end