Description of peel_option
Home > GISMO > core > @waveform > private > peel_option.m
peel_option
PURPOSE
SYNOPSIS
function [optExists, value, vargs] = peel_option(vargs, searchValue, searchClass, minPos)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
This function is called by:
waveform WAVEFORM Waveform Class constructor
SOURCE CODE
function [optExists, value, vargs] = peel_option(vargs, searchValue, searchClass, minPos)
   optExists = false; value = [];
   if minPos > numel(vargs)
      return
   end
   switch searchClass
      case 'char'
         for n = minPos:numel(vargs)
            if ischar(vargs{n})
               if isempty(searchValue) || strcmp(searchValue,vargs{n})
                  optExists = true; value = vargs{n}; vargs(n) = [];
                  return
               end
            end
         end
      otherwise
         for n = minPos: numel(vargs)
            if isa(vargs{n},searchClass)
               if isempty(searchValue) || vargs{n} == searchValue
                  optExists = true; value = vargs{n}; vargs(n) = [];
                  return
               end
            end
         end
   end
end