Description of time2offset
Home > GISMO > core > @waveform > private > time2offset.m
time2offset
PURPOSE
time2offset returns the offset within a waveform's data for time T
SYNOPSIS
function [offset actualTime] = time2offset(w,whichTime)
DESCRIPTION
time2offset returns the offset within a waveform's data for time T
 If the time is prior to existing samples, then offset=0 and actualTime=[]
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
extract EXTRACT creates a waveform with a subset of another's data.
SeismicTrace
SOURCE CODE
function [offset actualTime] = time2offset(w,whichTime)
   %time2offset returns the offset within a waveform's data for time T
   % If the time is prior to existing samples, then offset=0 and actualTime=[]
   st = get(w,'start'); %get matlab starting time
   F = get(w,'freq'); %number of samples/second
   whichTime = datenum(whichTime);
   %calculate the time offset within the waveform
   relativeMatlabTime = (whichTime * 86400) - (st * 86400);
   offset = round(relativeMatlabTime .* F + 1);
   actualTime = (offset-1) .* get(w,'period');
   actualTime = (actualTime ./ 86400) + st;
   if (offset < 1)
      %time is before samples listed.
      offset = 0;
      actualTime = [];
      return;
   end
end
% if...
% Scenario:         T   StartT  whichTime   relMatT  offset
% relMatT==Start    .01    1        1         0        0
% relMatT==start+1s .01    0        1sec      1sec     100