Description of unpackDataRequest
Home > GISMO > core > @waveform > private > unpackDataRequest.m
unpackDataRequest
PURPOSE
SYNOPSIS
function [dataSource, chanInfo, startTimes, endTimes, combineWaves] = unpackDataRequest(request)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_file LOAD_FILE
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_matfile LOAD_FILE
load_miniseed LOAD_MINISEED loads a waveform from MINISEED files
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
load_sac LOAD_SAC loads a waveform from SAC files
load_seisan LOAD_SEISAN loads a waveform from SEISAN files
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
antelopesource
SOURCE CODE
function [dataSource, chanInfo, startTimes, endTimes, combineWaves] = unpackDataRequest(request)
   dataSource = request.dataSource;
   chanInfo = request.chanInfo;
   startTimes = request.startTimes;
   endTimes = request.endTimes;
   combineWaves = request.combineWaves;
end