Description of abs
Home > GISMO > core > @waveform > abs.m
abs
PURPOSE
ABS Absolute value for the waveform object
SYNOPSIS
function w = abs(w)
DESCRIPTION
ABS Absolute value for the waveform object
   waveform = abs(waveform)
   equivelent to running "abs" on the data within the waveform.
   Input Argument
       WAVEFORM: waveform object       N-DIMENSIONAL
  input waveform may be N-dimensional
 See also ABS.
CROSS-REFERENCE INFORMATION
This function calls:
abs ABS Absolute value for the waveform object
This function is called by:
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
response_plot RESPONSE_PLOT plot an instrument response
scan SCAN scans a waveform for events which match a master.
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
db_get_origin_info ORIGIN = DB_GET_ORIGIN_INFO(EVENT,DATABASE_NAME) If EVENT is a vector
dd_collate dd_collate('event.dat')
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
synthb_aut This is synthetic219
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
agc This function applies automatic gain control (AGC) to each trace. This
check Check various features of a correlation object.
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
match Retain matching elements of two correlation objects.
norm C = NORM(C)
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorrrow XCORRROW Cross correlation for one or more traces.
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
oneMinuteData
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
colorbar_axis COLORBAR - Display color bar (color scale).
specgram SPECGRAM - plots spectrogram of waveforms
extract EXTRACT particle motion parameters from a threecomp object
plot PLOT plots a threecomp object
plot2 PLOT2 a figure of three component traces (deprecated).
plotpm PLOTPM Plot particle motion coefficients.
rotate Rotate component orientations
threecomp THREECOMP Object for three component waveform data
abs ABS Absolute value for the waveform object
clip CLIP clips a waveform's data at a particular max/min value range
hilbert HILBERT (for WAVEFORM objects) Discrete-time analytic Hilbert transform.
normalize
plot_panels PLOT_PANELS Plot multiple waveform objects as separate linked panels
plot_spectrum add_spectral_data Simple method to compute frequency
autoscale will automatically find the correct y-unites with which to plot something
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
resample RESAMPLE resamples a waveform at over every specified interval
waveform2rsam WAVEFORM2RSAM create an RSAM-like object from a waveform object
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
zero2nan ZERO2NAN: This function takes a waveform with gaps that have been filled
traceToWaveform traceToWaveform converts traceobjects to waveforms
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
agc acg apply automatic gain control to each trace
check Check various features of a correlation object.
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
match Retain matching elements of two correlation objects.
norm C = NORM(C)
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorrrow XCORRROW Cross correlation for one or more traces.
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
TraceData
amplitude_spectrum amplitude_spectrum Simple method to compute amplitude
autoscale autoscale automatically determine correct y-units for plotting
TraceSpectra
specgram specgram - plots spectrogram of traces
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
compute COMPUTE calculates the fast fourier transform of a waveform object
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
testWaveform
test_TraceData
messitup
SOURCE CODE
function w = abs(w)
   %ABS Absolute value for the waveform object
   %   waveform = abs(waveform)
   %   equivelent to running "abs" on the data within the waveform.
   %
   %   Input Argument
   %       WAVEFORM: waveform object       N-DIMENSIONAL
   %
   %  input waveform may be N-dimensional
   % See also ABS.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   for n=1:numel(w)
      w(n).data = abs(w(n).data);
   end
end