Description of addfield
Home > GISMO > core > @waveform > addfield.m
addfield
PURPOSE
ADDFIELD add fields and values to waveform object(s) V1.1
SYNOPSIS
function w = addfield(w,fieldname,value,noHistOption)
DESCRIPTION
ADDFIELD add fields and values to waveform object(s)                V1.1
   waveform = addfield(waveform, fieldname, value)
   This function creates a new user defined field, and fills it with the
   included value.  If fieldname exists, it will overwrite the existing
   value.
   Input Arguments
       WAVEFORM: a waveform object   N-DIMENSIONAL
       FIELDNAME: a string name
       VALUE: a value to be added for those fields.  Value can be anything
   Starting with version 1.0, waveform objects can hold user-defined
   fields.  To access the contents, use waveform/get, as you normally
   would.
   example:
       w = waveform; %start with a blank waveform.
       N = 1:45;     %create a variable containing the numbers 1-45
       S = 'Thursday'; %create a string variable
       C = {'first', 'second', N, S}; % create a cell aray with a variety
                                      % of data
       % add a field called "TESTFIELD", containing the numbers 1-45
       w = addfield(w,'TestField',N);
       % add another field called "MISHMOSH" containing the cell 'C'
       w = addfield(w,'mishmosh',C);
       disp(w) % results in the following output...
            station: UNK
            channel: EHZ
              start: 01-Jan-1970 00:00:00.00
                     duration(00:00:00.00)
               data: 0 samples
               freq: 100 Hz
              units: counts
             With misc fields...
             * TESTFIELD: [1x45] double object
             * MISHMOSH: [1x4] cell object
 See also WAVEFORM/SET, WAVEFORM/GET
CROSS-REFERENCE INFORMATION
This function calls:
set SET Set properties for correlation object
set SET: Set drumplot properties
set SET - Set filterobject properties
ismember ISMEMBER for scnlobjects
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
set SET inserts properties for threecomp object
ismember ISMEMBER waveform implementation of ismember
set SET Set properties for waveform object(s)
set SET Set properties for correlation object
set SET: Set helicorder properties
This function is called by:
apply_calib ADD RESPONSE FROM SUBNETS TO WAVEFORM OBJECTS
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
station_meta station_meta adds station metadata to a waveform
dmc_station_meta DMC_STATION_META adds station metadata to a waveform
cookbook COOKBOOK demonstrate the features of the mastercorr package.
scan SCAN scans a waveform for events which match a master.
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
db_get_arrival_info [ARRIVAL, ASSOC, ORIGIN, W] = DB_GET_ARRIVAL_INFO(ARID_LIST, DATABASE_NAME) Returns pertinent
db_get_origin_info ORIGIN = DB_GET_ORIGIN_INFO(EVENT,DATABASE_NAME) If EVENT is a vector
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
reducedisp_calc WAVEFORM = REDUCEDISP(WAVEFORM,DISTANCE) This function calculates the
interferogram C = INTERFEROGRAM(C)
oneMinuteData
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
create_demo_data This script was used once to create the demo dataset
threecomp THREECOMP Object for three component waveform data
loadobj LOADOBJ updates older versions of waveform class upon loading
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
sac2waveform SAC2WAVEFORM fill a waveform object from a sac header
waveform2sacheader WAVEFORM2SACHEADER generates a SAC header from a waveform object
antelopesource
iriswebservicesource
SeismicTrace
compute COMPUTE calculates the fast fourier transform of a waveform object
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
testWaveform
ideas2waveform OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
SOURCE CODE
function w = addfield(w,fieldname,value,noHistOption)
   %ADDFIELD add fields and values to waveform object(s)                V1.1
   %   waveform = addfield(waveform, fieldname, value)
   %   This function creates a new user defined field, and fills it with the
   %   included value.  If fieldname exists, it will overwrite the existing
   %   value.
   %
   %   Input Arguments
   %       WAVEFORM: a waveform object   N-DIMENSIONAL
   %       FIELDNAME: a string name
   %       VALUE: a value to be added for those fields.  Value can be anything
   %
   %   Starting with version 1.0, waveform objects can hold user-defined
   %   fields.  To access the contents, use waveform/get, as you normally
   %   would.
   %
   %   example:
   %       w = waveform; %start with a blank waveform.
   %       N = 1:45;     %create a variable containing the numbers 1-45
   %       S = 'Thursday'; %create a string variable
   %       C = {'first', 'second', N, S}; % create a cell aray with a variety
   %                                      % of data
   %
   %       % add a field called "TESTFIELD", containing the numbers 1-45
   %       w = addfield(w,'TestField',N);
   %
   %       % add another field called "MISHMOSH" containing the cell 'C'
   %       w = addfield(w,'mishmosh',C);
   %
   %       disp(w) % results in the following output...
   %            station: UNK
   %            channel: EHZ
   %              start: 01-Jan-1970 00:00:00.00
   %                     duration(00:00:00.00)
   %               data: 0 samples
   %               freq: 100 Hz
   %              units: counts
   %             With misc fields...
   %             * TESTFIELD: [1x45] double object
   %             * MISHMOSH: [1x4] cell object
   %
   %
   % See also WAVEFORM/SET, WAVEFORM/GET
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   useHistory = exist('noHistOption','var') && strcmpi(noHistOption,'nohist');
   if ischar(fieldname)
      fieldname = {upper(fieldname)}; %convert to cell
   else
      error('Waveform:addfield:invalidFieldname','fieldname must be a string')
   end
   actualfields = upper(fieldnames(w(1))); %get the object's intrinsic fieldnames
   if ismember(fieldname,actualfields)
      w = set(w, fieldname{1}, value); %set the value of the actual field
      warning('Waveform:addfield:fieldExists',...
         'Attempted to add intrinsic field.\nNo field added, but Values changed anyway');
      return
   end
   % Fieldname isn't one that is intrinsic to the waveform object
   for n=1:numel(w)                % for each possible waveform
      miscF = w(n).misc_fields;   % grab the misc_fields (cell of fieldnames)
      if ~any(strcmp(fieldname,miscF)) % if the field doesn't already exist...
         w(n).misc_fields = [miscF, fieldname]; %add the fieldname to the list
      end
      w(n) = set(w(n), fieldname{1},value);
   end
end