Description of addhistory
Home > GISMO > core > @waveform > addhistory.m
addhistory
PURPOSE
ADDHISTORY function in charge of adding history to a waveform
SYNOPSIS
function w = addhistory(w, whathappened,varargin)
DESCRIPTION
ADDHISTORY function in charge of adding history to a waveform
   waveform = addhistory(waveform, whathappened);
   waveform = addhistory(waveform, formatString, [variables...])
   Mostly, addhistory is internal to the waveform methods, and will be
   updated automatically when you change the waveform.  Things like
   filtering, taking a hilbert envelope, or detrending will automatically
   drop notes into the waveform's HISTORY field.
   The second way of using addhistory follows the syntax of sprintf
   Input Arguments
       WAVEFORM: a waveform object   N-DIMENSIONAL
       WHATHAPPENED: absolutely anything.  Really.
   AddHistory appends not only what happened, but also keeps track of WHEN
   it happened.
   Control of whether or not history is added automatically lies within
   the waveform constructor (in a global variable called WAVEFORM_HISTORY)
   example
       w = waveform; %create a blank waveform
       w = addhistory(w,'the following procedures done by DoIt.m');
       N = 1; M = 'Today'
       w = addhistory(w,'this is sample #%d date:%s',N,M);
       % output: "this is sample #1 date:Today"
 See also WAVEFORM/ADDFIELD, WAVEFORM/GET, WAVEFORM/HISTORY, SPRINTF
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
This function is called by:
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
crop c = CROP(c,[PRETRIG POSTTRIG])
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
align ALIGN resamples a waveform at over a specified interval
clearhistory CLEARHISTORY reset history of a waveform
clip CLIP clips a waveform's data at a particular max/min value range
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
loadobj LOADOBJ updates older versions of waveform class upon loading
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_sac LOAD_SAC loads a waveform from SAC files
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
remove_calib WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
set SET Set properties for waveform object(s)
stack STACK stacks data from array of waveforms
testWaveform
SOURCE CODE
function w = addhistory(w, whathappened,varargin)
   %ADDHISTORY function in charge of adding history to a waveform
   %   waveform = addhistory(waveform, whathappened);
   %   waveform = addhistory(waveform, formatString, [variables...])
   %
   %   Mostly, addhistory is internal to the waveform methods, and will be
   %   updated automatically when you change the waveform.  Things like
   %   filtering, taking a hilbert envelope, or detrending will automatically
   %   drop notes into the waveform's HISTORY field.
   %
   %   The second way of using addhistory follows the syntax of sprintf
   %
   %   Input Arguments
   %       WAVEFORM: a waveform object   N-DIMENSIONAL
   %       WHATHAPPENED: absolutely anything.  Really.
   %
   %   AddHistory appends not only what happened, but also keeps track of WHEN
   %   it happened.
   %
   %   Control of whether or not history is added automatically lies within
   %   the waveform constructor (in a global variable called WAVEFORM_HISTORY)
   %
   %   example
   %       w = waveform; %create a blank waveform
   %       w = addhistory(w,'the following procedures done by DoIt.m');
   %       N = 1; M = 'Today'
   %       w = addhistory(w,'this is sample #%d date:%s',N,M);
   %       % output: "this is sample #1 date:Today"
   %
   %
   % See also WAVEFORM/ADDFIELD, WAVEFORM/GET, WAVEFORM/HISTORY, SPRINTF
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   global WAVEFORM_HISTORY
   if nargin > 2,
      whathappened = sprintf(whathappened, varargin{:});
   end
   if WAVEFORM_HISTORY
      modtime = now;
      for N = 1 : numel(w);
         %History is stored in a cell, the format of which is [WHAT, WHEN]
         if isempty(w(N).history)
            w(N).history = {whathappened, modtime};
         else
            w(N).history = [w(N).history; {whathappened, modtime}];
         end
      end
   end
end