Description of clearhistory
Home > GISMO > core > @waveform > clearhistory.m
clearhistory
PURPOSE
CLEARHISTORY reset history of a waveform
SYNOPSIS
function w = clearhistory(w)
DESCRIPTION
CLEARHISTORY reset history of a waveform
   waveform = clearhistory(waveform)
   clears the history, leaving current date/time. To remove history
   altogether, use 'delfield'
   Input Argument
       WAVEFORM: a waveform object   N-DIMENSIONAL
   Control of whether or not history is added automatically lies within
   the waveform constructor (in a global variable called WAVEFORM_HISTORY)
 See also WAVEFORM/ADDHISTORY, WAVEFORM/DELFIELD, WAVEFORM/ADDFIELD.
CROSS-REFERENCE INFORMATION
This function calls:
addhistory ADDHISTORY function in charge of adding history to a waveform
This function is called by:
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
sac2waveform SAC2WAVEFORM fill a waveform object from a sac header
stack STACK stacks data from array of waveforms
testWaveform
SOURCE CODE
function w = clearhistory(w)
   %CLEARHISTORY reset history of a waveform
   %   waveform = clearhistory(waveform)
   %   clears the history, leaving current date/time. To remove history
   %   altogether, use 'delfield'
   %
   %   Input Argument
   %       WAVEFORM: a waveform object   N-DIMENSIONAL
   %
   %
   %   Control of whether or not history is added automatically lies within
   %   the waveform constructor (in a global variable called WAVEFORM_HISTORY)
   %
   %
   % See also WAVEFORM/ADDHISTORY, WAVEFORM/DELFIELD, WAVEFORM/ADDFIELD.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   [w.history] = deal({});
   w = addhistory(w,'Cleared History');
end