Description of clip
Home > GISMO > core > @waveform > clip.m
clip
PURPOSE
CLIP clips a waveform's data at a particular max/min value range
SYNOPSIS
function w = clip(w, vals)
DESCRIPTION
CLIP clips a waveform's data at a particular max/min value range
   waveform = clip(waveform, values)
   Input Arguments
       WAVEFORM: a waveform object   N-DIMENSIONAL
       VALUES: a number.  If a scalar, then amplitudes will be
           clipped at +/- value.  If a pair, eg. [Max, Min] then
           waveform will be clipped between these two values
   All values beyond maximum ranges will be set to the maximum range
 See also  WAVEFORM/DESPIKE
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
abs ABS Absolute value for the waveform object
addhistory ADDHISTORY function in charge of adding history to a waveform
disp DISP Waveform disp overloaded operator
disp CORRELATION/DISPLAY Command window display of a correlation object
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
DEP_xcorr C = XCORR(C)
testWaveform
SOURCE CODE
function w = clip(w, vals)
   %CLIP clips a waveform's data at a particular max/min value range
   %   waveform = clip(waveform, values)
   %
   %   Input Arguments
   %       WAVEFORM: a waveform object   N-DIMENSIONAL
   %       VALUES: a number.  If a scalar, then amplitudes will be
   %           clipped at +/- value.  If a pair, eg. [Max, Min] then
   %           waveform will be clipped between these two values
   %
   %   All values beyond maximum ranges will be set to the maximum range
   %
   %
   % See also  WAVEFORM/DESPIKE
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   if nargin < 2,
      vals = [];
   end
   switch numel(vals)
      case 0
         warning('Waveform:clip:noClipValue',...
            'No values given, waveform remains unclipped');
         return
      case 1 % clip at +/- input value
         if ~isnumeric(vals)
            error('Waveform:clip:invalidClipValue','Non-numeric clip value');
         end
         vals = abs(vals);
         disp(['Clipping at +/- ' num2str(vals)]);
         vals = [-vals vals];
      case 2
         if ~isnumeric(vals)
            error('Waveform:clip:invalidClipValue','Non-numeric clip value');
         end
         if vals(1) > vals(2)
            warning('Waveform:clip:reversedValues',...
               'Value1 %f > Value2 %f , Reversing', vals(1),vals(2));
            vals = vals([2 1]);
         end
         %everything is AOK
      otherwise
         warning('Waveform:clip:invalidClipValue',...
            'Invalid clip values. waveform remains unclipped. specify [min max] values');
         return
   end
   for N = 1: numel(w)
      d = w(N).data;
      d(d < vals(1)) = vals(1);
      d(d > vals(2)) = vals(2);
      w(N).data = d;
   end
   w = addhistory(w,...
      ['Clipped between ', num2str(vals(1)), ' and ', num2str(vals(2))] );
end