Description of combine
Home > GISMO > core > @waveform > combine.m
combine
PURPOSE
COMBINE merges waveforms based on start/end times and ChannelTag info.
SYNOPSIS
function combined_waveforms = combine (waveformlist)
DESCRIPTION
COMBINE merges waveforms based on start/end times and ChannelTag info.
 combined_waveforms = combine (waveformlist) takes a vector of waveforms
 and combines them based on SCNL information and start/endtimes.
 DOES NO OTHER CHECKS
CROSS-REFERENCE INFORMATION
This function calls:
extract EXTRACT extract matches to the master waveform
get GET - Get correlation properties
set SET Set properties for correlation object
sort C = SORT(C,'TIME')
waveform WAVEFORM Extract a waveform object.
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
extract
get GET for the scnl object
set SET - Set properties for scnlobject
unique UNIQUE return set of unique scnlobjects from an array
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
extract EXTRACT particle motion parameters from a threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
set SET inserts properties for threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
addhistory ADDHISTORY function in charge of adding history to a waveform
double DOUBLE returns a waveform's data as a double type
extract EXTRACT creates a waveform with a subset of another's data.
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
set SET Set properties for waveform object(s)
waveform WAVEFORM Waveform Class constructor
get GET - Get correlation properties
set SET Set properties for correlation object
sort C = SORT(C) Sorts traces from oldest to youngest.
waveform WAVEFORM Extract a waveform object.
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
Catalog CATALOG the blueprint for Catalog objects in GISMO
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_from_datasource load_from_datasource
antelopesource
sst2nan
sst2val SST2VAL: Set sections of waveform w to single value. Useful for setting
wfa2nan
waveform_antelope_test % Main function to generate tests
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
SUBFUNCTIONS
function w = piece_together(w)
function w = spliceAndPad(w1, w2, paddingAmount)
function w = spliceWaveform(w1, w2)
function result = overlaps(dt, sampleInterval)
function t = dt_seconds(w1,w2)
function w = timesort(w)
SOURCE CODE
function combined_waveforms = combine (waveformlist)
   %COMBINE merges waveforms based on start/end times and ChannelTag info.
   % combined_waveforms = combine (waveformlist) takes a vector of waveforms
   % and combines them based on SCNL information and start/endtimes.
   % DOES NO OTHER CHECKS
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   if numel(waveformlist) < 2  %nothing to do
      combined_waveforms = waveformlist;
      return
   end
   channelinfo = get(waveformlist,'channeltag');
   [uniquescnls, idx, scnlmembers] = unique(channelinfo);
   %preallocate
   combined_waveforms = repmat(waveform,size(uniquescnls));
   for i=1:numel(uniquescnls)
      w = waveformlist(scnlmembers == i);
      w = timesort(w);
      for j=(numel(w)-1):-1:1
         w(j) = piece_together(w(j:j+1));
         w(j+1) = waveform;
      end
      combined_waveforms(i) = w(1);
   end
end
function w = piece_together(w)
   if numel(w) > 2
      for i = numel(w)-1: -1 : 1
         w(i) = piece_together(w(i:i+1));
      end
      w = w(1);
      return;
   elseif numel(w) == 1
      return
   end
   if isempty(w(1))
      w = w(2);
      return;
   end;
   dt = dt_seconds(w(1),w(2));  %time overlap in seconds.
   sampleRates = round(get(w,'freq'));
   sampleInterval = 1 ./ sampleRates(1);
   if overlaps(dt, sampleInterval)
      w = spliceWaveform(w(1), w(2));
   else
      paddingAmount = round((dt * sampleRates(1))-1);
      w = spliceAndPad(w(1),w(2), paddingAmount);
   end
   w = w(1);
end
function w = spliceAndPad(w1, w2, paddingAmount)
   if paddingAmount > 0 && ~isinf(paddingAmount)
      toAdd = nan(paddingAmount,1);
   else
      toAdd = [];
   end
   w = set(w1,'data',[w1.data; toAdd; w2.data]);
end
function w = spliceWaveform(w1, w2)
   % NOTE * Function uses direct field access
   timesToGrab = sum(get(w1,'timevector') < get(w2,'start'));
   samplesRemoved = numel(w1.data) - timesToGrab;
   w = set(w1,'data',[double(extract(w1,'index',1,timesToGrab)); w2.data]);
   w= addhistory(w,'SPLICEPOINT: %s, removed %d points (overlap)',...
      datestr(get(w2,'start')),samplesRemoved);
end
function result = overlaps(dt, sampleInterval)
   result = (dt- sampleInterval .* 1.25) < 0;
end
function t = dt_seconds(w1,w2)
   %  w1----] t [----w2
   firstsampleT = get(w2,'start');
   lastsampleT = get(w1,'timevector'); lastsampleT = lastsampleT(end);
   t = firstsampleT*86400 - lastsampleT * 86400;
end
function w = timesort(w)
   [~, I] = sort(get(w,'start'));
   w = w(I);
end