Description of diff
Home > GISMO > core > @waveform > diff.m
diff
PURPOSE
DIFF Differentiate waveform
SYNOPSIS
function w = diff (w)
DESCRIPTION
DIFF Differentiate waveform
   waveform = diff(waveform)
   goes from Displacement -> Velocity -> Acceleration
   Input Arguments
       WAVEFORM: a waveform object   N-DIMENSIONAL
   Uses matlab's DIFF function to differentiate.  The way it handles the
   units may be a little kludegy.
   See also DIFF, WAVEFORM/INTEGRATE
CROSS-REFERENCE INFORMATION
This function calls:
diff DIFF differentiate each trace.
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
set SET inserts properties for threecomp object
diff DIFF Differentiate waveform
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
set SET Set properties for waveform object(s)
diff DIFF differentiate each trace.
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
diff DIFF differentiate each trace.
oneMinuteData
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
colorbar_axis COLORBAR - Display color bar (color scale).
diff DIFF Differentiate waveform
zero2nan ZERO2NAN: This function takes a waveform with gaps that have been filled
NewCorrelation
diff DIFF differentiate each trace.
TraceData
TraceSpectra
contiguous CONTIGUOUS find contiguous sequences in an input vector of integers
testWaveform
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
SOURCE CODE
function w = diff (w)
   %DIFF Differentiate waveform
   %   waveform = diff(waveform)
   %   goes from Displacement -> Velocity -> Acceleration
   %
   %   Input Arguments
   %       WAVEFORM: a waveform object   N-DIMENSIONAL
   %
   %   Uses matlab's DIFF function to differentiate.  The way it handles the
   %   units may be a little kludegy.
   %
   %   See also DIFF, WAVEFORM/INTEGRATE
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   Nmax = numel(w);
   allFreq = get(w,'freq');
   allUnits = get(w,'units'); %cell if numel(w)>1, char otherwise
   if ~iscell(allUnits)
      allUnits = {allUnits};
   end
   for I = 1 : Nmax
      w(I) = set(w(I),'data',diff(w(I).data) .* allFreq(I));
      tempUnits = allUnits{I};
      whereInUnits = strfind(tempUnits,' * sec');
      if isempty(whereInUnits)
         w(I) = set(w(I),'units', [tempUnits, ' / sec']);
      else
         tempUnits(whereInUnits(1) :whereInUnits(1)+5) = [];
         w(I) = set(w(I),'units',tempUnits);
      end
   end
end