Description of disp
Home > GISMO > core > @waveform > disp.m
disp
PURPOSE
DISP Waveform disp overloaded operator
SYNOPSIS
function disp(w)
DESCRIPTION
DISP Waveform disp overloaded operator
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
get GET - Get correlation properties
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
disp DISP - scnl disp overloaded operator
get GET for the scnl object
intersect intersect: Find the intersection between two SCNL objects. Returns only
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
This function is called by:
get_channeltags_active sites active for this day
get_timewindow GET_TIMEWINDOW
iceweb
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
uispecgram UISPECGRAM M-file for uispecgram.fig
incomplete OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
stream2waveform OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
response_get_from_db RESPONSE_GET_FROM_DB Get instrument response from database.
dmc_cookbook
irisFetch
extract EXTRACT extract matches to the master waveform
plot_stats PLOT_STATS plot statistics from master correlation algorithm
scan SCAN scans a waveform for events which match a master.
mastercorr_extract MASTERCORR_EXTRACT extract matches to the master waveform
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
hankelq HANKELQ Compute spectral ratio in two frequency bands
db_get_arrival_info [ARRIVAL, ASSOC, ORIGIN, W] = DB_GET_ARRIVAL_INFO(ARID_LIST, DATABASE_NAME) Returns pertinent
db_get_origin_info ORIGIN = DB_GET_ORIGIN_INFO(EVENT,DATABASE_NAME) If EVENT is a vector
dd_collate dd_collate('event.dat')
dd_make_scp DD_MAKE_SCP Create a draft control file for the correlation process
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
reducedisp_wfmeas REDUCEDISP_WFMEAS(STARTTIME,ENDTIME,SCNL,DIST,DS,DBOUT,FILT,TIMESTEP,ALGORITHM)
autobinsize Copied after modgiseis.xpy/autobinsize
bin_irregular BIN_IRREGULAR bin an irregularly-sampled timeseries (like earthquake origin times).
aef READ_CATALOG.AEF
seisan READ_CATALOG.SEISAN Read a Seisan event database - consisting of
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
which WHICH manage and switch between multiple GISMO archives
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
arrivals2waveforms ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
dbgetorigins DBGETORIGINS Load preferred origins from an Antelope CSS3.0
listMiniseedFiles LISTMINISEEDFILES retrieve a list of the Miniseed files referenced by a datasource, ChannelTag object and start/end times.
print_debug PRINT_DEBUG optionally display text based on the debug level.
Arrival Arrival the blueprint for Arrival objects in GISMO
Catalog CATALOG the blueprint for Catalog objects in GISMO
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
cookbook % Catalog Cookbook
disp CATALOG.DISP Display Catalog object
eev CATALOG.EEV - Browse an Catalog object one event at a time.
eventrate CATALOG.EVENTRATE
plotprmm CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
ChannelTag
EventRate
Sfile Class that describes data in a Seisan S-file
DEP_xcorr C = XCORR(C)
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
colormap C = COLORMAP(C)
correlation
display CORRELATION/DISPLAY Command window display of a correlation object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
interferogram C = INTERFEROGRAM(C)
match Retain matching elements of two correlation objects.
minus C = MINUS(C,I)
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
DEPRICATED_xcorr1xr This function performs cross correlations in sets by correlating one
DEPRICATED_xcorrcxc This function performs cross correlations of one correlation object
dendrogramplot Private method. See ../plot for details.
occurrenceplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
xcorr1x1 This function is the same as xcwfm1xr except that it uses matlab's xcorr
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
sort C = SORT(C,'TIME')
writedb WRITEDB write antelope database tables
xcorr C = XCORR(C)
disp DISP Datasource disp overloaded operator
display DISPLAY - datasource display overloaded operator
load_objects_from_file grab all the variables in a matlab file, and flip through them, returning
disp DISP - Filterobject disp overloaded operator
display DISPLAY - Filterobject display overloaded operator
filterobject FILTEROBJECT constructor for a filter object
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
despike %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
detectTremorEvents %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
oneMinuteData
reduce s.reduce('waveType', 'surface', 'waveSpeed', 2000, 'f', 2.0,);
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
tremorstalta rsam.detect Run an STA/LTA detector on a rsam object
disp DISP - scnl disp overloaded operator
display DISPLAY - scnlobject display overloaded operator
disp DISP - spectralobject disp overloaded operator
display DISPLAY - spectralobject display overloaded operator
cookbook This cookbook contains sample code to illustrate the basic functions of
cookbook_map COOKBOOK_MAP Plots a simple map to accompany cookbook data
diagnostic DIAGNOSTIC check for accurate behavior of threecomp object.
disp DISP Display threecomp object
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
plot3 PLOT3 Interactively make 3D plot of particle motion vector evolution
threecomp THREECOMP Object for three component waveform data
verify VERIFY Check for property conflicts in the threecomp object.
clip CLIP clips a waveform's data at a particular max/min value range
disp DISP Waveform disp overloaded operator
display DISPLAY Waveform Display overloaded operator
load_antelope_old load a waveform from antelope
load_file LOAD_FILE
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_matfile LOAD_FILE
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
resample RESAMPLE resamples a waveform at over every specified interval
savesac SAVESAC creates a SAC file from a waveform
waveform WAVEFORM Waveform Class constructor
antelopesource
get_antelope_traces GET_ANTELOPE_TRACE gets interesting data from database, and returns the tracebuf object
traceToWaveform traceToWaveform converts traceobjects to waveforms
iriswebservicesource
spatiotemporal_file
ChannelDetails
NewCorrelation
cookbook % Correlation object cookbook
dendrogramplot dendrogramplot create a dendrogram plot
disp CORRELATION/DISPLAY Command window display of a correlation object
interferogram C = INTERFEROGRAM(C)
match Retain matching elements of two correlation objects.
minus C = MINUS(C,I)
occurrenceplot Private method. See ../plot for details.
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
wiggleinterferogram Private method. See ../plot for details.
writedb WRITEDB write antelope database tables
xcorr xcorr calculate the correlation and lag for traces
xcorr1x1 This function is the same as xcwfm1xr except that it uses matlab's xcorr
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
SeismicTrace
disp disp Display information about SeismicTrace(s)
TraceData
TraceFilter
cookbook cookbook Cookbook for TraceFilter
cookbook cookbook Cookbook for TraceSpectra
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
disp DISP: Helicorder disp overloaded operator
display DISPLAY: Helicorder display overloaded operator
chk_t
utnow UTNOW
startup_GISMO STARTUP_GISMO recursively adds paths for contributed codes that build on
testWaveform
test_waveform_constructor test waveform creation
trloadcss_test % Main function to generate tests
waveform_antelope_test % Main function to generate tests
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
whichgismo WHICHGISMO Select from multiple GISMO archives.
SUBFUNCTIONS
function DispStr = size2str(sizeval)
SOURCE CODE
function disp(w)
   %DISP Waveform disp overloaded operator
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   if numel(w) > 1;
      disp(' ');
      fprintf('[%s] %s object with fields:\n', size2str(size(w)), class(w));
      disp('     ChannelTag');
      disp('     start');
      disp('     freq');
      disp('     data');
      disp('     units');
      disp('     history');
      % handle miscelleneous fields
      a = get(w(1),'misc_fields');
      for n=2:length(w);
         a = intersect(a,get(w(n),'misc_fields'));
      end
      if isempty(a) %no fields in common
         if ~isempty(get(w,'misc_fields'))
            % no fields in common, but fields exist
            disp('    With dissimilar fields');
         end
      else
         disp('   with common fields...')
         disp(a')
      end
   elseif numel(w) == 0
      disp('  no waveform');
   else %single waveform
      if isempty(get(w,'station')) | ...
            isempty(get(w,'channel')) | ...
            isnan(get(w,'Fs')) | ...
            get(w,'data_length')==0;
         disp('  (incomplete or empty waveform)');
      end
      fprintf(' ChannelTag: %-15s   [network.station.location.channel]\n', w.cha_tag.string);
      fprintf('      start: %s\n',get(w,'start_str'));
      fprintf('             duration(%s)\n' , get(w,'duration_str'));
      fprintf('       data: %d samples\n', numel(w.data));
      fprintf('       freq: %-10.4f Hz\n',get(w,'freq'));
      fprintf('      units: %s\n',get(w,'units'));
      historycount =  size(get(w,'history'));
      if historycount == 1
         plural='';
      else
         plural = 's';
      end
      fprintf('    history: [%d item%s], last modification: %s\n',...
         historycount(1), plural, datestr(max([w.history{:,2}])));
      if numel(get(w,'misc_fields')) > 0,
         disp('    With misc fields...');
      end;
      for n= get(w,'misc_fields')
         val = get(w,n{1}); %grab value associated with this misc_field
         displayIF = (isnumeric(val) || islogical(val)) && (numel(val)<=6);
         displayIF = displayIF || ischar(val);
         if strcmp(n{1},'HISTORY'), %special case!
            historycount =  size(val,1);
            if historycount == 1, plural=''; else, plural = 's'; end
            fprintf('    * HISTORY: [%d item%s], last modification: %s\n',...
               historycount, plural, datestr(max([val{:,2}])));
         else
            if ~displayIF
               %must be some sort of object or multiple-value field
               fprintf('    * %s: ',n{1});
               fprintf('[%s] %s object\n',...
                  size2str(size(val)), class(val) );
            else
               fprintf('    * %s: ',n{1});
               if ischar(val)
                  fprintf('%s',val);
               else
                  fprintf('%s',num2str(val));
               end
               fprintf('\n');
            end
         end
      end
   end
end
function DispStr = size2str(sizeval)
   % helper function that changes the way we view the size
   %   from : [1 43 2 6] (numeric)  to  '1x43x2x6' (char)
   DispStr = sprintf('x%d', sizeval);
   DispStr = DispStr(2:end);
end