Description of double
Home > GISMO > core > @waveform > double.m
double
PURPOSE
DOUBLE returns a waveform's data as a double type
SYNOPSIS
function n = double(W, option)
DESCRIPTION
DOUBLE returns a waveform's data as a double type
   N = double(waveform  [, option] )
   this is just a fancy way of saying get(W,'data')
   but can handle vectors of W. The data lengths of the vectors do not
   need to be the same.  By default it will zero-pad the end of all short
   vectors.  Using the OPTION, you can specify a NaN padding instead.
   Input Arguments
       WAVEFORM: a waveform object   assumed as 1xN DIMENSIONAL
               (If not, it will be treated as though it were 1xN!)
       OPTION: Handle to any function that creates an array of a
               dictated size.  The chosen function should work like:
               A = (nRows,nCols); and return a double array of the
               appropriate size. ex. @ones, @zeros, @nan.
   Output Arguments
       N: the columns of data
   example:
       % let W(1) be a waveform with data [0 1 2 5 3]
       % let W(2) be a waveform with data [2 5]
       Y = double(W);
       % Y is now [[ 0 2; 1 5; 2 0; 5 0; 3 0]
       Z = double(W,@nan); pads with NaN instead of zeros
       % Z is now [ 0 2; 1 5; 2 NaN; 5 NaN; 3 NaN]
 See also WAVEFORM/GET, NAN
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
ReadMSEEDFast ReadMSEEDFast(fileName)
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
irisFetch
scan SCAN scans a waveform for events which match a master.
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
conv c = CONV(c) convolves all traces with the final trace. By default the new
crop c = CROP(c,[PRETRIG POSTTRIG])
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
get GET - Get correlation properties
shadedplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr C = XCORR(C)
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
fft FFT Discrete Fourier transform. OVERLOADED for waveform & Spectralobject
ifft IFFT Inverse discrete Fourier transform. OVERLOADED FOR Spectralobject
pwelch PWELCH overloaded pwelch for spectralobjects
specgram SPECGRAM - plots spectrogram of waveforms
extract EXTRACT particle motion parameters from a threecomp object
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
plot PLOT plots a threecomp object
plotpm PLOTPM Plot particle motion coefficients.
rotate Rotate component orientations
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
mrdivide MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
mtimes MTIMES (*) Overloaded Matrix multiply for waveforms (UNIMPLEMENTED!).
plot PLOT plots a waveform object
plus PLUS (+) waveform addition w + q
power POWER (.^) waveform implementation of element-by-element power (.^)
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
set_sacheader set_sacheader modify sac header variables
rdivide RDIVIDE (./) Right array divide for WAVEFORMS.
stack STACK stacks data from array of waveforms
times TIMES (.*) overloaded Array multiply for WAVEFORM objects.
waveform WAVEFORM Waveform Class constructor
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
antelopesource
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
conv conv convolve all traces with the final trace
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
get GET - Get correlation properties
shadedplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr xcorr calculate the correlation and lag for traces
SeismicTrace
plot plot plots a SeismicTrace
TraceData
TraceSpectra
testWaveform
test_TraceData
SOURCE CODE
function n = double(W, option)
   %DOUBLE returns a waveform's data as a double type
   %   N = double(waveform  [, option] )
   %   this is just a fancy way of saying get(W,'data')
   %   but can handle vectors of W. The data lengths of the vectors do not
   %   need to be the same.  By default it will zero-pad the end of all short
   %   vectors.  Using the OPTION, you can specify a NaN padding instead.
   %
   %   Input Arguments
   %       WAVEFORM: a waveform object   assumed as 1xN DIMENSIONAL
   %               (If not, it will be treated as though it were 1xN!)
   %       OPTION: Handle to any function that creates an array of a
   %               dictated size.  The chosen function should work like:
   %               A = (nRows,nCols); and return a double array of the
   %               appropriate size. ex. @ones, @zeros, @nan.
   %
   %   Output Arguments
   %       N: the columns of data
   %
   %   example:
   %       % let W(1) be a waveform with data [0 1 2 5 3]
   %       % let W(2) be a waveform with data [2 5]
   %
   %       Y = double(W);
   %       % Y is now [[ 0 2; 1 5; 2 0; 5 0; 3 0]
   %
   %       Z = double(W,@nan); pads with NaN instead of zeros
   %       % Z is now [ 0 2; 1 5; 2 NaN; 5 NaN; 3 NaN]
   %
   % See also WAVEFORM/GET, NAN
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   if numel(W) <= 1
      n = W.data; %  assumption --> data is already a column of double!
      return
   end
   if nargin == 1
      createDefaultArray = @zeros;
   else
      if ischar(option)
         createDefaultArray = str2func(option);
      elseif isa(option,'function_handle')
         createDefaultArray = option;
      else
         error('waveform:double:invalidOption',...
            '''option'' must be either a function handle or function name.');
      end
   end
   m = get(W,'data_length');
   if isempty(m)
      n = [];
      return
   end
   m=m(:);
   if all(m == m(1))
      n = [W(:).data]; % easy-peazy since all data is of same length.
   else
      n = createDefaultArray(max(m),numel(W));
      for x=1:numel(W)
         n(1:m(x),x) = W(x).data; % assumes that data is a column of double!
      end
   end
end