Description of get
Home > GISMO > core > @waveform > get.m
get
PURPOSE
GET Get waveform properties
SYNOPSIS
function val = get(w,prop_name)
DESCRIPTION
GET Get waveform properties
   val = get(waveform,prop_name)
   Valid property names:
       CHANNELTAG, NETWORK, STATION, LOCATION, CHANNEL,
       CHANNELINFO : (gets the info as a string 'Net.Sta.Loc.Cha')
       FREQ, START_STR,
       END_STR, DATA, NYQ, PERIOD
     also:
       START, END : return datenum format (MatLab's format)
       START_EPOCH, END_EPOCH : return epoch format.
       DATA_LENGTH : return number of elements in data
       The following return time duration of data
       DURATION_STR :  text format
       DURATION: matlab (datenum) format
       DURATION_EPOCH : antelope (epoch) format (just # of seconds)
       TIMEVECTOR : return a vector of same length as data with
                    matlab-formatted times.
       MISC_FIELDS: gets a list of fields that were added to this waveform
       UNITS : Find out what units the data is in (ex. counts, nm/s)
   If waveform is N-dimensional, then VAL will be a cell of the same
   dimensions.  If GET would return single-values for the property, then
   VAL will be a matrix of type DOUBLE, arranged in the same dimensions.
       If additional fields were added to waveform using ADDFIELD, then
       values from these can be retrieved using the fieldname
       Example: Create a waveform, add a field, then get the field
           W = waveform;
           W = addfield(W,'P-pick', datenum('1/5/2007 02:12:15'));
           misc = get(W,'MISC_FIELDS'); %returns a cell with 'P-pick'
           PickTime = get(W,'P-pick'); % (same as) PickTime = get(W,misc);
   See also WAVEFORM/GETM, WAVEFORM/SET, WAVEFORM/ADDFIELD,
   WAVEFORM/DELFIELD
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
mep2dep convert a matlab date to an epoch date
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
apply_calib ADD RESPONSE FROM SUBNETS TO WAVEFORM OBJECTS
iceweb
makespectrogramthumbnails
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
waveform_remove_empty WAVEFORM_REMOVE_EMPTY remove empty waveform objects from a vector of waveform objects
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
uispecgram UISPECGRAM M-file for uispecgram.fig
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
demo_plutons
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
station_meta station_meta adds station metadata to a waveform
dmc_station_meta DMC_STATION_META adds station metadata to a waveform
extract EXTRACT extract matches to the master waveform
plot_stats PLOT_STATS plot statistics from master correlation algorithm
scan SCAN scans a waveform for events which match a master.
mastercorr_extract MASTERCORR_EXTRACT extract matches to the master waveform
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
hankelq HANKELQ Compute spectral ratio in two frequency bands
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
reducedisp_calc WAVEFORM = REDUCEDISP(WAVEFORM,DISTANCE) This function calculates the
reducedisp_wfmeas REDUCEDISP_WFMEAS(STARTTIME,ENDTIME,SCNL,DIST,DS,DBOUT,FILT,TIMESTEP,ALGORITHM)
reducedisp_write_wfmeas Opens DBNAME and inserts new reduced dispacement rows, one
arrival_histogram ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
depth_section DEPTH_SECTION plot depth sections of ray coverage.
tt_curve TRAVELTIME make travel time plots.
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
db_lookupunits LOOKUPUNITS checks the antelope database to find out what units are
listMiniseedFiles LISTMINISEEDFILES retrieve a list of the Miniseed files referenced by a datasource, ChannelTag object and start/end times.
cookbook % The SCNLOBJECT cookbook
EventRate
DEP_xcorr C = XCORR(C)
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
agc This function applies automatic gain control (AGC) to each trace. This
align c = ALIGN(c)
butter C = BUTTER(C,[TYPE],CUTOFF,[POLES])
cat c = cat(c1,c2,c3,...)
check Check various features of a correlation object.
cluster c = CLUSTER(c,CUTOFF) cuts the "branches" of the linkage tree to create
conv c = CONV(c) convolves all traces with the final trace. By default the new
cookbook % Correlation object cookbook
correlation
crop c = CROP(c,[PRETRIG POSTTRIG])
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
get GET - Get correlation properties
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
getstat c = GETSTAT(c)
interferogram C = INTERFEROGRAM(C)
linkage c = LINKAGE(c) Creates a hierarchical cluster tree for all waveforms in
match Retain matching elements of two correlation objects.
minus C = MINUS(C,I)
norm C = NORM(C)
corrplot Called internally by correlation/plot to plot correlation matrix.
dendrogramplot Private method. See ../plot for details.
eventplot Private method. See ../plot for details.
getval Function to extract a cell array from an
lagplot Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorrrow XCORRROW Cross correlation for one or more traces.
stack c = STACK(c)
verify VERIFY
writedb WRITEDB write antelope database tables
xcorr C = XCORR(C)
disp DISP Datasource disp overloaded operator
display DISPLAY - datasource display overloaded operator
getfilename GETFILENAME returns a filename that is associated with a single SCNL
isunassigned ISUNASSIGNED is true when no data source is associated with this object
query_file QUERY_FILE retrieves scnl, starttime and endtime information for all
cookbook % drumplot cookbook
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
display DISPLAY - Filterobject display overloaded operator
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
set SET - Set filterobject properties
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
oneMinuteData
scrollplot Created by Steven Lord, slord@mathworks.com
display DISPLAY - scnlobject display overloaded operator
ismember ISMEMBER for scnlobjects
colorbar_axis COLORBAR - Display color bar (color scale).
display DISPLAY - spectralobject display overloaded operator
fft FFT Discrete Fourier transform. OVERLOADED for waveform & Spectralobject
ifft IFFT Inverse discrete Fourier transform. OVERLOADED FOR Spectralobject
subdivide_axes returns handles for sub-axes of axis(h). These axes are createdb y
pwelch PWELCH overloaded pwelch for spectralobjects
specgram SPECGRAM - plots spectrogram of waveforms
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
align ALIGN Align and trim traces in threecomp object.
cookbook This cookbook contains sample code to illustrate the basic functions of
cookbook_map COOKBOOK_MAP Plots a simple map to accompany cookbook data
demo DEMO
diagnostic DIAGNOSTIC check for accurate behavior of threecomp object.
disp DISP Display threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
plot PLOT plots a threecomp object
plot2 PLOT2 a figure of three component traces (deprecated).
plot3 PLOT3 Interactively make 3D plot of particle motion vector evolution
plotpm PLOTPM Plot particle motion coefficients.
create_demo_data This script was used once to create the demo dataset
rotate Rotate component orientations
spin SPIN rotate and plot horizontal components
success SUCCESS Checks the success of a conversion to threecomp object.
threecomp THREECOMP Object for three component waveform data
verify VERIFY Check for property conflicts in the threecomp object.
align ALIGN resamples a waveform at over a specified interval
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
diff DIFF Differentiate waveform
disp DISP Waveform disp overloaded operator
display DISPLAY Waveform Display overloaded operator
double DOUBLE returns a waveform's data as a double type
extract EXTRACT creates a waveform with a subset of another's data.
fillgaps FILLGAPS - fill missing data with values of your choice
get GET Get waveform properties
getm GETM Get MULTIPLE waveform properties
gettimerange GETTIMERANGE returns the list of start and end times from a waveform array
integrate INTEGRATE integrates a waveform signal
isfield ISFIELD checks the presence of waveform fields.
ismember ISMEMBER waveform implementation of ismember
isvertical isvertical: Find all vertical component waveforms (boolean output)
legend legend creates a legend for a waveform graph
loadobj LOADOBJ updates older versions of waveform class upon loading
medfilt1 MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
mrdivide MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
pad PAD Pad a waveform from snum to enum
plot PLOT plots a waveform object
plot_panels PLOT_PANELS Plot multiple waveform objects as separate linked panels
plot_spectrum add_spectral_data Simple method to compute frequency
plus PLUS (+) waveform addition w + q
as_channeltag
autoscale will automatically find the correct y-unites with which to plot something
get_load_routine determine the load function based upon the datasource's type
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_from_datasource load_from_datasource
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
offset2time
time2offset time2offset returns the offset within a waveform's data for time T
waveform2sacheader WAVEFORM2SACHEADER generates a SAC header from a waveform object
rdivide RDIVIDE (./) Right array divide for WAVEFORMS.
remove_calib WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
resample RESAMPLE resamples a waveform at over every specified interval
savesac SAVESAC creates a SAC file from a waveform
set SET Set properties for waveform object(s)
sortby sortby sorts waveforms based on one of its properties
stack STACK stacks data from array of waveforms
times TIMES (.*) overloaded Array multiply for WAVEFORM objects.
waveform2rsam WAVEFORM2RSAM create an RSAM-like object from a waveform object
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
zero2nan ZERO2NAN: This function takes a waveform with gaps that have been filled
traceToWaveform traceToWaveform converts traceobjects to waveforms
NewCorrelation
corrplot corrplot plot the correlation matrix
dendrogramplot dendrogramplot create a dendrogram plot
eventplot Private method. See ../plot for details.
get GET - Get correlation properties
getval Function to extract a cell array from an
lagplot lagplot
minus C = MINUS(C,I)
occurrenceplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
SeismicTrace
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
TraceData
autoscale autoscale automatically determine correct y-units for plotting
TraceFilter
TraceSpectra
specgram specgram - plots spectrogram of traces
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
build BUILD: Helicorder builder function. A helicorder object (h) contains no
disp DISP: Helicorder disp overloaded operator
nan2sst
nan2wfa
ssd2sst
sst2nan
sst2ssd
sst2val SST2VAL: Set sections of waveform w to single value. Useful for setting
wfa2nan
wfa2sst
compute COMPUTE calculates the fast fourier transform of a waveform object
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
plot PLOT plot fourier transform of a waveform
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
correlation_diagnostics Test correlation toolbox
testScnlobject
testWaveform
messitup
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
SUBFUNCTIONS
function val = grabEndTime(w)
function val = stringDate(myDate)
function val = durationDate(myDate)
SOURCE CODE
function val = get(w,prop_name)
   %GET Get waveform properties
   %   val = get(waveform,prop_name)
   %
   %   Valid property names:
   %       CHANNELTAG, NETWORK, STATION, LOCATION, CHANNEL,
   %       CHANNELINFO : (gets the info as a string 'Net.Sta.Loc.Cha')
   %       FREQ, START_STR,
   %       END_STR, DATA, NYQ, PERIOD
   %     also:
   %       START, END : return datenum format (MatLab's format)
   %       START_EPOCH, END_EPOCH : return epoch format.
   %
   %       DATA_LENGTH : return number of elements in data
   %
   %       The following return time duration of data
   %       DURATION_STR :  text format
   %       DURATION: matlab (datenum) format
   %       DURATION_EPOCH : antelope (epoch) format (just # of seconds)
   %
   %       TIMEVECTOR : return a vector of same length as data with
   %                    matlab-formatted times.
   %
   %       MISC_FIELDS: gets a list of fields that were added to this waveform
   %       UNITS : Find out what units the data is in (ex. counts, nm/s)
   %
   %   If waveform is N-dimensional, then VAL will be a cell of the same
   %   dimensions.  If GET would return single-values for the property, then
   %   VAL will be a matrix of type DOUBLE, arranged in the same dimensions.
   %
   %       If additional fields were added to waveform using ADDFIELD, then
   %       values from these can be retrieved using the fieldname
   %
   %       Example: Create a waveform, add a field, then get the field
   %           W = waveform;
   %           W = addfield(W,'P-pick', datenum('1/5/2007 02:12:15'));
   %           misc = get(W,'MISC_FIELDS'); %returns a cell with 'P-pick'
   %           PickTime = get(W,'P-pick'); % (same as) PickTime = get(W,misc);
   %
   %
   %   See also WAVEFORM/GETM, WAVEFORM/SET, WAVEFORM/ADDFIELD,
   %   WAVEFORM/DELFIELD
   %  11/28/2008 added WAVEFORM_OBJECT_VERSION, which returns a single version
   %  field from the waveform object.  This is set with the constructor, and
   %  is used in load_obj.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   %global mep2dep
   %val_CELL = cell(size(w));
   %val = val_CELL;
   usedcell = false;
   singleWave = isscalar(w);
   switch upper(prop_name)
      % IDENTIFICATION PROPERTIES
      case {'STATION','CHANNEL','NETWORK','LOCATION'} %type:CELL
         val = get([w.cha_tag],prop_name);
         usedcell = true;
      case {'COMPONENT'} %type:CELL   GRANDFATHERED IN...
         val = get([w.cha_tag],'channel');
         usedcell = true;
         % DATA DESCRIBING PROPERTIES
      case {'FS', 'FREQ'} %type:DOUBLE
         val = [w.Fs];
      case 'DATA' %type:DOUBLE
         if singleWave
            val = w.data;
         else
            val = {w.data}; %cells of data values
            usedcell = true;
         end
      case 'NYQ' %type:DOUBLE
         val = [w.Fs] ./ 2;
      case 'PERIOD' %type:DOUBLE
         val = 1 ./ [w.Fs];
      case 'DATA_LENGTH' %type:DOUBLE
         val = zeros(size(w));
         for N = 1: numel(w)
            val(N) = numel(w(N).data);
         end
         % TIME PROPERTIES
      case {'START_STR'} %type:CELL
         val = stringDate([w.start]);
         usedcell = true;
      case {'START_EPOCH'} %type:DOUBLE
         val = mep2dep([w.start]);
      case {'START_MATLAB', 'START'} %type:DOUBLE
         val = [w.start];
      case {'END_STR'} %type:CELL
         val = stringDate(grabEndTime(w));
         usedcell = true;
      case {'END_EPOCH'} %type:DOUBLE
         val = mep2dep(grabEndTime(w));
      case {'END_MATLAB', 'END'} %type:DOUBLE
         val = grabEndTime(w);
      case {'DURATION_STR'} %type:CELL
         endvec = grabEndTime(w(:)) - [w(:).start];
         if numel(w) == 0
            val = durationDate(nan);
         elseif singleWave
            val = durationDate(endvec);
         else
            val = cell(size(w));
            for N = 1 : numel(w)
               val(N) = {durationDate(endvec(N))};
            end
            usedcell = true;
         end
      case {'DURATION_EPOCH'} %type:DOUBLE
         val = (grabEndTime(w) - [w.start]) * 86400;
         %epoch time is # of seconds.
      case {'DURATION_MATLAB', 'DURATION'} %type:DOUBLE
         val = grabEndTime(w) - [w.start];
      case {'TIMEVECTOR'} %type:CELL
         val = cell(size(w));
         for N = 1 : numel(w)
            Xvalues = linspace(w(N).start,get(w(N),'end'),length(w(N).data)+1);
            val{N} = Xvalues(1:end-1)';
         end
         usedcell = true;
      case {'MISC_FIELDS'} %type:CELL
         val = {w.misc_fields};
         usedcell = true;
      case {'UNITS'} %type : CELL
         val = {w.units};
         usedcell = true;
      case {'WAVEFORM_OBJECT_VERSION'}
         val = w(1).version;
      case {'SCNLOBJECT'} % legacy only
         % I'm making this whiny for now so it is obvious when things need to
         % be changed.  This warning should probably be pulled out once we
         % rerelease this.
         warning('waveform:get:scnlobjectsAreDepricated',...
            ['any usage of scnlobject should be replaced by ', ...
            '''channelinfo'' which uses the new ChannelTag class']);
         val = scnlobject([w.cha_tag]);
         %must add network & location, too.
      case {'CHANNELTAG'}
         val = [w.cha_tag];
      case {'CHANNELINFO'}
         val = string([w.cha_tag]);
      case {'HISTORY'}
         val = cell(size(w));
         for n=1:numel(w)
            val(n) = {w(n).history};
         end
         usedcell = true;
      otherwise
         %perhaps we're trying to get at one of the miscelleneous fields?
         val = cell(size(w));
         for n = 1 : numel(w)
            %loc is the position...
            %w(n).misc_fields should ALWAYS already be in uppercase
            mask = strcmp(upper(prop_name),w(n).misc_fields);
            %fieldwasfound = any(mask);
            %[fieldwasfound, loc] = ismember(prop_name, w(n).misc_fields);
            if any(mask)
               val{n} = w(n).misc_values{mask};
               %val{n} = w(n).misc_values{m};
            else
               error('Waveform:get:unrecognizedProperty',...
                  'Unrecognized property name : %s',  prop_name);
            end
         end
         %check to see if value can be returned as a numeric value instead
         %of cell.  Only if all values are numeric AND scalar
         numberize = true;
         for n=1:numel(val)
            if ~(isnumeric(val{n}) && isscalar(val{n}))
               numberize = false;
               usedcell = true;
               break
            end
         end
         if numberize,
            Z = val;
            val = nan(size(Z));
            for n=1:numel(Z)
               val(n) = Z{n};
            end
         end
   end;
   if (numel(val) == numel(w)) %THIS TEST CONDITIONALIZED 4/16/2008
      val = reshape(val,size(w)); %return values in proper shape
   end
   if usedcell && singleWave
      if isa(val,'cell')
         val = val{1}; % return the actual value, not a cell array
      end
   end;
end
%%%%%%%%%%%%%%%%
function val = grabEndTime(w)
   if isempty(w)
      %val = [];
      val = w.start;
      return
   end
   dlens = get(w,'data_length');
   dlens = dlens(:);
   myfrq = [w.Fs];
   myfrq = myfrq(:);
   seclen = dlens ./ myfrq;
   to_add = datenum([zeros(numel(w),5) seclen])';
   svals = [w(:).start];
   val = svals +  to_add;
   %endvec = datevec([w.start]) + [0 0 0 0 0 length(w.data)/w.Fs];
   %endvec = datevec([w.start]) + [0 0 0 0 0 get(w,'data_length') ./ get(w,'Freq')];
   %val = datenum(endvec);
end
%%%%%%%%%%%%%%%%
function val = stringDate(myDate)
   if isnan(myDate)
      warning('waveform:get:undefinedDate','Undefined date');
      val = 0;
      return
   end
   val = datestr(myDate,'yyyy-mm-dd HH:MM:SS.FFF');
end
%%%%%%%%%%%%%%%%
function val = durationDate(myDate)
   if isnan(myDate)
      %this likely happened because the frequency was undefined (NaN)
      val = '';
      return;
   end
   myDate = myDate(:);
   [yr, mo, da] = datevec(myDate);
   val = '';
   %if yr, val = [val sprintf('%2d years ',yr)]; end
   %if mo, val = [val sprintf('%2d months ',mo)]; end
   if (yr+mo+da)>1,
      val = [val sprintf('%4d days ',fix(myDate))];
   end
   val = [val datestr(myDate,'HH:MM:SS.FFF')];
end