Description of gettimerange
Home > GISMO > core > @waveform > gettimerange.m
gettimerange
PURPOSE
GETTIMERANGE returns the list of start and end times from a waveform array
SYNOPSIS
function [startTimeList endTimeList] = gettimerange(w)
DESCRIPTION
GETTIMERANGE returns the list of start and end times from a waveform array
[startTimeList endTimeList] = gettimerange(w)
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
get GET: Get helicorder properties
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
hankelq HANKELQ Compute spectral ratio in two frequency bands
load_file grab all the variables in a matlab file, and flip through them, returning
load_objects_from_file grab all the variables in a matlab file, and flip through them, returning
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
pad PAD Pad a waveform from snum to enum
plot PLOT plots a waveform object
plot_panels PLOT_PANELS Plot multiple waveform objects as separate linked panels
filter_by_time filter_by_time
scroll SCROLL scroll through the data in a waveform vector
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
spatiotemporal_file
SOURCE CODE
function [startTimeList endTimeList] = gettimerange(w)
   %GETTIMERANGE returns the list of start and end times from a waveform array
   %[startTimeList endTimeList] = gettimerange(w)
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   %specialized function that doesn't do much, ideal candidate for deprication
   startTimeList = get(w,'start');
   endTimeList = get(w,'end');
end