Description of isempty
Home > GISMO > core > @waveform > isempty.m
isempty
PURPOSE
ISEMPTY returns TRUE if waveform contains no data
SYNOPSIS
function TF = isempty(w)
DESCRIPTION
ISEMPTY returns TRUE if waveform contains no data
   TF = isempty(waveform);
   if multiple waveforms are passed, this returns 'true' ONLY if ALL
   waveforms are empty.
  See also ISEMPTY
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
uispecgram UISPECGRAM M-file for uispecgram.fig
ReadMSEEDFast ReadMSEEDFast(fileName)
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
xml2struct Convert xml file into a MATLAB structure
dmc_xml2struct Convert xml file into a MATLAB structure
irisFetch
extract EXTRACT extract matches to the master waveform
mastercorr_extract MASTERCORR_EXTRACT extract matches to the master waveform
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
ie_readchans IE_READCHANS Read and parse station/channel list from file
reducedisp_calc WAVEFORM = REDUCEDISP(WAVEFORM,DISTANCE) This function calculates the
reducedisp_wfmeas REDUCEDISP_WFMEAS(STARTTIME,ENDTIME,SCNL,DIST,DS,DBOUT,FILT,TIMESTEP,ALGORITHM)
write_lotos WRITE_LOTOS write files for LOTOS tomography codes.
calc_Mc CALC_MC Estimate magnitude of completeness
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
calc_McMaxCurvature CALC_MCMAXCURVATURE
synthb_aut This is synthetic219
importPlates IMPORTPLATES Import numeric data from a text file as column vectors.
aef READ_CATALOG.AEF
antelope READ_CATALOG.ANTELOPE load events from a CSS3.0 database using Antelope.
seisan READ_CATALOG.SEISAN Read a Seisan event database - consisting of
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
deprecated DEPRECATED issue a deprication warning
getpath GETPATH returns a path to GISMO toolbox(es)
remove REMOVE remove all paths to GISMO
rmgismo RMGISMO(SOURCE) removes all existing paths containing the phrase
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
dbgetorigins DBGETORIGINS Load preferred origins from an Antelope CSS3.0
print_debug PRINT_DEBUG optionally display text based on the debug level.
Arrival Arrival the blueprint for Arrival objects in GISMO
Catalog CATALOG the blueprint for Catalog objects in GISMO
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
eev CATALOG.EEV - Browse an Catalog object one event at a time.
ChannelTag
EventRate
Sfile Class that describes data in a Seisan S-file
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
cluster c = CLUSTER(c,CUTOFF) cuts the "branches" of the linkage tree to create
correlation
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
getstat c = GETSTAT(c)
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
dendrogramplot Private method. See ../plot for details.
eventplot Private method. See ../plot for details.
occurrenceplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
subset c = SUBSET(c,INDEX)
writedb WRITEDB write antelope database tables
xcorr C = XCORR(C)
getfilename GETFILENAME returns a filename that is associated with a single SCNL
load_objects_from_file grab all the variables in a matlab file, and flip through them, returning
setfile SETFILE associates a datasource object with a file (or directory)
subdivide_files_by_date SUBDIVIDE_FILES_BY_DATE given a datasource and daterange return list of files
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
getwaveform rsam.getwaveform() Get the waveform corresponding to the RSAM data
oneMinuteData
plotrsam [rsamobjects, ah]=plotrsam_wrapper(sta, chan, snum, enum, DATAPATH)
read_bob_file READ_BOB_FILE Load RSAM-like data from a BOB file into a SAM object.
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
ismember ISMEMBER for scnlobjects
scnlobject scnl (deprecated) : object that holds the stations, channel, network, and location for
colorbar_axis COLORBAR - Display color bar (color scale).
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
spectralobject SPECTRALOBJECT - spectralobject class constructor
align ALIGN Align and trim traces in threecomp object.
disp DISP Display threecomp object
get GET Get threecomp object properties.
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
rotate Rotate component orientations
spin SPIN rotate and plot horizontal components
threecomp THREECOMP Object for three component waveform data
verify VERIFY Check for property conflicts in the threecomp object.
addhistory ADDHISTORY function in charge of adding history to a waveform
align ALIGN resamples a waveform at over a specified interval
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
delfield DELFIELD removes fields from waveform object(s)
detrend DETREND remove linear trend from a waveform
diff DIFF Differentiate waveform
disp DISP Waveform disp overloaded operator
double DOUBLE returns a waveform's data as a double type
extract EXTRACT creates a waveform with a subset of another's data.
fillgaps FILLGAPS - fill missing data with values of your choice
get GET Get waveform properties
integrate INTEGRATE integrates a waveform signal
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
mean MEAN Average or mean value of waveform's data.
median MEDIAN middlemost value of waveform's sorted data.
min MIN Smallest value of a waveform.
pad PAD Pad a waveform from snum to enum
autoscale will automatically find the correct y-unites with which to plot something
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_from_file load waveforms from a file using myLoadfunc
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
peel_option
rqhd RQHD Read seismic handler (SH) header variables
sac2waveform SAC2WAVEFORM fill a waveform object from a sac header
winston_access
resample RESAMPLE resamples a waveform at over every specified interval
savesac SAVESAC creates a SAC file from a waveform
std STD Standard deviation of a waveform
taper WAVEFORM = TAPER(WAVEFORM,R) applies a cosine taper to the ends of a
var VAR Variance of a waveform's data
waveform WAVEFORM Waveform Class constructor
antelopesource
segtype2units segtype2units retrieves unit and description based on the segtype code
ChannelDetails
NewCorrelation
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
cluster cluster Construct agglomerative clusters from linkage for Seismic Traces
dendrogramplot dendrogramplot create a dendrogram plot
eventplot Private method. See ../plot for details.
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
getstat c = GETSTAT(c)
interferogram C = INTERFEROGRAM(C)
norm C = NORM(C)
occurrenceplot Private method. See ../plot for details.
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
subset c = SUBSET(c,INDEX)
taper TAPER tapers the ends of waveforms in the correlation object.
unifytracelengths unifytracelengths make all traces the same length (mode length)
wiggleinterferogram Private method. See ../plot for details.
writedb WRITEDB write antelope database tables
xcorr xcorr calculate the correlation and lag for traces
xcorrrow XCORRROW Cross correlation for one or more traces.
SeismicTrace
disp disp Display information about SeismicTrace(s)
plot plot plots a SeismicTrace
TraceData
autoscale autoscale automatically determine correct y-units for plotting
TraceSpectra
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
build BUILD: Helicorder builder function. A helicorder object (h) contains no
sst2nan
sst2val SST2VAL: Set sections of waveform w to single value. Useful for setting
wfa2nan
set SET: Set helicorder properties
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
plot PLOT plot fourier transform of a waveform
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
utnow UTNOW
testWaveform
SOURCE CODE
function TF = isempty(w)
   %ISEMPTY returns TRUE if waveform contains no data
   %   TF = isempty(waveform);
   %
   %   if multiple waveforms are passed, this returns 'true' ONLY if ALL
   %   waveforms are empty.
   %
   %
   %  See also ISEMPTY
   % VERSION: 1.0 of waveform objects
   % AUTHOR: Celso Reyes (celso@gi.alaska.edu)
   % LASTUPDATE: 2/6/2007
   %this rewrite short-circuits the check if any waveform is found that has no
   %data.
   TF = true;
   for n=1:numel(w)
      if ~isempty(w(n).data)
         TF = false;
         break
      end
   end
   % originally: TF = (get(w,'data_length') == 0) == 1;
end