Description of max
Home > GISMO > core > @waveform > max.m
max
PURPOSE
MIN Largest value of a waveform.
SYNOPSIS
function [Y, I] = max(w)
DESCRIPTION
MIN    Largest value of a waveform.
   Y = max(waveform)
   returns a scalar containing the minimum value of the waveform data
   [Y, I] = max(waveform)
   Input Arguments
       WAVEFORM: waveform object   N-DIMENSIONAL
   Output
       Y: array of same shape as WAVEFORM, with each element corresponding
          to the maximum value of each waveform
       I: index(es) of Y within each waveform.
   NOTE: If waveforms with no data are queried, Y and I will be NaN.  This
   differs from the built-in version of min which returns an empty set.
   This change allows max to be used for N-dimensional arrays of waveform
   objects.
   See also MAX, WAVEFORM/MIN, WAVEFORM/MEDIAN, WAVEFORM/MEAN, SORT.
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
plot_stats PLOT_STATS plot statistics from master correlation algorithm
scan SCAN scans a waveform for events which match a master.
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
depth_section DEPTH_SECTION plot depth sections of ray coverage.
map MAP plot a map of ray coverage.
tt_curve TRAVELTIME make travel time plots.
write_lotos WRITE_LOTOS write files for LOTOS tomography codes.
bin_irregular BIN_IRREGULAR bin an irregularly-sampled timeseries (like earthquake origin times).
bmemag BMEMAG
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
calc_McMaxCurvature CALC_MCMAXCURVATURE
seisan READ_CATALOG.SEISAN Read a Seisan event database - consisting of
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
dbgetorigins DBGETORIGINS Load preferred origins from an Antelope CSS3.0
Catalog CATALOG the blueprint for Catalog objects in GISMO
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
hist HIST plot histograms of magnitude distribution, depth
plotprmm CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
EventRate
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
correlation
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
norm C = NORM(C)
DEPRICATED_xcorr1xr This function performs cross correlations in sets by correlating one
DEPRICATED_xcorrcxc This function performs cross correlations of one correlation object
eventplot Private method. See ../plot for details.
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr1x1 This function is the same as xcwfm1xr except that it uses matlab's xcorr
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
waveform WAVEFORM Extract a waveform object.
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
getwaveform rsam.getwaveform() Get the waveform corresponding to the RSAM data
oneMinuteData
plot RSAM/PLOT plot rsam data
plotyy
read_bob_file READ_BOB_FILE Load RSAM-like data from a BOB file into a SAM object.
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
scrollplot Created by Steven Lord, slord@mathworks.com
tremorstalta rsam.detect Run an STA/LTA detector on a rsam object
colorbar_axis COLORBAR - Display color bar (color scale).
align ALIGN Align and trim traces in threecomp object.
plot PLOT plots a threecomp object
plot2 PLOT2 a figure of three component traces (deprecated).
plotpm PLOTPM Plot particle motion coefficients.
disp DISP Waveform disp overloaded operator
double DOUBLE returns a waveform's data as a double type
fix_data_length FIX_DATA_LENGTH adjust length of waveform data to allow batch processing
isfield ISFIELD checks the presence of waveform fields.
max MIN Largest value of a waveform.
normalize
plot PLOT plots a waveform object
plot_spectrum add_spectral_data Simple method to compute frequency
autoscale will automatically find the correct y-unites with which to plot something
waveform2sacheader WAVEFORM2SACHEADER generates a SAC header from a waveform object
resample RESAMPLE resamples a waveform at over every specified interval
scroll SCROLL scroll through the data in a waveform vector
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
antelopesource
NewCorrelation
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
eventplot Private method. See ../plot for details.
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
norm C = NORM(C)
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
waveform WAVEFORM Extract a waveform object.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
xcorr1x1 This function is the same as xcwfm1xr except that it uses matlab's xcorr
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
xcorr1xr_orig This function performs cross correlations in sets by correlating one
xcorrdec Same algorithm as xcorr1xr, except this function decomposes the complex
xcorrrow XCORRROW Cross correlation for one or more traces.
disp disp Display information about SeismicTrace(s)
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
plot plot plots a SeismicTrace
TraceData
autoscale autoscale automatically determine correct y-units for plotting
TraceSpectra
build BUILD: Helicorder builder function. A helicorder object (h) contains no
compute COMPUTE calculates the fast fourier transform of a waveform object
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
testWaveform
messitup
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
SOURCE CODE
function [Y, I] = max(w)
   %MIN    Largest value of a waveform.
   %   Y = max(waveform)
   %   returns a scalar containing the minimum value of the waveform data
   %   [Y, I] = max(waveform)
   %
   %   Input Arguments
   %       WAVEFORM: waveform object   N-DIMENSIONAL
   %
   %   Output
   %       Y: array of same shape as WAVEFORM, with each element corresponding
   %          to the maximum value of each waveform
   %       I: index(es) of Y within each waveform.
   %
   %   NOTE: If waveforms with no data are queried, Y and I will be NaN.  This
   %   differs from the built-in version of min which returns an empty set.
   %   This change allows max to be used for N-dimensional arrays of waveform
   %   objects.
   %
   %   See also MAX, WAVEFORM/MIN, WAVEFORM/MEDIAN, WAVEFORM/MEAN, SORT.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   Y = nan(size(w));
   I = nan(size(w));
   for n = 1 : numel(w);
      if isempty(w(n).data)
         warning('Waveform:max:noDataFound',...
            'no data in waveform #%d, index and value are set to NaN', n);
         continue
      end
      [Y(n), I(n)] = max(w(n).data);
   end
end