Description of mean
Home > GISMO > core > @waveform > mean.m
mean
PURPOSE
MEAN Average or mean value of waveform's data.
SYNOPSIS
function y = mean(w)
DESCRIPTION
MEAN Average or mean value of waveform's data.
   Y = mean(waveform)
   returns a scalar containing the mean value of the waveform data
   Input Arguments
       WAVEFORM: waveform object   N-DIMENSIONAL
   Output
       Y: array of same size as WAVEFORM, with each element corresponding
          to the mean value of the matching waveform
   NOTE: Values of NaN are ignored.
   See also NANMEAN, WAVEFORM/MIN, WAVEFORM/MAX, WAVEFORM/MEDIAN, SORT.
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
mean MEAN Average or mean value of waveform's data.
This function is called by:
hankelq HANKELQ Compute spectral ratio in two frequency bands
reducedisp_write_wfmeas Opens DBNAME and inserts new reduced dispacement rows, one
depth_section DEPTH_SECTION plot depth sections of ray coverage.
bmemag BMEMAG
calc_bmemag CALC_BMEMAG Calculate Maximum Likelihood b-value
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
agc This function applies automatic gain control (AGC) to each trace. This
check Check various features of a correlation object.
getstat c = GETSTAT(c)
interferogram C = INTERFEROGRAM(C)
minus C = MINUS(C,I)
makesynthwaves Add N traces of synthetic data to a correlation object. Alters properties: waves, trig,
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
stack c = STACK(c)
despike %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
oneMinuteData
reduce s.reduce('waveType', 'surface', 'waveSpeed', 2000, 'f', 2.0,);
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
specgram SPECGRAM - plots spectrogram of waveforms
extract EXTRACT particle motion parameters from a threecomp object
demean DEMEAN remove offset voltage from signal
fillgaps FILLGAPS - fill missing data with values of your choice
mean MEAN Average or mean value of waveform's data.
plot_spectrum add_spectral_data Simple method to compute frequency
waveform2sacheader WAVEFORM2SACHEADER generates a SAC header from a waveform object
resample RESAMPLE resamples a waveform at over every specified interval
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
agc acg apply automatic gain control to each trace
check Check various features of a correlation object.
getstat c = GETSTAT(c)
interferogram C = INTERFEROGRAM(C)
makesynthwaves Add N traces of synthetic data to a correlation object. Alters properties: waves, trig,
minus C = MINUS(C,I)
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
stack c = STACK(c)
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
disp disp Display information about SeismicTrace(s)
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
TraceData
specgram specgram - plots spectrogram of traces
build BUILD: Helicorder builder function. A helicorder object (h) contains no
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
plot PLOT plot fourier transform of a waveform
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
testWaveform
SOURCE CODE
function y = mean(w)
   %MEAN Average or mean value of waveform's data.
   %   Y = mean(waveform)
   %   returns a scalar containing the mean value of the waveform data
   %
   %   Input Arguments
   %       WAVEFORM: waveform object   N-DIMENSIONAL
   %
   %   Output
   %       Y: array of same size as WAVEFORM, with each element corresponding
   %          to the mean value of the matching waveform
   %
   %   NOTE: Values of NaN are ignored.
   %
   %   See also NANMEAN, WAVEFORM/MIN, WAVEFORM/MAX, WAVEFORM/MEDIAN, SORT.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   y = nan(size(w));
   % if the statistics toolbox is installed, use the builtin nanmean function
   % to ignore NaN values during the variance calculation.
   if ~isempty(ver('stats'))
      for I = 1 : numel(w);
         y(I) = nanmean( w(I).data );
      end
   else
      % the statistics toolbox is not installed, so any nan values will have
      % to be dealt with (ignored) manually.
      for I = 1 : numel(w);
         d = w(I).data;
         d = d(~isnan(d)); %ignore NaN values
         if ~isempty(d)
            y(I) = mean( d );
         end
      end
   end
end