Description of medfilt1
Home > GISMO > core > @waveform > medfilt1.m
medfilt1
PURPOSE
MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
SYNOPSIS
function w = medfilt1(w,size)
DESCRIPTION
MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
          Processing Toolbox) to waveform data
USAGE: w = medfilt1(w,size)
INPUTS: w    -  unfiltered waveform
        size -  size of median window (data points)
OUTPUTS: w = median filtered waveform
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
medfilt1 MEDFILT1 Median filter for RSAM objects
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
get GET Get waveform properties
medfilt1 MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
medfilt1 MEDFILT1 Median filter for RSAM objects
rsam
medfilt1 MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
medfilt1_test
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
SOURCE CODE
function w = medfilt1(w,size)
%MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
%          Processing Toolbox) to waveform data
%
%USAGE: w = medfilt1(w,size)
%
%INPUTS: w    -  unfiltered waveform
%        size -  size of median window (data points)
%
%OUTPUTS: w = median filtered waveform
% Author: Dane Ketner, Alaska Volcano Observatory
% $Date$
% $Revision$
for n=1:numel(w)
    s = get(w(n),'start');
    d = get(w(n),'data');
    d = medfilt1(d,size);
    w(n) = set(w(n),'data',d);
    w(n) = set(w(n),'start',s);
end