Description of median
Home > GISMO > core > @waveform > median.m
median
PURPOSE
MEDIAN middlemost value of waveform's sorted data.
SYNOPSIS
function y = median(w)
DESCRIPTION
MEDIAN middlemost value of waveform's sorted data.
   Y = median(waveform)
   returns a scalar containing the median value of the waveform data
   Input Arguments
       WAVEFORM: waveform object   N-DIMENSIONAL
   Output
       Y: array of same size as WAVEFORM, with each element corresponding
          to the median value of the matching waveform
   NOTE: NAN values are ignored
   See also NANMEDIAN, WAVEFORM/MIN, WAVEFORM/MAX, WAVEFORM/MEAN, SORT.
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
median MEDIAN middlemost value of waveform's sorted data.
This function is called by:
bin_irregular BIN_IRREGULAR bin an irregularly-sampled timeseries (like earthquake origin times).
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
Fs
oneMinuteData
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
extract EXTRACT particle motion parameters from a threecomp object
median MEDIAN middlemost value of waveform's sorted data.
resample RESAMPLE resamples a waveform at over every specified interval
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
TraceData
testWaveform
SOURCE CODE
function y = median(w)
   %MEDIAN middlemost value of waveform's sorted data.
   %   Y = median(waveform)
   %   returns a scalar containing the median value of the waveform data
   %
   %   Input Arguments
   %       WAVEFORM: waveform object   N-DIMENSIONAL
   %
   %   Output
   %       Y: array of same size as WAVEFORM, with each element corresponding
   %          to the median value of the matching waveform
   %
   %   NOTE: NAN values are ignored
   %
   %   See also NANMEDIAN, WAVEFORM/MIN, WAVEFORM/MAX, WAVEFORM/MEAN, SORT.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   y = zeros(size(w));
   %if the statistics toolbox is installed, use the builtin nanmedian function
   %to ignore NaN values during the variance calculation.
   if ~isempty(ver('stats'))
      for I = 1 : numel(w);
         y(I) = nanmedian(w(I).data);
      end
   else
      % the statistics toolbox is not installed, so any nan values will have
      % to be dealt with (ignored) manually.
      for I = 1 : numel(w);
         d = w(I).data;
         %data_to_med = data_to_med(~isnan(data_to_med));
         y(I) = median(d(~isnan(d)));
      end
   end
end