Description of min
Home > GISMO > core > @waveform > min.m
min
PURPOSE
MIN Smallest value of a waveform.
SYNOPSIS
function [Y, I] = min(w)
DESCRIPTION
MIN    Smallest value of a waveform.
   Y = min(waveform)
   returns a scalar containing the minimum value of the waveform data
   [Y, I] =
   Input Arguments
       WAVEFORM: waveform object   N-DIMENSIONAL
   Output
       Y: array of same size as WAVEFORM, with each element corresponding
          to the median value of the matching waveform
       I: index(es) of Y within each waveform.
   NOTE: If waveforms with no data are queried, Y and I will be NaN.  This
   differs from the built-in version of min which returns an empty set.
   This change allows min to be used for N-dimensional arrays of waveform
   objects.
   See also MIN, WAVEFORM/MAX, WAVEFORM/MEDIAN, WAVEFORM/MEAN, SORT.
CROSS-REFERENCE INFORMATION
This function calls:
isempty ISEMPTY Display threecomp object
isempty ISEMPTY returns TRUE if waveform contains no data
min MIN Smallest value of a waveform.
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
plot_stats PLOT_STATS plot statistics from master correlation algorithm
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
hankelq HANKELQ Compute spectral ratio in two frequency bands
db_get_origin_info ORIGIN = DB_GET_ORIGIN_INFO(EVENT,DATABASE_NAME) If EVENT is a vector
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
depth_section DEPTH_SECTION plot depth sections of ray coverage.
map MAP plot a map of ray coverage.
tt_curve TRAVELTIME make travel time plots.
bin_irregular BIN_IRREGULAR bin an irregularly-sampled timeseries (like earthquake origin times).
bmemag BMEMAG
calc_Mc CALC_MC Estimate magnitude of completeness
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
calc_McMaxCurvature CALC_MCMAXCURVATURE
calc_bmemag CALC_BMEMAG Calculate Maximum Likelihood b-value
synthb_aut This is synthetic219
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
arrivals2waveforms ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
dbget_closest_sites DBGET_CLOSEST_SITES Get closest sites from an Antelop database to a given [lon, lat]
readphafile READPHAFILE Read a Hypoellipse PHA pickfile
Catalog CATALOG the blueprint for Catalog objects in GISMO
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
eev CATALOG.EEV - Browse an Catalog object one event at a time.
hist HIST plot histograms of magnitude distribution, depth
EventRate
Sfile Class that describes data in a Seisan S-file
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
crop c = CROP(c,[PRETRIG POSTTRIG])
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
match Retain matching elements of two correlation objects.
eventplot Private method. See ../plot for details.
occurrenceplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
getwaveform rsam.getwaveform() Get the waveform corresponding to the RSAM data
oneMinuteData
plot RSAM/PLOT plot rsam data
plotyy
read_bob_file READ_BOB_FILE Load RSAM-like data from a BOB file into a SAM object.
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
scrollplot Created by Steven Lord, slord@mathworks.com
align ALIGN Align and trim traces in threecomp object.
isempty ISEMPTY Display threecomp object
plot PLOT plots a threecomp object
verify VERIFY Check for property conflicts in the threecomp object.
min MIN Smallest value of a waveform.
plot PLOT plots a waveform object
plot_panels PLOT_PANELS Plot multiple waveform objects as separate linked panels
autoscale will automatically find the correct y-unites with which to plot something
waveform2sacheader WAVEFORM2SACHEADER generates a SAC header from a waveform object
resample RESAMPLE resamples a waveform at over every specified interval
scroll SCROLL scroll through the data in a waveform vector
waveform2rsam WAVEFORM2RSAM create an RSAM-like object from a waveform object
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
antelopesource
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
crop crop crop all waveforms to a time window
eventplot Private method. See ../plot for details.
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
match Retain matching elements of two correlation objects.
occurrenceplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
disp disp Display information about SeismicTrace(s)
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
TraceData
build BUILD: Helicorder builder function. A helicorder object (h) contains no
testWaveform
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
SOURCE CODE
function [Y, I] = min(w)
   %MIN    Smallest value of a waveform.
   %   Y = min(waveform)
   %   returns a scalar containing the minimum value of the waveform data
   %   [Y, I] =
   %
   %   Input Arguments
   %       WAVEFORM: waveform object   N-DIMENSIONAL
   %
   %   Output
   %       Y: array of same size as WAVEFORM, with each element corresponding
   %          to the median value of the matching waveform
   %       I: index(es) of Y within each waveform.
   %
   %   NOTE: If waveforms with no data are queried, Y and I will be NaN.  This
   %   differs from the built-in version of min which returns an empty set.
   %   This change allows min to be used for N-dimensional arrays of waveform
   %   objects.
   %
   %   See also MIN, WAVEFORM/MAX, WAVEFORM/MEDIAN, WAVEFORM/MEAN, SORT.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   Y = nan(size(w));
   I = nan(size(w));
   for n = 1 : numel(w);
      if isempty(w(n).data)
         warning('Waveform:min:noDataFound',...
            'no data in waveform #%d, index and value are set to NaN', n);
         continue
      end
      [Y(n), I(n)] = min(w(n).data);
   end
end