Description of mrdivide
Home > GISMO > core > @waveform > mrdivide.m
mrdivide
PURPOSE
MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
SYNOPSIS
function C = mrdivide(W,B)
DESCRIPTION
MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function C = mrdivide(W,B)
   %MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
   % VERSION: 1.0 of waveform objects
   % AUTHOR: Celso Reyes (celso@gi.alaska.edu)
   % LASTUPDATE: 3/15/2009
   if ~(isnumeric(B))
      error('Waveform:mrdivide:invalidNumeratorClass',...
         'Cannot divide by a %s, must be numeric', class(B));
   end
   C = set(W, 'data', get(W,'data') / double(B));
end