Description of normalize
Home > GISMO > core > @waveform > normalize.m
normalize
PURPOSE
SYNOPSIS
function wn = normalize(w)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
demean DEMEAN removes the mean of each trace.
abs ABS Absolute value for the waveform object
demean DEMEAN remove offset voltage from signal
max MIN Largest value of a waveform.
demean DEMEAN removes the mean of each trace.
This function is called by:
plot PLOT plots a waveform object
SOURCE CODE
function wn = normalize(w)
w = demean(w);
m = max(abs(w));
wn = w./m;