Description of pad
Home > GISMO > core > @waveform > pad.m
pad
PURPOSE
PAD Pad a waveform from snum to enum
SYNOPSIS
function [ w ] = pad(w, snum, enum, padvalue)
DESCRIPTION
PAD Pad a waveform from snum to enum
   Sometimes it is useful to pad a waveform object
   so it starts earlier and ends later
   For example, you have 6 waveform objects, and you
   want to pad them so they all start and end at the same time
   This can be achieved with:
       [snum enum] = gettimerange(w) % assume gaps already filled, signal
       already detrended
       w2 = pad(w, min(snum), max(enum), 0)
CROSS-REFERENCE INFORMATION
This function calls:
extract EXTRACT extract matches to the master waveform
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
extract
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
extract EXTRACT particle motion parameters from a threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
set SET inserts properties for threecomp object
extract EXTRACT creates a waveform with a subset of another's data.
get GET Get waveform properties
gettimerange GETTIMERANGE returns the list of start and end times from a waveform array
isempty ISEMPTY returns TRUE if waveform contains no data
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
iceweb
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
load_antelope load a waveform from antelope
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
SOURCE CODE
function [ w ] = pad(w, snum, enum, padvalue)
%PAD Pad a waveform from snum to enum
%   Sometimes it is useful to pad a waveform object
%   so it starts earlier and ends later
%   For example, you have 6 waveform objects, and you
%   want to pad them so they all start and end at the same time
%   This can be achieved with:
%       [snum enum] = gettimerange(w) % assume gaps already filled, signal
%       already detrended
%       w2 = pad(w, min(snum), max(enum), 0)
% Glenn Thompson USF
    if ~exist('padvalue','var')
        padvalue=0; % could also be nanmean?
    end
    for waveform_num=1:numel(w)
        thisw = w(waveform_num);
        if isempty(thisw)
            continue;
        end
        y = get(thisw,'data');
        fs = get(thisw,'freq');
        [wsnum wenum] = gettimerange(thisw);
        if wsnum~=snum | wenum~=enum
            nbefore = round(86400*(wsnum-snum)*fs);
            nafter = round(86400*(enum-wenum)*fs);
            if nbefore>0
                y = [ones(nbefore, 1)*padvalue; y];
            end
            if nafter>0
                y = [y; ones(nafter, 1)*padvalue];
            end
            w(waveform_num)=set(thisw,'start',snum, 'data', y);
            % clip in case some waveforms are longer than requested range
            w(waveform_num) = extract(w(waveform_num), 'time', snum, enum);
        end
    end
end