Description of plot_helicorder
Home > GISMO > core > @waveform > plot_helicorder.m
plot_helicorder
PURPOSE
WAVEFORM/PLOT_HELICORDER Plot waveform objects as helicorders
SYNOPSIS
function [ output_args ] = plot_helicorder(w, varargin)
DESCRIPTION
WAVEFORM/PLOT_HELICORDER Plot waveform objects as helicorders
   Each waveform object is plotted as a separate helicorder plot using the
   drumplot class
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
demean DEMEAN removes the mean of each trace.
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
drumplot DRUMPLOT the blueprint for drumplot objects in GISMO
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
plot RSAM/PLOT plot rsam data
plot PLOT plots a threecomp object
demean DEMEAN remove offset voltage from signal
plot PLOT plots a waveform object
demean DEMEAN removes the mean of each trace.
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
plot plot plots a SeismicTrace
plot PLOT plot fourier transform of a waveform
This function is called by:
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
SOURCE CODE
function [ output_args ] = plot_helicorder(w, varargin)
%WAVEFORM/PLOT_HELICORDER Plot waveform objects as helicorders
%   Each waveform object is plotted as a separate helicorder plot using the
%   drumplot class
% Glenn Thompson 20160513
    for c=1:numel(w)
        h = drumplot(demean(w(c)), varargin{:});
        plot(h);
    end
end