Description of remove_calib
Home > GISMO > core > @waveform > remove_calib.m
remove_calib
PURPOSE
WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
SYNOPSIS
function w = remove_calib(w)
DESCRIPTION
WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
 which is automatically applied when reading waveforms from "wfdisc".
 The unit of output waveform will be in "COUNT"
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
addhistory ADDHISTORY function in charge of adding history to a waveform
delfield DELFIELD removes fields from waveform object(s)
get GET Get waveform properties
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function w = remove_calib(w)
   %WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
   % which is automatically applied when reading waveforms from "wfdisc".
   % The unit of output waveform will be in "COUNT"
   % AUTHOR: Yun Wang
   % $Date$
   % $Revision$
   % CHECK WAVEFORM
   if ~strcmpi(class(w),'waveform')
      error('Waveform:remove_calib:missingWaveform',...
         'Input must be a waveform object');
   end
   nrec = numel(w);
   for i = 1:nrec
      if(strcmp(get(w(i),'CALIBRATION_APPLIED'),'YES'))
         calib = get(w(i),'CALIB');
         % w.CALIB unit is nm/sec/count if w is in nm/sec
         w(i) = w(i)/calib;
         w(i) = set(w(i),'DATA',round(get(w(i),'DATA')));     % ensures integer values (counts)
         w(i) = addhistory(w(i),'Calibration removed');
         w(i) = delfield(w(i),'CALIBRATION_APPLIED');
         w(i) = delfield(w(i),'CALIB');
         w(i) = set(w(i),'UNITS','Counts');
      end
   end
end