Description of rms
Home > GISMO > core > @waveform > rms.m
rms
PURPOSE
RMS root mean square of a waveform
SYNOPSIS
function RMS = rms(W, varargin)
DESCRIPTION
RMS root mean square of a waveform
   RMS = sqrt((sum(signal .^2) / (N-1))
  Values of NaN are removed before RMS calculation.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
reducedisp_calc WAVEFORM = REDUCEDISP(WAVEFORM,DISTANCE) This function calculates the
sru readEvents.sru read a catalog sent by Seismic Research Unit, University of West
Sfile Class that describes data in a Seisan S-file
testWaveform
SOURCE CODE
function RMS = rms(W, varargin)
   %RMS root mean square of a waveform
   %   RMS = sqrt((sum(signal .^2) / (N-1))
   %
   %  Values of NaN are removed before RMS calculation.
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   RMS = zeros(size(W));
   for i = 1 : numel(W) %loop through an array of Waveforms
      Signal = W(i).data; %grab signal
      invalidMask = isnan(Signal);
      nInvalid = sum(invalidMask);
      N = length(Signal) - nInvalid; %
      RMS(i) = sqrt( sum(Signal(~invalidMask) .^ 2) / (N - 1) );
   end
end