Description of scroll
Home > GISMO > core > @waveform > scroll.m
scroll
PURPOSE
SCROLL scroll through the data in a waveform vector
SYNOPSIS
function scroll(w, timeStepSeconds)
DESCRIPTION
SCROLL scroll through the data in a waveform vector
CROSS-REFERENCE INFORMATION
This function calls:
extract EXTRACT extract matches to the master waveform
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
extract
plot RSAM/PLOT plot rsam data
scrollplot Created by Steven Lord, slord@mathworks.com
extract EXTRACT particle motion parameters from a threecomp object
plot PLOT plots a threecomp object
extract EXTRACT creates a waveform with a subset of another's data.
gettimerange GETTIMERANGE returns the list of start and end times from a waveform array
max MIN Largest value of a waveform.
min MIN Smallest value of a waveform.
plot PLOT plots a waveform object
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
plot plot plots a SeismicTrace
plot PLOT plot fourier transform of a waveform
This function is called by:
SOURCE CODE
function scroll(w, timeStepSeconds)
%SCROLL scroll through the data in a waveform vector
% fh = plot_panels(w);
% % hScrollLeft = uicontrol('Parent', fh, 'Style', 'pushbutton','String','<-','Position',[0 0 40 20]);
% % p = get(fh, 'Position');
% % hScrollRight = uicontrol('Parent', fh, 'Style', 'pushbutton','String','->','Position',[p(3)-40 0 40 20]);
%
%
% hScrollLeft = uicontrol('Parent', fh, 'Style', 'pushbutton','String','<-','Position',[0 0 0.05 0.01],'units','normalized');
% p = get(fh, 'Position');
% hScrollRight = uicontrol('Parent', fh, 'Style', 'pushbutton','String','->','Position',[0.95 0 0.05 0.01],'units','normalized');
%
% get(hScrollRight)
% set(hScrollRight,'units')
[snum enum]=gettimerange(w);
close all
h = scrollplot();
data = guidata(h);
data.w = w;
data.snum = min(snum);
data.enum = max(enum);
data.timeStep = timeStepSeconds/86400;
data.winstart = data.snum;
data.winend = data.snum + data.timeStep * 2;
data.zoomstart = data.winstart;
data.zoomend = data.winend;
data.we = extract(w,'time', data.winstart, data.winend);
data.autoscale = true;
guidata(h,data);
plot(data.we,'axeshandle',data.axes1,'autoscale',data.autoscale)
ylabel(data.axes1,'');
end