Description of set
Home > GISMO > core > @waveform > set.m
set
PURPOSE
SET Set properties for waveform object(s)
SYNOPSIS
function w = set(w, varargin)
DESCRIPTION
SET Set properties for waveform object(s)
   w = Set(w,prop_name, val, [prop_name, val])
   SET is one of the two gateway functions of an object, such as waveform.
   Properties that are changed through SET are typechecked and otherwise
   scrutinized before being stored within the waveform object.  This
   ensures that the other waveform methods are all retrieving valid data,
   thereby increasing the reliability of the code.
   Another strong advantage to using SET and GET to change  and retrieve
   properties, rather than just assigning them to the waveform directly,
   is that the underlying data structure can change and grow without
   harming the code that is written based on the waveform object.
   Valid property names:
       STATION, CHANNEL, FREQ, DATA, UNITS: self explanatory
       START :         Set the start-time using matlab format or string
       START_EPOCH:    Set the start-time using epoch (antelope) time
       SAMPLE_LENGTH : adjusts the length of the data to length VAL.
                       If this number is shorter than existing data, SET
                       truncates after sample VAL.  If it is longer, then
                       SET will pad the end with zeroes to get length VAL.
       If user-defined fields were added to the waveform (ie, through
       addField), these fieldnames are also available through set.
       for example
           % create a waveform object, and add a field called DUMMY with
           % the value 12
           w = addfield(waveform,'DUMMY',12);
           % change the value of the DUMMY field
           w = set(w,'DUMMY',32);
           % change the station and channel at once
           w = set(w,'Station','YCK', 'Channel', 'BHZ');
   Batch changes can be made if input w is a matrix (use with care!)
   NOTE: There is no set support for "version".  This is handled entirely
         within the waveform constructor and the loadobj function.
 NOTE: To avoid logging the history, append the argument 'nohist'
  See also WAVEFORM/GET
CROSS-REFERENCE INFORMATION
This function calls:
ChannelTag
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
addhistory ADDHISTORY function in charge of adding history to a waveform
get GET Get waveform properties
dep2mep convert an epoch date to a matlab date
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
apply_calib ADD RESPONSE FROM SUBNETS TO WAVEFORM OBJECTS
makespectrogramthumbnails
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
uispecgram UISPECGRAM M-file for uispecgram.fig
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
response_apply RESPONSE_APPLY Deconvolve an instrument response from a waveform object.
response_cookbook % Instrument response cookbook
response_plot RESPONSE_PLOT plot an instrument response
cookbook COOKBOOK example program using the IRIS DMC web services
dmc_cookbook
plot_stats PLOT_STATS plot statistics from master correlation algorithm
scan SCAN scans a waveform for events which match a master.
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
hankelq HANKELQ Compute spectral ratio in two frequency bands
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
arrival_histogram ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
dbload DBLOAD extracts travel times from a database
depth_section DEPTH_SECTION plot depth sections of ray coverage.
map MAP plot a map of ray coverage.
tt_curve TRAVELTIME make travel time plots.
synthb_aut This is synthetic219
db_lookupunits LOOKUPUNITS checks the antelope database to find out what units are
cookbook % The SCNLOBJECT cookbook
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
plot3 CATALOG.PLOT3 Plot hypocenters in 3-D
plot_time CATALOG.PLOT_TIME Plot magnitude and depth against time
plotprmm CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
EventRate
DEP_xcorr C = XCORR(C)
agc This function applies automatic gain control (AGC) to each trace. This
conv c = CONV(c) convolves all traces with the final trace. By default the new
cookbook % Correlation object cookbook
correlation
crop c = CROP(c,[PRETRIG POSTTRIG])
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
minus C = MINUS(C,I)
corrplot Called internally by correlation/plot to plot correlation matrix.
dendrogramplot Private method. See ../plot for details.
eventplot Private method. See ../plot for details.
lagplot Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
makesynthwaves Add N traces of synthetic data to a correlation object. Alters properties: waves, trig,
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
set SET Set properties for correlation object
stack c = STACK(c)
verify VERIFY
xcorr C = XCORR(C)
cookbook % drumplot cookbook
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
filterobject FILTEROBJECT constructor for a filter object
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
oneMinuteData
plot RSAM/PLOT plot rsam data
plotyy
scrollplot Created by Steven Lord, slord@mathworks.com
ismember ISMEMBER for scnlobjects
colorbar_axis COLORBAR - Display color bar (color scale).
loadobj LOADOBJ - handles updates to spectralobject
specgram SPECGRAM - plots spectrogram of waveforms
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
spectralobject SPECTRALOBJECT - spectralobject class constructor
align ALIGN Align and trim traces in threecomp object.
cookbook_map COOKBOOK_MAP Plots a simple map to accompany cookbook data
diagnostic DIAGNOSTIC check for accurate behavior of threecomp object.
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
plot PLOT plots a threecomp object
plot2 PLOT2 a figure of three component traces (deprecated).
plotpm PLOTPM Plot particle motion coefficients.
create_demo_data This script was used once to create the demo dataset
rotate Rotate component orientations
spin SPIN rotate and plot horizontal components
addfield ADDFIELD add fields and values to waveform object(s) V1.1
align ALIGN resamples a waveform at over a specified interval
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
diff DIFF Differentiate waveform
extract EXTRACT creates a waveform with a subset of another's data.
fillgaps FILLGAPS - fill missing data with values of your choice
fix_data_length FIX_DATA_LENGTH adjust length of waveform data to allow batch processing
integrate INTEGRATE integrates a waveform signal
loadobj LOADOBJ updates older versions of waveform class upon loading
medfilt1 MEDFILT1: Wrapper function for applying 1-D Median Filter (Signal
mrdivide MRDIVIDE (/) Slash or right matrix divide for WAVEFORMS.
mtimes MTIMES (*) Overloaded Matrix multiply for waveforms (UNIMPLEMENTED!).
pad PAD Pad a waveform from snum to enum
plot PLOT plots a waveform object
plot_panels PLOT_PANELS Plot multiple waveform objects as separate linked panels
autoscale will automatically find the correct y-unites with which to plot something
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
load_irisdmcws LOAD_IRISDMCWS loads waveforms using the IRIS Web Services Java Library
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
load_seisan LOAD_SEISAN loads a waveform from SEISAN files
load_winston LOAD_WINSTON handles retrieval of data from a winston waveserver.
sac2waveform SAC2WAVEFORM fill a waveform object from a sac header
remove_calib WAVEFORM = REMOVE_CALIB(WAVEFORM) removes calibration factor
resample RESAMPLE resamples a waveform at over every specified interval
set SET Set properties for waveform object(s)
smooth SMOOTH overloaded smooth function for waveform
stack STACK stacks data from array of waveforms
waveform2rsam WAVEFORM2RSAM create an RSAM-like object from a waveform object
zero2nan ZERO2NAN: This function takes a waveform with gaps that have been filled
traceToWaveform traceToWaveform converts traceobjects to waveforms
iriswebservicesource
ChannelDetails
NewCorrelation
cookbook % Correlation object cookbook
corrplot corrplot plot the correlation matrix
dendrogramplot dendrogramplot create a dendrogram plot
eventplot Private method. See ../plot for details.
lagplot lagplot
makesynthwaves Add N traces of synthetic data to a correlation object. Alters properties: waves, trig,
occurrenceplot Private method. See ../plot for details.
overlayplot Private method. See ../plot for details.
sampleplot Private method. See ../plot for details.
set SET Set properties for correlation object
shadedplot Private method. See ../plot for details.
statplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
wiggleplot Private method. See ../plot for details.
SeismicTrace
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
plot plot plots a SeismicTrace
autoscale autoscale automatically determine correct y-units for plotting
TraceSpectra
specgram specgram - plots spectrogram of traces
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
build BUILD: Helicorder builder function. A helicorder object (h) contains no
helicorder HELICORDER: Helicorder generates a multi-line display of input waveform
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
plot PLOT plot fourier transform of a waveform
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
amplitude_spectrum_test % Main function to generate tests
testScnlobject
testWaveform
messitup
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
ideas2waveform OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
SOURCE CODE
function w = set(w, varargin)
   %SET Set properties for waveform object(s)
   %   w = Set(w,prop_name, val, [prop_name, val])
   %   SET is one of the two gateway functions of an object, such as waveform.
   %   Properties that are changed through SET are typechecked and otherwise
   %   scrutinized before being stored within the waveform object.  This
   %   ensures that the other waveform methods are all retrieving valid data,
   %   thereby increasing the reliability of the code.
   %
   %   Another strong advantage to using SET and GET to change  and retrieve
   %   properties, rather than just assigning them to the waveform directly,
   %   is that the underlying data structure can change and grow without
   %   harming the code that is written based on the waveform object.
   %
   %   Valid property names:
   %
   %       STATION, CHANNEL, FREQ, DATA, UNITS: self explanatory
   %       START :         Set the start-time using matlab format or string
   %       START_EPOCH:    Set the start-time using epoch (antelope) time
   %       SAMPLE_LENGTH : adjusts the length of the data to length VAL.
   %                       If this number is shorter than existing data, SET
   %                       truncates after sample VAL.  If it is longer, then
   %                       SET will pad the end with zeroes to get length VAL.
   %
   %       If user-defined fields were added to the waveform (ie, through
   %       addField), these fieldnames are also available through set.
   %
   %       for example
   %           % create a waveform object, and add a field called DUMMY with
   %           % the value 12
   %           w = addfield(waveform,'DUMMY',12);
   %
   %           % change the value of the DUMMY field
   %           w = set(w,'DUMMY',32);
   %
   %           % change the station and channel at once
   %           w = set(w,'Station','YCK', 'Channel', 'BHZ');
   %
   %   Batch changes can be made if input w is a matrix (use with care!)
   %
   %   NOTE: There is no set support for "version".  This is handled entirely
   %         within the waveform constructor and the loadobj function.
   %
   % NOTE: To avoid logging the history, append the argument 'nohist'
   %
   %  See also WAVEFORM/GET
   % VERSION: 1.1 of waveform objects
   % AUTHOR: Celso Reyes (celso@gi.alaska.edu)
   % LASTUPDATE: March 15, 2009
   %4/22/08 added synonym for sample_length of data_length
   %global dep2mep
   % check to see if history is bypassed
   idx = numel(varargin);
   while idx > 1
      prop_name = upper(varargin{idx-1});
      val = varargin{idx};
      idx = idx - 2;
      %{
Vidx = 1 : numel(varargin);
while numel(Vidx) >= 2
  prop_name = upper(varargin{Vidx(1)});
  val = varargin{Vidx(2)};
      %}
      %for n = 1 : numel(w);
      %out = w(n);
      switch prop_name
         case 'SCNLOBJECT'
            switch class(val)
               case 'scnlobject'
                  [w.cha_tag] = deal(get(val,'channeltag'));
               case 'ChannelTag'
                  [w.cha_tag] = deal(val);
               case 'char'
                  [w.cha_tag] = deal(ChannelTag.parse(val));
               otherwise
                  % try it!
                  [w.cha_tag] = deal(ChannelTag(val));
                  % error('Waveform:set:propertyTypeMismatch','Expected a SCNLOBJECT or CHANNELTAG');
            end
            % whine while we refractor
            warning('Use set(ChannelTag) instead') % TODO: Decide if better generic name exists
         case {'CHANNELINFO', 'CHANNELTAG'}
            switch class(val)
               case 'scnlobject'
                  [w.cha_tag] = deal(ChannelTag(char(val)));
               case 'ChannelTag'
                  [w.cha_tag] = deal(val);
               case 'char'
                  [w.cha_tag] = deal(ChannelTag(val));
               otherwise
                  % try it!
                  [w.cha_tag] = deal(ChannelTag(val));
                  % error('Waveform:set:propertyTypeMismatch','Expected a SCNLOBJECT or CHANNELTAG');
            end
         case {'STATION','NETWORK', 'CHANNEL','LOCATION'}
            if ~ischar(val)
               error('Waveform:set:propertyTypeMismatch',...
                  '%s should be a string not a %s', prop_name,class(val));
            end
            all_chantags = set([w.cha_tag],prop_name,val);
            for n=1:numel(w)
               w(n).cha_tag = all_chantags(n);
            end
         case {'FS', 'FREQ'}
            if ~isnumeric(val)
               error('Waveform:set:propertyTypeMismatch',...
                  'Frequency should be numeric, not %s', class(val));
            end
            if numel(w)==1
               w.Fs = val(1);
            else
               [w.Fs] = deal(val(1));
            end
         case {'START', 'START_MATLAB'}
            %AUTOMATICALLY figures out whether date is antelope or matlab
            %format;
            if numel(val) == 1
               %expecting a number
               if numel(w) == 1
                  w.start = val;
               else
                  [w.start] = deal(val);
               end
            else
               %might be char, might be vector. give it a shot.
               if numel(w) == 1
                  w.start = datenum(val);
               else
                  [w.start] = deal(datenum(val));
               end
               % else
               %   error('Waveform:set:propertyTypeMismatch',...
               %    'Start time not assigned... Unknown value type: %s', class(val));
            end
         case {'START_ANTELOPE', 'START_EPOCH'}
            if ~isnumeric(val),
               error('Waveform:set:propertyTypeMismatch',...
                  'Epoch time should be numeric, not %s', class(val));
            end
            [w.start] = deal(datenum(dep2mep(val)));
         case 'DATA'
            if ~isnumeric(val)
               error('Waveform:set:propertyTypeMismatch',...
                  'DATA should be numeric, not %s', class(val));
            end
            if numel(w) == 1
               w.data = val(:);
            else
               [w.data] = deal(val(:)); %always a column
            end
         case 'UNITS'
            if ~ischar(val)
               error('Waveform:set:propertyTypeMismatch',...
                  'UNITS should be a string, not %s',class(val));
            end
            [w.units] = deal(val);
         case {'SAMPLE_LENGTH','DATA_LENGTH'} % chop data or zero pad to specific length
            if ~isnumeric(val),
               error('Waveform:set:propertyTypeMismatch',...
                  'SAMPLE_LENGTH should be numeric, not %s',class(val));
            end
            for n=1:numel(w);
               if numel(w(n).data) >= val
                  w(n).data = w(n).data(1:val,1);  % shrink the data
               else
                  w(n).data(numel(w(n).data)+1 :val , 1) = 0; %zero pad
               end
            end
         case 'HISTORY'
            w = addhistory(w, val);
         otherwise
            for n=1:numel(w)
               switch prop_name
                  case w(n).misc_fields
                     %mask = ismember(w(n).misc_fields, prop_name);
                     mask = strcmp(prop_name,w(n).misc_fields);
                     w(n).misc_values(mask) = {val};
                  otherwise
                     error('Waveform:set:unknownProperty',...
                        'can''t understand property name : %s', prop_name);
               end %switch
            end %n
      end %switch
      % Vidx(1:2) = []; %done with those parameters, move to the next ones...
   end
end