Description of sign
Home > GISMO > core > @waveform > sign.m
sign
PURPOSE
SIGN Signum function for waveforms.
SYNOPSIS
function w = sign(w)
DESCRIPTION
SIGN Signum function for waveforms.
 WAVEFORM = SIGN(WAVEFORM)
 see sign
CROSS-REFERENCE INFORMATION
This function calls:
sign SIGN removes the mean of each trace.
sign SIGN Signum function for waveforms.
sign SIGN convert traces to the sign of their data (+1, 0, -1)
This function is called by:
ReadMSEEDFast ReadMSEEDFast(fileName)
cookbook % Correlation object cookbook
sign SIGN removes the mean of each trace.
colorbar_axis COLORBAR - Display color bar (color scale).
sign SIGN Signum function for waveforms.
NewCorrelation
cookbook % Correlation object cookbook
sign SIGN convert traces to the sign of their data (+1, 0, -1)
TraceData
TraceSpectra
helicorder HELICORDER: Helicorder generates a multi-line display of input waveform
testWaveform
test_TraceData
SOURCE CODE
function w = sign(w)
   %SIGN Signum function for waveforms.
   % WAVEFORM = SIGN(WAVEFORM)
   % see sign
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   for n=1:numel(w)
      % w(n) = set(w(n),'data',sign(double(get(w(n),'data'))));
      w(n).data = sign(w(n).data);
   end
end