Description of smooth
Home > GISMO > core > @waveform > smooth.m
smooth
PURPOSE
SMOOTH overloaded smooth function for waveform
SYNOPSIS
function W = smooth(W, varargin)
DESCRIPTION
 SMOOTH overloaded smooth function for waveform
 Differs from MATLAB's smooth function in that it takes one or more
 waveforms instead of a data vector.
 See Also smooth
CROSS-REFERENCE INFORMATION
This function calls:
set SET Set properties for correlation object
set SET: Set drumplot properties
set SET - Set filterobject properties
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
set SET inserts properties for threecomp object
set SET Set properties for waveform object(s)
smooth SMOOTH overloaded smooth function for waveform
set SET Set properties for correlation object
set SET: Set helicorder properties
This function is called by:
EventRate
smooth SMOOTH overloaded smooth function for waveform
TraceData
SOURCE CODE
function W = smooth(W, varargin)
   % SMOOTH overloaded smooth function for waveform
   % Differs from MATLAB's smooth function in that it takes one or more
   % waveforms instead of a data vector.
   %
   % See Also smooth
   % AUTHOR: Celso Reyes, Geophysical Institute, Univ. of Alaska Fairbanks
   % $Date$
   % $Revision$
   for n = 1:numel(W)
      W(n) = set(W(n),'data',smooth(W(n).data,varargin{:}));
   end
end