Description of sortby
Home > GISMO > core > @waveform > sortby.m
sortby
PURPOSE
sortby sorts waveforms based on one of its properties
SYNOPSIS
function [W, I] = sortby(W, criteria)
DESCRIPTION
 sortby sorts waveforms based on one of its properties
 Wsorted = sortby(Win) sorts by the ChannelTag (N.S.L.C)
 Wsorted = sortby(Win, criteria), where criteria is a valid "get"
 request.  ex. starttime, endtime, channelinfo, freq, data_length, etc.
 [Wsorted, I] = sortby(Win...) will also return the index list so that
     Win(I) = Wsorted
 see also: sort, waveform/get
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
sort C = SORT(C,'TIME')
get
get GET: Get drumplot properties
get GET - Get filterobject properties
get GET for the scnl object
get GET - Get properties for spectralobject
get GET Get threecomp object properties.
get GET Get waveform properties
get GET - Get correlation properties
sort C = SORT(C) Sorts traces from oldest to youngest.
get GET: Get helicorder properties
This function is called by:
SOURCE CODE
function [W, I] = sortby(W, criteria)
   % sortby sorts waveforms based on one of its properties
   %
   % Wsorted = sortby(Win) sorts by the ChannelTag (N.S.L.C)
   %
   % Wsorted = sortby(Win, criteria), where criteria is a valid "get"
   % request.  ex. starttime, endtime, channelinfo, freq, data_length, etc.
   %
   % [Wsorted, I] = sortby(Win...) will also return the index list so that
   %     Win(I) = Wsorted
   %
   % see also: sort, waveform/get
   if nargin < 2
      criteria = 'channeltag';
   end
   % sort by a field
   [~, I] = sort(get(W,criteria));
   W = W(I);
end