Description of waveform2rsam
Home > GISMO > core > @waveform > waveform2rsam.m
waveform2rsam
PURPOSE
WAVEFORM2RSAM create an RSAM-like object from a waveform object
SYNOPSIS
function s = waveform2rsam(w, method, samplingPeriod)
DESCRIPTION
WAVEFORM2RSAM create an RSAM-like object from a waveform object
 RSAM data are typically 1 sample per minute, where each sample is the
 average amplitude of that minute of data. They are used extensively used
 in volcano monitoring.
 Usage:
   s = rsam(waveform, method, samplingPeriod)
   Input Arguments
       WAVEFORM: waveform object       N-dimensional
       METHOD: which method of sampling to perform within each sample
                window
           'max' : maximum value
           'min' : minimum value
           'mean': average value (Default)
           'median' : mean value
           'rms' : rms value (added 2011/06/01)
       SAMPLINGPERIOD : the number of seconds between samples (Default:
       60s)
   Examples:
       s = waveform2rsam(w) Each sample in the RSAM object is computed from a 60-s
       window of data. Successive windows do not overlap. Each window is
       detrended, NaN's replaced with mean value. Then the mean absolute
       value - i.e. the mean amplitude - is taken.
       s = waveform2rsam(w, 'rms') As above, but the root-mean-square absolute value
       is taken.
       s = waveform2rsam(w, 'max', 1.0) As above, but the max absolute value is
       taken, and the time window is 1s rather than 60s.
 Glenn Thompson 2014/10/28
CROSS-REFERENCE INFORMATION
This function calls:
detrend DETREND removes the slope of each trace.
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
rsam
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
abs ABS Absolute value for the waveform object
detrend DETREND remove linear trend from a waveform
fillgaps FILLGAPS - fill missing data with values of your choice
get GET Get waveform properties
min MIN Smallest value of a waveform.
resample RESAMPLE resamples a waveform at over every specified interval
set SET Set properties for waveform object(s)
detrend DETREND removes the slope of each trace.
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
separating_tremor_and_events Tremor range is 1-5 Hz
SOURCE CODE
function s = waveform2rsam(w, method, samplingPeriod)
%WAVEFORM2RSAM create an RSAM-like object from a waveform object
% RSAM data are typically 1 sample per minute, where each sample is the
% average amplitude of that minute of data. They are used extensively used
% in volcano monitoring.
%
% Usage:
%   s = rsam(waveform, method, samplingPeriod)
%
%   Input Arguments
%       WAVEFORM: waveform object       N-dimensional
%
%       METHOD: which method of sampling to perform within each sample
%                window
%           'max' : maximum value
%           'min' : minimum value
%           'mean': average value (Default)
%           'median' : mean value
%           'rms' : rms value (added 2011/06/01)
%
%       SAMPLINGPERIOD : the number of seconds between samples (Default:
%       60s)
%
%
%   Examples:
%       s = waveform2rsam(w) Each sample in the RSAM object is computed from a 60-s
%       window of data. Successive windows do not overlap. Each window is
%       detrended, NaN's replaced with mean value. Then the mean absolute
%       value - i.e. the mean amplitude - is taken.
%
%       s = waveform2rsam(w, 'rms') As above, but the root-mean-square absolute value
%       is taken.
%
%       s = waveform2rsam(w, 'max', 1.0) As above, but the max absolute value is
%       taken, and the time window is 1s rather than 60s.
%
% Glenn Thompson 2014/10/28
if ~exist('method', 'var')
    method = 'mean';
end
if ~exist('samplingPeriod', 'var')
    samplingPeriod = 60;
end
% detrend data after fill gaps to get rid of NaNs marking missing values
w = fillgaps(w, 'interp');
w = detrend(w);
for i = 1:numel(w)
    Wsamplingperiod = 1.0 / get(w(i), 'freq');
    % either set to whatever samplingPeriod seconds of data are, or the
    % length of data if less
    crunchfactor = min([round(samplingPeriod / Wsamplingperiod) numel(get(w(i),'data'))]);
    wabs = set(w(i), 'data', abs(get(w(i),'data')) );
    wresamp = resample(wabs, method, crunchfactor);
    s(i) = rsam(get(wresamp,'timevector')', get(wresamp,'data')', 'sta', get(wresamp, 'station'), 'chan', get(wresamp, 'channel'), 'units', get(wresamp, 'units'), 'snum', get(wresamp, 'start'), 'enum', get(wresamp, 'end'));
end