Description of is_sst
Home > GISMO > deprecated > @helicorder > private > SST > is_sst.m
is_sst
PURPOSE
IS_SST: Determine if array 'sst' is in proper SST format (Nx2 numeric)
SYNOPSIS
function bool = is_sst(sst)
DESCRIPTION
IS_SST: Determine if array 'sst' is in proper SST format (Nx2 numeric)
USAGE: bool = is_sst(sst)
INPUTS: sst - Event Start/Stop Times [Nx2 array of numeric time values]
OUTPUTS: bool - 1 or 0
 See also ADD_SST, CHK_T, COMPARE_SST, DELETE_SST, EXTRACT_SST, IS_SST,
          ISTEQUAL, MERGE_SST, SEARCH_SST, SORT_SST, NAN2SST, SSD2SST,
          SST2NAN, SST2SSD, SST2VAL, SST2WFA, WFA2SST
 Author: Dane Ketner, Alaska Volcano Observatory
 $Date$
 $Revision$
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
build BUILD: Helicorder builder function. A helicorder object (h) contains no
delete_sst DELETE_SST: Delete event SST (Start/Stop Times) between t1 and t2
extract_sst EXTRACT_SST: Extract event SST (Start/Stop Times) between t1 and t2
SOURCE CODE
function bool = is_sst(sst)
%IS_SST: Determine if array 'sst' is in proper SST format (Nx2 numeric)
%
%USAGE: bool = is_sst(sst)
%
%INPUTS: sst - Event Start/Stop Times [Nx2 array of numeric time values]
%
%OUTPUTS: bool - 1 or 0
%
% See also ADD_SST, CHK_T, COMPARE_SST, DELETE_SST, EXTRACT_SST, IS_SST,
%          ISTEQUAL, MERGE_SST, SEARCH_SST, SORT_SST, NAN2SST, SSD2SST,
%          SST2NAN, SST2SSD, SST2VAL, SST2WFA, WFA2SST
%
% Author: Dane Ketner, Alaska Volcano Observatory
% $Date$
% $Revision$
bool = 1;
if iscell(sst)
   for m = 1:numel(sst)
      if ~isnumeric(sst{m})||size(sst{m},2)~=2;
         bool =  0;
      end
   end
elseif ~isnumeric(sst)||size(sst,2)~=2;
   bool =  0;
end