Description of dendrogramplot
Home > GISMO > core > @correlation > private > dendrogramplot.m
dendrogramplot
PURPOSE
Private method. See ../plot for details.
SYNOPSIS
function dendrogramplot(c);
DESCRIPTION
 Private method. See ../plot for details.
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
disp DISP - scnl disp overloaded operator
get GET for the scnl object
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp disp Display information about SeismicTrace(s)
plot plot plots a SeismicTrace
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function dendrogramplot(c);
% Private method. See ../plot for details.
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
if ~isa(c,'correlation')
    error('First input must be a correlation object');
end;
if isempty(get(c,'LINK'))
    error('LINK field must be filled in input object');
end;
if ~isempty(get(c,'LAG'))
    disp('NOTE: Time corrections from LAG field have not been applied to traces yet.');
end;
% CREATE DENDROGRAM PLOT
[H,tmp,perm] = dendrogram(c.link,length(c.trig),'Orientation','right');
set(gcf,'Color','w','Position',[50 50 680 880]);
ylabel('event number','FontSize',16);
set(gca,'XGrid','on');
box on; hold on;
set(gcf,'Position',[0 0 640 1024]);
% SWITCH X AXIS LABELS
set(gca,'XDir','reverse');
% Fix by GT based on email by Kyle Brill, July 2016, see Issue 51
%label = 1- str2num(get(gca,'XTickLabel'));
label = 1- str2double(get(gca,'XTickLabel'));
set(gca,'XTickLabel',label);
%xlabel('distance (dissimilarlity)','FontSize',16);
xlabel('inter-cluster correlation','FontSize',16);
% MODIFY Y AXIS LABELS
if ~isempty(c.clust)
    YT = (get(gca,'YTickLabel'));
    %YT = strcat(YT,' (',num2str(c.clust(perm)),')');
    set(gca,'YTickLabel',YT);
    ylabel('event number (and cluster)','FontSize',16);
end
% PREP PRINT OUT
set(gcf, 'paperorientation', 'portrait');
set(gcf, 'paperposition', [.25 .25 8 10.5]);
% ADD WIGGLE PLOT
perm = fliplr(perm);
if length(perm)>=100
    plot(c,'sha',1,perm);
else
    plot(c,'wig',1,perm);
end
set(gcf,'Position',[641 0 640 1024]);