Description of lagplot
Home > GISMO > core > @correlation > private > lagplot.m
lagplot
PURPOSE
Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
SYNOPSIS
function lagplot(c);
DESCRIPTION
 Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
 $Date$
 $Revision$
CROSS-REFERENCE INFORMATION
This function calls:
colormap C = COLORMAP(C)
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
load Purpose:
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
get GET Get waveform properties
set SET Set properties for waveform object(s)
colormap colormap apply a colormap to the cross-correlation
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function lagplot(c);
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% PREP PLOT
figure('Color','w','Position',[50 50 600 500]);
set(gcf,'DefaultAxesFontSize',14);
imagesc(c.L);
title('Lag time for maximum correlation (s)');
% ADD DATES TO AXES
n = length(c.trig);
set(gca,'XTick',[1:round(n/25):n]);
set(gca,'YTick',[1:round(n/25):n]);
yt = get(gca,'YTick');
set(gca,'YTickLabel',datestr(c.trig(yt),'yyyy-mm-dd HH:MM'),'FontSize',6);
% DRESS UP THE FIGURE
cmap = load('colormap_lag.txt');
colormap(cmap);
colorbar;
xlabel('Event number');
ylabel('Event date');
%PRINT OUT FIGURE
set(gcf, 'paperorientation', 'portrait');
set(gcf, 'paperposition', [1.25 2.5 6 6]);
%print(gcf, '-depsc2', 'FIG_tartan.ps')