Description of overlayplot
Home > GISMO > core > @correlation > private > overlayplot.m
overlayplot
PURPOSE
Private method. See ../plot for details.
SYNOPSIS
function overlayplot(c,scale,ord)
DESCRIPTION
 Private method. See ../plot for details.
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
subset CATALOG.SUBSET Create a new catalogObject by subsetting based
correlation
get GET - Get correlation properties
norm C = NORM(C)
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
stack c = STACK(c)
subset c = SUBSET(c,INDEX)
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
abs ABS Absolute value for the waveform object
get GET Get waveform properties
max MIN Largest value of a waveform.
mean MEAN Average or mean value of waveform's data.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
stack STACK stacks data from array of waveforms
get GET - Get correlation properties
norm C = NORM(C)
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
stack c = STACK(c)
subset c = SUBSET(c,INDEX)
plot plot plots a SeismicTrace
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
NewCorrelation
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
SOURCE CODE
function overlayplot(c,scale,ord)
% Private method. See ../plot for details.
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% PREP PLOT
figure('Color','w','Position',[50 50 850 200]);
box on; hold on;
% GET TEMP CORRELATION OBJECT
c1 = correlation(c);
c1 = set(c1,'WAVEFORMS', get(c,'WAVEFORMS'));
c1 = set(c1,'TRIG', get(c,'TRIG'));
c1 = subset(c1,ord);
c1 = norm(c1);
c1 = stack(c1);
c1 = norm(c1);
% GET MEAN TRACE AMPLITUDE FOR SCALING BELOW
maxlist = [];
for i = 1:length(c1.trig)
    maxlist(end+1) = max(abs( get(c1.W(i),'DATA') ));
end;
normval = mean(maxlist);
% LOOP THROUGH WAVEFORMS
tmin =  999999;
tmax = -999999;
count = 0;
for i = 1:length(c1.trig)-1
    count = count + 1;
    d = get(c1.W(i),'DATA');
    d = scale * d/normval;
    d = -1 * d;                 % because scale is reversed below
    wstartrel = 86400*(get(c1.W(i),'START_MATLAB')-c1.trig(i));    % relative start time (trigger is at zero)
    tr = wstartrel + [ 0:length(d)-1]'/get(c1.W(i),'Fs');
    plot(tr,d,'-','Color',[.4 .4 1],'LineWidth',1);
    % save min and max relative trace times
    if tr(1) < tmin
        tmin = tr(1);
    end;
    if tr(end) > tmax
        tmax = tr(end);
    end;
end;
% PLOT THE STACK OF TRACES
d = get(c1.W(end),'DATA');
d = scale * d/normval;
d = -1 * d;
wstartrel = 86400*(get(c1.W(end),'START_MATLAB')-c1.trig(end));
tr = wstartrel + [ 0:length(d)-1]'/get(c1.W(end),'Fs');
plot(tr,d,'k-','LineWidth',2);
% adjust figure
axis([tmin tmax -1.1 1.1]);
set(gca,'YDir','reverse');
set(gca,'YTick',[]);
xlabel('Relative Time,(s)','FontSize',8);
text(tmin,-0.8,[' (' num2str(length(c1.trig)-1) ' traces)'],'HorizontalAlignment','Left');
%PRINT OUT FIGURE
set(gcf, 'paperorientation', 'portrait');
set(gcf, 'paperposition', [.25 5 8 2]);
%print(gcf, '-depsc2', 'FIG_alignwfm.ps')