Description of dmc_cookbook
Home > GISMO > contributed > iris_dmc_tools > dmc_cookbook.m
dmc_cookbook
PURPOSE
SYNOPSIS
function dmc_cookbook
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
dmc_station_meta DMC_STATION_META adds station metadata to a waveform
disp CATALOG.DISP Display Catalog object
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
disp DISP Datasource disp overloaded operator
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
set SET - Set filterobject properties
load Purpose:
disp DISP - scnl disp overloaded operator
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
set SET - Set properties for spectralobject
disp DISP Display threecomp object
set SET inserts properties for threecomp object
success SUCCESS Checks the success of a conversion to threecomp object.
waveform WAVEFORM Get waveforms from a threecomp object
disp DISP Waveform disp overloaded operator
set SET Set properties for waveform object(s)
waveform WAVEFORM Waveform Class constructor
disp CORRELATION/DISPLAY Command window display of a correlation object
set SET Set properties for correlation object
waveform WAVEFORM Extract a waveform object.
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function dmc_cookbook
disp('UNDER CONSTRUCTION ...');
% CREATE WAVEFORMS
% These waveforms are empty but contain network_station_channel info
stas = {'CKN' 'CGL' 'CRP' 'CRP' 'CRP' 'CRP' 'SPU' 'CKL' 'CKT' 'BGL' 'NCG' 'JUNK'};
chanTags = ChannelTag.array('AV',stas,'--','EHZ');
for n = numel(chantags) : -1 : 1;
   w(n) = set(waveform,'channelinfo',chanTags(n));
   w(n) = set(w(n),'DATA',rand(1)*sin(2*pi*rand(1):.05:100));
   w(n) = set(w(n),'FREQ',20);
   w(n) = set(w(n),'START',randi([datenum('2008/01/01') datenum('2011/01/01')]));
end
% LOAD TEST DATA FROM THE MASTER EVENT CORRELATION TOOLBOX
load mastercorr_cookbook_data.mat
% QUERY THE IRIS DMC FOR STATION METADATA
% The final waveform does not contains a network_station combination that
% does not exist in the DMC. No metadata is returned for this station. The
% boolean mask SUCCESS can be used to test for this.
[w,success] = dmc_station_meta(w)
[w,success] = dmc_station_meta(w,'CheckEach')