Description of irisFetch
Home > GISMO > contributed > iris_dmc_tools > irisFetch.m
irisFetch
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
irisFetch
disp CATALOG.DISP Display Catalog object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
disp DISP - scnl disp overloaded operator
ismember ISMEMBER for scnlobjects
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
isempty ISEMPTY Display threecomp object
disp DISP Waveform disp overloaded operator
double DOUBLE returns a waveform's data as a double type
isempty ISEMPTY returns TRUE if waveform contains no data
ismember ISMEMBER waveform implementation of ismember
disp CORRELATION/DISPLAY Command window display of a correlation object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
irisFetch
SUBFUNCTIONS
function v = version()
function ts = Traces(network, station, location, channel, startDate, endDate, varargin)
function extractAdditionalArguments(argList)
function getTheTraces()
function [channelStructure, urlParams] = Channels(detailLevel, varargin)
function [stationStructure, urlParams] = Stations(detailLevel, varargin)
function [networkStructure, urlParams] = Networks(detailLevel, network, station, location, channel, varargin)
function verifyArguments(nArgs)
function setOutputLevel()
function connectToStationService()
function setBaseUrlFromParameterList()
function removeParameter(s)
function [p, i] = getParameter(s)
function pn = parameterNames()
function pv = parameterValues()
function setCriteria()
function fetchTheStations()
function [events, urlParams] = Events(varargin)
function connectToJar(isSilent)
function [respstructures, urlparams] = Resp(network, station, location, channel, starttime, endtime)
function runExamples()
function channelList = flattenToChannel(networkTree)
function stationList = flattenToStation(networkTree)
function [js, je] = testResp(starttime, endtime)
function testThis(varargin)
function javadateTime = showTimeInDetail(t)
function myDateStr = makeDateStr(dateInput)
function d = jArrayList2complex(jArrayList)
function mts = convertTraces(traces)
function javadate = mdate2jdate(matlabdate)
function M = getSettableFields(obj)
function [M, argType] = getSetters(obj)
function [M, argType] = getSetters(obj)
function [methodList, argType] = getMethods(obj,searchPrefix)
function [getterList, fieldList] = getMethodsAndFields(obj)
function out = parser_for_IRIS_WS_2_0_0(value)
function s = parse(value,stacklistt)
function matlabdate = jdate2mdate(javadate)
function s = addUnits(theUnit)
function s = parseAnArray(theArray)
function crit = addCriteria(crit, value, addMethod)
function crit = setBoxCoordinates(crit, value)
function crit = setCriteria(crit, paramList)
SOURCE CODE
classdef irisFetch
   % IRISFETCH allows seamless access to data stored within the IRIS-DMC via FDSN services
   %
   % irisFetch Methods:
   %
   % irisFetch waveform retrieval Methods:
   %    Traces - retrieve sac-equivalent waveforms with channel metadata
   %
   % irisFetch FDSN station webservice Methods:
   %    Channels - retrieve metadata as an array of channels
   %    Stations - retrieve metadata as an array of stations
   %    Networks - retrieve metadata as an array of networks
   %
   % irisFetch FDSN event webservice Methods:
   %    Events - retrieve events parameters (such as origins and magnitudes) from a catalog
   %
   % irisFetch miscelleneous Methods:
   %    Resp - retrive RESP formatted response data from the irisws-resp service
   %    version - display the current version number
   %    connectToJar - attempt to connect to the required IRIS-WS JAR file
   %    runExamples - displays and runs some sample queries to the web service.
   %
   %  irisFetch requires version 2.0 or greater of the IRIS Web Services Library java jar
   %  for more details, click on 'connectToJar' above.
   %
   %  For additional guidance, type help <method>, use irisFetch.runExamples, or check out
   %  the online manual http://www.iris.edu/dms/nodes/dmc/software/downloads/irisFetch.m/.
   %
   %see also JAVAADDPATH
   % Celso Reyes, Rich Karstens
   % IRIS-DMC
   % February 2014
   %{
 *******************************************************************************
 * Copyright (c) 2013 IRIS DMC supported by the National Science Foundation.
 *
 * This file is part of Iris Matlab Fetch (irisFetch).
 *
 * irisFetch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * irisFetch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * A copy of the GNU Lesser General Public License is available at
 * <http://www.gnu.org/licenses/>.
 ******************************************************************************
   %}
   properties (Constant = true)
      VERSION           = '2.0.6';  % irisFetch version number
      DATE_FORMATTER    = 'yyyy-mm-dd HH:MM:SS.FFF'; %default data format, in ms
      MIN_JAR_VERSION   = '2.0.4'; % minimum version of IRIS-WS jar required for compatibility
      VALID_QUALITIES   = {'D','R','Q','M','B'}; % list of Qualities accepted by Traces
      DEFAULT_QUALITY   = 'B'; % default Quality for Traces
      FETCHER_LIST      = {'Traces','Stations','Events','Resp'}; % list of functions that fetch
      forceDataAsDouble = true; %require that traces are returned as doubles regardless of original format
   end %constant properties
   properties (Constant = true, Hidden = true)
      MS_IN_DAY         = 86400000; % milliseconds in day
      BASE_DATENUM      = 719529; % Matlab startdate=0000-Jan-1 vs java's startdate=1970-Jan-1
      SURROGATE_JAR     = 'http://www.iris.edu/files/IRIS-WS/2/IRIS-WS-2.0-latest.jar';
      M2J_MAP           = containers.Map (...
         {'java.util.Date',...
         'java.lang.Double',...
         'java.lang.Long',...
         'java.lang.Integer',...
         'java.lang.String',...
         'boolean'},...
         {@(x) java.util.Date(((datenum(x)-irisFetch.BASE_DATENUM) * irisFetch.MS_IN_DAY) + .5), ...%@(x) irisFetch.mdate2jdate(x) ,...
         @(x) java.lang.Double(x),...
         @(x) java.lang.Long(x),...
         @(x) java.lang.Integer(x),...
         @(x) x,...
         @(x) x}...
         ); %details for MATLAB to JAVA conversions
      appName           = ['MATLAB:irisFetch/' irisFetch.VERSION]; %used as useragent of queries
      recursionAssert   = false; %check for recursions while parsing java into structs
   end %hidden constant properties
   methods(Static)
      function v = version()
         v = irisFetch.VERSION;
      end
      function ts = Traces(network, station, location, channel, startDate, endDate, varargin )
         %irisFetch.Traces retrieves sac-equivalent waveform with channel metadata
         %  tr = irisFetch.Traces(network, station, location, channel, startDate, endDate)
         %  will use channel and date criteria to retrieve one or more seismic traces,
         %  which are stored as structures containing typical SAC-equivalent metadata.
         %
         %  startDate and endDate must be formatted thusly:
         %      'YYYY-MM-DD hh:mm:ss' or 'YYYY-MM-DD hh:mm:ss.sss'
         %
         %  network, station, location, and channel all accept comma separated lists, as
         %  well as '*' and '?' wildcards.
         %
         %  tr = irisFetch.Traces(..., quality) allows you to specify the data's quality,
         %  such as 'B' (which stands for "best").  This SEED quality code defines how data overlaps
         %   are processed by the dataselect service.
         %
         %  tr = irisFetch.Traces(..., 'includePZ') will also retrieve poles and zeroes.
         %  These are the same poles/zeros as found from http://service.iris.edu/irisws/sacpz/1/
         %
         %  tr = irisFetch.Traces(..., 'verbose') provides additional debugging information
         %
         %  tr = irisFetch.Traces(..., usernameAndPassword ) allows authorized users to
         %  access restricted data. usernameAndPassword must be a cell containing the
         %  username and password.
         %     Sample:
         %       unamepwd = {'nobody@iris.edu', 'anonymous'}
         %
         %  tr = irisFetch.Traces(..., urlbase) will allow traces to be read from an
         %  alternate data center. url base is only the first part of the web address. For
         %  example, the IRIS datacenter would be 'http://service.iris.edu/'. These
         %  settings are "sticky", so that all calls for waveform data or station metadata
         %  will go to that datacenter until a new one is specified.
         %
         %  ABOUT THE RETURNED TRACE
         %    The returned trace(s) will be a 1xN array of structs. Each struct contains
         %    fields with information pertaining to that specific trace, such as channel
         %    information, start & end times, units, etc.
         %
         %    If the requested data does not exist, then an empty (1x0) trace struct will be
         %    returned. If the original data contains data gaps, then each continuous data
         %    segment will be returned as its own trace.
         %
         %  COMMON MANIPULATIONS:
         %
         %    See a text representation of the start date to millisecond accuracy, from a trace tr:
         %      datestr(tr.startTime, 'yyyy-mm-dd HH:MM:SS.FFF')
         %
         %    Scale the data, so that resulting values are in sensitivityUnits.
         %      tr.data = tr.data ./ tr.sensitivity;    % this example works only for single trace
         %
         %  EXAMPLES:
         %    Get 4 hours of data (timeseries + metdata) from a station:
         %      tr = irisFetch.Traces('IU','ANMO','10','BHZ','2010-02-27 06:30:00','2010-02-27 10:30:00')
         %
         %    Get 3 channels (via wildcards), including response, for a 4-hour time period:
         %      ts = irisFetch.Traces('IU','ANMO','10','BH?','2010-02-27 06:30:00','2010-02-27 10:30:00','includePZ')
         %
         %
         %    Get data from all channels from a comma-separated list of stations:
         %      ts = irisFetch.Traces('IU','ANMO,ANTO,YSS','00','*','2010-02-27 06:30:00','2010-02-27 10:30:00')
         %
         %  SEE ALSO datestr
         if ~exist('extensions.fetch.TraceData','class')
            irisFetch.connectToJar()
         end
         import edu.iris.dmc.*
         % import edu.iris.dmc.*
         % these variables are shared among all the nested functions
         getsacpz    = false;
         verbosity   = false;
         authorize   = false;
         quality     = irisFetch.DEFAULT_QUALITY;
         username    = '';
         userpwd     = '';
         newbase     = '';
         safeLocation = @(x) strrep(x,' ','-');
         extractAdditionalArguments(varargin);
         startDateStr   = irisFetch.makeDateStr(startDate);
         endDateStr     = irisFetch.makeDateStr(endDate);
         location       = safeLocation(location);
         tracedata      = edu.iris.dmc.extensions.fetch.TraceData();
         tracedata.setAppName(irisFetch.appName);
         tracedata.setVerbosity(verbosity);
         if ~isempty(newbase)
            if (verbosity)
                fprintf ('Using services at base: %s\n', newbase);
            end
            tracedata.setBASE_URL(newbase);
         end
         getTheTraces();
         return
         % ---------------------------------------------------------------
         % END TRACES: MAIN
         % ===============================================================
         function extractAdditionalArguments(argList)
            % extracts getsacpz, verbosity, authorize, quality, username, and userpwd
            % Parameters are handled "intelligently" so that [paramname, paramval] pairs
            % aren't necessry
            for n=1:numel(argList)
               param = argList{n};
               switch class(param)
                  case 'cell'
                     assert(numel(param)==2 && all(cellfun(@ischar, param)),...
                        'A cell parameter is assumed to contain credentials. eg. {''nobody@iris.edu'',''anonymous''}.');
                     [username, userpwd] = deal(param{:});
                     authorize         = true;
                  case 'char'
                     switch upper(param)
                        case irisFetch.VALID_QUALITIES
                           quality     = param;
                        case {'INCLUDEPZ'}
                           getsacpz    = true;
                        case {'VERBOSE'}
                           verbosity   = true;
                        otherwise
                           if length(param)>7 && strcmpi(param(1:7),'http://')
                              % set the bases
                              newbase = param;
                           else
                           error('IRISFETCH:Trace:unrecognizedParameter',...
                              'The text you included as an optional parameter did not parse to either a qualitytype (D,R,Q,M,B) or ''INCLUDEPZ'' or ''VERBOSE'' or a service base URL');
                           end
                     end
                     %case 'logical' DEPRECATED
                     %   verbosity         = param; % old usage, deprecated.
                  otherwise
                     error('IRISFETCH:Trace:unrecognizedParameter',...
                        'The optional parameter wasn''t recognized. %s', class(param));
               end
            end
            if verbosity
               disp({'spz:',getsacpz,'vb:',verbosity,'auth:',authorize,'qual:',quality,'un&pw:',username,userpwd});
            end
         end % extractAdditionalArguments
         function getTheTraces()
            traces=[];
            try
               if authorize
                  if verbosity
                     fprintf('traces = tracedata.fetchTraces("%s", "%s", "%s", "%s", "%s", "%s", ''%s'', %d, "%s", "%s")\n',...
                        network, station, location, channel, startDateStr, endDateStr, quality, getsacpz, username, userpwd);%char(userpwd - userpwd + 42));
                  end
                  traces = tracedata.fetchTraces(network, station, location, channel, ...
                     startDateStr, endDateStr, quality, getsacpz, username, userpwd);  %db removed (;)
               else
                  if verbosity
                     fprintf('traces = tracedata.fetchTraces("%s", "%s", "%s", "%s", "%s", "%s", ''%s'', %d)\n',...
                        network, station, location, channel, startDateStr, endDateStr, quality, getsacpz);
                  end
                  traces = tracedata.fetchTraces(network, station, location, channel, ...
                     startDateStr, endDateStr, quality, getsacpz); %db removed (;)
               end
               if verbosity
                  fprintf('tracedata.fetchTraces successfully completed, resulting in %d traces before converting\n', numel(traces)); %db
               end
            catch je
               % Debug messages:
               %warning('An [%s] exception occurred in irisFetch.getTheTraces() but was caught\n full text follows:\nmessage:\n%s\n\n', je.identifier,je.message) %db
               %disp(je.cause); %db
               %disp(je.stack); %db
               switch je.identifier
                  case 'MATLAB:Java:GenericException'
                     if any(strfind(je.message,'URLNotFoundException'));
                        error('IRISFETCH:Trace:URLNotFoundException',...
                           'Trace found no requested data and returned the following error:\n%s',...
                           je.message);
                     end
                     if any(strfind(je.message,'java.io.IOException: edu.iris.dmc.service.UnauthorizedAccessException'));
                        error('IRISFETCH:Trace:UnauthorizedAccessException',...
                           'Invalid Username and Password combination\n');
                     end
                     if any(strfind(je.message,'NoDataFoundException'));
                        if verbosity
                           warning('IRISFETCH:Trace:URLNotFoundException',...
                           'Trace found no requested data and returned the following error:\n%s',...
                           je.message);
                        end
                     end
                  otherwise
                     fprintf('Exception occured in IRIS Web Services Library: %s\n', je.message);
                     rethrow(je)
               end
            end
            ts = irisFetch.convertTraces(traces);
            clear traces
         end %function getTheTraces
      end % Traces
      function [channelStructure, urlParams] = Channels(detailLevel, varargin)
         %irisFetch.Channels retrieves station metadata from IRIS-DMC as an array of channels
         %  s = irisFetch.Channels(DETAIL,NETWORK,STATION,LOCATION,CHANNEL) retrieves
         %  station metadata from the IRIS-DMC into an array of channels.  DETAIL is one of
         %  'CHANNEL', or 'RESPONSE' and should be explicitly declared. DETAIL defaults to 'CHANNEL'
         %  Network, station, location, and channel parameters are passed directly to the
         %  java library, so both comma-separated  lists and wildcards (? and *) are accepted.
         %
         %  All five parameters are required for all queries, but may be wildcarded by
         %  using '' for their values.
         %
         %  [s, myParams] = irisFetch.Channels( ... ) also returns the URL parameters that
         %  were used to make the query.
         %
         %  irisFetch.Channels(..., 'BASEURL',alternateURL) specifies an alternate base URL
         %  to query. By default queries go to: http://service.iris.edu/fdsnws/station/1/
         %
         %  s = irisFetch.Channels( ... , paramName, value [, ...]]) allows any number of
         %  parameter-value pairs to be included in the selection criteria.  Valid
         %  parameter names are listed in help for irisFetch.Networks
         %
         %  Example: to retrieve channel-level BHZ metadata from any station named ANMO:
         %      s = irisFetch.Channels('channel','*','ANMO','*','BHZ')
         %
         %  Note: This function effectively deprecates irisFetch.flattenToChannel
         %
         %See also Networks, Stations
         if isempty(detailLevel)
            detailLevel = 'CHANNEL';
         end
         assert(ismember(upper(detailLevel),{'CHANNEL','RESPONSE'}),...
            'To retrieve channels, the detailLevel must be either ''CHANNEL'' or ''RESPONSE''');
         [channelStructure, urlParams] = irisFetch.Networks(detailLevel, varargin{:});
         if ~isempty(channelStructure)
            channelStructure = irisFetch.flattenToChannel(channelStructure);
         end
      end
      function [stationStructure, urlParams] = Stations(detailLevel, varargin)
         %irisFetch.Stations retrieves station metadata from IRIS-DMC as an array of stations
         %  s = irisFetch.Stations(DETAIL,NETWORK,STATION,LOCATION,CHANNEL) retrieves
         %  station metadata from the IRIS-DMC into an array of stations.  DETAIL is one
         %  of 'STATION','CHANNEL', or  'RESPONSE' and should be explicitly declared.
         %  DETAIL defaults to 'STATION'
         %
         %  Network, station, location, and channel parameters are passed directly to the
         %  java library, so both comma-separated lists and wildcards (? and *) are accepted.
         %
         %  All five parameters are required for all queries, but may be wildcarded by
         %  using '' for their values.
         %
         %  [s, myParams] = irisFetch.Stations( ... ) also returns the URL parameters that
         %  were used to make the query.
         %
         %  irisFetch.Stations(..., 'BASEURL',alternateURL) specifies an alternate base URL
         %  to query. By default queries go to: http://service.iris.edu/fdsnws/station/1/
         %
         %  s = irisFetch.Stations( ... , paramName, value [, ...]]) allows any number of
         %  parameter-value pairs to be included in the selection criteria.  Valid
         %  parameter names are listed in help for irisFetch.Networks
         %
         %  Example: to retrieve channel-level metadata, stored in an array of stations:
         %      s = irisFetch.Stations('channel','IU','A*','*','BHZ')
         %
         %  Note: This function effectively deprecates the irisFetch.flattenToStation
         %
         %See also Networks, Channels
         if isempty(detailLevel)
            detailLevel = 'STATION';
         end
         assert(ismember(upper(detailLevel),{'STATION','CHANNEL','RESPONSE'}),...
            'To retrieve stations, the detailLevel must be either ''STATION'', ''CHANNEL'', or ''RESPONSE''');
         [stationStructure, urlParams] = irisFetch.Networks(detailLevel,varargin{:});
         if ~isempty(stationStructure)
            stationStructure = irisFetch.flattenToStation(stationStructure);
         end
      end
      function [networkStructure, urlParams] = Networks(detailLevel, network, station, location, channel, varargin)
         %irisFetch.Stations retrieves station metadata from IRIS-DMC as an array of networks
         %  s = irisFetch.Networks(DETAIL,NETWORK,STATION,LOCATION,CHANNEL), retrieves
         %  station metadata into an array of networks. These parameters are required for
         %  all queries, but may be wildcarded by using '' for their values. Network,
         %  station, location, and channel parameters are passed directly to the java
         %  library, so both comma-separated lists and wildcards (? and *) are accepted.
         %  Detail is one of 'NETWORK','STATION','CHANNEL', or 'RESPONSE' and should be
         %  explicitly declared. Defaults to 'NETWORK'
         %
         %  [s, myParams] = irisFetch.Networks( ... ) also returns the URL parameters that
         %  were used to make the query.
         %
         %  irisFetch.Networks(..., 'BASEURL',alternateURL) specifies an alternate base URL
         %  to query. By default queries go to: http://service.iris.edu/fdsnws/station/1/
         %
         %  s = irisFetch.Networks( ... , paramName, value [, ...]]) allows any number of
         %  parameter-value pairs to be included in the selection criteria.  See the list
         %  below.
         %
         %  Valid parameters are listed below.  For detailed descriptions of their effect
         %  and use, consult the station webservice webpage, available at:
         %     http://service.iris.edu/fdsnws/station/1/
         %
         %  PARAMETER LIST (for IRIS-WS-2.0.0.jar)
         %    The following take time values, of the format 'yyyy-mm-dd HH:MM:SS'
         %      'StartTime', 'EndTime', 'StartBefore', 'EndBefore'
         %      'StartAfter', 'EndAfter' 'UpdatedAfter'
         %
         %    The following take values in degrees and work together to define a search box
         %      'MinimumLatitude', 'MaximumLatitude', 'MinimumLongitude','MaximumLongitude'
         %
         %    These params take values in degrees to define a search disk / annular region
         %      'Latitude', 'Longitude', 'MinimumRadius','MaximumRadius'
         %
         %    Other params, that accept true or false  (no quotes)
         %    'IncludeAvailability','MatchTimeSeries', 'IncludeRestricted'
         %
         %  CONVENIENCE PARAMETERS
         %    'boxcoordinates'    : [minLat, maxLat, minLon, maxLon]
         %                           % use NaN as a wildcard
         %    'radialcoordinates' : 1x4 double :
         %                           [Lat, Lon, MaxRadius, MinRadius]
         %                           % MinRadius is optional
         %
         %  To retrieve similar information, but organize as an array of either channels
         %  or stations, use irisFetch.Channels or irisFetch.Stations respectively.
         %
         %SEE ALSO Channels, Stations
         import edu.iris.dmc.*
         outputLevel  = '';
         service      = []; % will be a java service object
         crit         = []; % will be a java criteria object
         j_networks   = []; % will be the returned java networks
         %if ~exist('edu.iris.dmc.criteria.StationCriteria','class')
         if ~exist('criteria.StationCriteria','class')
            irisFetch.connectToJar()
         end
         if isempty(detailLevel)
            detailLevel = 'NETWORK';
         end
         verifyArguments(nargin);
         setOutputLevel();
         connectToStationService();
         setCriteria();
         fetchTheStations();
         networkStructure=irisFetch.parser_for_IRIS_WS_2_0_0(j_networks);
         if nargout == 2
            urlParams = crit.toUrlParams;
         end
         return
         % -------------------------------------------------------------
         % END STATIONS: MAIN
         % =============================================================
         function verifyArguments(nArgs)
            if nArgs==1 && strcmpi(detailLevel,'help')
               disp('HELP request recognized, but not implemented');
               return
            elseif nArgs < 5
               error('not enough arguments.%d',nArgs);
            end
         end %verifyArguments
         function setOutputLevel()
            try
               outputLevel = edu.iris.dmc.criteria.OutputLevel.(upper(detailLevel));
               % outputLevel = edu.iris.dmc.criteria.OutputLevel.(upper(detailLevel));
            catch je
               switch je.identifier
                  case 'MATLAB:undefinedVarOrClass'
                     error('IRISFETCH:NoIrisWSJarInstalled',...
                        ['The necessary IRIS-WS java library was not recognized or found. ',...
                        'Please ensure it is on your javaclasspath']);
                  case 'MATLAB:subscripting:classHasNoPropertyOrMethod'
                     error('IRISFETCH:invalidOutputLevel',...
                        'The selected outputLevel [''%s''] was not recognized.',...
                        upper(detailLevel));
                  otherwise
                     rethrow(je);
               end
            end
         end % setOutputLevel
         function connectToStationService()
            serviceManager = edu.iris.dmc.service.ServiceUtil.getInstance();
            serviceManager.setAppName(['MATLAB:irisFetch/' irisFetch.version()])
            setBaseUrlFromParameterList();
            removeParameter('BASEURL');
            return
            % - - - - - - - - - - - - - - -
            function setBaseUrlFromParameterList()
               baseUrl = getParameter('BASEURL');
               if ~isempty(baseUrl)
                  service = serviceManager.getStationService(baseUrl);
               else
                  service = serviceManager.getStationService();
               end % setBaseUrlFromParameterList
            end
         end %connectToStationService()
         function removeParameter(s)
            [UNUSED_VARIABLE, idx] = getParameter(s); %#ok<ASGLU>
            varargin(idx * 2 -1 : idx* 2) = [];
         end
         function [p, i] = getParameter(s)
            i = find(strcmpi(parameterNames(),s),1,'first');
            p = parameterValues();
            p = p(i);
         end
         function pn = parameterNames()
            pn = varargin(1:2:end);
         end
         function pv = parameterValues()
            pv = varargin(2:2:end);
         end
         function setCriteria()
            crit = edu.iris.dmc.criteria.StationCriteria;
            %crit = edu.iris.dmc.criteria.StationCriteria;
            %----------------------------------------------------------
            % Deal with the Station/Network/Channel/Location parameters
            % These are treated separately, as they're "add" & not "set"
            % Each may handle multiple strings (as a cell array)
            %----------------------------------------------------------
            crit = irisFetch.addCriteria(crit, network, 'addNetwork');
            crit = irisFetch.addCriteria(crit, station, 'addStation');
            crit = irisFetch.addCriteria(crit, location,'addLocation');
            crit = irisFetch.addCriteria(crit, channel, 'addChannel');
            crit = irisFetch.setCriteria(crit, varargin);
         end %setCriteria
         function fetchTheStations()
            try
               j_networks = service.fetch(crit, outputLevel);
            catch je
               if strfind(je.message,'ServiceNotSupportedException')
                  error('IRISFETCH:ServiceNotSupportedByLibrary',...
                     'The IRIS-WS java library version doesn''t support the requested station service version');
               elseif strfind(je.message,'NoDataFoundException')
                  warning('IRISFETCH:NoDataFoundException','No data was found that matched your criteria');
                  j_networks = [];
               else
                  rethrow(je)
               end
            end %catch
         end %fetchTheStations
      end %Networks
      function [events, urlParams] = Events(varargin)
         %irisFetch.Events retrieves event data from the IRIS-DMC
         %  ev = irisFetch.Events(param, value [, ...]) retrieves event data from the
         %  IRIS-DMC database as a matlab structure.  An arbitrary number of
         %  parameter-value pairs may be specified in order to narrow down the search
         %  results.
         %
         %  [ev, myParams] = irisFetch.Events( ... ) also returns the URL parameters that
         %  were used to make the query.
         %
         %  irisFetch.Events(..., 'BASEURL',alternateURL) specifies an alternate base URL
         %  to query. By default queries go to: http://service.iris.edu/fdsnws/event/1/
         %
         %  Usable parameters are listed below.  For detailed descriptions of their effect
         %  and use, consult the webservice webpage for events, available at:
         %
         %  http://service.iris.edu/fdsnws/event/1/
         %
         %  Examples:
         %
         %  Retrieve event parameters regarding earthquakes of a specific size and location:
         %      ev = irisFetch.Events('MinimumMagnitude',6.0,...
         %          'minimumLatitude',45,'maximumLatitude', 60,...
         %          'minimumLongitude', -150,'maximumLongitude', -90)
         %
         %PARAMETER LIST (for IRIS-WS-2.0.0.jar)
         % contributor, endTime, eventId, fetchLimit, latitude, longitude, magnitudeType,
         % maximumDepth, maximumLatitude, maximumLongitude, maximumMagnitude,
         % minimumDepth, minimumLatitude, minimumLongitude, minimumMagnitude,
         % minimumRadius, maximumRadius, offset, startTime updatedAfter
         %
         %CONVENIENCE PARAMETERS
         %   'boxcoordinates'    : [minLat, maxLat, minLon, maxLon]   % use NaN as a wildcard
         %   'radialcoordinates' : [Lat, Lon, MaxRadius, MinRadius]   % MinRadius is optional
         %
         %NOTE: Any parameter-value pair that is not listed here will be passed along to
         %      the Event Service. this is to accomodate other datacenters that may have
         %      specialized request parameters.
         import edu.iris.dmc.*
         % import edu.iris.dmc.*
         %if ~exist('edu.iris.dmc.criteria.EventCriteria','class')
         if ~exist('criteria.EventCriteria','class')
            irisFetch.connectToJar()
         end
         %serviceManager = ws.service.ServiceUtil.getInstance();
         serviceManager = edu.iris.dmc.service.ServiceUtil.getInstance();
         serviceManager.setAppName(['MATLAB:irisFetch/' irisFetch.version()]);
         indexOffsetOfBASEURL=find(strcmpi(varargin(1:2:end),'BASEURL'),1,'first') * 2;
         if ~isempty(indexOffsetOfBASEURL)
            baseURL = varargin{indexOffsetOfBASEURL};
         end
         if exist('baseURL','var')
            varargin(indexOffsetOfBASEURL-1:indexOffsetOfBASEURL) = [];
            service = serviceManager.getEventService(baseURL);
         else
            service = serviceManager.getEventService();
         end
         %crit = ws.criteria.EventCriteria;
         crit = criteria.EventCriteria;
         crit = irisFetch.setCriteria(crit, varargin);
         if nargout == 2
            urlParams = crit.toUrlParams;
         end
         disp('fetching...')
         try
            j_events = service.fetch(crit);
         catch er
            if any(strfind(er.message,'NoDataFoundException')) || any(strfind(er.message,'No Content'))
               warning('IRISFETCH:NoDataFoundException','No data was found that matched your criteria');
               events=[];
               return
            end
            rethrow(er);
         end
         fprintf('\n\n%d events found *************\n\n',j_events.size);
         disp('parsing into MATLAB structures')
         events=irisFetch.parser_for_IRIS_WS_2_0_0(j_events);
         % v2.0 uses Preferred, while original code uses "Primary"
      end
      function connectToJar(isSilent)
         %irisFetch.connectToJar connects to the jar for this MATLAB session
         %  irisFetch.connectToJar() searches the javaclasspath for the
         %  IRIS-WS jar file. If it does not exist, then it will try to access the latest
         %  jar over the internet. If it cannot connect, it will error.
         %
         %  irisFetch requires version 2.0.2 or greater of the IRIS Web Services Library java jar,
         %  available from:
         %
         %  http://www.iris.edu/files/IRIS-WS/2/
         %
         %  This jar file must be added to your MATLAB path, which may be done
         %  in a variety of ways.  One common way is to include a javaaddpath
         %  statement in the startup.m file.  For more details, consult MATLAB's
         %  documentation for 'Bringing Java Classes and Methods into MATLAB
         %  Workspace'.
         %
         % SEE ALSO javaaddpath
         assert(usejava('jvm'),'IRISFETCH:jvmNotRunning','irisFetch requires Java to run.');
         isSilent = nargin>0 && strcmpi(isSilent,'silent');
         if exist('edu.iris.dmc.extensions.fetch.TraceData','class');
            return
         end
         if ~isSilent
            disp('please add the latest IRIS-WS.jar file to your javaclasspath.');
            fprintf('Available here: %s\n',irisFetch.SURROGATE_JAR);
            disp('ex.  javaaddpath(''/usr/local/somewhere/IRIS-WS.jar'');');
         end
         javaaddpath(irisFetch.SURROGATE_JAR);
         if ~exist('edu.iris.dmc.extensions.fetch.TraceData','class');
            error('irisFetch:noDefaultJar',...
               'Unable to access the default jar.  Please download and add the latest IRIS-WS-JAR to your javaclasspath.');
         end
      end
      function [respstructures, urlparams] = Resp(network, station, location, channel, starttime, endtime)
         % retrieve the RESP information into a character string.
         % net, sta, loc, and cha are all required.
         % channels and locations may be wildcarded using either ? or *
         % starttime and endtime options may be ignored by using [] instead of a time.
         import edu.iris.dmc.*
         %crit = edu.iris.dmc.criteria.RespCriteria();
         crit = criteria.RespCriteria();
         crit.setNetwork(network);
         crit.setStation(station);
         crit.setLocation(location);
         crit.setChannel(channel);
         if ~isempty(starttime)
            crit.setStartTime(irisFetch.mdate2jdate(starttime));
         end
         if ~isempty(endtime)
            crit.setEndTime(irisFetch.mdate2jdate(endtime));
         end
         urlparams = char(crit.toUrlParams());
         serviceManager = edu.iris.dmc.service.ServiceUtil.getInstance();
         baseUrl = 'http://service.iris.edu/irisws/resp/1/';
         serviceManager.setAppName(['MATLAB:irisFetch/' irisFetch.version()]);
         service = serviceManager.getRespService(baseUrl);
         respstructures= char(service.fetch(crit));
      end
      function runExamples()
         delay=1; % seconds
         codeToExecute={
            '% Retrieve 1 hr of all ''HZ'' channels from all locations at station ANMO for net IU'
            'traces = irisFetch.Traces(''IU'',''ANMO'',''*'',''?HZ'',''2010-02-27 06:30:00'',''2010-02-27 07:30:00'')'
            '% Notice that multiple traces were retrieved, look at the first trace.'
            'tr = traces(1)'
            '% -------- plot the data from the first trace, and then label the plot ------'
            'sampletimes=linspace(tr.startTime,tr.endTime,tr.sampleCount); %calculate the time of each sample'
            'whos(''sampletimes'')'
            'plot(sampletimes,tr.data);'
            'legendDetails = sprintf(''%s-%s-%s'', tr.network, tr.station, tr.location, tr.channel)'
            'legend(legendDetails);'
            'title(''Simple plot'');'
            'datetick;'
            ' '
            '% next, get some station data (same data, at different levels of detail'
            'n = irisFetch.Networks(''Response'',''IU'',''ANMO'','''',''BHZ'',''baseurl'',''http://service.iris.edu/fdsnws/station/1/'')';
            's = irisFetch.Stations(''Response'',''IU'',''ANMO'','''',''BHZ'')';
            'c = irisFetch.Channels(''Response'',''IU'',''ANMO'','''',''BHZ'')';
            ' '
            '% retrieve station data using other search parameters'
            'arcticNetworkList = irisFetch.Networks(''Station'','''','''','''','''',''minimumlatitude'',66.3)';
            'netNames = {arcticNetworkList.NetworkCode}'
            ' '
            '% retrieve event data'
            ' ev = irisFetch.Events(''minimummagnitude'',8.0)'
            ' ev(1)'
            ' ev = irisFetch.Events(''starttime'',''2010-02-27'',''endtime'',''2010-02-28 12:00:00'',''catalog'',''ISC'',''includeallorigins'',true,''includeallmagnitudes'',true)'
            ' '
            '% retrieve the RESP formatted response for a station'
            'irisFetch.Resp(''IU'',''ANMO'',''00'',''BHZ'',now,now)'
            };
         for n=1:numel(codeToExecute)
            disp(codeToExecute{n});
            eval(codeToExecute{n});
            pause(delay);
         end
         clear traces tr n s c ev
      end %fn runExamples
   end % static methods
   methods(Static, Hidden=true)
      function channelList = flattenToChannel(networkTree)
         %irisFetch.flattenToChannel flattens the structure returned by irisFetch.Networks
         %  flatStruct = irisFetch.flattenToChannel(networkTree) takes the hierarchy
         %  returned by irisFetch.Networks, and returns a 1xN array of channels  (channel
         %  epochs, technically).
         %
         %  flatStruct is an array containing ALL channel epochs.
         assert(isa(networkTree,'struct'),'Cannot Flatten a non-structure');
         %eliminate stations that have no channels
         for n=1:numel(networkTree)
            hasNoChannel = arrayfun(@(x) isempty(x.Channels),networkTree(n).Stations);
            networkTree(n).Stations(hasNoChannel) = []; % networkTree(n).Stations(~hasNoChannel);
         end
         %eliminate networks that have no stations
         networksWithoutStations = arrayfun(@(x) isempty(x.Stations),networkTree);
         networkTree(networksWithoutStations) = [];
         if isempty(networkTree);
            warning('IRISFETCH:flattenToChannel:noValidChannels','No channels found, returning an empty array');
            return
         end
         for n=1:numel(networkTree)
            nc    = networkTree(n).NetworkCode;
            nd    = networkTree(n).Description;
            [networkTree(n).Stations.NetworkCode]        = deal(nc);
            [networkTree(n).Stations.NetworkDescription] = deal(nd);
            for m = 1 : numel(networkTree(n).Stations)
               sc = networkTree(n).Stations(m).StationCode;
               sd = networkTree(n).Stations(m).Description;
               sn = networkTree(n).Stations(m).Site;
               [networkTree(n).Stations(m).Channels.NetworkCode]        = deal(nc);
               [networkTree(n).Stations(m).Channels.NetworkDescription] = deal(nd);
               [networkTree(n).Stations(m).Channels.StationCode]        = deal(sc);
               [networkTree(n).Stations(m).Channels.StationDescription] = deal(sd);
               [networkTree(n).Stations(m).Channels.Site] = deal(sn);
               % write the long StationName again to the main level.
               [networkTree(n).Stations(m).Channels.StationName] = deal(sn.Name);
            end
         end
         tmp = [networkTree.Stations];
         channelList=[tmp.Channels];
         clear tmp
         % now, reorder to make it visually coherent.
         descriptorstuff={'NetworkCode';'StationCode';'LocationCode';'ChannelCode';'NetworkDescription';'StationName';'Site'};
         positionalstuff={'Latitude';'Longitude';'Elevation';'Depth';'Azimuth';'Dip'};
         otherstuff={'SampleRate';'SampleRateRatio';'StartDate';'EndDate'};
         fieldsattop=[descriptorstuff; positionalstuff; otherstuff];
         fn = fieldnames(channelList);
         fieldsattop = fieldsattop(ismember(fieldsattop,fn)); %ensure fields exist
         for n=1:numel(fieldsattop);
            fn(strcmp(fn,fieldsattop(n))) = [];
         end
         neworder = [fieldsattop; fn];
         channelList = orderfields(channelList, neworder);
      end
      function stationList = flattenToStation(networkTree)
         %irisFetch.flattenToStation flattens the structure returned by irisFetch.Stations
         %
         %USAGE
         %  flatStruct = irisFetch.flattenToStation(networkTree)
         %
         %This takes the hierarchy returned by irisFetch.Stations, and
         %returns a 1xN array of stations (station epochs, technically).
         assert(isa(networkTree,'struct'),'Cannot Flatten a non-structure');
         emptyNetworks = arrayfun(@(x) isempty(x.Stations),networkTree);
         for n=1:numel(networkTree)
            nc    = networkTree(n).NetworkCode;
            nd    = networkTree(n).Description;
            [networkTree(n).Stations.NetworkCode]        = deal(nc);
            [networkTree(n).Stations.NetworkDescription] = deal(nd);
         end
         stationList = [networkTree(~emptyNetworks).Stations];
         for m=1:numel(stationList)
               stationList(m).StationName = stationList(m).Site.Name;
         end
         % now, reorder to make it visually coherent.
         descriptorstuff={'NetworkCode';'StationCode';'NetworkDescription';'StationName';'Site'};
         positionalstuff={'Latitude';'Longitude';'Elevation'};
         otherstuff={'StartDate';'EndDate'};
         fieldsattop=[descriptorstuff; positionalstuff; otherstuff];
         if ~isstruct(stationList)
            warning('IRISFETCH:flattenToStation:noValidStations','No stations found, returning an empty array');
            return
         end
         fn = fieldnames(stationList);
         fieldsattop = fieldsattop(ismember(fieldsattop,fn)); %ensure fields exist
         for n=1:numel(fieldsattop);
            fn(strcmp(fn,fieldsattop(n))) = [];
         end
         neworder = [fieldsattop; fn];
         stationList = orderfields(stationList, neworder);
      end
      function [js, je] = testResp(starttime, endtime)
         n=now;
         testThis('IU','ANMO','00','BHZ',[],[]);
         testThis('IU','ANMO','00','*',[],[]);
         testThis('IU','ANMO','*','BHZ',[],[]);
         testThis('IU','ANMO','00','BHZ',[],now-1);
         testThis('IU','ANMO','00','BHZ',n-600,[]);
         testThis('IU','ANMO','00','BHZ',n,n-1);
         testThis('IU','ANMO','?0','BHZ',n,n-1);
         testThis('IU','ANMO','00','B?Z',n,n-1);
         testThis('IU','ANMO','00','BHZ','9/20/2012','9/20/2012 03:00:00');
         %testThis('IU','*','00','BHZ',[],[]); %should fail
         %testThis('*','ANMO','00','BHZ',[],[]); % should fail
         if exist('starttime','var') && ~isempty(starttime)
            js = showTimeInDetail(starttime);
         end
         disp(' ');
         if exist('endtime','var') && ~isempty(endtime)
            je = showTimeInDetail(endtime);
         end
         function testThis(varargin)
            try
               [r, url] = irisFetch.Resp(varargin{:});
               whos r
               disp(['url: ', url]);
               parampairs={
                  'network'   ,varargin{1}, 'station'   ,varargin{2}, 'location'  ,varargin{3}, 'channel'   ,varargin{4}
                  };
               disp(paramPairs)
               if ~isempty(varargin{5})
                  st = datestr(varargin{5},31);
                  st(11)='T';
                  parampairs = [parampairs, {'starttime',st}];
               end
               if ~isempty(varargin{6})
                  ed = datestr(varargin{6},31);
                  ed(11)='T';
                  parampairs = [parampairs, {'endtime',ed}];
               end
               [s,code]=urlread('http://service.iris.edu/irisws/resp/1/query','get', parampairs); %#ok<NASGU>
               assert(strcmp(r,s));
            catch myerror
               warning('RESPTEST:failure',myerror.identifier);
            end
         end
         function javadateTime = showTimeInDetail(t)
            dv          = datevec(t);
            dv(6)       = ceil(dv(6) * 1000) / 1000;
            t           = datenum(dv);
            s           = dv(6);
            % t must be either a date number or a string.
            javadateTime      = irisFetch.mdate2jdate(t);
            matlabTimeString  = datestr(t,irisFetch.DATE_FORMATTER);
            %crit          = edu.iris.dmc.criteria.RespCriteria();
            crit          = criteria.RespCriteria();
            crit.setEndTime(javadateTime);
            reconvertedMatlabTime = ...
               datestr(irisFetch.jdate2mdate(javadateTime),irisFetch.DATE_FORMATTER);
            %urlString         = char(criteria.toUrlParams().get(0));
            urlString         = crit.toUrlParams().get(0).toCharArray()';
            if ~(all(reconvertedMatlabTime == matlabTimeString));
               disp(s-fix(s));
               if datenum(reconvertedMatlabTime) > datenum(t)
                  fprintf('^ ');
               else
                  fprintf('v ');
               end
               fprintf('InputTime: %s  ; jDateTime: %s ; millis: %d\nReConvert: %s\nURL: %s\n',...
                  matlabTimeString, ...
                  javadateTime.toGMTString.toCharArray()', ...
                  rem(javadateTime.getTime(),1000),...
                  reconvertedMatlabTime,...
                  urlString);
            end
         end %fn showTimeInDetail
      end %fn testResp
   end %static hidden methods
   methods(Static, Access=protected)
      function myDateStr = makeDateStr(dateInput)
         myDateStr = datestr(dateInput, irisFetch.DATE_FORMATTER);
      end
      function d = jArrayList2complex(jArrayList)
         % for use on ArrayList objects containing things with getReal() and getImaginary()
         %  edu.iris.dmc.sacpz.model.Pole
         %  edu.iris.dmc.sacpz.model.Zero
         %  edu.iris.dmc.station.model.ComplexNumber
         if jArrayList.size()<1
            assert(0==1,'Never should reach this');
            d      = zeros(0,1); % optimized
         else
            jArray = jArrayList.toArray;
            dr     = zeros(numel(jArray),1);
            di     = zeros(numel(jArray),1);
            for n = 1 : jArrayList.size()%:-1: 1
               dr(n,1) = jArray(n).getReal().doubleValue;
               di(n,1) = jArray(n).getImaginary().doubleValue;
            end
            d      = complex(dr,di);
         end
      end
      function mts = convertTraces(traces)
         %irisFetch.convertTraces converts traces from java to a matlab structure
         %   mts = convertTraces(traces) where TRACES a java trace class. If the input
         %   traces are empty, then a 1x0 structure is returned.
         blankSacPZ = struct('units','','constant',[],'poles',[],'zeros',[]);
         blankTrace = struct('network','','station','','location',''...
            ,'channel','','quality','',...
            'latitude',0,'longitude',0,'elevation',0,'depth',0,...
            'azimuth',0,'dip',0,...
            'sensitivity',0,'sensitivityFrequency',0,...
            'instrument','','sensitivityUnits','UNK',...
            'data',[],'sampleCount',0,'sampleRate',nan,...
1000             'startTime',0,'endTime',0,'sacpz',blankSacPZ);
1001          mts=blankTrace;
1002          if isempty(traces)
1003             disp('... since traces is empty, creating an empty structure')
1004             mts(1) = []; % keep the structure, but force it to be 1x0 trace
1005          end
1006          for i = 1:length(traces)
1007             mt=blankTrace;
1008             mt.network  = char(traces(i).getNetwork());
1009             mt.station  = char(traces(i).getStation());
1010             mt.location = char(traces(i).getLocation());
1011             mt.channel  = char(traces(i).getChannel());
1012
1013             mt.quality  = char(traces(i).getQuality());
1014
1015             mt.latitude  = traces(i).getLatitude();
1016             mt.longitude = traces(i).getLongitude();
1017             mt.elevation = traces(i).getElevation();
1018             mt.depth     = traces(i).getDepth();
1019             mt.azimuth   = traces(i).getAzimuth();
1020             mt.dip       = traces(i).getDip();
1021
1022             mt.sensitivity = traces(i).getSensitivity();
1023             mt.sensitivityFrequency = traces(i).getSensitivityFrequency();
1024
1025             mt.instrument  = char(traces(i).getInstrument());
1026             mt.sensitivityUnits = char(traces(i).getSensitivityUnits());
1027             dataType = char(traces(i).getDataType);
1028             switch dataType
1029                case {'INTEGER','INT24'}
1030                   mt.data        = traces(i).getAsInt();
1031                case {'DOUBLE'}
1032                   mt.data        = traces(i).getAsDouble();
1033                case {'FLOAT'}
1034                   mt.data        = traces(i).getAsFloat();
1035                case {'SHORT'}
1036                   mt.data        = traces(i).getAsShort();
1037                otherwise
1038                   % mt.data      = traces(i).getData(); %returns an ArrayList
1039                   mt.data        = traces(i).getAsDouble();
1040                   warning('IRISFETCH:convertTraces:noDataTypeSpecified',...
1041                      'No dataType was specified by the retrieved trace. returning as Double (which may be incorrect)');
1042             end
1043             if irisFetch.forceDataAsDouble
1044                mt.data = double(mt.data);
1045             end
1046             mt.sampleCount = traces(i).getSampleCount();
1047             mt.sampleRate  = traces(i).getSampleRate();
1048
1049             startDateString = char(traces(i).getStartTime().toString());
1050             endDateString  = char(traces(i).getEndTime().toString());
1051
1052             mt.startTime   = datenum(startDateString, irisFetch.DATE_FORMATTER);
1053             mt.endTime     = datenum(endDateString, irisFetch.DATE_FORMATTER);
1054
1055             try
1056                jsacpz = traces(i).getSacpz();
1057             catch er
1058                warning('An [%s] exception occurred in irisFetch.convertTraces() but was caught\n full text follows', er.identifier) %db
1059                disp(er);
1060                if strcmp(er.identifier,'MATLAB:noSuchMethodOrField')
1061                   warning('IRISFETCH:convertTraces:noGetSacPZmethod',...
1062                      'probably using older verision of the ws-library. please retrieve the latest version');
1063                   jsacpz = [];
1064                else
1065                   rethrow(er)
1066                end
1067             end
1068             if ~isempty(jsacpz)
1069                sacpz.units       = char(traces(i).getSacpz().getInputUnit());
1070                sacpz.constant    = traces(i).getSacpz().getConstant();
1071                if (not(traces(i).getSacpz().getPoles().isEmpty()))
1072                    sacpz.poles   = irisFetch.jArrayList2complex(traces(i).getSacpz().getPoles());
1073                else
1074                    sacpz.poles   = [];
1075                end
1076                if (not(traces(i).getSacpz().getZeros().isEmpty()))
1077                    sacpz.zeros   = irisFetch.jArrayList2complex(traces(i).getSacpz().getZeros());
1078                else
1079                    sacpz.zeros   = [];
1080                end
1081                mt.sacpz          = sacpz;
1082             end
1083             mts(i) = mt;
1084          end
1085       end
1086
1087
1088       %----------------------------------------------------------------
1089       % DATE conversion routines
1090       %
1091       % Java classes that can be used:
1092       %     java.sql.Timestamp : handles nanoseconds
1093       %     java.util.Date     : handles milliseconds
1094       %
1095       % MATLAB is accurate to 0.01 milliseconds
1096       %----------------------------------------------------------------
1097
1098       function javadate = mdate2jdate(matlabdate)
1099          %mdate2jdate converts a matlab date to a java Date class
1100          %  javadate = irisFetch.mdate2jdate(matlab_date)converts from matlab to java with
1101          %  millisecond precision.
1102
1103          if ischar(matlabdate)
1104             matlabdate = datenum(matlabdate);
1105          end
1106          if ~isnumeric(matlabdate) || ~isscalar(matlabdate)
1107             error('IRISFETCH:mdate2jdate:incorrectDateFormat',...
1108                'A scalar matlab datenum was expected, but a different kind of value was received.');
1109          end
1110
1111          jmillis = ((matlabdate-irisFetch.BASE_DATENUM) * irisFetch.MS_IN_DAY) + .5 ; % add 0.5 to keep it in sync.
1112
1113          javadate = java.util.Date(jmillis); %convert to a Date, loosing nanosecond precision
1114          % javadate = java.util.Date(((datenum(matlabdate)-irisFetch.BASE_DATENUM) * irisFetch.MS_IN_DAY) + .5)
1115       end
1116
1117       %----------------------------------------------------------------
1118       % Look for GET / SET methods for the class.
1119       %----------------------------------------------------------------
1120       function M = getSettableFields(obj)
1121          % strip the first 3 letters off the field ('set')
1122          M        = irisFetch.getSetters(obj);
1123          startsWithSet=find(strncmp(M,'set',3));
1124          for n=1:numel(startsWithSet)
1125             M(startsWithSet(n))  = {M{startsWithSet(n)}(4:end)};
1126          end
1127       end
1128       %{
1129        function [M, argType] = getSetters(obj)
1130           [M, argType] = irisFetch.getMethods(obj,'set');
1131        end
1132       %}
1133       function [M, argType] = getSetters(obj)
1134          % assumption is that any function that returns a criteria object of the same class is
1135          % a "Set" method. The first time a class is encountered, it's set methods and
1136          % arguments are memorized.
1137
1138          persistent className             % contains the list of classes that have already been done
1139          persistent listOfSetters         % contains a cell list of set-methods for each class
1140          persistent listOfArguments       % contains a cell list of inputs corresponding to each setter
1141
1142          if isempty(className)
1143             className = {};
1144             listOfSetters={};
1145             listOfArguments={};
1146          end
1147
1148          thisClass=class(obj);
1149
1150          memorizedClass                 = strcmp(thisClass, className);
1151
1152          if ~any(memorizedClass)
1153             classIndex                  = numel(className) + 1;
1154             className(classIndex)       = {thisClass};
1155
1156             all_methods                 = methods(thisClass);
1157             full_methods                = methods(thisClass,'-full');
1158             is_setter                   = strcmp(thisClass, strtok(full_methods));
1159             [UNUSED_VARIABLE, setter_inputs]          = strtok(strtok(full_methods(is_setter),')'),'('); %#ok<ASGLU> %loose ()
1160
1161             listOfArguments(classIndex) = {strrep(setter_inputs,'(','')};
1162             listOfSetters(classIndex)   = {all_methods(is_setter)};
1163
1164             memorizedClass = strcmp(thisClass, className);
1165             % disp (['Adding ', thisClass, ' setters ...']);
1166          end
1167
1168          M                             = listOfSetters{memorizedClass};
1169          argType                       = listOfArguments{memorizedClass};
1170       end
1171
1172       function [methodList, argType] = getMethods(obj,searchPrefix)
1173          persistent className methodsAndArguments
1174          if isempty(className)
1175             className            = {''};
1176             methodsAndArguments  = {{''},{''}};
1177          end
1178
1179          thisClass = class(obj);
1180          TF = strcmp(thisClass, className);
1181          if any(TF) % shortcut if this has been done before
1182             methodList  = methodsAndArguments{TF,1};
1183             argType     = methodsAndArguments{TF,2};
1184             return
1185          else
1186             loc = numel(className)+1;
1187          end
1188
1189
1190          argType     = {}; %methodList = [];
1191          M           = methods(obj);
1192          M2          = methods(obj,'-full');
1193          idx         = strncmp(searchPrefix,M, length(searchPrefix));
1194          methodList  = M(idx);
1195          argList     = M2(idx);
1196
1197          p1          = strfind(argList,'(');
1198          p2          = strfind(argList,')');
1199          for n=1:numel(argList)
1200             argType(n) = {argList{n}(p1{n}+1:p2{n}-1)}; %#ok<AGROW>
1201          end
1202
1203          className(loc)             = {thisClass};
1204          methodsAndArguments(loc,1) = {methodList};
1205          methodsAndArguments(loc,2) = {argType};
1206
1207       end
1208       %%
1209       %================================================================
1210       %----------------------------------------------------------------
1211       % BEGIN: PARSING ROUTINES
1212       %----------------------------------------------------------------
1213
1214       function [getterList, fieldList] = getMethodsAndFields(obj)
1215
1216
1217          % this function uses a cache to speed up the retrieval of
1218          % get_methods and fieldnames.
1219
1220          persistent className
1221          persistent methodL
1222          persistent fieldL
1223
1224          if isempty(className)
1225             className = {''};
1226             methodL = {''};
1227             fieldL = {''};
1228          end
1229
1230          thisClass = class(obj);
1231
1232          TF = strcmp(thisClass, className);
1233
1234          if any(TF) % shortcut if this has been done before
1235             getterList = methodL{TF};
1236             fieldList = fieldL{TF};
1237             return
1238          else
1239             loc = numel(className)+1;
1240          end
1241
1242          allMethods = methods(obj);
1243          getterList = allMethods(strncmp('get',allMethods, 3));
1244
1245          % filter classes need class names for them to make sense to users.
1246          if isa(obj,'edu.iris.dmc.station.model.Filter')
1247             getterList = getterList(...
1248                ~(strcmp('get',getterList) | ...
1249                strcmp('getAny',getterList)));
1250
1251          else
1252             getterList = getterList(...
1253                ~(strcmp('get',getterList) | ...
1254                strcmp('getClass',getterList) | ...
1255                strcmp('getAny',getterList)));
1256          end
1257          % eliminate recursions
1258          switch thisClass
1259             case 'edu.iris.dmc.station.model.Station'
1260                n = strcmp(getterList,'getNetwork');
1261             case 'edu.iris.dmc.station.model.StationEpoch'
1262                n = strcmp(getterList,'getStations');
1263             case 'edu.iris.dmc.station.model.Channel'
1264                n = strcmp(getterList,'getStationEpoch');
1265             case 'edu.iris.dmc.station.model.ChannelEpoch'
1266                n = strcmp(getterList,'getChannels');
1267             case 'edu.iris.dmc.station.model.Response'
1268                n = strcmp(getterList,'getChannelEpoch');
1269             case 'edu.iris.dmc.station.model.Sensor'
1270                n = strcmp(getterList,'getChannelEpoch');
1271             otherwise
1272                n=[];
1273          end
1274          getterList(n)  = [];
1275
1276          fieldList      = strrep(getterList,'get',''); %get rid of 'get'
1277
1278          className(loc) = {thisClass};
1279          methodL(loc)   = {getterList};
1280          fieldL(loc)    = {fieldList};
1281       end
1282
1283       function out = parser_for_IRIS_WS_2_0_0(value)
1284          % call other classes based on this function
1285
1286          out=irisFetch.parse(value, containers.Map);
1287       end
1288
1289       function s = parse(value,stacklistt)
1290          % parse takes each value, looks up its class, and converts it to MATLAB
1291          % struct = parse(javaObject) recursively parses a java object. If the java object
1292          % contains objects of other java classes, then they will be parsed also.
1293          %
1294          % struct = parse(javaObject, stacklistt)
1295
1296          persistent stacklist
1297          if nargin == 2
1298             stacklist = stacklistt;
1299          end
1300
1301
1302          myClass = class(value);
1303
1304          if irisFetch.recursionAssert
1305             try
1306                tf = stacklist(myClass);
1307             catch %#ok<CTCH>
1308                stacklist(myClass)= false;
1309                tf = false;
1310             end
1311             if tf
1312                % if stacklist(myClass)
1313                [x,UNUSED_VARIABLE] = dbstack(1); %#ok<NASGU> %remove this call from the stack, and get the list
1314                error(['\n\nRecursion detected. attempt to parse a\n  [%s] \n  '...
1315                   'when a parent of the same class exists.\n'...
1316                   'Please comment out the offending line of code (line %d)\n'],myClass,x(1).line);
1317             end
1318             stacklist(myClass)=true;
1319
1320          end
1321
1322          switch myClass
1323
1324             case {'java.util.ArrayList'}
1325                if irisFetch.recursionAssert
1326                   stacklist(myClass)=false;
1327                end
1328                % disp(['parsing array of: ', class(value.get(0)) ]) ;
1329                for n=1 : value.size()
1330                   s(n)=irisFetch.parse(value.get(n-1)); %#ok<AGROW> % class(value.get(0))
1331                end
1332             case 'double'
1333                s=value;
1334             case {'edu.iris.dmc.fdsn.station.model.Dip' %MOVED
1335                   'edu.iris.dmc.fdsn.station.model.AngleType'
1336                   'edu.iris.dmc.fdsn.station.model.SampleRate'
1337                   'edu.iris.dmc.fdsn.station.model.SecondType'
1338                   'edu.iris.dmc.fdsn.station.model.VoltageType'
1339                   'edu.iris.dmc.fdsn.station.model.Frequency'
1340                   'edu.iris.dmc.fdsn.station.model.Azimuth'
1341                   'edu.iris.dmc.fdsn.station.model.Channel$ClockDrift'
1342                   'edu.iris.dmc.fdsn.station.model.Distance'
1343                   'edu.iris.dmc.fdsn.station.model.LongitudeBaseType'
1344                   'edu.iris.dmc.fdsn.station.model.LatitudeBaseType'
1345                   'edu.iris.dmc.fdsn.station.model.Float'
1346                   }
1347                s                  = value.getValue();
1348                % unused get routines: getUnit, getPlusError,getMinusError
1349
1350             case {'edu.iris.dmc.timeseries.model.Timeseries'}
1351                s.NetworkCode             = char(value.getNetworkCode());
1352                s.StationCode             = char(value.getStationCode());
1353                s.Location                = char(value.getLocation());
1354                s.ChannelCode             = char(value.getChannelCode());
1355                s.DataQuality             = irisFetch.parse(value.getDataQuality()); % get char
1356                s.Segments                = irisFetch.parse(value.getSegments());    % get java.util.Collection
1357
1358             case {'edu.iris.dmc.fdsn.station.model.FIR$NumeratorCoefficient'}
1359                s                   = value.getValue(); %was s.Value
1360
1361             case {'edu.iris.dmc.fdsn.station.model.ResponseListElement'}
1362                s.Frequency               = irisFetch.parse(value.getFrequency());   % get edu.iris.dmc.fdsn.station.model.Frequency
1363                s.Amplitude               = irisFetch.parse(value.getAmplitude());   % get edu.iris.dmc.fdsn.station.model.Float
1364                s.Phase                   = irisFetch.parse(value.getPhase());       % get edu.iris.dmc.fdsn.station.model.AngleType
1365
1366             case {'edu.iris.dmc.fdsn.station.model.RestrictedStatus'}
1367                s.value                   = char(value.value());
1368                s.values                  = irisFetch.parseAnArray(value.values());
1369                s.name                    = char(value.name());
1370                s.ordinal                 = value.ordinal();
1371
1372             case {'edu.iris.dmc.fdsn.station.model.Sensitivity'}
1373                s.FrequencyStart          = double(value.getFrequencyStart());
1374                s.FrequencyEnd            = double(value.getFrequencyEnd());
1375                s.FrequencyDBVariation    = double(value.getFrequencyDBVariation());
1376                s.Value                   = value.getValue();
1377                s.Frequency               = value.getFrequency();
1378                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1379                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1380                % s.OutputUnitsName         = char(value.getOutputUnits().getName); % get edu.iris.dmc.fdsn.station.model.Units
1381                % s.OutputUnitsDescription  = char(value.getOutputUnits().getDescription); % get edu.iris.dmc.fdsn.station.model.Units
1382
1383
1384             case {'edu.iris.dmc.fdsn.station.model.Polynomial'}
1385                s.ApproximationType       = char(value.getApproximationType());
1386                s.Name                    = char(value.getName());
1387                s.Description             = char(value.getDescription());
1388                s.Coefficient = irisFetch.parseAnArray(value.getCoefficient());
1389                s.FrequencyLowerBound     = value.getFrequencyLowerBound().getValue; % get edu.iris.dmc.fdsn.station.model.Frequency
1390                s.FrequencyUpperBound     = value.getFrequencyUpperBound().getValue; % get edu.iris.dmc.fdsn.station.model.Frequency
1391                s.ApproximationLowerBound = value.getApproximationLowerBound().doubleValue;
1392                s.ApproximationUpperBound = value.getApproximationUpperBound().doubleValue;
1393                s.MaximumError            = value.getMaximumError().doubleValue;
1394                s.ResourceId              = char(value.getResourceId());
1395                s.InputUnits = irisFetch.addUnits(value.getInputUnits());  % get edu.iris.dmc.fdsn.station.model.Units
1396                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits());  % get edu.iris.dmc.fdsn.station.model.Units
1397
1398             case {'edu.iris.dmc.timeseries.model.Segment$Type'}
1399                s.values = irisFetch.parseAnArray(value.values());
1400                s.name                    = char(value.name());
1401                s.ordinal                 = value.ordinal();
1402
1403
1404             case {'edu.iris.dmc.fdsn.station.model.package-info'}
1405
1406             case {'edu.iris.dmc.fdsn.station.model.BaseFilter'}
1407                s.Name                    = char(value.getName());
1408                s.Description             = char(value.getDescription());
1409                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1410                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1411                s.ResourceId              = char(value.getResourceId());
1412
1413             case {'edu.iris.dmc.fdsn.station.model.LogType'}
1414                s.Entry = irisFetch.parseAnArray(value.getEntry());
1415
1416             case {'edu.iris.dmc.fdsn.station.model.ResponseList'}
1417                s.ResponseListElement = irisFetch.parseAnArray(value.getResponseListElement());
1418                s.Name                    = char(value.getName());
1419                s.Description             = char(value.getDescription());
1420                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1421                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1422                s.ResourceId              = char(value.getResourceId());
1423
1424             case {'edu.iris.dmc.fdsn.station.model.Units'}
1425                s.Name                    = char(value.getName());
1426                s.Description             = char(value.getDescription());
1427
1428             case {'edu.iris.dmc.fdsn.station.model.ResponseStage'}
1429                s.Number                  = double(value.getNumber());
1430                s.PolesZeros              = irisFetch.parse(value.getPolesZeros());  % get edu.iris.dmc.fdsn.station.model.PolesZeros
1431                s.Coefficients            = irisFetch.parse(value.getCoefficients()); % get edu.iris.dmc.fdsn.station.model.Coefficients
1432                s.ResponseList            = irisFetch.parse(value.getResponseList()); % get edu.iris.dmc.fdsn.station.model.ResponseList
1433                s.FIR                     = irisFetch.parse(value.getFIR());         % get edu.iris.dmc.fdsn.station.model.FIR
1434                s.Polynomial              = irisFetch.parse(value.getPolynomial());  % get edu.iris.dmc.fdsn.station.model.Polynomial
1435                s.Decimation              = irisFetch.parse(value.getDecimation());  % get edu.iris.dmc.fdsn.station.model.Decimation
1436                s.StageGain               = irisFetch.parse(value.getStageGain());   % get edu.iris.dmc.fdsn.station.model.Gain
1437
1438
1439             case {'edu.iris.dmc.fdsn.station.model.SampleRateRatioType'}
1440                s.NumberSamples           = double(value.getNumberSamples());
1441                s.NumberSeconds           = double(value.getNumberSeconds());
1442
1443             case {'edu.iris.dmc.fdsn.station.model.Decimation'}
1444                s.Offset                  = value.getOffset().doubleValue;
1445                s.Delay                   = irisFetch.parse(value.getDelay());       % get edu.iris.dmc.fdsn.station.model.Float
1446                s.InputSampleRate         = irisFetch.parse(value.getInputSampleRate()); % get edu.iris.dmc.fdsn.station.model.Frequency
1447                s.Factor                  = value.getFactor().doubleValue;
1448                s.Correction              = irisFetch.parse(value.getCorrection());  % get edu.iris.dmc.fdsn.station.model.Float
1449
1450             case {'edu.iris.dmc.timeseries.model.Segment'}
1451                s.Type                    = irisFetch.parse(value.getType());        % get edu.iris.dmc.timeseries.model.Segment$Type
1452                s.StartTime               = irisFetch.parse(value.getStartTime());   % get java.sql.Timestamp
1453                s.EndTime                 = irisFetch.parse(value.getEndTime());     % get java.sql.Timestamp
1454                s.ShortData               = irisFetch.parseAnArray(value.getShortData());
1455                s.SampleCount             = value.getSampleCount();
1456                s.Samplerate              = value.getSamplerate();
1457                s.DoubleData              = irisFetch.parseAnArray(value.getDoubleData());
1458                s.FloatData               = irisFetch.parseAnArray(value.getFloatData());
1459                s.IntData                 = irisFetch.parseAnArray(value.getIntData());
1460                s.ExpectedNextSampleTime  = irisFetch.parse(value.getExpectedNextSampleTime()); % get java.sql.Timestamp
1461
1462
1463             case {'edu.iris.dmc.fdsn.station.model.PhoneNumberType'}
1464                s.Phone = sprintf('%s: [+%d] %03d %s',... % desc: [+country] area phonenum
1465                   char(value.getDescription()),...
1466                   double(value.getCountryCode()),...
1467                   double(value.getAreaCode()),...
1468                   char(value.getPhoneNumber()));
1469
1470             case {'edu.iris.dmc.sacpz.model.PZ',...
1471                   'edu.iris.dmc.fdsn.station.model.ComplexNumber',...
1472                   'edu.iris.dmc.sacpz.model.Zero',...
1473                   'edu.iris.dmc.fdsn.station.model.PoleZero',...
1474                   'edu.iris.dmc.sacpz.model.Pole'}
1475                s = complex(value.getReal.getValue(), value.getImaginary.getValue());
1476
1477             case {'edu.iris.dmc.sacpz.model.PolesZeros'}
1478                s.Poles = irisFetch.parseAnArray(value.getPoles());
1479                s.Zeros = irisFetch.parseAnArray(value.getZeros());
1480
1481             case {'edu.iris.dmc.fdsn.station.model.Filter'}
1482                s.Name                    = char(value.getName());
1483                s.Description             = char(value.getDescription());
1484                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1485                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1486                s.ResourceId              = char(value.getResourceId());
1487
1488             case {'edu.iris.dmc.fdsn.station.model.FIR'}
1489                s.Symmetry                = char(value.getSymmetry());
1490                sz = value.getNumeratorCoefficient.size;
1491                if sz>0
1492                   s.NumeratorCoefficient=arrayfun(@getValue,value.getNumeratorCoefficient.toArray(javaArray('edu.iris.dmc.fdsn.station.model.FIR$NumeratorCoefficient',sz)));
1493                   % s.Numerator(sz,1)=0;
1494                else
1495                   s.NumeratorCoefficient=[];
1496                end
1497                value.getNumeratorCoefficient.clear;
1498                %s.NumeratorCoefficient = irisFetch.parseAnArray(value.getNumeratorCoefficient());
1499                s.Name                    = char(value.getName());
1500                s.Description             = char(value.getDescription());
1501                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1502                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1503                s.ResourceId              = char(value.getResourceId());
1504
1505             case {'edu.iris.dmc.fdsn.station.model.DataAvailability'}
1506                s.Extent                  = irisFetch.parse(value.getExtent());      % get edu.iris.dmc.fdsn.station.model.DataAvailabilityExtent
1507                s.Span = irisFetch.parseAnArray(value.getSpan());
1508
1509             case {'edu.iris.dmc.fdsn.station.model.RestrictedStatusType'}
1510                s.value                   = char(value.value());
1511                s.values = irisFetch.parseAnArray(value.values());
1512                s.name                    = char(value.name());
1513                s.ordinal                 = value.ordinal();
1514
1515             case {'edu.iris.dmc.fdsn.station.model.Gain'}
1516                s.Value                   = value.getValue();
1517                s.Frequency               = value.getFrequency();
1518
1519             case {'edu.iris.dmc.fdsn.station.model.Equipment'}
1520                s.Type                    = char(value.getType());
1521                s.SerialNumber            = char(value.getSerialNumber());
1522                s.Description             = char(value.getDescription());
1523                s.Model                   = char(value.getModel());
1524                s.Manufacturer            = char(value.getManufacturer());
1525                s.Vendor                  = char(value.getVendor());
1526                s.InstallationDate        = irisFetch.jdate2mdate(value.getInstallationDate());
1527                s.RemovalDate             = irisFetch.jdate2mdate(value.getRemovalDate());
1528                s.CalibrationDate = irisFetch.parseAnArray(value.getCalibrationDate());
1529                s.ResourceId              = char(value.getResourceId());
1530
1531             case {'edu.iris.dmc.fdsn.station.model.DataAvailabilityExtent'}
1532                s.End                     = irisFetch.jdate2mdate(value.getEnd());
1533                s.Start                   = irisFetch.jdate2mdate(value.getStart());
1534
1535
1536             case {'edu.iris.dmc.fdsn.station.model.Coefficients'}
1537                s.CfTransferFunctionType  = char(value.getCfTransferFunctionType());
1538                sz = value.getNumerator.size;
1539                if sz>0
1540                   s.Numerator=arrayfun(@getValue,value.getNumerator.toArray(javaArray('edu.iris.dmc.fdsn.station.model.Float',sz)));
1541                   % s.Numerator(sz,1)=0;
1542                else
1543                   s.Numerator=[];
1544                end
1545                s.Denominator = irisFetch.parseAnArray(value.getDenominator());
1546                s.Name                    = char(value.getName());
1547                s.Description             = char(value.getDescription());
1548                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1549                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1550                s.ResourceId              = char(value.getResourceId());
1551
1552             case {'edu.iris.dmc.sacpz.model.AbstractPZ'}
1553                s.Real                    = double(value.getReal());
1554                s.Imaginary               = double(value.getImaginary());
1555
1556                %----------------------------------------------------------------------------------
1557                % EVENT
1558                %----------------------------------------------------------------------------------
1559             case {'edu.iris.dmc.event.model.Origin'}
1560                s.Time                    = irisFetch.jdate2mdate(value.getTime());
1561                s.Latitude                = value.getLatitude();
1562                s.Longitude               = value.getLongitude();
1563                s.Depth                   = value.getDepth() / 1000; %getDepth returns m. stored as km
1564                s.Author                  = char(value.getAuthor());
1565                s.Catalog                 = char(value.getCatalog());
1566                s.Contributor             = char(value.getContributor());
1567                s.ContributorOriginId     = char(value.getContributorOriginId());
1568                s.ContributorEventId      = char(value.getContributorEventId());
1569                s.PublicId                = char(value.getPublicId());
1570                s.Arrivals = irisFetch.parseAnArray(value.getArrivals());
1571
1572             case {'edu.iris.dmc.event.model.Pick'}
1573                s.Location                = char(value.getLocation());
1574                s.Channel                 = char(value.getChannel());
1575                s.Time                    = irisFetch.jdate2mdate(value.getTime());
1576                s.Network                 = char(value.getNetwork());
1577                s.Station                 = char(value.getStation());
1578                s.PickId                  = char(value.getPickId());
1579
1580             case {'edu.iris.dmc.event.model.Arrival'}
1581                s.PublicId                = char(value.getPublicId());
1582                s.Distance                = double(value.getDistance());
1583                s.Azimuth                 = double(value.getAzimuth());
1584                s.Phase                   = char(value.getPhase());
1585                s.Picks = irisFetch.parseAnArray(value.getPicks());
1586                s.TimeResidual            = double(value.getTimeResidual());
1587
1588             case {'edu.iris.dmc.event.model.Magnitude'}
1589                s.Value                   = double(value.getValue());
1590                s.Type                    = char(value.getType());
1591                s.Author                  = char(value.getAuthor());
1592                s.PublicId                = char(value.getPublicId());
1593                s.OriginPublicId          = char(value.getOriginPublicId());
1594
1595             case {'edu.iris.dmc.event.model.Event'}
1596                s.Type                    = char(value.getType());
1597                s.FlinnEngdahlRegionCode  = double(value.getFlinnEngdahlRegionCode());
1598                s.FlinnEngdahlRegionName  = char(value.getFlinnEngdahlRegionName());
1599                try
1600                   tmpPreferredOrigin         = irisFetch.parse(value.getPreferredOrigin()); % get edu.iris.dmc.event.model.Origin
1601                catch %#ok<CTCH>
1602                   tmpPreferredOrigin=[];
1603                end
1604                if ~isempty(tmpPreferredOrigin)
1605                   s.PreferredTime         = tmpPreferredOrigin.Time;
1606                   s.PreferredLatitude     = tmpPreferredOrigin.Latitude;
1607                   s.PreferredLongitude    = tmpPreferredOrigin.Longitude;
1608                   s.PreferredDepth        = tmpPreferredOrigin.Depth;
1609                else
1610                   [s.PreferredTime, s.PreferredLatitude, s.PreferredLongitude,s.PreferredDepth] = deal(nan);
1611                end
1612                tmpPreferredMagnitude      = irisFetch.parse(value.getPreferredMagnitude()); % get edu.iris.dmc.event.model.Magnitude
1613                if ~isempty(tmpPreferredMagnitude)
1614                   s.PreferredMagnitudeType = tmpPreferredMagnitude.Type;
1615                   s.PreferredMagnitudeValue = tmpPreferredMagnitude.Value;
1616                else
1617                   s.PreferredMagnitudeType = '';
1618                   s.PreferredMagnitudeValue = nan;
1619                end
1620                s.PreferredOrigin     = tmpPreferredOrigin;
1621                s.Origins            = irisFetch.parseAnArray(value.getOrigins());
1622                s.PreferredMagnitude = tmpPreferredMagnitude;
1623                s.Magnitudes         = irisFetch.parseAnArray(value.getMagnitudes());
1624                s.Picks = irisFetch.parseAnArray(value.getPicks());
1625                s.PublicId                = char(value.getPublicId());
1626
1627             case {'edu.iris.dmc.fdsn.station.model.Message'}
1628                s.Networks = irisFetch.parseAnArray(value.getNetwork());
1629
1630             case {'edu.iris.dmc.sacpz.model.NumberUnit'}
1631                s.Value                   = double(value.getValue());
1632                s.Unit                    = char(value.getUnit());
1633
1634             case {'edu.iris.dmc.fdsn.station.model.Comment'}
1635                s.Value                   = char(value.getValue());
1636                s.Id                      = double(value.getId());
1637                s.Author = irisFetch.parseAnArray(value.getAuthor());
1638                s.BeginEffectiveDate      = irisFetch.jdate2mdate(value.getBeginEffectiveDate());
1639                s.EndEffectiveDate        = irisFetch.jdate2mdate(value.getEndEffectiveDate());
1640                % s.BeginEffectiveTime      = irisFetch.jdate2mdate(value.getBeginEffectiveTime());
1641                % s.EndEffectiveTime        = irisFetch.jdate2mdate(value.getEndEffectiveTime());
1642
1643             case {'edu.iris.dmc.fdsn.station.model.PolesZeros'}
1644                s.Zero = irisFetch.parseAnArray(value.getZero());
1645                s.PzTransferFunctionType  = char(value.getPzTransferFunctionType());
1646                s.NormalizationFactor     = value.getNormalizationFactor();
1647                s.Pole = irisFetch.parseAnArray(value.getPole());
1648                s.NormalizationFrequency  = irisFetch.parse(value.getNormalizationFrequency()); % get edu.iris.dmc.fdsn.station.model.Frequency
1649                s.Name                    = char(value.getName());
1650                s.Description             = char(value.getDescription());
1651                s.ResourceId              = char(value.getResourceId());
1652                s.InputUnits = irisFetch.addUnits(value.getInputUnits);
1653                s.OutputUnits = irisFetch.addUnits(value.getOutputUnits);
1654
1655             case {'edu.iris.dmc.fdsn.station.model.DataAvailabilitySpan'}
1656                s.End                     = irisFetch.jdate2mdate(value.getEnd());
1657                s.Start                   = irisFetch.jdate2mdate(value.getStart());
1658                s.NumberSegments          = double(value.getNumberSegments());
1659                s.MaximumTimeTear         = double(value.getMaximumTimeTear());
1660
1661             case {'edu.iris.dmc.fdsn.station.model.Site'}
1662                s.Name                    = char(value.getName());
1663                s.Country                 = char(value.getCountry());
1664                s.Description             = char(value.getDescription());
1665                s.Town                    = char(value.getTown());
1666                s.County                  = char(value.getCounty());
1667                s.Region                  = char(value.getRegion());
1668
1669             case {'edu.iris.dmc.fdsn.station.model.Polynomial$Coefficient'}
1670                s = value.getValue();
1671
1672             case {'edu.iris.dmc.fdsn.station.model.NominalType'}
1673                s.value                   = char(value.value());
1674                s.values = irisFetch.parseAnArray(value.values());
1675                s.name                    = char(value.name());
1676                s.ordinal                 = value.ordinal();
1677
1678
1679             case {'edu.iris.dmc.fdsn.station.model.Response'}
1680                s.InstrumentSensitivity   = irisFetch.parse(value.getInstrumentSensitivity()); % get edu.iris.dmc.fdsn.station.model.Sensitivity
1681                s.Stage = irisFetch.parseAnArray(value.getStage());
1682                s.InstrumentPolynomial    = irisFetch.parse(value.getInstrumentPolynomial()); % get edu.iris.dmc.fdsn.station.model.Polynomial
1683
1684
1685             case {'edu.iris.dmc.fdsn.station.model.Station$Operator'}
1686                s.Agency = irisFetch.parseAnArray(value.getAgency());
1687                s.Contact = irisFetch.parseAnArray(value.getContact());
1688                s.WebSite                 = char(value.getWebSite());
1689
1690             case {'edu.iris.dmc.timeseries.model.Record'}
1691                s.Location = irisFetch.parseAnArray(value.getLocation());
1692                s.StartTime               = irisFetch.parse(value.getStartTime());   % get java.sql.Timestamp
1693                s.EndTime                 = irisFetch.parse(value.getEndTime());     % get java.sql.Timestamp
1694                s.SampleRate              = value.getSampleRate();
1695                s.ExpectedNextSampleTime  = irisFetch.parse(value.getExpectedNextSampleTime()); % get java.sql.Timestamp
1696                s.NumberOfSamples         = value.getNumberOfSamples();
1697
1698             case {'edu.iris.dmc.fdsn.station.model.PersonType'}
1699                s.Name = irisFetch.parseAnArray(value.getName());
1700                s.Agency = irisFetch.parseAnArray(value.getAgency());
1701                s.Email = irisFetch.parseAnArray(value.getEmail());
1702                s.Phone = irisFetch.parseAnArray(value.getPhone());
1703
1704             case {'edu.iris.dmc.fdsn.station.model.BaseNodeType'}
1705                assert('did not expect to get here');
1706                s.Comment = irisFetch.parseAnArray(value.getComment());
1707                s.Code                    = char(value.getCode());
1708                s.Description             = char(value.getDescription());
1709                s.StartDate               = irisFetch.jdate2mdate(value.getStartDate());
1710                s.EndDate                 = irisFetch.jdate2mdate(value.getEndDate());
1711                % s.StartTime               = irisFetch.jdate2mdate(value.getStartTime());
1712                % s.EndTime                 = irisFetch.jdate2mdate(value.getEndTime());
1713                % assert(strcmp(datestr(s.StartTime,31), datestr(s.StartDate,31)),'dates don''t match for network %s  %s vs %s\n',s.Code, datestr(s.StartTime,31), datestr(s.StartDate,31))
1714                s.DataAvailability        = irisFetch.parse(value.getDataAvailability()); % get edu.iris.dmc.fdsn.station.model.DataAvailability
1715                s.RestrictedStatus        = char(value.getRestrictedStatus());
1716                s.AlternateCode           = char(value.getAlternateCode());
1717                s.HistoricalCode          = char(value.getHistoricalCode());
1718
1719
1720             case {'edu.iris.dmc.fdsn.station.model.Channel'}
1721                s.ChannelCode                    = char(value.getCode());
1722                s.LocationCode            = char(value.getLocationCode());
1723                s.Description             = char(value.getDescription());
1724                s.Type = char(value.getType());
1725                s.Response                = irisFetch.parse(value.getResponse());    % get edu.iris.dmc.fdsn.station.model.Response
1726                % take the instrument sensitivity. These values are the INPUT units, which
1727                % matches previous irisFetch
1728                if isstruct(s.Response.InstrumentSensitivity)
1729                   s.SensitivityFrequency= s.Response.InstrumentSensitivity.Frequency;
1730                   s.SensitivityUnitDescription = s.Response.InstrumentSensitivity.InputUnits{2};
1731                   s.SensitivityUnits = s.Response.InstrumentSensitivity.InputUnits{1};
1732                   s.SensitivityValue = s.Response.InstrumentSensitivity.Value;
1733                else
1734                   s.SensitivityFrequency = NaN;
1735                   s.SensitivityUnitDescription = '';
1736                   s.SensitivityUnits = '';
1737                   s.SensitivityValue = NaN;
1738                end
1739
1740                s.Equipment               = irisFetch.parse(value.getEquipment());   % get edu.iris.dmc.fdsn.station.model.Equipment
1741                s.SampleRateRatio         = irisFetch.parse(value.getSampleRateRatio()); % get edu.iris.dmc.fdsn.station.model.SampleRateRatioType
1742                s.StorageFormat           = char(value.getStorageFormat());
1743                s.ClockDrift              = irisFetch.parse(value.getClockDrift());  % get edu.iris.dmc.fdsn.station.model.Channel$ClockDrift
1744                s.DataLogger              = irisFetch.parse(value.getDataLogger());  % get edu.iris.dmc.fdsn.station.model.Equipment
1745                s.Sensor                  = irisFetch.parse(value.getSensor());      % get edu.iris.dmc.fdsn.station.model.Equipment
1746                s.PreAmplifier            = irisFetch.parse(value.getPreAmplifier()); % get edu.iris.dmc.fdsn.station.model.Equipment
1747                s.ExternalReference = irisFetch.parseAnArray(value.getExternalReference());
1748
1749                s.Latitude           = value.getLatitudeValue().doubleValue;
1750                s.Longitude          = value.getLongitudeValue().doubleValue;
1751                s.Elevation          = value.getElevationValue().doubleValue;
1752                s.Depth              = value.getDepthValue().doubleValue;
1753                s.Azimuth            = value.getAzimuthValue().doubleValue;
1754                s.Dip                = value.getDipValue().doubleValue;
1755
1756                s.SampleRate         = value.getSampleRateValue().doubleValue;
1757
1758                s.CalibrationUnits        = irisFetch.parse(value.getCalibrationUnits()); % get edu.iris.dmc.fdsn.station.model.Units
1759                %         s.Comment = irisFetch.parseAnArray(value.getComment());
1760                %s.StartTime               = irisFetch.jdate2mdate(value.getStartTime());
1761                s.StartDate               = irisFetch.jdate2mdate(value.getStartDate());% duplicates StartTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1762                %s.EndTime                 = irisFetch.jdate2mdate(value.getEndTime());
1763                s.EndDate                 = irisFetch.jdate2mdate(value.getEndDate());% duplicates EndTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1764                s.DataAvailability        = irisFetch.parse(value.getDataAvailability()); % get edu.iris.dmc.fdsn.station.model.DataAvailability
1765                s.RestrictedStatus        = char(value.getRestrictedStatus());
1766                s.AlternateCode           = char(value.getAlternateCode());
1767                s.HistoricalCode          = char(value.getHistoricalCode());
1768
1769             case {'edu.iris.dmc.fdsn.station.model.Station'}
1770                % s.Network                 = irisFetch.parse(value.getNetwork());     % get edu.iris.dmc.fdsn.station.model.Network
1771                s.StationCode                    = char(value.getCode());
1772                % s.AlternateCode           = char(value.getAlternateCode());
1773                % s.Channel                = irisFetch.parseAnArray(value.getChannels());
1774                s.Latitude                = value.getLatitude().getValue();    % get edu.iris.dmc.fdsn.station.model.Latitude
1775                s.Longitude               = value.getLongitude().getValue();   % get edu.iris.dmc.fdsn.station.model.Longitude
1776                s.Elevation               = irisFetch.parse(value.getElevation());   % get edu.iris.dmc.fdsn.station.model.Distance
1777                s.Site                    = irisFetch.parse(value.getSite());        % get edu.iris.dmc.fdsn.station.model.Site
1778                % s.Vault                   = char(value.getVault());
1779                % s.Geology                 = char(value.getGeology());
1780                % s.Equipment = irisFetch.parseAnArray(value.getEquipment());
1781                % s.Operator = irisFetch.parseAnArray(value.getOperator());
1782                % s.CreationDate            = irisFetch.jdate2mdate(value.getCreationDate());
1783                % s.TerminationDate         = irisFetch.jdate2mdate(value.getTerminationDate());
1784                % s.ExternalReference = irisFetch.parseAnArray(value.getExternalReference());
1785                s.Comment = irisFetch.parseAnArray(value.getComment());
1786                s.Description             = char(value.getDescription());
1787                %s.StartTime               = irisFetch.jdate2mdate(value.getStartTime());
1788                %s.EndTime                 = irisFetch.jdate2mdate(value.getEndTime());
1789                s.StartDate               = irisFetch.jdate2mdate(value.getStartDate()); % duplicates StartTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1790                s.EndDate                 = irisFetch.jdate2mdate(value.getEndDate()); % duplicates EndTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1791                s.DataAvailability        = irisFetch.parse(value.getDataAvailability()); % get edu.iris.dmc.fdsn.station.model.DataAvailability
1792                s.RestrictedStatus        = char(value.getRestrictedStatus());
1793                %s.HistoricalCode          = char(value.getHistoricalCode());
1794                s.Channels                = irisFetch.parseAnArray(value.getChannels());
1795                s.TotalNumberChannels     = double(value.getTotalNumberChannels());
1796                s.SelectedNumberChannels  = double(value.getSelectedNumberChannels());
1797
1798             case {'edu.iris.dmc.fdsn.station.model.Network'}
1799                s.NetworkCode                    = char(value.getCode());
1800                s.Description             = char(value.getDescription());
1801                s.Comment                 = irisFetch.parseAnArray(value.getComment());
1802                %s.StartTime               = irisFetch.jdate2mdate(value.getStartTime());
1803                s.StartDate               = irisFetch.jdate2mdate(value.getStartDate());% duplicates StartTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1804                %s.EndTime                 = irisFetch.jdate2mdate(value.getEndTime());
1805                s.TotalNumberStations     = double(value.getTotalNumberStations());
1806                s.SelectedNumberStations  = double(value.getSelectedNumberStations());
1807                s.EndDate                 = irisFetch.jdate2mdate(value.getEndDate()); % duplicates EndTime (but using org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl)
1808                s.DataAvailability        = irisFetch.parse(value.getDataAvailability()); % get edu.iris.dmc.fdsn.station.model.DataAvailability
1809                s.Stations                = irisFetch.parseAnArray(value.getStations());
1810                s.RestrictedStatus        = char(value.getRestrictedStatus());
1811                % s.AlternateCode           = char(value.getAlternateCode());
1812                % s.HistoricalCode          = char(value.getHistoricalCode());
1813
1814
1815             case {'edu.iris.dmc.sacpz.model.Sacpz'}
1816                s.Location                = char(value.getLocation());
1817                s.Channel                 = char(value.getChannels());
1818                s.Comment                 = char(value.getComment());
1819                s.StartTime               = irisFetch.jdate2mdate(value.getStartTime());
1820                s.Description             = char(value.getDescription());
1821                s.Depth                   = double(value.getDepth());
1822                s.Azimuth                 = double(value.getAzimuth());
1823                s.Elevation               = double(value.getElevation());
1824                s.EndTime                 = irisFetch.jdate2mdate(value.getEndTime());
1825                s.SampleRate              = double(value.getSampleRate());
1826                s.Network                 = char(value.getNetwork());
1827                s.Station                 = char(value.getStations());
1828                s.Latitude                = value.getLatitude().getValue();
1829                s.Longitude               = value.getLongitude().getValue();
1830                s.Sensitivity             = irisFetch.parse(value.getSensitivity()); % get edu.iris.dmc.sacpz.model.NumberUnit
1831                s.Created                 = irisFetch.jdate2mdate(value.getCreated());
1832                s.Poles                 = irisFetch.parseAnArray(value.getPoles());
1833                s.Zeros                 = irisFetch.parseAnArray(value.getZeros());
1834                s.Inclination             = double(value.getInclination());
1835                s.InputUnit               = char(value.getInputUnit());
1836                s.OutputUnit              = char(value.getOutputUnit());
1837                s.InstrumentType          = char(value.getInstrumentType());
1838                s.InstrumentGain          = irisFetch.parse(value.getInstrumentGain()); % get edu.iris.dmc.sacpz.model.NumberUnit
1839                s.A0                      = double(value.getA0());
1840                s.Constant                = value.getConstant();
1841
1842             otherwise
1843                warning('IRISFETCH:parse:classNotFound','%s was not found',myClass)%who knows?
1844          end % cases
1845          if irisFetch.recursionAssert
1846             stacklist(myClass)=false;
1847          end
1848       end  % main function
1849
1850       function matlabdate = jdate2mdate(javadate)
1851          if isempty(javadate)
1852             matlabdate = [];
1853             return;
1854          end
1855          % NOTE: Matlab cannot provide nanosecond resolution, though it can come close...
1856          switch class(javadate)
1857             case 'java.sql.Timestamp' % nanosecond precision
1858                matlabdate = datenummx(1970, 1, 1, 0, 0, (fix(javadate.getTime()/1000) + javadate.getNanos / 1000000000));
1859             case 'java.util.Date' % millisecond precision
1860                matlabdate = datenummx(1970, 1, 1, 0, 0, javadate.getTime()/1000);
1861             case{'javax.xml.datatype.XMLGregorianCalendar',...
1862                   'org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl'}
1863                if isempty(javadate.getFractionalSecond)
1864                   mySecond=javadate.getSecond;
1865                else
1866                   mySecond=javadate.getSecond + double(javadate.getFractionalSecond);
1867                end
1868                matlabdate= datenummx(...
1869                   javadate.getYear, javadate.getMonth,  javadate.getDay, ...
1870                   javadate.getHour, javadate.getMinute, mySecond);
1871             otherwise
1872                matlabdate= datenum(strrep(char(javadate.toString),'T',' ')); % this will probably crash
1873          end
1874          matlabdate=datestr(matlabdate, irisFetch.DATE_FORMATTER);
1875       end %fn jdate2mdate
1876
1877       function s = addUnits(theUnit)
1878          if ~isempty(theUnit)
1879             s         = { char(theUnit.getName), char(theUnit.getDescription) };  % get edu.iris.dmc.fdsn.station.model.Units
1880          else
1881             s = {'',''};
1882          end
1883       end
1884
1885       function s = parseAnArray(theArray)
1886          persistent getAz getDis getResid
1887          if isempty(getAz) || isempty(getDis) || isempty(getResid)
1888             getAz    =@(x) double(x.getAzimuth());
1889             getDis   =@(x) double(x.getDistance());
1890             getResid =@(x) double(x.getTimeResidual());
1891          end
1892          if isnumeric(theArray),
1893             s = theArray;
1894             return
1895          end
1896
1897          arraySize = theArray.size();
1898          if arraySize == 0,
1899             s=[];
1900             return
1901          end
1902
1903          firstItem = theArray.get(0);
1904
1905          if isjava(firstItem)
1906             switch class(firstItem)
1907                case {'edu.iris.dmc.fdsn.event.model.Event'}
1908                   disp('counter detailing the event')
1909                case {'edu.iris.dmc.fdsn.station.model.Network'}
1910                   disp('counter detailing network');
1911             end
1912             for nn=arraySize : -1 : 1
1913                s(nn)= irisFetch.parse(theArray.get(nn-1));
1914             end
1915             theArray.clear;
1916             return
1917          end
1918
1919          if arraySize == 1
1920             s=firstItem;
1921          elseif ischar(firstItem)
1922             s=char(theArray);
1923          else % the array doesn't contain java or text, so it's probably just numbers.
1924             try
1925                s=double(theArray.toArray(javaArray('java.lang.Double',arraySize)));
1926             catch er
1927                disp(er.message)
1928                fprintf('unable to convert %s as though it were numbers.\n', class(theArray.get(0)));
1929                for nn=arraySize:-1:1
1930                   s(nn)={theArray.get(nn-1)};% create a cell
1931                end
1932             end
1933          end
1934          theArray.clear;
1935       end %fn parseAnArray
1936
1937       %----------------------------------------------------------------
1938       % END: PARSING ROUTINES
1939       %----------------------------------------------------------------
1940       %================================================================
1941       %%
1942
1943       function crit = addCriteria(crit, value, addMethod)
1944          %used to add Sta, Net, Loc, Chan to criteria
1945          % For example:
1946          %   singleAddToCriteria(criteria, {'OKCF','MNO?'},'addStation')
1947          % will invoke:
1948          %   criteria.addStation('OKCF').addStation('MNO?')
1949
1950          if isempty(value)
1951             return %do nothing
1952          end
1953          if ~iscell(value)
1954             % it's probably a string
1955             crit.(addMethod)(value);
1956          else
1957             % a cell may have multiple values.
1958             for n=1:numel(value)
1959                crit.(addMethod)(value{n});
1960             end
1961          end
1962       end
1963
1964       function crit = setBoxCoordinates(crit, value)
1965          % setBoxCoordinates (minLat, maxLat, minLon, maxLon)
1966          % values of 'NAN' are ignored
1967          assert(numel(value)==4,'IRISFETCH:setBoxCoordinates:InvalidParameterCount',...
1968             'Expected [minLat, maxLat, minLon, maxLon]');
1969
1970          setMethods = {'setMinimumLatitude','setMaximumLatitude',...
1971             'setMinimumLongitude','setMaximumLongitude'};
1972          for n=1:numel(setMethods)
1973             if ~isnan(value(n))
1974                crit.(setMethods{n})(java.lang.Double(value(n)));
1975             end
1976          end
1977       end
1978
1979       function crit = setCriteria(crit, paramList)
1980
1981          %----------------------------------------------------------
1982          % The following code allows for open-ended search criteria
1983          % that can change when the java library changes
1984          %
1985          % Instead of hard-coding each Setter, query the java class to determine its set methods
1986          %
1987          % Also determine the input parameters for each setter, then
1988          % use that to properly create/cast the data.
1989          %----------------------------------------------------------
1990
1991          % Get a list of parameters, their set functions, and input
1992          % types, and do it outside the loop so they are not needlessly
1993          % rerun
1994
1995          [allSetMethods, argType]   = irisFetch.getSetters(crit);
1996          settableFieldnames         = irisFetch.getSettableFields(crit);
1997          allMethods                 = methods(crit);
1998
1999          while ~isempty(paramList) && numel(paramList) >= 2
2000
2001             % Grab the parameter pair, then remove from parameter list
2002             [param value] = deal(paramList{1:2});
2003             paramList(1:2)=[];
2004
2005             indexOfMethod = strcmpi(param,settableFieldnames);
2006
2007             if any(indexOfMethod)
2008                try
2009                   converter=irisFetch.M2J_MAP(argType{indexOfMethod});
2010                catch er
2011                   disp(er.message)
2012                   fprintf('Unanticipated argument type [%s]... trying\n',argType{indexOfMethod});
2013                   converter=@(x) x;
2014                end
2015                crit.(allSetMethods{indexOfMethod})(converter(value));
2016                continue
2017             end % if any
2018
2019             % we shall only pass this point if existing methods were not used
2020
2021             switch lower(param)
2022                %handle special cases
2023                case 'boxcoordinates'
2024                   crit = irisFetch.setBoxCoordinates(crit, value);
2025
2026                case 'radialcoordinates'
2027                   crit.setLatitude(java.lang.Double(value(1)));
2028                   crit.setLongitude(java.lang.Double(value(2)));
2029                   crit.setMaximumRadius(java.lang.Double(value(3)));
2030                   if numel(value) ==4 && ~isnan(value(4))
2031                      crit.setMinimumRadius(java.lang.Double(value(4)));
2032                   end
2033
2034
2035                case 'includeavailability'
2036                   assert((islogical(value)||isnumeric(value)) &&isscalar(value),'The value of IncludeAvailability should be a scalar logical: true or false (no quotes)');
2037                   crit.setIncludeAvailability(value);
2038                case 'includerestricted'
2039                   assert((islogical(value)||isnumeric(value)) &&isscalar(value),'The value of IncludeRestricted should be a logical: true or false (no quotes)');
2040                   crit.setIncludeRestricted(value);
2041                case 'matchtimeseries'
2042                   assert((islogical(value)||isnumeric(value)) &&isscalar(value),'The value of MatchTimeseries should be a logical: true or false (no quotes)');
2043                   crit.setMatchTimeSeries(value);
2044
2045                case 'limit'
2046                   crit.setFetchLimit(java.lang.Integer(value));
2047                otherwise
2048                   try
2049                      % this will blow up if java doesn't recognize "value"
2050                      crit.(allMethods{strcmpi(allMethods,param)})(value);
2051                   catch
2052                      switch(class(value))
2053                         case 'double'; value=num2str(value);
2054                         case 'logical'; if value; value='true'; else value='false'; end
2055                      end
2056                      assert(ischar(value),'IRISFETCH:Event:InvalidParameterPair','When adding arbitrary parameter pairs, value must be a string. In this case, %s=<%s>',param,class(value));
2057                      crit.add(param,value); %as of 2.0.2 can add arbitrary parameter/value pairs.
2058                   end
2059                   % %this will blow up if java doesn't recognize "value"
2060                   % crit.(allMethods{strcmpi(allMethods,param)})(value);
2061             end
2062          end
2063       end
2064    end %static protected methods
2065 end
2066