Description of hist
Home > GISMO > core > @Catalog > hist.m
hist
PURPOSE
HIST plot histograms of magnitude distribution, depth
SYNOPSIS
function hist(catalogObject);
DESCRIPTION
HIST plot histograms of magnitude distribution, depth
distribution etc
   catalog_object.hist()
CROSS-REFERENCE INFORMATION
This function calls:
hist HIST plot histograms of magnitude distribution, depth
max MIN Largest value of a waveform.
min MIN Smallest value of a waveform.
This function is called by:
plot_stats PLOT_STATS plot statistics from master correlation algorithm
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
arrival_histogram ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
calc_McMaxCurvature CALC_MCMAXCURVATURE
synthb_aut This is synthetic219
Catalog CATALOG the blueprint for Catalog objects in GISMO
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
hist HIST plot histograms of magnitude distribution, depth
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
cluster cluster Construct agglomerative clusters from linkage for Seismic Traces
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
SOURCE CODE
function hist(catalogObject);
    %HIST plot histograms of magnitude distribution, depth
    %distribution etc
    %   catalog_object.hist()
    mmin = min(catalogObject.mag);
    mmax = max(catalogObject.mag);
    bincenters = floor(mmin*10)/10 + 0.05 : 0.1 : floor(mmax*10)/10 + 0.05;
    hist(catalogObject.mag, bincenters);
end