Description of plot_time
Home > GISMO > core > @Catalog > plot_time.m
plot_time
PURPOSE
CATALOG.PLOT_TIME Plot magnitude and depth against time
SYNOPSIS
function plot_time(catalogObject)
DESCRIPTION
CATALOG.PLOT_TIME Plot magnitude and depth against time
   catalogObject.plot_time()
CROSS-REFERENCE INFORMATION
This function calls:
set SET Set properties for correlation object
set SET: Set drumplot properties
set SET - Set filterobject properties
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
set SET inserts properties for threecomp object
set SET Set properties for waveform object(s)
set SET Set properties for correlation object
set SET: Set helicorder properties
This function is called by:
Catalog CATALOG the blueprint for Catalog objects in GISMO
SOURCE CODE
function plot_time(catalogObject)
    %CATALOG.PLOT_TIME Plot magnitude and depth against time
    %   catalogObject.plot_time()
    % Glenn Thompson 2014/06/01
    symsize = get_symsize(catalogObject);
    timerange = catalogObject.gettimerange();
    xlims = [floor(timerange(1)) ceil(timerange(2))];
    % time-depth
    if all(isnan(catalogObject.depth))
        warning('No depth data to plot');
    else
        figure;
        set(gcf,'Color', [1 1 1]);
        subplot(2,1,1);
        scatter(catalogObject.otime, catalogObject.depth, symsize);
        set(gca, 'XLim', xlims);
        datetick('x');
        xlabel('Date');
        ylabel('Depth (km)');
        set(gca, 'YDir', 'reverse');
        grid on;
        % time-mag
        subplot(2,1,2);
    end
    if all(isnan(catalogObject.mag))
        warning('No magnitude data to plot');
    else
        scatter(catalogObject.otime, catalogObject.mag, symsize);
        %stem(catalogObject.otime, catalogObject.mag);
        set(gca, 'XLim', xlims);
        datetick('x');
        xlabel('Date');
        ylabel('Magnitude');
        grid on;
    end
end