Description of plotprmm
Home > GISMO > core > @Catalog > plotprmm.m
plotprmm
PURPOSE
CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
SYNOPSIS
function plotprmm(catalogObject)
DESCRIPTION
CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
set of events
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp DISP Datasource disp overloaded operator
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
disp DISP - scnl disp overloaded operator
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
set SET - Set properties for spectralobject
disp DISP Display threecomp object
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
disp DISP Waveform disp overloaded operator
max MIN Largest value of a waveform.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
disp CORRELATION/DISPLAY Command window display of a correlation object
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp disp Display information about SeismicTrace(s)
plot plot plots a SeismicTrace
disp DISP: Helicorder disp overloaded operator
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
Catalog CATALOG the blueprint for Catalog objects in GISMO
SOURCE CODE
function plotprmm(catalogObject)
    %CATALOG.PLOTPRMM Plot the peak rate and maximum magnitude of a
    %set of events
    figure
    symsize = get_symsize(catalogObject);
    t=catalogObject.gettimerange();
    days = t(2) - t(1);
    if all(isnan(catalogObject.mag))
        warning('No magnitude data to plot');
    else
        % plot magnitudes
        subplot(2,1,1), scatter(catalogObject.otime, catalogObject.mag, symsize);
        %stem(catalogObject.otime, catalogObject.mag);
        set(gca, 'XLim', [floor(t(1)) ceil(t(2))]);
        datetick('x');
        xlabel('Date');
        ylabel('Magnitude');
        grid on;
        % put 'MM' label by max mag event
        [mm, mmi] = max(catalogObject.mag);
        text(catalogObject.otime(mmi), catalogObject.mag(mmi), 'MM','color','r');
        disp(sprintf('MM=%.1f occurs at %.1f%% of time series',mm,100*(catalogObject.otime(mmi) - t(1))/days));
        % plot event rate in 100 equal bins
        binsize = days/100;
        erobj = catalogObject.eventrate('binsize',binsize);
        %erobj = catalogObject.eventrate();
        subplot(2,1,2),plot(erobj.time, erobj.counts);
        set(gca, 'XLim', [floor(t(1)) ceil(t(2))]);
        datetick('x');
        xlabel('Date');
        ylabel('Event Rate');
        grid on;
        % put 'PR' label by peak-rate
        [pr, pri] = max(erobj.counts);
        text(erobj.time(pri), erobj.counts(pri), 'PR','color','r');
        disp(sprintf('PR=%d occurs at %.1f%% of time series',pr,100*(erobj.time(pri) - erobj.snum)/(erobj.enum-erobj.snum)));
    end
end