Description of summary
Home > GISMO > core > @Catalog > summary.m
summary
PURPOSE
CATALOG.SUMMARY Summarise a Catalog object
SYNOPSIS
function summary(obj)
DESCRIPTION
CATALOG.SUMMARY Summarise a Catalog object
CROSS-REFERENCE INFORMATION
This function calls:
summary CATALOG.SUMMARY Summarise a Catalog object
This function is called by:
Catalog CATALOG the blueprint for Catalog objects in GISMO
summary CATALOG.SUMMARY Summarise a Catalog object
SOURCE CODE
function summary(obj)
%CATALOG.SUMMARY Summarise a Catalog object
    summary(obj.table)
end