Description of Fs
Home > GISMO > core > @rsam > Fs.m
Fs
PURPOSE
SYNOPSIS
function fs = Fs(self)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
median MEDIAN middlemost value of waveform's sorted data.
This function is called by:
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
minus C = MINUS(C,I)
stack c = STACK(c)
rsam
pwelch PWELCH overloaded pwelch for spectralobjects
specgram SPECGRAM - plots spectrogram of waveforms
minus C = MINUS(C,I)
stack c = STACK(c)
sta_lta STA_LTA: Short-Time-Average/Long-Time-Average event detector.
plot PLOT plot fourier transform of a waveform
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
SOURCE CODE
function fs = Fs(self)
    l = length(self.dnum);
    s = self.dnum(2:l) - self.dnum(1:l-1);
    fs = 1.0/(median(s)*86400);
end