Description of load
Home > GISMO > core > @rsam > load.m
load
PURPOSE
Purpose:
SYNOPSIS
function self = load(self)
DESCRIPTION
 Purpose:
    Loads derived data from a binary file in the BOB RSAM format
    The pointer position at which to reading from the binary file is determined from f.snum
    Load all the data from f.snum to f.enum. So if timewindow is 12:34:56 to 12:44:56,
    it is the samples at 12:35, ..., 12:44 - i.e. 10 of them.
 Input:
    self.f - a structure which contains 'file', 'snum', 'enum' and 'found' parameters
 Author:
   Glenn Thompson, MVO, 2000
CROSS-REFERENCE INFORMATION
This function calls:
catmatrices CATMATRICES - concatenate 2D matrices of arbitrary size
ceilminute CEILMINUTE round up datenum to next minute mark
This function is called by:
iceweb
montserrat_remove_analog_sites
incomplete OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
stream2waveform OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
stream_matfile2waveform OBSPY.STREAM2WAVEFORM Use ObsPy to read a stream object and then convert
demo_plutons
response_demo_waveforms RESPONSE_DEMO_WAVEFORMS returns the absolute path to the demo database
dmc_cookbook
load_cookbook_data LOAD_COOKBOOK_DATA Load sample data used in MASTERCORR.COOKBOOK
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
dd_collate dd_collate('event.dat')
map MAP plot a map of ray coverage.
cookbook % Catalog Cookbook
webmap CATALOG.WEBMAP Plot hypocenters in map view using webmap
colormap C = COLORMAP(C)
correlation
corrplot Called internally by correlation/plot to plot correlation matrix.
lagplot Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
wiggleinterferogram Private method. See ../plot for details.
load_file grab all the variables in a matlab file, and flip through them, returning
load_objects_from_file grab all the variables in a matlab file, and flip through them, returning
loadbobfile LOADBOBFILE Load an RSAM binary file
rsam
spectralobject SPECTRALOBJECT - spectralobject class constructor
demo DEMO
diagnostic DIAGNOSTIC check for accurate behavior of threecomp object.
load_file LOAD_FILE
load_matfile LOAD_FILE
load_obspy LOAD_OBSPY loads matlab files that were saved by ObsPy as per the ObsPy tutorial
spatiotemporal_file
NewCorrelation
colormap colormap apply a colormap to the cross-correlation
corrplot corrplot plot the correlation matrix
lagplot lagplot
wiggleinterferogram Private method. See ../plot for details.
TraceSpectra
testWaveform
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
ideas2waveform OPEN_INFRASOUND Open UAF/GI infrasound data as a waveform object.
SOURCE CODE
function self = load(self)
% Purpose:
%    Loads derived data from a binary file in the BOB RSAM format
%    The pointer position at which to reading from the binary file is determined from f.snum
%    Load all the data from f.snum to f.enum. So if timewindow is 12:34:56 to 12:44:56,
%    it is the samples at 12:35, ..., 12:44 - i.e. 10 of them.
%
% Input:
%    self.f - a structure which contains 'file', 'snum', 'enum' and 'found' parameters
% Author:
%   Glenn Thompson, MVO, 2000
    % initialise return variables
    f = self.files;
    [yyyy, ~]=datevec(f.snum);
    days=365;
    if mod(yyyy,4)==0
        days=366;
    end
    datapointsperday = 1440;
    headersamples = 0;
    tz=0;
    if strfind(f.file,'RSAM')
        headersamples=datapointsperday;% for PC-SEIS RSAM data there is a 1 day header
        tz=-4;% for Montserrat RSAM data time zone is off by 4 hours
    end
    startsample = ceil( (f.snum-datenum(yyyy,1,1))*datapointsperday)+headersamples;
    endsample   = (f.enum-datenum(yyyy,1,1)) *datapointsperday + headersamples;
    nsamples    = endsample - startsample + 1;
    % create dnum & blank data vector
    dnum_ = ceilminute(f.snum)+(0:nsamples-1)/datapointsperday - tz/24;
    data_ = nan(1,length(dnum_));
    if f.found
        % file found
        debug.print_debug(0, sprintf( 'Loading data from %s, position %d to %d of %d', ...
             f.file, startsample,(startsample+nsamples-1),(datapointsperday*days) ));
        fid=fopen(f.file,'r', 'l'); % big-endian for Sun, little-endian for PC
        % Position the pointer
        offset=(startsample)*4;
        fseek(fid,offset,'bof');
        % Read the data
        [data_, ~] = fread(fid, nsamples, 'float32');
        fclose(fid);
        debug.print_debug(0, sprintf('mean of data loaded is %e',nanmean(data_)));
        % Transpose to give same dimensions as dnum
        data_=data_';
        % Test for Nulls
        datafound = any(data_ > 0);
    else
       datafound = false;
       debug.print_debug(0, sprintf('File %s not found', f.file));
    end
    % Now paste together the matrices
    self.dnum = catmatrices(dnum_, self.dnum);
    self.data = catmatrices(data_, self.data);
    if ~datafound
        debug.print_debug(0, sprintf('%s: No data loaded from file %s',mfilename,f.file));
    end
    % eliminate any data outside range asked for
    myRange = self.dnum >= self.snum & self.dnum <= self.enum;
    self.dnum = self.dnum(myRange);
    self.data = self.data(myRange);
    % Fill NULL values with NaN
    self.data(self.data == -998 | self.data == 0) = NaN;
end