Description of plotyy
Home > GISMO > core > @rsam > plotyy.m
plotyy
PURPOSE
SYNOPSIS
function plotyy(obj1, obj2, varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
set SET Set properties for correlation object
set SET: Set drumplot properties
set SET - Set filterobject properties
plotyy
set SET - Set properties for scnlobject
set SET - Set properties for spectralobject
set SET inserts properties for threecomp object
max MIN Largest value of a waveform.
min MIN Smallest value of a waveform.
set SET Set properties for waveform object(s)
set SET Set properties for correlation object
set SET: Set helicorder properties
This function is called by:
EventRate
oneMinuteData
plotyy
SOURCE CODE
function plotyy(obj1, obj2, varargin)
   p = inputParser;
   p.addParameter('snum',max([obj1.dnum(1) obj2.dnum(1)]));
   p.addParameter('enum', min([obj1.dnum(end) obj2.dnum(end)]));
   p.addParameter('fun1','plot');
   p.addParameter('fun2','plot');
   p.parse(varargin{:});
   Args = p.Results;
    [ax, ~, ~] = plotyy(obj1.dnum, obj1.data, obj2.dnum, obj2.data, Args.fun1, Args.fun2);
    datetick('x');
    set(ax(2), 'XTick', [], 'XTickLabel', {});
    set(ax(1), 'XLim', [Args.snum Args.enum]);
end