Description of save
Home > GISMO > core > @rsam > save.m
save
PURPOSE
RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
SYNOPSIS
function save(self, filepattern)
DESCRIPTION
 RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
 file
 Examples:
   1. save data to myfile.bob
       r.save('myfile.bob')
   2. save to file like YEAR_STATION_CHANNEL_MEASURE.bob
       r.save('YYYY_SSSS_CCC_MMMM.bob')
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
diff DIFF differentiate each trace.
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
diff DIFF Differentiate waveform
disp DISP Waveform disp overloaded operator
diff DIFF differentiate each trace.
disp CORRELATION/DISPLAY Command window display of a correlation object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
iceweb
montserrat_remove_analog_sites
setup
waveform_wrapper WAVEFORM_WRAPPER try multiple datasource objects in
demo_plutons
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
cookbook % Catalog Cookbook
conv c = CONV(c) convolves all traces with the final trace. By default the new
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
rsam
create_demo_data This script was used once to create the demo dataset
conv conv convolve all traces with the final trace
deconv c = DECONV(c) convolves all traces with the final trace. By default the new
testWaveform
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
SOURCE CODE
function save(self, filepattern)
    % RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
    % file
    %
    %
    % Examples:
    %   1. save data to myfile.bob
    %       r.save('myfile.bob')
    %
    %   2. save to file like YEAR_STATION_CHANNEL_MEASURE.bob
    %       r.save('YYYY_SSSS_CCC_MMMM.bob')
    %
    for c=1:numel(self)
        dnum = self(c).dnum;
        data = self(c).data;
        file = filepattern;
        % substitute for station
        file = regexprep(file, 'SSSS', upper(self(c).sta));
        % substitute for channel
        file = regexprep(file, 'CCC', upper(self(c).chan));
        % substitute for measure
        file = regexprep(file, 'MMMM', self(c).measure);
        % since dnum may not be ordered and contiguous, this function
        % should write data based on dnum only
        if length(dnum)~=length(data)
                debug.print_debug(0,sprintf('%s: Cannot save to %s because data and time vectors are different lengths',mfilename,filename));
                return;
        end
        if length(data)<1
                debug.print_debug(0,'No data. Aborting');
            return;
        end
        % filename
        % set start year and month, and end year and month
        [syyy sm]=datevec(self(c).snum);
        [eyyy em]=datevec(self(c).enum);
        if syyy~=eyyy
            if ~strfind(filepattern, 'YYYY')
                        error('can only save RSAM data to BOB file if all data within 1 year (or you can add YYYY in your file pattern)');
            end
        end
        for yyyy=syyy:eyyy
            % how many days in this year?
            daysperyear = 365;
            if (mod(yyyy,4)==0)
                    daysperyear = 366;
            end
            % Substitute for year
            fname = regexprep(file, 'YYYY', sprintf('%04d',yyyy) );
            debug.print_debug(2,sprintf('Looking for file: %s\n',fname));
            if ~exist(fname,'file')
                    debug.print_debug(2, ['Creating ',fname])
                    rsam.makebobfile(fname, daysperyear);
            end
            datapointsperday = 1440;
            % round times to minute
            dnum = round((dnum-1/86400) * 1440) / 1440;
            % subset for current year
            dnumy = dnum(dnum < datenum(yyyy + 1, 1, 1));
            datay = data(dnum < datenum(yyyy + 1, 1, 1));
            % find the next contiguous block of data
            diff=dnumy(2:end) - dnumy(1:end-1);
            i = find(diff > 1.5/1440 | diff < 0.5/1440);
            disp(sprintf('Saving to %s',fname));
            if length(i)>0
                % slow mode
                for c=1:length(dnumy)
                    % write the data
                    startsample = round((dnumy(c) - datenum(yyyy,1,1)) * datapointsperday);
                    offset = startsample*4;
                    fid = fopen(fname,'r+');
                    fseek(fid,offset,'bof');
                    debug.print_debug(2, sprintf('saving data with mean of %e from to file %s, starting at position %d',nanmean(datay),fname,startsample,(datapointsperday*daysperyear)))
                    fwrite(fid,datay(c),'float32');
                    fclose(fid);
                end
            else
                % fast mode
                % write the data
                startsample = round((dnumy(1) - datenum(yyyy,1,1)) * datapointsperday);
                offset = startsample*4;
                fid = fopen(fname,'r+','l'); % little-endian. Anything written on a PC is little-endian by default. Sun is big-endian.
                fseek(fid,offset,'bof');
                debug.print_debug(2, sprintf('saving data with mean of %e from to file %s, starting at position %d/%d',nanmean(datay),fname,startsample,(datapointsperday*daysperyear)))
                fwrite(fid,datay,'float32');
                fclose(fid);
            end
        end
    end
end