Description of scrollplot
Home > GISMO > core > @rsam > scrollplot.m
scrollplot
PURPOSE
Created by Steven Lord, slord@mathworks.com
SYNOPSIS
function scrollplot(s)
DESCRIPTION
 Created by Steven Lord, slord@mathworks.com
 Uploaded to MATLAB Central
 http://www.mathworks.com/matlabcentral
 7 May 2002
 Permission is granted to adapt this code for your own use.
 However, if it is reposted this message must be intact.
CROSS-REFERENCE INFORMATION
This function calls:
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
get GET Get waveform properties
max MIN Largest value of a waveform.
min MIN Smallest value of a waveform.
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
plot plot plots a SeismicTrace
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
scroll SCROLL scroll through the data in a waveform vector
SOURCE CODE
function scrollplot(s)
    % Created by Steven Lord, slord@mathworks.com
    % Uploaded to MATLAB Central
    % http://www.mathworks.com/matlabcentral
    % 7 May 2002
    %
    % Permission is granted to adapt this code for your own use.
    % However, if it is reposted this message must be intact.
    % Generate and plot data
    x=s.dnum();
    y=s.data();
    dx=1;
    %% dx is the width of the axis 'window'
    a=gca;
    p=plot(x,y);
    % Set appropriate axis limits and settings
    set(gcf,'doublebuffer','on');
    %% This avoids flickering when updating the axis
    set(a,'xlim',[min(x) min(x)+dx]);
    set(a,'ylim',[min(y) max(y)]);
    % Generate constants for use in uicontrol initialization
    pos=get(a,'position');
    Newpos=[pos(1) pos(2)-0.1 pos(3) 0.05];
    %% This will create a slider which is just underneath the axis
    %% but still leaves room for the axis labels above the slider
    xmax=max(x);
    xmin=min(x);
    xmin=0;
    %gs = get(gcbo,'value')+[min(x) min(x)+dx]
    S=sprintf('set(gca,''xlim'',get(gcbo,''value'')+[%f %f])',[xmin xmin+dx])
    %% Setting up callback string to modify XLim of axis (gca)
    %% based on the position of the slider (gcbo)
    % Creating Uicontrol
    h=uicontrol('style','slider',...
        'units','normalized','position',Newpos,...
        'callback',S,'min',xmin,'max',xmax-dx);
        %'callback',S,'min',0,'max',xmax-dx);
end