Description of datenum2epoch
Home > GISMO > libgismo > datenum2epoch.m
datenum2epoch
PURPOSE
EPOCH = DATENUM2EPOCH(TIME) translates Matlab numeric
SYNOPSIS
function epoch = datenum2epoch(time)
DESCRIPTION
 EPOCH = DATENUM2EPOCH(TIME) translates Matlab numeric
 date format into Unix epoch date format.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
response_get_from_db RESPONSE_GET_FROM_DB Get instrument response from database.
antelope READ_CATALOG.ANTELOPE load events from a CSS3.0 database using Antelope.
listMiniseedFiles LISTMINISEEDFILES retrieve a list of the Miniseed files referenced by a datasource, ChannelTag object and start/end times.
write CATALOG.WRITE Write an Catalog object to disk
EventRate
writedb WRITEDB write antelope database tables
writedb WRITEDB write antelope database tables
antelope2waveform_test dbpath = '/aerun/sum/db/archive/archive_2011/archive_2011_11_16';
SOURCE CODE
% EPOCH = DATENUM2EPOCH(TIME) translates Matlab numeric
% date format into Unix epoch date format.
% Author: Michael West. Modified Glenn Thompson.
% $Date$
% $Revision$
function epoch = datenum2epoch(time)
epoch = zeros(size(time));
if admin.antelope_exists()
    for n = 1:numel(time)
        epoch(n) = str2epoch(datestr(time(n),'mm/dd/yyyy HH:MM:SS.FFF'));
    end
else
    % Does not account for leap seconds.
    for n = 1:numel(time)
        epoch(n) = (time - datenum(1970,1,1,0,0,0))*86400;
    end
end