Description of epoch2datenum
Home > GISMO > libgismo > epoch2datenum.m
epoch2datenum
PURPOSE
TIME = EPOCH2DATENUM(EPOCH) translates Unix epoch date format into Matlab
SYNOPSIS
function time = epoch2datenum(epoch)
DESCRIPTION
 TIME = EPOCH2DATENUM(EPOCH) translates Unix epoch date format into Matlab
 numeric date format.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
hankelq HANKELQ Compute spectral ratio in two frequency bands
dd_make_scp DD_MAKE_SCP Create a draft control file for the correlation process
dd_process_scp DD_PROCESS_SCP Process correlations by station and channel
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
reducedisp_plot REDUCEDISP_PLOT plot reduced displacement data.
dbload DBLOAD extracts travel times from a database
antelope LOAD_ARRIVALS Load arrivals from a CSS3.0 database
antelope2waveform ANTELOPE2WAVEFORM Load waveform objects from Antelope database
arrivals2waveforms ARRIVALS2WAVEFORMS Load waveform objects corresponding to an arrivals structure
dbgetarrivals DBGETARRIVALS Load arrivals from an Antelope CSS3.0 database
dbgetorigins DBGETORIGINS Load preferred origins from an Antelope CSS3.0
EventRate
load_antelope load a waveform from antelope
load_antelope_old load a waveform from antelope
load_miniseed LOAD_MINISEED loads a waveform from MINISEED files
get_antelope_traces GET_ANTELOPE_TRACE gets interesting data from database, and returns the tracebuf object
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
SOURCE CODE
% TIME = EPOCH2DATENUM(EPOCH) translates Unix epoch date format into Matlab
% numeric date format.
% Author: Michael West, Modified by Glenn Thompson
% $Date$
% $Revision$
function time = epoch2datenum(epoch)
    if admin.antelope_exists()
        time = datenum(epoch2str(epoch,'%m %d %Y %H %M %S.%s'),'mm dd yyyy HH MM SS.FFF');
    else % does not handle leap seconds
        time = datenum(1970,1,1,0,0,epoch);
    end
end