Description of floorminute
Home > GISMO > libgismo > floorminute.m
floorminute
PURPOSE
FLOORMINUTE round up datenum to next minute mark
SYNOPSIS
function dnum=floorminute(dnum,nummins)
DESCRIPTION
 FLOORMINUTE round up datenum to next minute mark
 dnum=floorminute(dnum)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
SOURCE CODE
function dnum=floorminute(dnum,nummins)
% FLOORMINUTE round up datenum to next minute mark
% dnum=floorminute(dnum)
% AUTHOR: Glenn Thompson, University of Alaska Fairbanks
% $Date$
% $Revision$
if ~exist('nummins','var')
    nummins =1;
end
factor = 1440/nummins;
dnum=floor(dnum*factor)/factor;