Description of utnow
Home > GISMO > libgismo > utnow.m
utnow
PURPOSE
UTNOW
SYNOPSIS
function utdnum=utnow()
DESCRIPTION
 UTNOW
    ut_datenum = utnow()
    Return a MATLAB datenum corresponding to the current UT time/date.
    Uses Unix date command, so should work on Linux, Solaris & MacOS.
    It is a convenient way to compute UTC regardless of whether summer
    time applies.
    Caveats:
    Currently only configured for 'AKDT' and 'AKST'. If your Unix
    timezone is anything else, you need to add cases.
    See also datenum, now
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
isempty ISEMPTY Display threecomp object
disp DISP Waveform disp overloaded operator
isempty ISEMPTY returns TRUE if waveform contains no data
disp CORRELATION/DISPLAY Command window display of a correlation object
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
get_timewindow GET_TIMEWINDOW
iceweb
saveImageFile saveImageFile(IMGDIR, fname, res);
SUBFUNCTIONS
function atomTime = get_atomic_time()
SOURCE CODE
function utdnum=utnow()
% UTNOW
%    ut_datenum = utnow()
%    Return a MATLAB datenum corresponding to the current UT time/date.
%    Uses Unix date command, so should work on Linux, Solaris & MacOS.
%
%    It is a convenient way to compute UTC regardless of whether summer
%    time applies.
%
%    Caveats:
%    Currently only configured for 'AKDT' and 'AKST'. If your Unix
%    timezone is anything else, you need to add cases.
%
%    See also datenum, now
%    Author: Glenn Thompson
    persistent hour_adjust; % assumes time zone is UTC  i.e. GMT
    if isempty(hour_adjust) % look up first time only
        atomtime = get_atomic_time();
        [status, unixnowstr] = system('date +"%Y-%m-%d %H:%M:%S"');
        unixnow = datenum(unixnowstr);
        hour_adjust = round(24 * (unixnow - atomtime));
    end
    hour_adjust
    if isunix
        [status, unixnowstr] = system('date +"%Y-%m-%d %H:%M:%S"');
        unixnow = datenum(unixnowstr);
        [status, unixnowTZ] = system('date +"%Z"');
        unixnowTZ = unixnowTZ(1:end-1); % chomp
        switch unixnowTZ
%             case 'BST'
%                 utdnum = unixnow - 1/24;
            case 'AKDT'
                utdnum = unixnow + 8/24;
            case 'AKST'
                utdnum = unixnow + 9/24;
            otherwise
                utdnum = unixnow + hour_adjust;
        end
    else
        disp('utnow: Sorry, your system does not support the Unix date command.')
    end
end
function atomTime = get_atomic_time()
    URL = 'http://tycho.usno.navy.mil/cgi-bin/timer.pl';
    atomTime = datenum(regexp(urlread(URL), ...
        '<BR>(.*)\sUTC','tokens','once'),'mmm. dd, HH:MM:SS');
end