Description of filterobject
Home > GISMO > core > @filterobject > filterobject.m
filterobject
PURPOSE
FILTEROBJECT constructor for a filter object
SYNOPSIS
function f = filterobject(anything, cutoff, poles)
DESCRIPTION
 FILTEROBJECT constructor for a filter object
   f = filterobject() creates a new default filterobject
   f = filterobject(filterobject) duplicates a filterobject
   f = filterobject(type, cutoff, poles) create user-defined filterobject
   TYPE:  'B' : Bandpass, 'H' : Highpass, 'L' : Lowpass
   CUTOFF: [low, high] for bandpass, single value for others
   POLES: number of poles used in the filter
   default new object: Bandpass from 0.8 Hz to 5Hz, 2 poles (as dictated
   by this constructor file
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
set SET Set properties for correlation object
disp DISP Datasource disp overloaded operator
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
filterobject FILTEROBJECT constructor for a filter object
set SET - Set filterobject properties
disp DISP - scnl disp overloaded operator
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
set SET - Set properties for spectralobject
disp DISP Display threecomp object
set SET inserts properties for threecomp object
disp DISP Waveform disp overloaded operator
set SET Set properties for waveform object(s)
disp CORRELATION/DISPLAY Command window display of a correlation object
set SET Set properties for correlation object
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
set SET: Set helicorder properties
This function is called by:
setup
demo_plutons
response_cookbook % Instrument response cookbook
cookbook COOKBOOK demonstrate the features of the mastercorr package.
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
hankelq HANKELQ Compute spectral ratio in two frequency bands
butter C = BUTTER(C,[TYPE],CUTOFF,[POLES])
cookbook % drumplot cookbook
filt FILT: Quick function for 2-pole filtering waveforms and avoiding the
filterobject FILTEROBJECT constructor for a filter object
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
separating_tremor_and_events Tremor range is 1-5 Hz
SUBFUNCTIONS
function load_global_namespace()
SOURCE CODE
function f = filterobject(anything, cutoff, poles)
% FILTEROBJECT constructor for a filter object
%   f = filterobject() creates a new default filterobject
%   f = filterobject(filterobject) duplicates a filterobject
%   f = filterobject(type, cutoff, poles) create user-defined filterobject
%
%   TYPE:  'B' : Bandpass, 'H' : Highpass, 'L' : Lowpass
%   CUTOFF: [low, high] for bandpass, single value for others
%   POLES: number of poles used in the filter
%
%   default new object: Bandpass from 0.8 Hz to 5Hz, 2 poles (as dictated
%   by this constructor file
% VERSION: 1.0 of filter objects
% AUTHOR: Celso Reyes
% LASTUPDATE: 1/30/2007
load_global_namespace;
switch nargin
    case 0
            %create a fresh filterobject
            f.type = 'B';
            f.cutoff = [0.8 5];
            f.poles = 2;
            f = class(f, 'filterobject');
    case 1
        if isa(anything, 'filterobject')
            f = anything;
        else
            error(['trying to use filterobject(' class(anything) ')']);
        end
    case 3
        f = filterobject;
        f = set(f,'type',anything, 'cutoff', cutoff,'poles',poles);
    otherwise
        disp('Invalid arguments in filterobject constructor');
end;
%% LOAD filterobject's global namespace
% replaces SUITE_STUFF
function load_global_namespace()
persistent FILTER_NAMESPACE
if FILTER_NAMESPACE
    return
else
    FILTER_NAMESPACE = true;
end
%
% global FILTER_LONG
% global FILTER_STANDARD
%
% FILTER_LONG = filterobject('L',0.999,2);
% FILTER_STANDARD = filterobject('B', [0.8 5.0] ,2);