Description of filt
Home > GISMO > core > @filterobject > filt.m
filt
PURPOSE
FILT: Quick function for 2-pole filtering waveforms and avoiding the
SYNOPSIS
function wave = filt(wave,f_type,f_rng)
DESCRIPTION
FILT: Quick function for 2-pole filtering waveforms and avoiding the
      hassle of generating a filterobject
USAGE: wave = filt(wave,f_type,f_rng)
INPUTS:  wave - input waveform
         f_type - 'lp', 'hp', 'bp' (all 2 pole filters)
OUTPUT: wave - filtered waveform
CROSS-REFERENCE INFORMATION
This function calls:
filterobject FILTEROBJECT constructor for a filter object
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
fillgaps FILLGAPS - fill missing data with values of your choice
This function is called by:
cookbook COOKBOOK demonstrate the features of the mastercorr package.
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
SOURCE CODE
function wave = filt(wave,f_type,f_rng)
%FILT: Quick function for 2-pole filtering waveforms and avoiding the
%      hassle of generating a filterobject
%
%USAGE: wave = filt(wave,f_type,f_rng)
%
%INPUTS:  wave - input waveform
%         f_type - 'lp', 'hp', 'bp' (all 2 pole filters)
%OUTPUT: wave - filtered waveform
wave = fillgaps(wave,0);
if any(strcmpi(f_type,{'b','bp','band','bandpass'}))
    wave = filtfilt(filterobject('B',f_rng,2),wave);
elseif any(strcmpi(f_type,{'h','hp','high','highpass'}))
    wave = filtfilt(filterobject('H',f_rng,2),wave);
elseif any(strcmpi(f_type,{'l','lp','low','lowpass'}))
    wave = filtfilt(filterobject('L',f_rng,2),wave);
end