Description of filtfilt
Home > GISMO > core > @filterobject > filtfilt.m
filtfilt
PURPOSE
FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
SYNOPSIS
function w =filtfilt(f, w, NYQ)
DESCRIPTION
FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
   waveform = filtfilt(filterobject, waveform);
   waveform = filtfilt(filterobject, data, NYQ);
      'filtfilt' is a function that filters data at a specified
      cutoff frequency with zero time shift.
      INPUT values are as follows:
        "filterobject" is a filter object
        "waveform" is one or more waveform objects
        "data" is any data vector (generally of type DOUBLE).
        "NYQ" is the nyquist frequency
  See also FILTFILT, BUTTER
CROSS-REFERENCE INFORMATION
This function calls:
butter C = BUTTER(C,[TYPE],CUTOFF,[POLES])
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
addhistory ADDHISTORY function in charge of adding history to a waveform
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
set SET Set properties for waveform object(s)
butter butter create and apply a butterworth filter to the traces
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
apply_filter
demo_plutons
cookbook COOKBOOK demonstrate the features of the mastercorr package.
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
hankelq HANKELQ Compute spectral ratio in two frequency bands
reducedisp_wfmeas REDUCEDISP_WFMEAS(STARTTIME,ENDTIME,SCNL,DIST,DS,DBOUT,FILT,TIMESTEP,ALGORITHM)
butter C = BUTTER(C,[TYPE],CUTOFF,[POLES])
cookbook % drumplot cookbook
filt FILT: Quick function for 2-pole filtering waveforms and avoiding the
filtfilt FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
TraceFilter
gismo_examples Standard clearing MATLAB workspace & command window, closing figures
separating_tremor_and_events Tremor range is 1-5 Hz
SUBFUNCTIONS
function [b, a] = getButter(f, WN)
SOURCE CODE
function w =filtfilt(f, w, NYQ)
%FILTFILT - filterobject implementation of FILTFILT, use on waveform Object
%   waveform = filtfilt(filterobject, waveform);
%   waveform = filtfilt(filterobject, data, NYQ);
%
%      'filtfilt' is a function that filters data at a specified
%      cutoff frequency with zero time shift.
%
%      INPUT values are as follows:
%        "filterobject" is a filter object
%        "waveform" is one or more waveform objects
%        "data" is any data vector (generally of type DOUBLE).
%        "NYQ" is the nyquist frequency
%
%
%  See also FILTFILT, BUTTER
% VERSION: 1.0 of filter objects
% AUTHOR: Celso Reyes
% LASTUPDATE: 1/30/2007
% Check, if w is a number array, just quick & dirty it...
if isnumeric(w)
    WN = f.cutoff / NYQ;
    [b, a] = getButter(f,WN);
    w = filtfilt(b, a, w);
elseif isa(w,'waveform')
    % check for gaps
    HASGAP = 0;
    for n = 1:numel(w)
        if any(isnan(double(w(n))))
            HASGAP = 1;
        end
    end
    if HASGAP
        warning('Filterobject:filtfilt:hasNaN',...
            ['Waveform(s) contain data gaps (NaN values). This '...
            'will cause filtfilt to return an answer of all NaN.  To prevent '...
            'this, use waveform/fillgaps to replace NaN with an appropriate'...
            ' value.  \nSee help waveform/fillgaps.']);
    end
    for n = 1 : numel(w);
        WN = f.cutoff / get(w(n),'NYQ');     %only one filter is assumed!
        [b, a] = getButter(f,WN);
        w(n) = set(w(n),'data', filtfilt(b, a, double(w(n))) );
    end
end
w = addhistory(w,['Filtered: Type:', get(f,'type'), ' Cutoff: [',...
    num2str(get(f,'cutoff')), '] Poles: [' , num2str(get(f,'poles')),']' ]);
%- - - -  helper function - - - - %
function [b, a] = getButter(f, WN)
switch f.type
    case 'H';
        [b,a] = butter(f.poles, WN, 'high');
    case 'B';
        [b,a] = butter(f.poles, WN);
    case 'L';
        [b,a] = butter(f.poles, WN);
end;