Description of conv
Home > GISMO > core > @correlation > conv.m
conv
PURPOSE
c = CONV(c) convolves all traces with the final trace. By default the new
SYNOPSIS
function c = conv(c,varargin)
DESCRIPTION
 c = CONV(c) convolves all traces with the final trace. By default the new
 correlation object has traces that are 2*N-1 samples long, where the
 original traces are of length N. Because all traces ...
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
set SET Set properties for correlation object
verify VERIFY
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
get GET for the scnl object
set SET - Set properties for scnlobject
fft FFT Discrete Fourier transform. OVERLOADED for waveform & Spectralobject
get GET - Get properties for spectralobject
ifft IFFT Inverse discrete Fourier transform. OVERLOADED FOR Spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
verify VERIFY Check for property conflicts in the threecomp object.
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
scan SCAN scans a waveform for events which match a master.
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
NewCorrelation
SOURCE CODE
function c = conv(c,varargin)
% c = CONV(c) convolves all traces with the final trace. By default the new
% correlation object has traces that are 2*N-1 samples long, where the
% original traces are of length N. Because all traces ...
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% READ & CHECK ARGUMENTS
if (nargin>2)
    error('Wrong number of inputs');
end;
if ~isa(c,'correlation')
    error('First input must be a correlation object');
end
% GENERAL PARAMETERS
c = verify(c);
traces = get(c,'Traces');
keyTrace = traces;
X = fft(double(c.W));
Y = repmat(fft(double(c.W(keyTrace))) , 1 , traces);
save
Z = ifft(X.*conj(Y));
for n = 1:traces
    c.W(n) = set( c.W(n) , 'DATA' , Z(:,n) );
end