Description of deconv
Home > GISMO > core > @correlation > deconv.m
deconv
PURPOSE
c = DECONV(c) convolves all traces with the final trace. By default the new
SYNOPSIS
function c = deconv(c,varargin)
DESCRIPTION
 c = DECONV(c) convolves all traces with the final trace. By default the new
 correlation object has traces that are 2*N-1 samples long, where the
 original traces are of length N. Because all traces ...
 ** NOTE TO USERS: Though most plotting routines normalize adjacent traces
 to comparable amplitudes for display, the real trace amplitudes often
 very by orders of magnitudes. Depending on the features the user is
 trying to highlight, it may make sense to normalize the trace amplitudes
 before stacking. This can be performed with the NORM function.
CROSS-REFERENCE INFORMATION
This function calls:
get GET - Get correlation properties
set SET Set properties for correlation object
verify VERIFY
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
get GET for the scnl object
set SET - Set properties for scnlobject
fft FFT Discrete Fourier transform. OVERLOADED for waveform & Spectralobject
get GET - Get properties for spectralobject
ifft IFFT Inverse discrete Fourier transform. OVERLOADED FOR Spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
verify VERIFY Check for property conflicts in the threecomp object.
abs ABS Absolute value for the waveform object
double DOUBLE returns a waveform's data as a double type
get GET Get waveform properties
set SET Set properties for waveform object(s)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
SOURCE CODE
function c = deconv(c,varargin)
% c = DECONV(c) convolves all traces with the final trace. By default the new
% correlation object has traces that are 2*N-1 samples long, where the
% original traces are of length N. Because all traces ...
%
% ** NOTE TO USERS: Though most plotting routines normalize adjacent traces
% to comparable amplitudes for display, the real trace amplitudes often
% very by orders of magnitudes. Depending on the features the user is
% trying to highlight, it may make sense to normalize the trace amplitudes
% before stacking. This can be performed with the NORM function.
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
error('This code is not yet functional. Sorry - MEW');
% READ & CHECK ARGUMENTS
if (nargin>2)
    error('Wrong number of inputs');
end;
if ~isa(c,'correlation')
    error('First input must be a correlation object');
end
% GENERAL PARAMETERS
c = verify(c);
traces = get(c,'Traces');
keyTrace = traces;
X = fft(double(c.W));      % all traces
Y = repmat(fft(double(c.W(keyTrace))) , 1 , traces);   % single trace
%Z = ifft(X ./ Y);
e = 0.01 * sum(abs(Y(:,1)).^2);
numerator = X .* conj(Y) ;
denominator = abs(Y).^2 + e ;
%denominator = Y .* conj(Y) + e ;
Z = ifft(numerator ./ denominator);
save
for n = 1:traces
    c.W(n) = set( c.W(n) , 'DATA' , Z(:,n) );
end