Description of demean
Home > GISMO > core > @correlation > demean.m
demean
PURPOSE
DEMEAN removes the mean of each trace.
SYNOPSIS
function c = demean(c,varargin);
DESCRIPTION
 DEMEAN removes the mean of each trace.
 C = DEMEAN(C) removes the DC offset from each trace. In most cases it is
 unnecessary to call this function directly. By default, all traces are
 demeaned and detrended when they are loaded into a correlation object.
 This is one of the assumptions of the correlation toolbox.
CROSS-REFERENCE INFORMATION
This function calls:
demean DEMEAN removes the mean of each trace.
demean DEMEAN remove offset voltage from signal
demean DEMEAN removes the mean of each trace.
This function is called by:
cookbook COOKBOOK demonstrate the features of the mastercorr package.
mastercorr_cookbook Demonstration of the major features of the master waveform correlation
reducedisp_calc WAVEFORM = REDUCEDISP(WAVEFORM,DISTANCE) This function calculates the
reducedisp_wfmeas REDUCEDISP_WFMEAS(STARTTIME,ENDTIME,SCNL,DIST,DS,DBOUT,FILT,TIMESTEP,ALGORITHM)
correlation
demean DEMEAN removes the mean of each trace.
integrate INTEGRATE integrates each trace.
threecomp THREECOMP Object for three component waveform data
normalize
plot_helicorder WAVEFORM/PLOT_HELICORDER Plot waveform objects as helicorders
waveform2sound WAVEFORM2SOUND generate an audio file from a waveform object.
NewCorrelation
demean DEMEAN removes the mean of each trace.
integrate INTEGRATE integrates each trace.
testWaveform
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
SOURCE CODE
function c = demean(c,varargin);
% DEMEAN removes the mean of each trace.
%
% C = DEMEAN(C) removes the DC offset from each trace. In most cases it is
% unnecessary to call this function directly. By default, all traces are
% demeaned and detrended when they are loaded into a correlation object.
% This is one of the assumptions of the correlation toolbox.
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
c.W = demean(c.W);