Description of find
Home > GISMO > core > @correlation > find.m
find
PURPOSE
INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
SYNOPSIS
function index = find(c,varargin)
DESCRIPTION
 INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
 Returns a list of trace numbers belonging to the cluster specified by
 WHICH_CLUSTER. If WHICH_CLUSTER is 1, then cluster with the most traces
 will be returned. If WHICH_CLUSTER is 2, then the seconds largest cluster
 will be returned, and so on. Often this use will be paired with SUBSET or
 STACK. For example, to plot the largest cluster of traces followed by
 a stack of these traces:
   INDEX = FIND(c,'CLUST',1)
   c1 = SUBSET(c,INDEX)
   c1 = stack(c1)
   plot(c1)
 INDEX = FIND(c,'BIG',SIZE)
 Returns a list of trace numbers belonging to any cluster that has at
 leats SIZE number of traces. For example, to get all clusters that
 contain 5 or more traces:
   INDEX = FIND(c,'BIG',5)
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
cat c = cat(c1,c2,c3,...)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
sort C = SORT(C,'TIME')
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
isempty ISEMPTY Display threecomp object
disp DISP Waveform disp overloaded operator
isempty ISEMPTY returns TRUE if waveform contains no data
max MIN Largest value of a waveform.
cat c = cat(c1,c2,c3,...)
disp CORRELATION/DISPLAY Command window display of a correlation object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
sort C = SORT(C) Sorts traces from oldest to youngest.
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
iceweb
spectrogram_iceweb SPECTROGRAM_ICEWEB produce an multi-channel spectrogram plot in the style of
uispecgram UISPECGRAM M-file for uispecgram.fig
ReadMSEEDFast ReadMSEEDFast(fileName)
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
demo_plutons
response_get_from_db RESPONSE_GET_FROM_DB Get instrument response from database.
station_meta station_meta adds station metadata to a waveform
dmc_station_meta DMC_STATION_META adds station metadata to a waveform
irisFetch
extract EXTRACT extract matches to the master waveform
scan SCAN scans a waveform for events which match a master.
mastercorr_extract MASTERCORR_EXTRACT extract matches to the master waveform
mastercorr_scan MASTERCORR_SCAN scans a waveform for events which match a master.
hankelq HANKELQ Compute spectral ratio in two frequency bands
dd_collate dd_collate('event.dat')
dd_make_scp DD_MAKE_SCP Create a draft control file for the correlation process
arrivals_rearrange % Arrange info from earthquake catalogue into a more useful format
import_events IMPORT_EVENTS Import waveforms associated with earthquake events.
arrival_histogram ARRIVAL_HISTOGRAM compare the number of arrivals to each station.
dbload DBLOAD extracts travel times from a database
depth_section DEPTH_SECTION plot depth sections of ray coverage.
map MAP plot a map of ray coverage.
tt_curve TRAVELTIME make travel time plots.
write_lotos WRITE_LOTOS write files for LOTOS tomography codes.
bin_irregular BIN_IRREGULAR bin an irregularly-sampled timeseries (like earthquake origin times).
calc_McBest CALC_MCBEST Calculate best Mc from combining methods
calc_McMaxCurvature CALC_MCMAXCURVATURE
synthb_aut This is synthetic219
aef READ_CATALOG.AEF
which WHICH manage and switch between multiple GISMO archives
dbgetorigins DBGETORIGINS Load preferred origins from an Antelope CSS3.0
mag2eng MAG2ENG Convert (a vector of) magnitude into (a vector of) equivalent energy(ies).
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
eev CATALOG.EEV - Browse an Catalog object one event at a time.
ChannelTag
EventRate
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
check Check various features of a correlation object.
cluster c = CLUSTER(c,CUTOFF) cuts the "branches" of the linkage tree to create
cookbook % Correlation object cookbook
correlation
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
match Retain matching elements of two correlation objects.
eventplot Private method. See ../plot for details.
occurrenceplot Private method. See ../plot for details.
wiggleinterferogram Private method. See ../plot for details.
xcorr1xr XCORR1XR Cross correlate 1 trace against all other traces at once.
verify VERIFY
setfile SETFILE associates a datasource object with a file (or directory)
subdivide_files_by_date SUBDIVIDE_FILES_BY_DATE given a datasource and daterange return list of files
bvalue BVALUE evaluate b-value, a-value and magnitude of completeness
duration_amplitude DURATION_AMPLITUDE Use the duration-amplitde
extract
oneMinuteData
read_bob_file READ_BOB_FILE Load RSAM-like data from a BOB file into a SAM object.
remove_calibration_pulses
resample RESAMPLE resamples a rsam object at over every specified intercrunchfactor
save RSAM/SAVE - save an rsam-like object to an RSAM/BOB binary
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
specgram SPECGRAM - plots spectrogram of waveforms
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
extract EXTRACT particle motion parameters from a threecomp object
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
getproperty GETPROPERTY returns a property value from a property list, or a default
threecomp THREECOMP Object for three component waveform data
extract EXTRACT creates a waveform with a subset of another's data.
fillgaps FILLGAPS - fill missing data with values of your choice
plot_spectrum add_spectral_data Simple method to compute frequency
autoscale will automatically find the correct y-unites with which to plot something
getproperty GETPROPERTY returns a property value from a property list, or a default
load_antelope_workaround load a waveform from antelope
rqhd RQHD Read seismic handler (SH) header variables
zero2nan ZERO2NAN: This function takes a waveform with gaps that have been filled
ChannelDetails
NewCorrelation
adjusttrig ADJUSTTRIG adjusts the trigger times of each trace
cookbook % Correlation object cookbook
eventplot Private method. See ../plot for details.
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
getclusterstat GETCLUSTERSTAT gets detais of individual correlation clusters.
match Retain matching elements of two correlation objects.
occurrenceplot Private method. See ../plot for details.
SeismicTrace
TraceData
autoscale autoscale automatically determine correct y-units for plotting
TraceSpectra
sst2ssd
compute COMPUTE calculates the fast fourier transform of a waveform object
freqindex WAVEFORM = FREQINDEX(WAVEFORM) calculates the frequency index of a waveform.
plot PLOT plot fourier transform of a waveform
amplitude_spectrum add_spectral_data Simple method to compute frequency
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
wf_fftplot WF_FFTPLOT(WAVEFORM) plot fourier transform of the data.
wf_fi WAVEFORM = WF_FI(WAVEFORM) calculates the frequency index of a waveform.
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
crossfeed CROSSFEED Checks for crossfeeding and duplicate data channels
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
whichgismo WHICHGISMO Select from multiple GISMO archives.
SUBFUNCTIONS
function index = find_clu(c,n);
function index = find_big(c,n);
SOURCE CODE
function index = find(c,varargin)
% INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
% Returns a list of trace numbers belonging to the cluster specified by
% WHICH_CLUSTER. If WHICH_CLUSTER is 1, then cluster with the most traces
% will be returned. If WHICH_CLUSTER is 2, then the seconds largest cluster
% will be returned, and so on. Often this use will be paired with SUBSET or
% STACK. For example, to plot the largest cluster of traces followed by
% a stack of these traces:
%   INDEX = FIND(c,'CLUST',1)
%   c1 = SUBSET(c,INDEX)
%   c1 = stack(c1)
%   plot(c1)
%
% INDEX = FIND(c,'BIG',SIZE)
% Returns a list of trace numbers belonging to any cluster that has at
% leats SIZE number of traces. For example, to get all clusters that
% contain 5 or more traces:
%   INDEX = FIND(c,'BIG',5)
%
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% READ & CHECK ARGUMENTS
if ~isa(c,'correlation')
    error('First input must be a correlation object');
end
if length(varargin)==0
   error('More arguments needed');
else
    type = varargin{1};
end
% EXECUTE FIND TYPE
if strncmpi(type,'CLU',3)
    n = varargin{2};
    if isa(n,'double')
        index = find_clu(c,n);
    else
       error('second argument must be a number');
    end
elseif strncmpi(type,'BIG',3)
    n = varargin{2};
    if isa(n,'double')
        index = find_big(c,n);
    else
       error('second argument must be a number');
    end
else
    error('This use of find is not recognized');
end;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FIND CLUSTERS
%
function index = find_clu(c,n);
if isempty(c.clust)
    error('No cluster information available. Consider using the linkage and cluster functions.');
end
famsize = histc(c.clust,[0:max(c.clust)]+.5);
[famsize,fami] = sort(famsize,'descend');
if n > max(c.clust)
   error(['There are only ' num2str(max(c.clust)) ' clusters']);
end
index = [];
for i = 1:length(n)
    index = cat(1,index,find(c.clust==fami(n(i))));
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FIND BIGGEST CLUSTERS
%
function index = find_big(c,n);
famsize = histc(c.clust,[0:max(c.clust)]+.5);
[famsize,fami] = sort(famsize,'descend');
if n > max(famsize)
   disp(['There are no clusters with more than ' num2str(max(famsize)) ' traces']);
end
index = [];
f = find(famsize>=n);
for i = 1:length(f)
    index = cat(1,index,find(c.clust==fami(f(i))));
end