Description of sort
Home > GISMO > core > @correlation > sort.m
sort
PURPOSE
C = SORT(C,'TIME')
SYNOPSIS
function c = norm(c,varargin)
DESCRIPTION
 C = SORT(C,'TIME')
 Sorts traces a function of time from oldest to youngest.
 Currently no other types of sorting have been implimented
 C = SORT(C)
 Short hand for SORT(C,'TIME')
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
subset CATALOG.SUBSET Create a new catalogObject by subsetting based
sort C = SORT(C,'TIME')
subset c = SUBSET(c,INDEX)
disp DISP Datasource disp overloaded operator
disp DISP - Filterobject disp overloaded operator
disp DISP - scnl disp overloaded operator
disp DISP - spectralobject disp overloaded operator
disp DISP Display threecomp object
disp DISP Waveform disp overloaded operator
disp CORRELATION/DISPLAY Command window display of a correlation object
sort C = SORT(C) Sorts traces from oldest to youngest.
subset c = SUBSET(c,INDEX)
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
This function is called by:
uispecgram UISPECGRAM M-file for uispecgram.fig
corrderived_plot_swarm_history CORRDERIVED_PLOT_SWARM_HISTORY plots relevent details of seismic swarms
plot_stats PLOT_STATS plot statistics from master correlation algorithm
mastercorr_plot_stats MASTERCORR_PLOT_STATS plot statistics from master correlation algorithm
dd_collate dd_collate('event.dat')
dbget_closest_sites DBGET_CLOSEST_SITES Get closest sites from an Antelop database to a given [lon, lat]
ChannelTag
cluster c = CLUSTER(c,CUTOFF) cuts the "branches" of the linkage tree to create
cookbook % Correlation object cookbook
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
sort C = SORT(C,'TIME')
set SET - Set filterobject properties
set SET - Set properties for spectralobject
particlemotion PARTICLEMOTION calculates particle motion vectors for threecomp object
combine COMBINE merges waveforms based on start/end times and ChannelTag info.
load_antelope_workaround load a waveform from antelope
sortby sortby sorts waveforms based on one of its properties
NewCorrelation
cluster cluster Construct agglomerative clusters from linkage for Seismic Traces
cookbook % Correlation object cookbook
sort C = SORT(C) Sorts traces from oldest to youngest.
SeismicTrace
sort_sst SORT_SST: Sort SST (Event Start/Stop Times) based on start times
testChanneltag
get_total GET_TOTAL Read in the complete AEIC Total earthquake catalog
aeic_total_catalog AEIC_TOTAL_CATALOG Read in the complete AEIC Total earthquake catalog
SOURCE CODE
function c = norm(c,varargin)
% C = SORT(C,'TIME')
% Sorts traces a function of time from oldest to youngest.
% Currently no other types of sorting have been implimented
%
% C = SORT(C)
% Short hand for SORT(C,'TIME')
%
% Author: Michael West, Geophysical Institute, Univ. of Alaska Fairbanks
% $Date$
% $Revision$
% READ & CHECK ARGUMENTS
if ~isa(c,'correlation')
    error('First input must be a correlation object');
end
% CHOOSE SORT TYPE
if nargin==1
    type = 'TIM';
elseif ischar(varargin{1})
    type = varargin{1};
else
    error('Incorrect inputs');
end;
% SORT TRACES
if strncmpi(type,'TIM',3)
    [S,I] = sort(c.trig);
    c = subset(c,I);
else
    disp('Sort type not recognized');
end;