Description of cookbook_map
Home > GISMO > core > @threecomp > cookbook_map.m
cookbook_map
PURPOSE
COOKBOOK_MAP Plots a simple map to accompany cookbook data
SYNOPSIS
function cookbook_map(TC,W,backAzimuth)
DESCRIPTION
COOKBOOK_MAP Plots a simple map to accompany cookbook data
 COOKBOOK_MAP(TC,W) plots a simple map of station and origin locations
 for the demo dataset used in the threecomp cookbook. It is intended to be
 used internal to the demo only.
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
set SET - Set filterobject properties
plot RSAM/PLOT plot rsam data
disp DISP - scnl disp overloaded operator
get GET for the scnl object
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
legend legend creates a legend for a waveform graph
plot PLOT plots a waveform object
set SET Set properties for waveform object(s)
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
disp disp Display information about SeismicTrace(s)
legend legend Create a legend for the graph of a trace.
plot plot plots a SeismicTrace
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
SOURCE CODE
function cookbook_map(TC,W,backAzimuth)
%COOKBOOK_MAP Plots a simple map to accompany cookbook data
% COOKBOOK_MAP(TC,W) plots a simple map of station and origin locations
% for the demo dataset used in the threecomp cookbook. It is intended to be
% used internal to the demo only.
% PLOT MAP
figure('Color','w','Position',[50 50 400 400]);
staLat = get(W(:,1),'STATIONLATITUDE');
staLon = get(W(:,1),'STATIONLONGITUDE');
origLat = get(W(:,1),'ORIGINLATITUDE');
origLon = get(W(:,1),'ORIGINLONGITUDE');
staName = get(W(:,1),'STATION');
plot(staLon,staLat,'bo','LineWidth',3,'MarkerSize',7);
hold on; box on; grid on;
plot(origLon,origLat,'ro','LineWidth',3,'MarkerSize',9);
set(gca,'DataAspectRatio',[1 cosd(34) 1]);
if exist('reckon')==2
    for n=1:size(W,1)
        text(staLon(n),staLat(n),['  ' staName{n}],'FontWeight','bold');
        [arrowLat(1) arrowLon(1)] = reckon(staLat(n),staLon(n), -0.3, backAzimuth(n));
        [arrowLat(2) arrowLon(2)] = reckon(staLat(n),staLon(n), 0.3, backAzimuth(n));
        plot(arrowLon,arrowLat,'b-');
    end
else
    disp('** WARNING **');
    disp('Full cookbook example requires the mapping toolbox. It is used to ');
    disp('plot backazimuths. Note thta the mapping toolbox is NOT needed to ');
    disp('use the threecomp object, however.');
end
text(origLon(n),origLat(n),['  origin'],'FontWeight','bold');
xlabel('Longitude');
ylabel('Latitude');
legend('stations','origin','backazimuth','Location','NorthWest');