Description of plot3
Home > GISMO > core > @threecomp > plot3.m
plot3
PURPOSE
PLOT3 Interactively make 3D plot of particle motion vector evolution
SYNOPSIS
function plot3(TC)
DESCRIPTION
PLOT3 Interactively make 3D plot of particle motion vector evolution
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
plot3 CATALOG.PLOT3 Plot hypocenters in 3-D
get GET - Get correlation properties
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
disp DISP - scnl disp overloaded operator
get GET for the scnl object
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
plot2 PLOT2 a figure of three component traces (deprecated).
plot3 PLOT3 Interactively make 3D plot of particle motion vector evolution
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
This function is called by:
Catalog CATALOG the blueprint for Catalog objects in GISMO
plot3 PLOT3 Interactively make 3D plot of particle motion vector evolution
ChannelDetails
SOURCE CODE
function plot3(TC)
%PLOT3 Interactively make 3D plot of particle motion vector evolution
    %% Extract data for whole threecomp object
    w = get(TC,'waveform');
    fs = get(w(1), 'freq');
    yz = get(w(1),'data');
    yr = get(w(2),'data');
    yt = get(w(3),'data');
    %% Get user to mouse click the window of interest
    plot2(TC);
    while true,
        % Select start and end times with mouse
        ylims=get(gca,'ylim');
        disp('Select start of time window with left mouse click')
        [xclick1 yclick1]=ginput(1);
        line([xclick1 xclick1],ylims);
        disp('Select end of time window with right mouse click')
        [xclick2 yclick2]=ginput(1);
        line([xclick2 xclick2],ylims);
        % Plotting
        fh = figure;
        nsamples = length(yz);
        startSample = ceil(xclick1 * fs);
        endSample = floor(xclick2 * fs);
        plot3(yr(startSample:endSample), yt(startSample:endSample), yz(startSample:endSample));
        xlabel('Radial')
        ylabel('Transverse')
        zlabel('Vertical')
        axis equal
        choice = menu('Select new time window?', 'yes', 'no');
        if choice==2
            return
        end
        close
    end
end