Description of about
Home > GISMO > deprecated > fft_tools > +wf_fft > about.m
about
PURPOSE
Miscellaneous tools for working with waveforms.
SYNOPSIS
function about
DESCRIPTION
Miscellaneous tools for working with waveforms.
 Tools in this package are specific enough or customized enough that they
 do not belong as built-in methods for the waveform class.
CROSS-REFERENCE INFORMATION
This function calls:
wf_fft WAVEFORM = WF_FFT(WAVEFORM) calculate frequency spectrum of a waveform.
This function is called by:
sacpz SACPZ Class for reading SAC pole-zero files downloaded from IRIS
NewCorrelation
SOURCE CODE
function about
%Miscellaneous tools for working with waveforms.
% Tools in this package are specific enough or customized enough that they
% do not belong as built-in methods for the waveform class.
help wf_fft;