Description of readCatalog
Home > gismotools > GISMO > classes > catalog > readCatalog.m
readCatalog
PURPOSE
READCATALOG: Read seismic events from common file formats & data sources.
SYNOPSIS
function self = readCatalog(catalog_source, varargin)
DESCRIPTION
READCATALOG: Read seismic events from common file formats & data sources.
  readEvents loads events from a seismic event catalog into a GISMO
  Catalog object.
 USAGE
  cobj = readCatalog(catalog_source, 'param1', value1, 'param2', value2 ...)
     loads a seismic event catalog into a GISMO/Catalog object.
     catalog_source is a method by which the source catalog is
     retrieved, or format in which the source catalog is stored.
  The name-value parameter pairs supported by readCatalog mirror those of
  irisFetch.Events, which currently are:
      contributor, startTime, endTime, eventId, fetchLimit, latitude, longitude, magnitudeType,
      maximumDepth, maximumLatitude, maximumLongitude, maximumMagnitude,
      minimumDepth, minimumLatitude, minimumLongitude, minimumMagnitude,
      minimumRadius, maximumRadius, offset, updatedAfter.
  An arbitrary number of parameter-value pairs may be specified in order to
  narrow down the search results. Some catalog_source allow additional
  name-value parameter pairs.
  By default readCatalog will only retrieve basic event metadata such as
  (preferred) origin time, longitude, latitude, depth and magnitude.
  However:
  cobj = readCatalog(..., 'addarrivals', true)
  will also include more detailed information, such as phase arrivals and
  different measurements of magnitude. Warning - this may become slow,
  especially for large datasets.
 LOADING FROM IRIS/FSDN web services via irisfetch.m:
   cobj = readCatalog('irisfetch', 'param1', value1, 'param2', value2 ...)
             loads events, origins and magnitudes from IRIS-DMC or other
             FSDN data sources via irisFetch.m. The allowed parameter-value
             pairs are those allowed by irisFetch.Events.
 LOADING FROM ANTELOPE/DATASCOPE CSS3.0 DATABASES
   cobj = readCatalog('datascope', 'dbpath', path_to_database)
     loads events, origins and magnitudes from a Datascope CSS3.0
     database using Kent Lindquist's Antelope Toolbox for MATLAB. As a
     minimum, the database must have an origin table.
   Additional name-value parameter pairs supported by 'datascope' are:
       'archiveformat'
       'subset_expression'
   If the database is stored in daily volumes, e.g. foo/bar_YYYY_MM_DD,
   rather than a single database use the 'archiveformat'
   name/value pair, e.g.
   cobj = readCatalog('antelope', 'dbpath', 'foo/bar', 'archiveformat','daily');
   For monthly volumes, e.g. foo/bar_YYYY_MM, set 'archiveformat' to
   'monthly':
   cobj = readCatalog('antelope', 'dbpath', 'foo/bar', 'archiveformat','monthly');
   [Note: it would be much better if I could do 'dbpath',
   'foo/bar_%YYYY%MM%DD', 'year', 'month', 'day' as Celso does for
   datasource].
   cobj = readCatalog(..., 'subset_expression', subset_expression)
             will subset the database given a valid datascope subset
             expression.
   If the subset_expression parameter name/value pair is omitted, a expression
   can also be formed from other name/value pairs. These are:
       PARAMETER  VALUE
       'snum'     a datenum denoting the minimum origin time
       'enum'     a datenum denoting the maximum origin time
       'minmag'   the minimum magnitude
       'mindepth' the minimum depth (in km)
       'maxdepth' the maximum depth (in km)
       'region'   a 4-element vector: [minlon maxlon minlat maxlat]
 READING FROM A SEISAN-DERIVED DAT FILE
   obj = readCatalog('aef', 'dbpath', dbpath)
     will attempt to load all Seisan-derived AEF summary files in the
     directory specified by dbpath.
     To subset the data, use parameter name/value pairs (snum, enum,
     minmag, mindepth, maxdepth, region).
 READING S-FILES FROM A SEISAN YYYY/MM REA DATABASE
   obj = readCatalog('seisandb', 'dbpath', dbpath)
     will attempt to load all Seisan S-files in the
     directory specified by dbpath (which should be the parent of
     YYYY/MM directories)
     To subset the data, use parameter name/value pairs (snum, enum,
     minmag, mindepth, maxdepth, region).
% EXAMPLES
   (1) Import all events from the demo database
         % get path to demo database
         dbpath = demodb('avo');
         % read events from database
         obj = readCatalog('datascope', 'dbpath', dbpath);
   (2) As previous example, but use a subset expression also. Here we
       subset for origins within 15 km of Redoubt volcano:
         obj = readCatalog('datascope', 'dbpath', dbpath, 'subset_expression', 'deg2km(distance(lat, lon, 60.4853, -152.7431))<15.0');
   (3) Read all magnitude>7 events from IRIS DMC via irisFetch.m:
         obj = readCatalog('irisfetch', 'MinimumMagnitude', 7.0);
   (4) Read all events within 20 km of Redoubt volcano from IRIS DMC:
         obj = readCatalog('irisfetch','radialcoordinates', [60.4853 -152.7431 km2deg(20)]);
   (5) Read Alaska Earthquake Center events greater than M=4.0 in 2009
       within rectangular region lat = 55 to 65, lon = -170 to -135 from
       the "Total" database of all regional earthquakes in Alaska:
         obj = readCatalog('datascope', 'dbpath', '/Seis/catalogs/aeic/Total/Total', 'snum', datenum(2009,1,1), 'enum', datenum(2010,1,1), 'minmag', 4.0, 'region', [-170.0 -135.0 55.0 65.0]);
   (6) As 5, but use a subset_expression instead:
         obj = readCatalog('datascope', 'dbpath', '/Seis/catalogs/aeic/Total/Total', 'subset_expression', 'time > "2009/1/1" & time < "2010/1/1"' & ml > 4 & lon > -170.0 & lon < -135.0 & lat > 55.0 & lat < 65.0');
   (7) Read MVO data from station MBWH for all of year 2000:
         obj = readCatalog('aef', 'dbpath', fullfile('/raid','data','seisan','mbwh_catalog'), 'snum', datenum(2000,1,1), 'enum', datenum(2000,12,31,23,59,59));
   (8) Read Sfiles from MVOE_ Seisan database for January 2000 (this can be slow, especially over a network drive):
         obj = readCatalog('seisandb', 'dbpath', fullfile('/raid','data','seisan','REA','MVOE_'), 'snum', datenum(2000,1,1), 'enum', datenum(2000,1,2) );
   (9) Read from a SRU catalog in a text file:
         obj = readCatalog('sru', '/raid/data/seisan/REA/DMNCA/DominicaCatalog.txt');
% See also CATALOG, EVENT, MAGNITUDE, IRISFETCH. CATALOG_COOKBOOK
 Author: Glenn Thompson (glennthompson1971@gmail.com)
 $Date: $
 $Revision: $
CROSS-REFERENCE INFORMATION
This function calls:
Catalog_full
Catalog_lite
Event
Netmag
Origin
This function is called by:
catalog CATALOG
catalog_cookbook % CATALOG and EVENTRATE cookbook
SUBFUNCTIONS
function self = load_datascope_events(varargin)
function [lon, lat, depth, dnum, evid, orid, nass, mag, mb, ml, ms, etype, auth] = dbloadprefors(dbpath, subset_expression)
function self = convert_irisFetch_to_Catalog(ev)
function self = load_aef(varargin)
function self = import_aef_file(dirpath, yyyy, mm, snum, enum, RUNMODE)
function self = load_seisandb(varargin)
function files = list_sfiles(dbpath, snum, enum)
function s=read_sfile(sfiledir, sfilebase,sta,chan);
function sfilednum=sfile2dnum(sfile)
function self=read_vdap(filename)
function self=read_SRU(filename)
function out = ensure_dateformat(t)
SOURCE CODE
function self = readCatalog(catalog_source, varargin)
%READCATALOG: Read seismic events from common file formats & data sources.
%  readEvents loads events from a seismic event catalog into a GISMO
%  Catalog object.
%
%
% USAGE
%
%  cobj = readCatalog(catalog_source, 'param1', value1, 'param2', value2 ...)
%     loads a seismic event catalog into a GISMO/Catalog object.
%     catalog_source is a method by which the source catalog is
%     retrieved, or format in which the source catalog is stored.
%
%  The name-value parameter pairs supported by readCatalog mirror those of
%  irisFetch.Events, which currently are:
%      contributor, startTime, endTime, eventId, fetchLimit, latitude, longitude, magnitudeType,
%      maximumDepth, maximumLatitude, maximumLongitude, maximumMagnitude,
%      minimumDepth, minimumLatitude, minimumLongitude, minimumMagnitude,
%      minimumRadius, maximumRadius, offset, updatedAfter.
%  An arbitrary number of parameter-value pairs may be specified in order to
%  narrow down the search results. Some catalog_source allow additional
%  name-value parameter pairs.
%
%  By default readCatalog will only retrieve basic event metadata such as
%  (preferred) origin time, longitude, latitude, depth and magnitude.
%  However:
%
%  cobj = readCatalog(..., 'addarrivals', true)
%
%  will also include more detailed information, such as phase arrivals and
%  different measurements of magnitude. Warning - this may become slow,
%  especially for large datasets.
%
% LOADING FROM IRIS/FSDN web services via irisfetch.m:
%   cobj = readCatalog('irisfetch', 'param1', value1, 'param2', value2 ...)
%             loads events, origins and magnitudes from IRIS-DMC or other
%             FSDN data sources via irisFetch.m. The allowed parameter-value
%             pairs are those allowed by irisFetch.Events.
%
% LOADING FROM ANTELOPE/DATASCOPE CSS3.0 DATABASES
%
%   cobj = readCatalog('datascope', 'dbpath', path_to_database)
%     loads events, origins and magnitudes from a Datascope CSS3.0
%     database using Kent Lindquist's Antelope Toolbox for MATLAB. As a
%     minimum, the database must have an origin table.
%
%   Additional name-value parameter pairs supported by 'datascope' are:
%       'archiveformat'
%       'subset_expression'
%
%   If the database is stored in daily volumes, e.g. foo/bar_YYYY_MM_DD,
%   rather than a single database use the 'archiveformat'
%   name/value pair, e.g.
%
%   cobj = readCatalog('antelope', 'dbpath', 'foo/bar', 'archiveformat','daily');
%
%   For monthly volumes, e.g. foo/bar_YYYY_MM, set 'archiveformat' to
%   'monthly':
%
%   cobj = readCatalog('antelope', 'dbpath', 'foo/bar', 'archiveformat','monthly');
%
%   [Note: it would be much better if I could do 'dbpath',
%   'foo/bar_%YYYY%MM%DD', 'year', 'month', 'day' as Celso does for
%   datasource].
%
%   cobj = readCatalog(..., 'subset_expression', subset_expression)
%             will subset the database given a valid datascope subset
%             expression.
%
%   If the subset_expression parameter name/value pair is omitted, a expression
%   can also be formed from other name/value pairs. These are:
%       PARAMETER  VALUE
%       'snum'     a datenum denoting the minimum origin time
%       'enum'     a datenum denoting the maximum origin time
%       'minmag'   the minimum magnitude
%       'mindepth' the minimum depth (in km)
%       'maxdepth' the maximum depth (in km)
%       'region'   a 4-element vector: [minlon maxlon minlat maxlat]
%
% READING FROM A SEISAN-DERIVED DAT FILE
%
%   obj = readCatalog('aef', 'dbpath', dbpath)
%     will attempt to load all Seisan-derived AEF summary files in the
%     directory specified by dbpath.
%
%     To subset the data, use parameter name/value pairs (snum, enum,
%     minmag, mindepth, maxdepth, region).
%
% READING S-FILES FROM A SEISAN YYYY/MM REA DATABASE
%
%   obj = readCatalog('seisandb', 'dbpath', dbpath)
%     will attempt to load all Seisan S-files in the
%     directory specified by dbpath (which should be the parent of
%     YYYY/MM directories)
%
%     To subset the data, use parameter name/value pairs (snum, enum,
%     minmag, mindepth, maxdepth, region).
%
%% EXAMPLES
%
%   (1) Import all events from the demo database
%         % get path to demo database
%         dbpath = demodb('avo');
%         % read events from database
%         obj = readCatalog('datascope', 'dbpath', dbpath);
%
%   (2) As previous example, but use a subset expression also. Here we
%       subset for origins within 15 km of Redoubt volcano:
%         obj = readCatalog('datascope', 'dbpath', dbpath, 'subset_expression', 'deg2km(distance(lat, lon, 60.4853, -152.7431))<15.0');
%
%   (3) Read all magnitude>7 events from IRIS DMC via irisFetch.m:
%         obj = readCatalog('irisfetch', 'MinimumMagnitude', 7.0);
%
%   (4) Read all events within 20 km of Redoubt volcano from IRIS DMC:
%         obj = readCatalog('irisfetch','radialcoordinates', [60.4853 -152.7431 km2deg(20)]);
%
%   (5) Read Alaska Earthquake Center events greater than M=4.0 in 2009
%       within rectangular region lat = 55 to 65, lon = -170 to -135 from
%       the "Total" database of all regional earthquakes in Alaska:
%         obj = readCatalog('datascope', 'dbpath', '/Seis/catalogs/aeic/Total/Total', 'snum', datenum(2009,1,1), 'enum', datenum(2010,1,1), 'minmag', 4.0, 'region', [-170.0 -135.0 55.0 65.0]);
%
%   (6) As 5, but use a subset_expression instead:
%         obj = readCatalog('datascope', 'dbpath', '/Seis/catalogs/aeic/Total/Total', 'subset_expression', 'time > "2009/1/1" & time < "2010/1/1"' & ml > 4 & lon > -170.0 & lon < -135.0 & lat > 55.0 & lat < 65.0');
%
%   (7) Read MVO data from station MBWH for all of year 2000:
%         obj = readCatalog('aef', 'dbpath', fullfile('/raid','data','seisan','mbwh_catalog'), 'snum', datenum(2000,1,1), 'enum', datenum(2000,12,31,23,59,59));
%
%   (8) Read Sfiles from MVOE_ Seisan database for January 2000 (this can be slow, especially over a network drive):
%         obj = readCatalog('seisandb', 'dbpath', fullfile('/raid','data','seisan','REA','MVOE_'), 'snum', datenum(2000,1,1), 'enum', datenum(2000,1,2));
%
%   (9) Read from a SRU catalog in a text file:
%         obj = readCatalog('sru', '/raid/data/seisan/REA/DMNCA/DominicaCatalog.txt');
%
%% See also CATALOG, EVENT, MAGNITUDE, IRISFETCH. CATALOG_COOKBOOK
%
% Author: Glenn Thompson (glennthompson1971@gmail.com)
% $Date: $
% $Revision: $
    switch lower(data_source)
        case {'css3.0','antelope', 'datascope'}
            % url is called dbpath within load_datascope_events
            self = load_datascope_events(varargin{:});
        case 'irisfetch'
            ev = irisFetch.Events(varargin{:});
            self = convert_irisFetch_to_Catalog(ev);
        case 'seisandb'
            self = load_seisandb(varargin{:});
        case 'aef'
            self = load_aef(varargin{:});
        case 'sru'
            self = read_SRU(varargin{:});
        otherwise
            self = NaN;
            fprintf('format %s unknown\n\n',data_source);
    end
end
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function self = load_datascope_events(varargin)
    if ~admin.antelope_exists
        error('This function requires the Antelope toolbox for Matlab');
        return;
    end
    % Process input arguments
    p = inputParser;
    p.addParamValue('dbpath', @isstr);
    p.addParamValue('subset_expression', '', @isstr);
    p.addParamValue('archiveformat', 'single file', @isstr);
    p.addParamValue('snum', [], @isnumeric);
    p.addParamValue('enum', [], @isnumeric);
    p.addParamValue('minmag', [], @isnumeric);
    p.addParamValue('region', [], @isnumeric);
    p.addParamValue('subclass', '*', @ischar);
    p.addParamValue('mindepth', [], @isnumeric);
    p.addParamValue('maxdepth', [], @isnumeric);
    p.addParamValue('RUNMODE', 'fast', @isstr);
    p.parse(varargin{:});
    fields = fieldnames(p.Results);
    for i=1:length(fields)
        field=fields{i};
        % val = eval(sprintf('p.Results.%s;',field));
        val = p.Results.(field);
        eval(sprintf('%s = val;',field));
    end
    % Create a dbeval subset_expression if not already set.
    if ~exist('subset_expression', 'var') | isempty(subset_expression)
        if nargin > 2
            expr = '';
            if ~isempty(snum) & isnumeric(snum)
                expr = sprintf('%s && time >= %f',expr,datenum2epoch(snum));
            end
            if ~isempty(enum) & isnumeric(enum)
                expr = sprintf('%s && time <= %f',expr,datenum2epoch(enum));
            end
            if ~isempty(minmag) & isnumeric(minmag)
                expr = sprintf('%s && (ml >= %f || mb >= %f || ms >= %f)',expr,minmag,minmag,minmag);
            end
            if ~isempty(region) & isnumeric(region)
                leftlon = region(1); rightlon=region(2); lowerlat=region(3); upperlat=region(4);
                expr = sprintf('%s && (lat >= %f && lat <= %f && lon >= %f && lon <= %f)',expr,lowerlat, upperlat, leftlon, rightlon);
            end
            if ~isempty(mindepth) & isnumeric(mindepth)
                expr = sprintf('%s && (depth >= %f)', expr,mindepth);
            end
            if ~isempty(maxdepth) & isnumeric(maxdepth)
                expr = sprintf('%s && (depth <= %f)', expr,maxdepth);
            end
            subset_expression = expr(4:end);
            clear expr
        end
    end
    % BUILD DBNAMELIST
    dbpathlist = {};
    if strcmp(archiveformat,'single file') % Just 1 entry
        dbpathlist = {dbpath};
    else
        if isempty(snum) || isempty(enum)
            disp(sprintf('Failure: you must set values for \"snum\" and \"enum\" parameters when \"archiveformat\" is set to \"daily\" or \"monthly\"'));
            return;
        end
        if strcmp(archiveformat,'daily')
            for dnum=floor(snum):floor(enum-1/1440)
                dbpathfull = sprintf('%s_%s',dbpath,datestr(dnum, 'yyyy_mm_dd'));
                if exist(sprintf('%s.origin',dbpathfull),'file')
                    dbpathlist{end+1} = dbpathfull; % Add here
                else
                    fprintf('%s.origin not found\n',dbpath);
                end
            end
        elseif strcmp(archiveformat,'monthly')
            for yyyy=dnum2year(snum):1:dnum2year(enum)
                for mm=dnum2month(snum):1:dnum2month(enum)
                    dnum = datenum(yyyy,mm,1);
                    dbpathfull = sprintf('%s%04d_%02d',dbpath,yyyy,mm);
                    if exist(sprintf('%s.origin',dbpath),'file')
                        dbpathlist{end+1} = dbpathfull; % Add here
                    else
                        fprintf('%s.origin not found\n',dbpath);
                    end
                end
            end
        end
    end
    % LOAD FROM DBNAMELIST
    % Initialize to empty
    [lat, lon, depth, dnum, time, evid, orid, nass, mag, ml, mb, ms, etype, auth] = deal([]);
    subclass = '';
    for dbpathitem = dbpathlist
        % Load vectors
        [lon0, lat0, depth0, dnum0, evid0, orid0, nass0, mag0, mb0, ml0, ms0, subclass0, auth0] = dbloadprefors(dbpathitem, subset_expression);
        if length(lon0) == length(mag0)
            % Concatentate vectors
            lon   = cat(1, lon,   lon0);
            lat   = cat(1, lat,   lat0);
            depth = cat(1, depth, depth0);
            dnum  = cat(1, dnum,  dnum0);
            evid  = cat(1, evid,  evid0);
            orid  = cat(1, orid,  orid0);
            nass  = cat(1, nass,  nass0);
            mag   = cat(1, mag,   mag0);
            mb   = cat(1, mb,   mb0);
            ml   = cat(1, ml,   ml0);
            ms   = cat(1, ms,   ms0);
            subclass  = cat(2, subclass, subclass0);
            auth = cat(1,  auth, auth0);
        end
    end
    mag(mag<-3.0)=NaN;
    if strcmp(p.Results.RUNMODE, 'slow')
        %%% SLOW MODE %%%
        % Create an Event object for each longitude in the list
        event_list = [];
        for i=1:length(lon) % Loop over each element in vector
            magnitude_obj = Netmag(mag(i));
            origin_obj = Origin(dnum(i), lon(i), lat(i), depth(i), ...
                'orid', orid(i), 'etype', subclass(i), 'netmags', [magnitude_obj] ...
                );
            event_list = [ ...
                event_list ...
                Event( ...
                    [origin_obj], ...
                    'evid', evid(i) ...
                    ) ...
                ];
        end
        % CREATE CATALOG OBJECT
        self = Catalog_full(event_list);
    elseif strcmp(p.Results.RUNMODE, 'fast')
        %%% FAST MODE %%%
        self = Catalog_lite(lat, lon, depth, dnum, mag, subclass);
    end
    st = dbstack;
    self = self.addfield('method', st(1).name);
    self = self.addfield('dbpath', dbpath);
    self = self.addfield('archiveformat', archiveformat);
    ds = datasource('antelope', dbpath);
    self = self.addfield('datasource', ds);
end
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [lon, lat, depth, dnum, evid, orid, nass, mag, mb, ml, ms, etype, auth] = dbloadprefors(dbpath, subset_expression)
    numorigins = 0;
    [lat, lon, depth, dnum, time, evid, orid, nass, mag, ml, mb, ms, etype, auth] = deal([]);
    if iscell(dbpath)
        dbpath = dbpath{1};
    end
    debug.print_debug(sprintf('Loading data from %s',dbpath),3);
    ORIGIN_TABLE_PRESENT = dbtable_present(dbpath, 'origin');
    if (ORIGIN_TABLE_PRESENT)
        db = dblookup_table(dbopen(dbpath, 'r'), 'origin');
        numorigins = dbquery(db,'dbRECORD_COUNT');
        debug.print_debug(sprintf('Got %d records from %s.origin',numorigins,dbpath),1);
        if numorigins > 0
            EVENT_TABLE_PRESENT = dbtable_present(dbpath, 'event');
            if (EVENT_TABLE_PRESENT)
                db = dbjoin(db, dblookup_table(db, 'event') );
                numorigins = dbquery(db,'dbRECORD_COUNT');
                debug.print_debug(sprintf('Got %d records after joining event with %s.origin',numorigins,dbpath),1);
                if numorigins > 0
                    db = dbsubset(db, 'orid == prefor');
                    numorigins = dbquery(db,'dbRECORD_COUNT');
                    debug.print_debug(sprintf('Got %d records after subsetting with orid==prefor',numorigins),1);
                    if numorigins > 0
                        db = dbsort(db, 'time');
                    else
                        % got no origins after subsetting for prefors - already reported
                        debug.print_debug(sprintf('%d records after subsetting with orid==prefor',numorigins),0);
                        return
                    end
                else
                    % got no origins after joining event to origin table - already reported
                    debug.print_debug(sprintf('%d records after joining event table with origin table',numorigins),0);
                    return
                end
            else
                debug.print_debug('No event table found, so will use all origins from origin table, not just prefors',0);
            end
        else
            % got no origins after opening origin table - already reported
            debug.print_debug(sprintf('origin table has %d records',numorigins),0);
            return
        end
    else
        debug.print_debug('no origin table found',0);
        return
    end
    numorigins = dbquery(db,'dbRECORD_COUNT');
    debug.print_debug(sprintf('Got %d prefors prior to subsetting',numorigins),2);
    % Do the subsetting
    if ~isempty(subset_expression)
        db = dbsubset(db, subset_expression);
        numorigins = dbquery(db,'dbRECORD_COUNT');
        debug.print_debug(sprintf('Got %d prefors after subsetting',numorigins),2);
    end
    if numorigins>0
        if EVENT_TABLE_PRESENT
            [lat, lon, depth, time, evid, orid, nass, ml, mb, ms, auth] = dbgetv(db,'lat', 'lon', 'depth', 'time', 'evid', 'orid', 'nass', 'ml', 'mb', 'ms', 'auth');
        else
            [lat, lon, depth, time, orid, nass, ml, mb, ms, auth] = dbgetv(db,'lat', 'lon', 'depth', 'time', 'orid', 'nass', 'ml', 'mb', 'ms', 'auth');
            disp('Setting evid == orid');
            evid = orid;
        end
        etype0 = dbgetv(db,'etype');
        if isempty(etype0)
                etype = char(ones(numorigins,1)*'R');
        else
            % convert etypes
            % AVO codes are A, B, C, E, G, L, O, R, X, a, b, h, i, x and
            % '-' = the null etype in Antelope
            % AVO Classification Codes
            % 'a' = Volcano-Tectonic (VT)
            % 'b' = Low-Frequency (LF)
            % 'h' = Hybrid
            % 'E' = Regional-Tectonic
            % 'T' = Teleseismic
            % 'i' = Shore-Ice
            % 'C' = Calibrations
            % 'o' = Other non-seismic
            % 'x' = Cause unknown
            % But AVO catalog also contains A, B, G, L, O, R, X
            % Assuming A, B, O and X are same as a, b, o and x, that still
            % leaves G, L and R
            etype0=char(etype0);
            etype(etype0=='a')='t';
            etype(etype0=='A')='t';
            etype(etype0=='b')='l';
            etype(etype0=='B')='l';
            etype(etype0=='-')='u';
            etype(etype0==' ')='u';
            etype(etype0=='E')='R';
            etype(etype0=='T')='D';
            etype(etype0=='x')='u';
            etype(etype0=='X')='u';
            etype(etype0=='O')='o';
        end
        etype = char(etype); % sometimes etype gets converted to ASCII numbers
        % get mag
        mag = max([ml mb ms], [], 2);
        % convert time from epoch to Matlab datenumber
        dnum = epoch2datenum(time);
    end
    % close database
    dbclose(db);
end
function self = convert_irisFetch_to_Catalog(ev)
    % Create an Event object for each longitude in the list
    event_list = [];
    for i=1:length(ev) % Loop over each element in vector
       % try
            magnitude_obj = [Netmag(NaN)];
            if ~isnan(ev(i).PreferredMagnitudeValue)
                magnitude_obj = ...
                    Netmag( ...
                        ev(i).PreferredMagnitude.Value, ...
                        'magtype', ev(i).PreferredMagnitude.Type ...
                    );
            end
            origin_obj = [];
            evid = 0;
            if ev(i).PreferredTime
                origin_obj = ...
                    Origin( ...
                        datenum(ev(i).PreferredOrigin.Time), ...
                        ev(i).PreferredOrigin.Longitude, ...
                        ev(i).PreferredOrigin.Latitude, ...
                        ev(i).PreferredOrigin.Depth, ...
                        'etype', ev(i).Type, ...
                        'netmags', magnitude_obj ...
                    );
                evid = ev(i).PreferredOrigin.ContributorEventId;
            end
            if isnumeric(evid)
                event_list = ...
                    [event_list ...
                        Event( ...
                            [origin_obj], ...
                            'evid', ev(i).PreferredOrigin.ContributorEventId ...
                        );
                    ];
            else
                 event_list = ...
                    [event_list ...
                        Event( ...
                            [origin_obj] ...
                        );
                    ];
            end
        %catch ME
        %    ev(i)
        %    rethrow(ME);
        %end
    end
    % CREATE CATALOG OBJECT
    self = ...
        Catalog_full( ...
            event_list, ...
            'description', '' ...
        );
    st = dbstack;
    self = self.addfield('method', st(1).name);
end
% function irisFetchExists()
%     if exist('dirisFetch')~=2
%         [st,i]=dbstack();
%         error(sprintf('%s:%s:line %d: irisFetch.m not found\n',st(1).file,st(1).name,st(1).line));
%     end
% end
%% LOAD_AEF
function self = load_aef(varargin)
    % LOAD_AEF
    %   Wrapper for loading dat files generated from Seisan S-FILES (REA) databases.
    %   DAT file name is like YYYYMM.dat
    %   DAT file format is like:
    %
    %   YYYY MM DD HH MM SS c  MagE
    %
    %   where YYYY MM DD HH MM SS is time in UTC
    %         c is subclass
    %              r = rockfall
    %              e = lp-rockfall
    %              l = long period (lp)
    %              h = hybrid
    %              t = volcano-tectonic
    %              R = regional
    %              u = unknown
    %         MagE is equivalent magnitude, based on energy
    %         produced by the program ampengfft. These values come
    %         from magnitude database that formed part of a
    %         real-time alarm system, but these deleted were
    %         maliciously deleted in June 2003. A magnitude was
    %         computed for each event, assuming a location at sea
    %         level beneath the dome. Regardless of type. This was
    %         particularly helpful for understanding trends in
    %         cumulative energy for different types from week to
    %         week or month to month, and for real-time alarm
    %         messages about pyroclastic flow signals where an
    %         indication of event size was very important.
    %
    %
    % Process input arguments
    p = inputParser;
    p.addParamValue('dbpath', '', @isstr);
    p.addParamValue('snum', 0, @isnumeric);
    p.addParamValue('enum', now, @isnumeric);
    p.addParamValue('minmag', [], @isnumeric);
    p.addParamValue('region', [], @isnumeric);
    p.addParamValue('subclass', '*', @ischar);
    p.addParamValue('mindepth', [], @isnumeric);
    p.addParamValue('maxdepth', [], @isnumeric);
    p.addParamValue('RUNMODE', 'fast', @isstr);
    p.parse(varargin{:});
    fields = fieldnames(p.Results);
    for i=1:length(fields)
        field=fields{i};
        % val = eval(sprintf('p.Results.%s;',field));
        val = p.Results.(field);
        eval(sprintf('%s = val;',field));
    end
    if ~exist(dbpath, 'dir')
        fprintf('Directory %s not found. Perhaps you need to generate from S files?\n',dbpath);
        return;
    end
    lnum=snum;
    % loop over all years and months selected
    while (  lnum <= enum ),
        [yyyy, mm] = datevec(lnum);
        % concatenate catalogs
        obj0 = import_aef_file(dbpath,yyyy,mm,snum,enum,p.Results.RUNMODE);
        if exist('self', 'var')
            self = self + obj0;
        else
            self = obj0;
        end
        clear obj0;
        % ready for following month
        lnum=datenum(yyyy,mm+1,1);
    end
    self.mag(self.mag<-3)=NaN;
    if ~isempty(self.dnum)
        % cut data according to threshold mag
        if ~isempty(minmag)
            disp('Applying minimum magnitude filter')
            m = find(self.mag > minmag);
            fprintf('Accepting %d events out of %d\n',length(m),length(self.dnum));
            self.event_list = self.event_list(m);
        end
    end
end
%% IMPORT_AEF_FILE
function self = import_aef_file(dirpath, yyyy, mm, snum, enum, RUNMODE)
    self = [];
    fprintf('\nAPPEND SEISAN %4d-%02d\n',yyyy,mm)
    datfile = fullfile(dirpath,sprintf('%4d%02d.dat',yyyy,mm));
    if exist(datfile,'file')
        disp(['loading ',datfile]);
        [yr,mn,dd,hh,mi,ss,etype0,mag0] = textread(datfile,'%d %d %d %d %d %d %s %f');
        dnum = datenum(yr,mn,dd,hh,mi,ss)';
        mag = mag0';
        etype = char(etype0)';
        l = length(dnum);
        if strcmp(RUNMODE, 'slow')
            % SLOW MODE
            % Create an Event object for each dnum in the list
            event_list = [];
            for i=1:l % Loop over each element in vector
                if dnum(i)>=snum & dnum(i)<=enum
                    disp(sprintf('%s %5.2f',datestr(dnum(i)), mag(i)))
                    if mag(i) < -3.0
                        mag(i) = NaN;
                    end
                    magnitude_obj = Netmag(mag(i));
                    origin_obj = Origin(dnum(i), NaN, NaN, NaN, ...
                            'orid', str2num(sprintf('%4d%02d_%05d',yyyy,mm,i)), ...
                            'netmags', [magnitude_obj], ...
                            'etype', etype(i) ...
                        );
                    event_list = [ ...
                        event_list ...
                        Event( ...
                            [origin_obj], ...
                            'evid', str2num(sprintf('%4d%02d_%05d',yyyy,mm,i)) ...
                            ) ...
                        ];
                end
            end
            % CREATE CATALOG OBJECT
            self = Catalog_full( event_list );
        elseif strcmp(RUNMODE, 'fast')
            % FAST MODE
            self = Catalog_lite([], [], [], dnum, mag, etype);
        end
        st = dbstack;
        self = self.addfield('method', st(1).name);
        self = self.addfield('dbpath', dirpath);
    else
        disp([datfile,' not found']);
    end
end
function self = load_seisandb(varargin)
    % LOAD_SEISANDB
    %   Wrapper for loading dat files generated from Seisan S-FILES (REA) databases.
    %   DAT file name is like YYYYMM.dat
    %   DAT file format is like:
    %
    %   YYYY MM DD HH MM SS c  MagE
    %
    %   where YYYY MM DD HH MM SS is time in UTC
    %         c is subclass
    %              r = rockfall
    %              e = lp-rockfall
    %              l = long period (lp)
    %              h = hybrid
    %              t = volcano-tectonic
    %              R = regional
    %              u = unknown
    %         MagE is equivalent magnitude, based on energy
    %         produced by the program ampengfft. These values come
    %         from magnitude database that formed part of a
    %         real-time alarm system, but these were deleted in June 2003.
    %
    %         A magnitude was
    %         computed for each event, assuming a location at sea
    %         level beneath the dome. Regardless of type. This was
    %         particularly helpful for understanding trends in
    %         cumulative energy for different types from week to
    %         week or month to month, and for real-time alarm
    %         messages about pyroclastic flow signals where an
    %         indication of event size was very important.
    %
    %
    % Process input arguments
    p = inputParser;
    p.addParamValue('dbpath', '', @isstr);
    p.addParamValue('snum', 0, @isnumeric);
    p.addParamValue('enum', now, @isnumeric);
    p.addParamValue('RUNMODE', 'fast', @isstr);
    p.parse(varargin{:});
    fields = fieldnames(p.Results);
    for i=1:length(fields)
        field=fields{i};
        % val = eval(sprintf('p.Results.%s;',field));
        val = p.Results.field;
        eval(sprintf('%s = val;',field));
    end
    if ~exist(dbpath, 'dir')
        fprintf('Directory %s not found\n',dbpath);
        self = struct;
        return;
    end
    % get dir list of matching sfiles
    sfiles = list_sfiles(dbpath, snum, enum);
    % loop over sfiles
    for i=1:length(sfiles)
        % read
        disp(sprintf('Processing %s',fullfile(sfiles(i).dir, sfiles(i).name)));
        thiss = read_sfile(sfiles(i).dir, sfiles(i).name, '*', '*');
        try
            s(i)=thiss;
        catch
            s(i)
            thiss
            warning('Wrong number of fields?')
        end
s(i)
        % add to catalog
        dnum(i)  = s(i).dnum;
        etype(i) = s(i).subclass;
        lat(i) = s(i).latitude;
        lon(i) = s(i).longitude;
        depth(i) = s(i).depth;
        s(i).magnitude
        % SKELETON
        mag(i) = NaN;
        try
            sfile_mags = [s(i).magnitude.value];
            if ~isempty(sfile_mags)
                disp('**************** ********************')
                mag(i) = max(sfile_mags);
            end
        end
        % also do something with parameters spdur, bbdur, amp, eng, pkf,
        % station
        % Compute a magnitude from amp & eng, but need to know where
        % stations are. I can save these as MA and ME, to distinguish from
        % Ml, Ms, Mb, Mw if those exist
%         catch
%             i
%             %s(i) = struct();
%             disp('- failed');
%             dnum(i) = NaN;
%             etype(i) = 'u';
%         end
    end
    l = length(dnum);
    if strcmp(RUNMODE, 'slow')
        % SLOW MODE
        % Create an Event object for each dnum in the list
        event_list = [];
        for i=1:l % Loop over each element in vector
            if dnum(i)>=snum & dnum(i)<=enum
                [yyyy,mm]=datevec(dnum(i));
                disp(sprintf('%s %5.2f',datestr(dnum(i)), mag(i)))
                if mag(i) < -3.0
                    mag(i) = NaN;
                end
                magnitude_obj = Netmag(mag(i));
                origin_obj = Origin(dnum(i), lon(i), lat(i), depth(i), ...
                        'orid', str2num(sprintf('%4d%02d%05d',yyyy,mm,i)), ...
                        'etype', etype(i), ...
                        'netmags', [magnitude_obj] ...
                    );
                event_list = [ ...
                    event_list ...
                    Event( ...
                        [origin_obj], ...
                        'evid', str2num(sprintf('%4d%02d%05d',yyyy,mm,i)) ...
                        ) ...
                    ];
            end
        end
        % CREATE CATALOG OBJECT
        self = Catalog_full(event_list);
    elseif strcmp(RUNMODE, 'fast')
        % FAST MODE
        self = Catalog_lite([], [], [], dnum, mag, etype);
    end
    st = dbstack;
    self = self.addfield('method', st(1).name);
    self = self.addfield('dbpath', dbpath);
    self = self.addfield('sfile', s);
    wavdbpath = strrep(dbpath, 'REA', 'WAV');
    ds = datasource('seisan', wavdbpath);
    self = self.addfield('datasource', ds);
end
function files = list_sfiles(dbpath, snum, enum)
    % LIST_SFILES Load waveform files from a Seisan database
    %   s = list_sfiles(dbpath, snum, enum) search a Seisan
    %   database for Sfiles matching the time range given by snum
    %   and enum.
    %
    %   Notes:
    %     Seisan Sfiles are typically stored in a Seisan
    %     Seisan database, which is a tree of 4-digit-year/2-digit-month
    %     directories. They have a name matching DD-HHMM-SSc.SYYYYMM
    %
    %   Example:
    %       Load all data for all stations & channels between 1000 and 1100
    %       UTC on March 1st, 2001.
    %
    %           dbpath = '/raid/data/seisan/REA/DSNC_';
    %           snum = datenum(2001,3,1,10,0,0);
    %           enum = datenum(2001,3,1,11,0,0);
    %           s = list_sfiles(dbpath, snum, enum)
    %
    files = [];
    % Test dbpath
    if ~exist(dbpath,'dir')
        disp(sprintf('dbpath %s not found',dbpath))
        return
    end
    %% Compile a list from all directories from snum to enum
    sdv = datevec(snum);
    edv = datevec(enum);
    fileindex = 0;
    for yyyy=sdv(1):edv(1)
       for mm=sdv(2):edv(2)
           seisandir = fullfile(dbpath, sprintf('%4d',yyyy), sprintf('%02d',mm) );
           newfiles = dir(fullfile(seisandir, sprintf('*%4d%02d',yyyy,mm)));
           for i=1:length(newfiles)
               dnum = sfile2dnum(newfiles(i).name);
               if dnum >= snum & dnum <= enum
                   fileindex = fileindex + 1;
                   newfiles(i).dir = seisandir;
                   files = [files; newfiles(i)];
               elseif dnum>enum
                   break;
               end
           end
       end
    end
    %% Echo the list of matching sfiles
    disp(sprintf('There are %d sfiles matching your request',numel(files)))
end
function s=read_sfile(sfiledir, sfilebase,sta,chan);
% READ_SFILE import data from a single MVO SFILE generated in SEISAN.
% USAGE: s=read_sfile(sfiledir, sfilebase,sta,chan)
% INPUT VARIABLES:
%   sfiledir = directory of the S-file
%   sfilebase = basename of the S-file
%   sta = the station to load, or can be set to '*' for all
%   chan = the channel to load, or can be set to '*' for all
%       note: only last character of chan is used for matching presently
% OUTPUT VARIABLES:
%   s = a structure containing
%       aef = a structure with vector fields
%           amp = MAX AVERAGE AMPLITUDE OF SIGNAL
%           eng = SEISMIC ENERGY
%           ssam = percentage of energy in 11 different frequency bins
%           pkf = PEAK FREQUENCY
%           scnl = SCNLOBJECT
%       stime = EVENT TIME
%       ...and many more variables...
%
% EXAMPLE:
%   s = read_sfile('/raid/data/seisan/REA/MVOE_/2002/02', '27-2109-46L.S200202','*', '*')
%   s = read_sfile('/raid/data/seisan/AEF/MVOE_/2002/02', '2002-02-27-2311-34S.MVO___014.aef','*','*')
    % Validate
    fullpath = fullfile(sfiledir, sfilebase);
    if ~ischar(fullpath) || ~exist(fullpath)
        warning(sprintf('catalog:readCatalog:notFound','%s not found',fullpath));
        % eval(['help ' mfilename]);
        help(mfilename);
    end
    % initialize
    s = struct();
    s.aef = struct('amp', [], 'eng', [], 'ssam', {}, 'pkf', [], 'scnl', []);
    s.subclass='_';
    s.bbdur=NaN;
    s.stime = '';
    s.dnum = sfile2dnum(sfilebase);
    s.wavfiles = '';
    s.error = NaN;
    s.gap = NaN;
    s.magnitude = struct();
    s.longitude = NaN;
    s.latitude = NaN;
    s.depth = NaN;
    aef = struct();
    % open file
    fid=fopen(fullpath,'r');
    patternstr = ['VOLC',' ',sta];
    linenum = 1;
    aeflinenum = 0;
    magnum = 0;
    while fid ~= -1,
        tline = fgetl(fid);
        %disp(sprintf('line = %d',linenum));
        %disp(tline);
        linelength=length(tline);
        if ischar(tline) & linelength == 80 % must be an 80 character string, or close file
            if tline(80) == '1'
                if length(strtrim(tline(2:20)))  >= 14
                    s.year = str2num(tline(2:5));
                    s.month = str2num(tline(7:8));
                    day = str2num(tline(9:10));
                    hour = str2num(tline(12:13));
                    minute = str2num(tline(14:15));
                    second = str2num(tline(17:20));
                    if floor(second) == 60
                        minute = minute + 1;
                        second = second - 60.0;
                    end
                    s.otime = datenum(s.year, s.month, day, hour, minute, floor(second));
                end
                s.mainclass = strtrim(tline(22:23));
                lat = str2num(tline(24:30));
                lon = str2num(tline(31:38));
                depth = str2num(tline(39:43));
                if isempty(lat)
                    s.latitude = NaN;
                end
                if isempty(lon)
                    s.longitude = NaN;
                end
                if isempty(depth)
                    s.depth = NaN;
                end
                s.z_indicator = strtrim(tline(44));
                s.agency = strtrim(tline(46:48));
                s.no_sta=str2num(tline(49:51));
                if isempty(s.no_sta)
                    s.no_sta=0;
                end
                s.rms=str2num(tline(52:55));
                tline(56:75)
                if ~isempty(strtrim(tline(56:59)));
                    magnum = magnum + 1;
                    s.magnitude(magnum).value = str2num(tline(56:59));
                    s.magnitude(magnum).type = tline(60);
                    s.magnitude(magnum).agency = strtrim(tline(61:63));
                end
                if ~isempty(strtrim(tline(64:67)))
                    magnum = magnum + 1;
                    s.magnitude(magnum).value = str2num(tline(64:67));
                    s.magnitude(magnum).type = tline(68);
                    s.magnitude(magnum).agency = strtrim(tline(69:71));
                end
                if ~isempty(strtrim(tline(72:75)))
                    magnum = magnum + 1;
                    s.magnitude(magnum).value = str2num(tline(72:75));
                    s.magnitude(magnum).type = tline(76);
                    s.magnitude(magnum).agency = strtrim(tline(77:79));
                end
            end
            % Process Type 2 line, Macroseismic Intensity Information
            if tline(80) == '2'
               s.maximum_intensity=str2num(tline(28:29));
            end
            if tline(80) == '3'   % This is SEISAN identifier for summary lines in the Sfile
                if strfind(tline,'VOLC')
                    if strfind(tline,'MAIN')  % This identifies the volcanic type
                        s.subclass=tline(12);
                    else % A TYPE 3 LINE LIKE "VOLC STA"
                        if strcmp(sta,'*') || strfind(tline,sta)
                            if strcmp(chan,'*') ||  strfind(tline(14:15),chan(end))
                                aeflinenum = aeflinenum + 1;
                                thissta = strtrim(tline(7:10));
                                thischan = strtrim(tline(12:15));
                                aef.scnl(aeflinenum) = scnlobject(thissta, thischan);
                                try
                                    %aef.amp(aeflinenum)=str2num(tline(20:27));
                                    aef.amp(aeflinenum)=str2num(tline(18:25));
                                catch
                                    tline
                                    tline(20:27)
                                    aeflinenum
                                    aef.amp
                                    error('aef.amp')
                                end
                                %aef.eng(aeflinenum)=str2num(tline(30:37));
                                aef.eng(aeflinenum)=str2num(tline(28:35));
                                for i = 1:11
                                    %startindex = (i-1)*3 + 40;
                                    startindex = (i-1)*3 + 38;
                                    ssam(i) = str2num(tline(startindex:startindex+1));
                                end
1000                                 aef.ssam{aeflinenum} = ssam;
1001                                 aef.pkf(aeflinenum)=str2num(tline(73:77));   % Peak frequency (Frequency of the largest peak
1002                             end
1003                         end
1004                     end
1005                 elseif strcmp(tline(2:7), 'ExtMag')
1006                     magnum = magnum + 1;
1007                     s.magnitude(magnum).value = str2num(tline(9:12));
1008                     s.magnitude(magnum).type = tline(13);
1009                     s.magnitude(magnum).agency = strtrim(tline(14:16));
1010                 elseif strcmp(tline(1:4), 'URL')
1011                     s.url = strtrim(tline(6:78));
1012                 end
1013
1014             end
1015
1016             if tline(80) == '6'
1017                 s.wavfiles = tline(2:79);
1018                 wavfile{1} = tline(2:36);
1019             end
1020
1021             % Process Type E line, Hyp error estimates
1022             if tline(80) == 'E'
1023                 s.gap=str2num(tline(6:8));
1024                 s.error.origintime=str2num(tline(15:20));
1025                 s.error.latitude=str2num(tline(25:30));
1026                 s.error.longitude=str2num(tline(33:38));
1027                 s.error.depth=str2num(tline(39:43));
1028                 s.error.covxy=str2num(tline(44:55));
1029                 s.error.covxz=str2num(tline(56:67));
1030                 s.error.covyz=str2num(tline(68:79));
1031             end
1032
1033             % Process Type F line, Fault plane solution
1034             % Format has changed need to fix AAH - 2011-06-23
1035             if tline(80) == 'F' %and not s.focmec.has_key('dip'):
1036                 s.focmec.strike=str2num(tline(1:10));
1037                 s.focmec.dip=str2num(tline(11:20));
1038                 s.focmec.rake=str2num(tline(21:30));
1039                 %s.focmec.bad_pols=str2num(tline(61:66));
1040                 s.focmec.agency=tline(67:69);
1041                 s.focmec.source=tline(71:77);
1042                 s.focmec.quality=tline(78);
1043             end
1044
1045             % Process Type H line, High accuracy line
1046             % This replaces some origin parameters with more accurate ones
1047             if tline(80) == 'H'
1048                 osec0=str2num(tline(17:22));
1049                 yyyy0=str2num(tline(2:5));
1050                 mm0=str2num(tline(7:8));
1051                 dd0=str2num(tline(9:10));
1052                 hh0=str2num(tline(12:13));
1053                 mi0=str2num(tline(14:15));
1054                 s.otime=datenum(yyyy0, mm0, dd0, hh0, mi0, osec0)
1055                 s.latitude=str2num(tline(24:32));
1056                 s.longitude=str2num(tline(34:43));
1057                 s.depth=str2num(tline(45:52));
1058                 s.rms=str2num(tline(54:59));
1059             end
1060
1061             if tline(80) == 'I'
1062                 s.last_action=strtrim(tline(9:11));
1063                 s.action_time=strtrim(tline(13:26));
1064                 s.analyst = strtrim(tline(31:33));
1065                 s.id = str2num(tline(61:74));
1066             end
1067
1068             if tline(2:8)=='trigger'
1069                 s.bbdur=str2num(tline(18:19)); % EARTHWORM TRIGGER DURATION (including pre & posttrigger times?)
1070                 s.bbdur=str2num(tline(19:23));
1071             elseif tline(2:7)=='sptrig'
1072                 s.spdur=str2num(tline(19:23));
1073             end
1074
1075             if tline(22:24) == 'MVO' &  (tline(80) == '6') % DATE AND TIME OF THE EVENT
1076                 s.stime=tline(2:19);
1077             end
1078         else
1079             fclose(fid);
1080             break
1081         end
1082         linenum = linenum + 1;
1083     end
1084     s.aef = aef;
1085 end
1086
1087 function sfilednum=sfile2dnum(sfile)
1088     ddstr=sfile(1:2);
1089     hhstr=sfile(4:5);
1090     mistr=sfile(6:7);
1091     ssstr=sfile(9:10);
1092     yystr=sfile(14:17);
1093     mm=str2num(sfile(18:19));
1094     months=['Jan';'Feb';'Mar';'Apr';'May';'Jun';'Jul';'Aug';'Sep';'Oct';'Nov';'Dec'];
1095     mmstr=months(mm,:);
1096     datestring=[ddstr,'-',mmstr,'-',yystr,' ',hhstr,':',mistr,':',ssstr];
1097     try
1098         sfilednum=datenum(datestring);
1099     catch
1100         error(sprintf('Could not convert %s to a datenum for sfile=%s. Returning 0', datestring, sfile));
1101     end
1102 end
1103
1104 function self=read_vdap(filename)
1105 %READ_VDAP read Hypoellipse summary files and PHA pickfiles
1106 %   based on Montserrat analog network
1107 %   cobj = read_vdap(filename) will read the catalog file, and create a
1108 %   Catalog object
1109 %
1110 %   Summary file has lines like:
1111 %
1112 %   PHA phase file has lines like:
1113 %   MGHZEP 1 950814071436.76
1114 %   MSPTIPU0 950814071437.96
1115 %   MGATEPU0 950814071437.92                                              00011
1116 %   MLGT PD0 950814071438.09       39.41 S 2
1117 %   MWHTEPD1 950814071437.61       38.78 S 2                              00009
1118 %   1-4: sta code
1119 %   5:   E or I
1120 %   6:   P (or blank)
1121 %   7:   U or D
1122 %   8:   quality 0-4
1123 %  10-24: YYMMDDhhmmss.ii for P
1124 %  31-35: ss.ii for S
1125 %  37:   S (or blank)
1126 %  39:   quality 0-4
1127 % Glenn Thompson 2014/11/14
1128
1129     %% read the headers and data
1130     fid = fopen(phafilename);
1131     tline = fgetl(fid);
1132     while ischar(tline)
1133         tline = fgetl(fid);
1134         stacode = tline(1:4);
1135         p_eori = tline(5);
1136         p = tline(6);
1137         p_uord = tline(7);
1138         p_qual = tline(8);
1139         p_datetime = tline(10:24);
1140         s_datetime = tline(31:35);
1141         s = tline(37);
1142         s_qual = tline(39);
1143     end
1144     fclose(fid);
1145
1146
1147 end
1148
1149
1150 function self=read_SRU(filename)
1151 %READ_SRU read a catalog sent by Seismic Research Unit, University of West
1152 %Indies
1153 %   Based on a Dominica catalog sent to Ophelia George
1154 %   cobj = read_SRU(filename) will read the catalog file, and create a
1155 %   Catalog object
1156 %
1157 %   File has lines like:
1158 %   #EVENT_ID    P    S    LAT.    LONG    DEP.    DATE    TIME    RMSE    MAG.
1159 %   9703120.002    3    3    15.4170N    61.2890W    3    19970322    658.23    0.347    2.5
1160 %
1161 % Glenn Thompson 2014/11/14
1162
1163     %% read the headers and data
1164     fid = fopen(filename);
1165     headers = textscan(fid, '%s', 10); % header is just 10 strings
1166     data = textscan(fid, '%f%d%d%s%s%f%s%f%f%f'); % import the columns from each tab separated row as float, integer, integer, string, ...
1167     fclose(fid);
1168
1169     %% wrangle the data into variables we can use
1170     evid=data{1}; % event id - like 9703120.002 - but we'll probably just renumber them from 1
1171     nassP=data{2}; % number of associated P arrivals - like 3
1172     nassS=data{3}; % number of associated S arrivals - like 3
1173
1174     % latitude like '15.4170N'
1175     latstr = data{4};
1176     for c=1:numel(latstr)
1177         thislatstr = latstr{c};
1178         hemisphere = thislatstr(end);
1179         lat(c) = str2num(thislatstr(1:end-1));
1180         if lower(hemisphere)=='s'
1181             lat(c) = -lat(c);
1182         end
1183     end
1184
1185     % longitude like '61.2890W'
1186     lonstr = data{5};
1187     for c=1:numel(lonstr)
1188         thislonstr = lonstr{c};
1189         hemisphere = thislonstr(end);
1190         lon(c) = str2num(thislonstr(1:end-1));
1191         if lower(hemisphere)=='w'
1192             lon(c) = -lon(c);
1193         end
1194     end
1195
1196     % depth like 3
1197     depth = data{6};
1198
1199     % date like 19970322
1200     yyyymmdd = data{7};
1201     for c=1:numel(yyyymmdd)
1202         thisyyyymmdd = yyyymmdd{c};
1203         yyyy(c) = str2num(thisyyyymmdd(:,1:4));
1204         mo(c) = str2num(thisyyyymmdd(:,5:6));
1205         dd(c) = str2num(thisyyyymmdd(:,7:8));
1206     end
1207
1208     % time like 658.23 for 00:06:58.23 but really HHMMSS.MS
1209     hhmmss = data{8};
1210     for c=1:numel(hhmmss)
1211         thishhmmss = sprintf('%09.2f',hhmmss(c));
1212         hh(c) = str2num(thishhmmss(:,1:2));
1213         mm(c) = str2num(thishhmmss(:,3:4));
1214         ss(c) = str2num(thishhmmss(:,5:9));
1215     end
1216
1217     dnum = datenum(yyyy, mo, dd, hh, mm, ss);
1218     datestr(dnum)
1219
1220     % RMS Error
1221     rms = data{9};
1222
1223     % Magnitude
1224     mag = data{10};
1225
1226
1227     %% Create an etype (assume type 'tectonic')
1228     etype = repmat('t',numel(dnum));
1229
1230     %% Create our Catalog object
1231     % FAST MODE
1232     self = Catalog_lite(lat, lon, depth, dnum, mag, etype);
1233     % WE COULD ADD ANOTHER METHOD HERE IN SLOW MODE TO CREATE A FULL
1234     % CATALOG OBJECT, MAKING USE OF FIELDS LIKE nassP, rms etc.
1235 end
1236
1237 function out = ensure_dateformat(t)
1238 % stolen from waveform
1239    % returns a matrix of datenums of same shape as t
1240    if isnumeric(t)
1241       out = t;
1242    elseif ischar(t),
1243       for n = size(t,1) : -1 : 1
1244          out(n) = datenum(t(n,:));
1245       end
1246    elseif iscell(t)
1247       out(:) = datenum(t);
1248    end
1249    % previously implemented as:
1250    % if ischar(startt), startt = {startt}; end
1251    % if ischar (endt), endt = {endt}; end;
1252    % startt = reshape(datenum(startt(:)),size(startt));
1253    % endt = reshape(datenum(endt(:)),size(endt));
1254 end