Description of SeismicTrace
Home > GISMO > core > dev > @SeismicTrace > SeismicTrace.m
SeismicTrace
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
extract EXTRACT extract matches to the master waveform
disp CATALOG.DISP Display Catalog object
plot CATALOG.PLOT Plot hypocenters in map view and cross-sections
ChannelTag
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
sort C = SORT(C,'TIME')
waveform WAVEFORM Extract a waveform object.
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
plot PLOT: Drumplot plotting function. A drumplot object (h) contains no
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
set SET - Set filterobject properties
extract
plot RSAM/PLOT plot rsam data
ChannelTag ChannelTag Converter from scnlobject to ChannelTag
disp DISP - scnl disp overloaded operator
get GET for the scnl object
ismember ISMEMBER for scnlobjects
set SET - Set properties for scnlobject
unique UNIQUE return set of unique scnlobjects from an array
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
disp DISP Display threecomp object
extract EXTRACT particle motion parameters from a threecomp object
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
plot PLOT plots a threecomp object
set SET inserts properties for threecomp object
waveform WAVEFORM Get waveforms from a threecomp object
addfield ADDFIELD add fields and values to waveform object(s) V1.1
disp DISP Waveform disp overloaded operator
double DOUBLE returns a waveform's data as a double type
extract EXTRACT creates a waveform with a subset of another's data.
get GET Get waveform properties
history HISTORY retrieve the history of a waveform object
isempty ISEMPTY returns TRUE if waveform contains no data
isfield ISFIELD checks the presence of waveform fields.
ismember ISMEMBER waveform implementation of ismember
legend legend creates a legend for a waveform graph
plot PLOT plots a waveform object
time2offset time2offset returns the offset within a waveform's data for time T
set SET Set properties for waveform object(s)
waveform WAVEFORM Waveform Class constructor
disp CORRELATION/DISPLAY Command window display of a correlation object
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
plot PLOT(C) plots waveforms stored in a correlation object. Traces are
set SET Set properties for correlation object
sort C = SORT(C) Sorts traces from oldest to youngest.
waveform WAVEFORM Extract a waveform object.
SeismicTrace
disp disp Display information about SeismicTrace(s)
legend legend Create a legend for the graph of a trace.
linkedplot linkedplot Plot multiple waveform objects as separate linked panels
plot plot plots a SeismicTrace
TraceData
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
set SET: Set helicorder properties
plot PLOT plot fourier transform of a waveform
This function is called by:
antelopesource
NewCorrelation
SeismicTrace
TraceFilter
specgram specgram - plots spectrogram of traces
specgram2 SPECGRAM2 - plots spectrograms of waveforms with waveform along top
test_ChanDetails
waveform_antelope_test % Main function to generate tests
SUBFUNCTIONS
function obj = SeismicTrace(varargin)
function N = get.network(obj)
function obj = set.network(obj, val)
function S = get.station(obj)
function obj = set.station(obj, val)
function L = get.location(obj)
function obj = set.location(obj, val)
function C = get.channel(obj)
function obj = set.channel(obj, val)
function st = get.start(obj)
function obj = set.start(obj, v)
function val = sampletimes(obj)
function val = firstsampletime(obj, stringformat)
function val = lastsampletime(obj, stringformat)
function tf = startsbefore(A, B)
function tf = startsafter(A, B)
function tf = endsbefore(A, B)
function tf = endsafter(A, B)
function s = get.name(T)
function T = set.name(T, val)
function T = align(T,alignTime, newSamprate, method)
function T = noteRealignment(T, startt, samprate)
function T = set.userdata(T, val)
function T = renameUserField(T, oldField, newField, failSilently)
function subfield = mvField(subfield, oldField, newField)
function testUserField(obj, fn, value)
function T = setUserDataRule(T, fieldname, allowedType, allowedCount, allowedRange)
function [T, I] = sortby(T, criteria)
function combined_traces = combine (traces)
function Tout = pieceTogether(T1, T2)
function T1 = spliceAndPad(T1, T2, nToPad)
function T1 = spliceTrace(T1, T2)
function T = timesort(T)
function outW = extract(T, method, startV, endV)
function [B,A] = swap(A,B)
function obj = calibapply(obj)
function obj = calibunapply(obj)
function T = addhistory(T, whathappened,varargin)
function T = clearhistory(T)
function [myhist] = get.history(t)
function W = waveform(T)
function CT = ChannelTag(T)
function T = toTrace(item, itemlabel, conversionfunction)
function T = syntheticdata(names, starts, ends, samplerate)
function T = retrieve(ds, names, starts, ends, miscfilters)
SOURCE CODE
classdef SeismicTrace < TraceData
   %SeismicTrace   Control seismic data including channel and time info
   %  SeismicTrace inherits the ability to manipulate timeseries data from
   %  TraceData, and adds the capability to handle chanel descriptor tags,
   %  handle userdata fields, track history, timestamping, and basic
   %  calibration.
   %
   %  SeismicTrace is the replacement class for waveform
   %
   %  Much functionality is provided by the TraceData class, so see the
   %  help for that class for more details
   %
   %  See also retrieve, TraceData, waveform, ChannelTag
   % Author: Celso Reyes, unless otherwise specified in the class functions
   % Contributions by: Glenn Thompson, Michael West, Carl Tape
   % Based on waveform, by Celso Reyes
   properties(Dependent)
      % Network.Station.Location.Channel code, as char.
      % By setting the name, the related network, station, location,
      % channel, and channelinfo fields are also set
      % see also network, station, location, channel, channelinfo
      name % N.S.L.C code
      network % network code
      station % station code
      location % location code
      channel % channel code
      start
   end
   properties
      % history, stored as a structure of (what, when),
      % where "what" can be anything, and "when" is a matlab datenum
      % see also SeismicTrace.addhistory, SeismicTrace.clearhistory
      history = struct('what','created SeismicTrace','when',now);
      % structure containing user-defined fields
      % Field names are case sensitive.
      % Field values can be validated if a UserDataRule is specified.
      %
      % see also SeismicTrace.userdata, SeismicTrace.setUserDataRule,
      % SeismicTrace.renameUserField
      userdata = struct();
      % contains calibration values for this trace.
      % see also SeismicTrace.setcalib, SeismicTrace.removecalib, SeismicTrace.applycalib
      calib = struct('value',1,'applied',false);
      %struct that mirrors userdata, but contains two fields:
      %   allowed_type: a class name (or empty). If this
      %   exist, then when data is assigned to userdata, it
      %   will be type-checked.
      %   min_count, max_count: if empty,any sized array can be
      %   assigned to this field.  If a single number, then
      %   eac assignment must have exactly this number of values.
      %   if [min max], then any number of values between min
      %   and max inclusive may be assigned to this.
      % see also SeismicTrace.userdata, SeismicTrace.setUserDataRule,
      % SeismicTrace.renameUserField
      UserDataRules
   end
   properties(Hidden)
      mat_starttime % start time in matlab-time
      channelinfo = ChannelTag; % channelTag
   end
   properties(Hidden, Dependent)
   end
   methods
      function obj = SeismicTrace(varargin)
         %SeismicTrace   Constructor for SeismicTrace objects
         %   St=SeismicTrace will return an empty SeismicTrace
         %   St=SeismicTrace(waveform) creates a SeismicTrace from a
         %   waveform objct. This might get removed and put into waveform
         %
         %   See also TraceData, ChannelTag, Waveform
         obj@TraceData(varargin{:});
         switch nargin
            case 1
               if isa(varargin{1}, 'waveform')
                  if numel(varargin{1}) > 1
                     for n=1:numel(varargin{1})
                        st(n) = SeismicTrace(varargin{1}(n));
                     end
                     obj = reshape(st,size(varargin{1}));
                     return
                  end
                  obj.channelinfo = get(varargin{1},'channeltag');
                  obj.mat_starttime = get(varargin{1}, 'start');
                  H = get(varargin{1}, 'history');
                  for n=1:size(H,1);
                     if isempty(H{n,1}) || isempty(H{n,2})
                        continue
                     end
                     obj.history(end+1).what = H{n,1};
                     obj.history(end).when = H{n,2};
                  end
                  miscFields = get(varargin{1},'misc_fields');
                  for n = 1: numel(miscFields)
                     if ~isempty(miscFields{n})
                        obj.userdata.(miscFields{n})= get(varargin{1},miscFields{n});
                     end
                  end
               else
                  error('SeismicTrace:unknownConversion',...
                     'Do not know how to make a SeismicTrace from a %s',...
                     class(varargin{1}));
               end
         end %switch
      end
      %% get/set of channel-related data
      function N = get.network(obj)
         N = obj.channelinfo.network;
      end
      function obj = set.network(obj, val)
         obj.channelinfo.network = val;
      end
      function S = get.station(obj)
         S = obj.channelinfo.station;
      end
      function obj = set.station(obj, val)
         obj.channelinfo.station = val;
      end
      function L = get.location(obj)
         L = obj.channelinfo.location;
      end
      function obj = set.location(obj, val)
         obj.channelinfo.location = val;
      end
      function C = get.channel(obj)
         C = obj.channelinfo.channel;
      end
      function obj = set.channel(obj, val)
         obj.channelinfo.channel = val;
      end
      %%
      function st = get.start(obj)
         st = datestr(obj.mat_starttime,'yyyy-mm-dd HH:MM:SS.FFF');
      end
      function obj = set.start(obj, v)
         if isnumeric(v) && numel(v) == 1
            obj.mat_starttime = v;
         elseif ischar(v)
            obj.mat_starttime = datenum(v);
         else
            error('do not understand start assignment. must be a matlab datenum or a string')
         end
         % could add ability to translate from java or datetime
      end
      function val = sampletimes(obj)
         %sampletimes   Retrieve matlab date for each sample
         %
         %   Replaces waveform's get(w, 'timevector')
         val = sampletimes@TraceData(obj) + obj.mat_starttime;
      end
      function val = firstsampletime(obj, stringformat)
         %firstsampletime   Time of first sample as matlab date or string.
         %  val = trace.lastsampletime will return as a datenum
         %  val = trace.lastsampletime(FORMAT) will return a string
         %  formatted according to FORMAT.
         %  For multiple traces, a character array will be returned.
         %
         %  See also datestr
         val = [obj.mat_starttime];
         if exist('stringformat','var')
            val = datestr(val,stringformat);
         else
            val = reshape(val,size(obj));
         end
      end
      function val = lastsampletime(obj, stringformat)
         %lastsampletime   Time of last sample as matlab date or string.
         %  val = trace.lastsampletime will return as a datenum
         %  val = trace.lastsampletime(FORMAT) will return a string
         %  formatted according to FORMAT.
         %
         %  For multiple traces, a character array will be returned.
         %  See also datestr
         secDurs = [obj.duration];
         secDurs = secDurs(:);
         assert(all(~isnan([obj.samplerate])),...
            'SeismicTrace:lastsampletime:Uncalculatable',...
            'Missing samplerate for one or more waveforms. lastsampletime is incalculable');
         idx = secDurs > 0;
         ps_idx = 1./[obj(idx).samplerate];
         secDurs_idx = secDurs(idx);
         secDurs(idx) = secDurs_idx - ps_idx(:);
         fst = obj.firstsampletime();
         val = fst(:) + secDurs(:)/86400;
         if exist('stringformat','var')
            val = datestr(val,stringformat);
         else
            val = reshape(val,size(obj));
         end
      end
      function tf = startsbefore(A, B)
         %startsbefore   Compare starttimes of SeismicTrace
         %   tf = A.startsbefore(B)  will return TRUE if Trace A starts
         %   before trace B starts.
         %
         %   If B is something other than a SeismicTrace, then it will try
         %   to convert to a MATLAB datenum before converting.
         %
         %   See also: startsafter, endsbefore, endsafter, datenum,
         %   datetime
         if isa(B,'SeismicTrace')
            tf = A.firstsampletime < B.firstsampletime;
         else % handle datenums, datestrings, or datetimes
            tf = A.firstsampletime < datenum(B);
         end
      end
      function tf = startsafter(A, B)
         %startsafter   Compare starttimes of SeismicTrace
         %   tf = A.startsafter (B) will return TRUE if Trace A starts after
         %   Trace B.
         %
         %   If B is something other than a SeismicTrace, then it will try
         %   to convert to a MATLAB datenum before converting.
         %
         %   See also: startsafter, endsbefore, endsafter, datenum,
         %   datetime
         if isa(B,'SeismicTrace')
            tf = A.firstsampletime > B.firstsampletime;
         else % handle datenums, datestrings, or datetimes
            tf = A.firstsampletime > datenum(B);
         end
      end
      function tf = endsbefore(A, B)
         %endsbefore   Compare last samples of SeismicTrace
         %   tf = A.endsbefore (B)  will return TRUE if Trace A ends before
         %   trace B
         %
         %   If B is something other than a SeismicTrace, then it will try
         %   to convert to a MATLAB datenum before converting.
         %
         %   See also: startsafter, endsbefore, endsafter, datenum,
         %   datetime
         if isa(B,'SeismicTrace')
            tf = A.lastsampletime < B.lastsampletime;
         else % handle datenums, datestrings, or datetimes
            tf = A.lastsampletime < datenum(B);
         end
      end
      function tf = endsafter(A, B)
         %endsafter   Compare last samples of SeismicTrace
         %   tf = A.endsafter (B) will return TRUE if Trace A ends after
         %   Trace B.
         %
         %   If B is something other than a SeismicTrace, then it will try
         %   to convert to a MATLAB datenum before converting.
         %
         %   See also: startsafter, endsbefore, endsafter, datenum,
         %   datetime
         if isa(B,'SeismicTrace')
            tf = A.lastsampletime > B.lastsampletime;
         else % handle datenums, datestrings, or datetimes
            tf = A.lastsampletime > datenum(B);
         end
      end
      function s = get.name(T)
         if numel(T) ==1
            s = T.channelinfo.string;
         else
            s=arrayfun(@(x) x.channelinfo.string, T, 'UniformOutput',false);
         end
      end
      function T = set.name(T, val)
         assert(numel(T) == 1, 'only can set name for individual traces');
         T.channelinfo = ChannelTag(val);
      end
      function T = align(T,alignTime, newSamprate, method)
         %align   Resample a seismic trace over a specified interval
         %   T = T.align(alignTime, newSamprate)
         %   T = T.align(alignTime, newSamprate, method)
         %
         %   Input Arguments
         %       T: SeismicTrace      N-dimensional
         %       ALIGNTIME: either a single matlab time or an array of times
         %       the same shape as the input TRACE matrix.
         %       NEWSAMPRATE: sample rate of the newly aligned traces
         %       in samples/second
         %       METHOD: Any of the methods listed in function INTERP1
         %          If omitted, then the default is '<a href="matlab: help pchip">pchip</a>'
         %
         %   Output
         %       The output waveform has the new samplerate newSamprate and a
         %       a starttime calculated by the specified method, using
         %       the <a href="matlab: help interp1">interp1</a> function.
         %
         %   METHODOLOGY
         %     The alignTime is projected forward or backward in time at the
         %     specified sample interval until it approaches the original waveform's
         %     start time.  The rest of the waveform is then interpolated at the
         %     sample rate.
         %
         %     Methodology Example.
         %         A waveform starts on 1/1/2008 12:00, with sample rate of 10
         %         samples/sec, and has data covering 10 minutes  (6000 samples).
         %         The resampled data is requested for time 1/1/2008 12:05:00.03,
         %         also at 10 samples/sec.
         %         The resulting data will start at 1/1/2008 12:00:00.3, and have
         %         5999 samples, with the last sample occurring at 12:09:59.830.
         %
         %   Examples of usefulness?  Particle motions, coordinate transformations.
         %   If used for particle motions, consider <a href="matlab:help plotmatrix">plotmatrix</a> command.
         %
         %   example:
         %       chanNames = {'AV.KDAK..BHZ','AV.KDAK.BHN','AV.KDAK.BHE'};
         %       tags = ChannelTag(chanNames); %grab all 3 channels
         %       % for each component, grab winston data on Kurile Earthquake
         %       T = Trace.retrieve(mydatasource,tags,'1/13/2007 04:20:00','1/13/2007 04:30:00');
         %       T = T.align('1/37/2007 4:22:00', w(1).samplerate);
         %
         %
         % See also interp1, plotmatrix
         oneSecond = 1/86400;
         if ~exist('method','var')
            method = 'pchip';
         end
         if ischar(alignTime),
            alignTime =  datenum(alignTime);
         end
         oneAlignTime = numel(alignTime) == 1;
         hasCompatibleSize = oneAlignTime || ... single align time OR
            all(size(alignTime) == size(T)) || ... same shape OR
            (numel(alignTime) == length(T) && ... both vectors have
            numel(T) == length(alignTime));     % the same length
         assert(hasCompatibleSize, 'SeismicTrace:align:invalidAlignSize',...
            'alignTime must be either a single time or a matrix the same shape as the traces');
         if oneAlignTime % same align time for all traces
            alignTime = repmat(alignTime,size(T));
         end
         newSamplesPerSec = 1 / newSamprate ;  %# samplesPerSecond
         timeStep = newSamplesPerSec * oneSecond;
         existingStarts = T.firstsampletime();
         existingEnds = T.lastsampletime();
         % calculate the offset of the closest "aligned" time, by projecting the
         % desired sample rate and time forward or backward onto these waveforms'
         % start time.
         deltaTime = existingStarts - alignTime;  % time in between
         % if deltatime (-):alignTime AFTER existingStarts,
         % if deltatime (+):alignTime BEFORE existingStarts
         closestStartTime = existingStarts - rem(deltaTime,timeStep);
         for n=1:numel(T)
            origTimes = T(n).sampletimes;
            % newTimes MUST be in one column, else DATA field gets corrupted
            newTimes = ( closestStartTime(n):timeStep:existingEnds(n) )';
            %get rid of samples that lay entirely outside the existing waveform's
            %range (ie, only interpolate values BETWEEN points)
            newTimes(newTimes < origTimes(1) | newTimes > origTimes(end)) = [];
            T(n).data = interp1(...
               origTimes,...     original times (x)
               T(n).data,...         original data (y)
               newTimes,...    new times (x1)
               method);           %  method
            T(n).start = newTimes(1); % must be a datenum
            T(n).samplerate = newSamprate;
         end
         %% update histories
         % if all waves were aligned to the same time, then handle all history here
         if oneAlignTime
            noteRealignment(T, alignTime(1), newSamprate);
         else
            for n=1:numel(T)
               T(n) = noteRealignment(T(n), alignTime(n), newSamprate);
            end
         end
         function T = noteRealignment(T, startt, samprate)
            timeStr = datestr(startt,'yyyy-mm-dd HH:MM:SS.FFF');
            myHistory = sprintf('aligned data to %s at %f samples/sec', timeStr, samprate);
            T = T.addhistory(myHistory);
         end
      end
      %% Handling User-defined fields
      %TODO: Guarentee or document how the userfield things work for
      %multiple trace objects. First thought: They should be performed
      %individually, on a single object
      %
      % waveform/delfield has been replaced by using matlab's rmfield:
      % T.userdata = rmfield(T.userdata, 'fieldToDelete');
      % isfield is not implemented because matlab's can be used:
      % isfield(T.userdata,'something');
      function T = set.userdata(T, val)
         %sets userdata fields for a trace object
         % T.userdata.myfield = value;
         %
         % to impose constraings on the values that this field can
         % retrieve, use: SeismicTrace.SetUserDataRule(myfield,...)
         %
         % to delete the field:
         % T.userdata = rmfield(T.userdata, 'fieldToRemove');
         % see also SeismicTrace.SetUserDataRule, rmfield
         oldfields = fieldnames(T.userdata);
         fn = fieldnames(val);
         fieldToAdd = fn(~ismember(fn, oldfields));
         if ~isempty(fieldToAdd) && any(strcmpi(fieldToAdd, oldfields))
            % we have a case change!! uh-oh.
            similarlyNamed = oldfields{strcmpi(oldfields, fieldToAdd)};
            error(['attempted to add field [''%s''], '...
               'but a similar field [''%s''] exists.\n'...
               'Check your case and try again'],...
               fieldToAdd{1}, similarlyNamed);
         end
         %fn_existing = fieldnames(T.userdata);
         %newfn = ~ismember(fieldnames(val),val
         for f = 1:numel(fn);
            testUserField(T, fn{f}, val.(fn{f}))
         end
         T.userdata = val;
      end
      function T = renameUserField(T, oldField, newField, failSilently)
         %renameUserField   Rename a userdata field
         %  T = T.renameuserField(oldName, newName);
         %  rename a field if it exists to a new name.
         %
         %  Also renames the associated Rules field
         %
         %  Possible sticking-points to deal with:
         %  1. both oldField and newField exist in T.userdata -> error
         %  2. newField already exists in T.userdata -> ignore
         %  3. neither newField or oldfield exists in T.Userdata -> warning
         %
         %  if failSilently is true, then failures will not result in an
         %  error.
         %
         %  See also: userdata, userDataRule
         oldFieldExists = isfield(T.userdata, oldField);
         newFieldExists = isfield(T.userdata, newField);
         sameNames = strcmp(oldField, newField);
         if ~exist('failSilently', 'var'); failSilently = false; end;
         if sameNames
            if failSilently
               return
            else
               warning('oldField is the same as newField [%s]. Ignoring', oldField);
               return
            end
         end
         if oldFieldExists
            if newFieldExists %BOTH fields exist
               if (~isempty(newField))  %but the new one isn't empty
                  error('Both fields already exist, and userdata.%s already contains data',newField);
               else % but the new one is empty, so proceed normally
                  if ~failSilently
                     warning('Both fields exist, but since userdata.%s is empty, its value is being replaced', newField);
                  end
                  T.userdata = mvField(T.userdata, oldField, newField);
                  if isfield(T.UserDataRules,oldfield);
                     T.UserDataRules = mvField(T.UserDataRules,oldField, newField);
                  end
               end
            else % only the old field exists, so proceed normally
                  T.userdata = mvField(T.userdata, oldField, newField);
                  if isfield(T.UserDataRules,oldfield);
                     T.UserDataRules = mvField(T.UserDataRules,oldField, newField);
                  end
            end
         else
            if newFieldExists  %only the new field exists
               % already renamed. ignore
            else % neither field exists
               if ~failSilently
                 warning('field [%s] does not exist in userdata', oldField);
               end
            end
         end
         function subfield = mvField(subfield, oldField, newField)
            tmp = subfield.(oldField);
            subfield = rmfield(subfield,oldField);
            [subfield.(newField)] = tmp;
         end
      end
      function testUserField(obj, fn, value)
         %testUserField   apply the testing rules to a userdata field
         %  will error with detailed information about how the field fails
         %  validation.
         %
         %  see also setUserDataRule
         if ~isfield(obj.UserDataRules,fn)
            return;
         end
         if ~isfield(obj.userdata,fn)
            if exist('value','var')
               % continue on
            else
               return
            end
         end
         rules = obj.UserDataRules.(fn);
         if ~rules.inUse
            return
         end
         if ~exist('value','var')
            value = obj.userdata.(fn);
         end
         % test the type
         if ~isempty(rules.allowed_type) && ...
               ~isa(value, rules.allowed_type)
            error('User-defined field [%s] requires input of class [%s], but value was a [%s]',...
               fn, rules.allowed_type, class(value));
         end
         % test the number of items
         if ~isempty(rules.min_count) && numel(value) < rules.min_count
            error('User-defined field [%s]: Size of value [%d] is too small. Min allowed size is %d',...
               fn, numel(value), rules.min_count);
         end
         if ~isempty(rules.max_count) && numel(value) > rules.max_count
            error('User-defined field [%s]: Size of value [%d] is too big. Max allowed size is %d',...
               fn, numel(value), rules.max_count);
         end
         % test the value (only works for numeric types)
         if ~isempty(rules.min_value) && value < rules.min_value
            error('User-defined field [%s]: Assigned value [%f] is too small. Min allowed is %f',...
               fn, value, rules.min_value);
         end
         if ~isempty(rules.max_value) && value >rules.max_value
            error('User-defined field [%s]: Assigned value [%f] is too big. Max allowed is %f',...
               fn, value, rules.max_value);
         end
      end
      function T = setUserDataRule(T, fieldname, allowedType, allowedCount, allowedRange)
         %setUserDataRule   create rules to govern data entry into userdata fields.
         % T = T.setUserData(fieldname, classname) will have the class
         % checked each time a value is assigned to the userdata
         % field T.userdata.fieldname.
         %
         % T = T.setUserDataRule(fieldname, classname, count) controls the
         % array size for any assignments to T.userdata.fieldname.  count
         % may be a single number N or a range [nMin nMax]
         % for any value assigned to T.userdata.fieldname,
         %    numel(value) == N or Nmin <= numel(value) <= Nmax
         %
         % T = T.setUserDataRule(fieldname, classname, count, range)
         % for numeric classes, range will specify the min/max values.
         %
         % T = T.setUserDataRule(fieldname) will clear the constraints.
         % examples:
         % T = T.setUserDataRule('height','double',1, [0 inf]); will ensure
         % that height will always be a scalar positive double
         % ...setUserDataRule('code','char',[1 4]) will ensure that any
         % assignments to T.userdata.code will be a string between 1 and 4
         % characters in length.
         %
         % See also testUserField, renameUserField,
         assert(ischar(fieldname))
         if ~exist('allowedType', 'var')
            T.UserDataRules.(fieldname).inUse = false;
            return
         else
            T.UserDataRules.(fieldname).inUse = true;
         end
         %add the rules to UserDataRules
         if ischar(allowedType) || isempty(allowedType)
            T.UserDataRules.(fieldname).allowed_type = allowedType;
         else
            error('AllowedType must be a class name or empty');
         end
         if ~exist('allowedCount', 'var')
            allowedCount = [];
         end
         if isnumeric(allowedCount)
            switch numel(allowedCount)
               case 0
                  T.UserDataRules.(fieldname).min_count = -inf;
                  T.UserDataRules.(fieldname).max_count = inf;
               case 1
                  T.UserDataRules.(fieldname).min_count = allowedCount;
                  T.UserDataRules.(fieldname).max_count = allowedCount;
               case 2
                  T.UserDataRules.(fieldname).min_count = allowedCount(1);
                  T.UserDataRules.(fieldname).max_count = allowedCount(2);
               otherwise
                  error('allowedCount must be either empty, or numeric with 1 or 2 values');
            end
         else
            error('allowedCount must be either empty, or numeric with 1 or 2 values');
         end
         if ~exist('allowedRange', 'var') || strcmp(allowedType,'char')
            allowedRange = [];
         end
         if isnumeric(allowedRange)
            switch numel(allowedRange)
               case 0
                  T.UserDataRules.(fieldname).min_value = [];
                  T.UserDataRules.(fieldname).max_value = [];
               case 2
                  T.UserDataRules.(fieldname).min_value = allowedRange(1);
                  T.UserDataRules.(fieldname).max_value = allowedRange(2);
               otherwise
                  error('allowedRange must be either empty, or [min max]');
            end
         else
            error('allowedRange must be either empty, or [min max]');
         end
      end
      %%
      function [T, I] = sortby(T, criteria)
         %sortby   sort SeismicTraces based on a property
         %  Tsorted = sortby(Tin) sorts by the name (N.S.L.C) in
         %  purely alphabetical order. Depending on the length of each
         %  field, the final results may not be in an expected order.
         %
         %  Tsorted = sortby(Tin, cirt), where CRIT is a valid property
         %
         % [Wsorted, I] = sortby(Win...) will also return the index list so that
         %     Win(I) = Wsorted
         %
         %   Examples:
         %   tSorted = T.sortby('samplerate');  % sort by sample rate
         %   tSorted = T.sortby('firstsample'); % sort by start time
         %   tSorted = T.sortby('station');     % sort by station name
         %   tSorted = T.sortby('duration');    % sort by the duration
         %   tSorted = T.sortby('var');         % sort bythe variance
         %
         %   Generally, if you can request a scalar value from a Seismic
         %   Trace using function A, then 'A' is a valid criteria.
         %
         %   Advanced usage:
         %   sortby also accepts functions, so that the following example is
         %   valid:
         %     myfunc = @(x) median(x) - min(x);
         %     Tsorted = T.sortby(myfunc)
         %
         %
         % see also: sort
         if nargin < 2
            criteria = 'name';
         end
         if ischar(criteria)
            % could be a property or a method
            if ismember(criteria,properties(T))
               if ischar(T(1).(criteria))
               [~,I] = sort({T.(criteria)});
               else
               [~,I] = sort([T.(criteria)]);
               end
            elseif ismethod(T,criteria)
               [~,I] = sort(T.(criteria));
            end
         elseif isa(criteria, 'function_handle')
            [~, I] = sort(criteria(T));
         else
            error('unable to sort');
            % TODO: add ability to sort userdata fields
         end
         % sort by a field
         % [~, I] = sort(get(T,criteria));
         T = T(I);
      end
      function combined_traces = combine (traces)
         %combine   Merge waveforms based on start/end times and ChannelTag
         %  combined_waveforms = combine(traces) combines based on
         %  ChannelTag and start/endtimes.
         %
         % DOES NO OTHER CHECKS
         if numel(traces) == 0  %nothing to do
            combined_traces = traces;
            return
         end
         chaninfo = [traces.channelinfo];
         [uniquechans, ~, chanbin] = unique(chaninfo);
         %preallocate
         combined_traces = repmat(SeismicTrace,size(uniquechans));
         for i=1:numel(uniquechans)
            T = traces(chanbin == i);
            T = timesort(T);
            for j=(numel(T)-1):-1:1
               T(j) = pieceTogether(T(j), T(j+1));
               T(j+1) = [];
            end
            combined_traces(i) = T;
         end
         function Tout = pieceTogether(T1, T2)
            %pieceTogether
            if isempty(T1.data)
               Tout = T2;
               return;
            end;
            dtSecs = (T2.firstsampletime - T1.lastsampletime) * 86400;
            sampRate = T1.samplerate;
            if sampRate > 1
               sampRate = round(sampRate);
            elseif sampRate > 0
               sampRate = 1 / (round(1 / sampRate));
            end
            sampleInterval = 1 ./ sampRate;
            overlaps = (dtSecs - sampleInterval .* 1.25) < 0;
            if overlaps
               Tout = spliceTrace(T1, T2);
            else
               paddingAmount = round((dtSecs * sampRate)-1);
               Tout = spliceAndPad(T1,T2, paddingAmount);
            end
         end
         function T1 = spliceAndPad(T1, T2, nToPad)
            %spliceAndPad   Combine two traces that do not overlap
            if nToPad > 0 && ~isinf(nToPad)
               T1.data = [T1.data; nan(nToPad,1); T2.data];
            else
               T1.data = [T1.data; T2.data];
            end
         end
         function T1 = spliceTrace(T1, T2)
            %spliceTrace   combines two traces that  overlap
            timesToGrab = sum(T1.sampletimes < T2.firstsampletime);
            samplesRemoved = numel(T1.data) - timesToGrab;
            T1.data = [double(extract(T1,'index',1,timesToGrab)); T2.data];
            T1= T1.addhistory('SPLICEPOINT: %s, removed %d points (overlap)',...
               T2.start, samplesRemoved);
         end
         function T = timesort(T)
            [~, I] = sort([T.mat_starttime]);
            T = T(I);
         end
      end
         %TODO: make this SeismicTrace-y.  This is currently written for waveforms
         %TODO: Decide on proper wording! Should this be multiple functions?
      function outW = extract(T, method, startV, endV)
         %extract   creates a waveform with a subset of another's data.
         %   waveform = extract(waveform, 'TIME', startTime, endTime)
         %       returns a waveform with the subset of data from startTime to
         %       endTime.  Both times are matlab formatted (string or datenum)
         %
         %   waveform = extract(waveform, 'INDEX', startIndex, endIndex)
         %       returns a waveform with the subset of data from StartIndex to
         %       EndIndex.  this is roughly equivelent to grabbing the waveform's
         %       data into an array, as in D = get(W,'data'), then returning a
         %       waveform with the subset of data,
         %       ie. waveform = set(waveform,'data', D(startIndex:endIndex));
         %
         %   waveform = extract(waveform, 'INDEX&DURATION', startIndex, duration)
         %       a hybrid method that starts from data index startIndex, and then
         %       returns a specified length of data as indicated by duration.
         %       Duration is a matlab formatted time (string or datenum).
         %
         %   waveform = extract(waveform, 'TIME&SAMPLES', startTime, Samples)
         %       a hybrid method that starts from data index startIndex, and then
         %       returns a specified length of data as indicated by duration.
         %       Duration is a matlab formatted time (string or datenum).
         %
         %   Input Arguments:
         %       WAVEFORM: waveform object        N-DIMENSIONAL
         %       METHOD: 'TIME', or 'INDEX', or 'INDEX&DURATION'
         %           TIME: starttime and endtime are absolute times
         %                   (include the date)
         %           INDEX: startt and endt are the offset (index) within the data
         %           INDEX&DURATION: first value is an offset (index), the next says
         %                           how much data to retrieve...
         %           TIME&SAMPLES: grab first value at time startTime, and grab
         %                         Samplength data points
         %       STARTTIME:  Start time (matlab or text format)
         %       ENDTIME:    End time (matlab or text format)
         %       STARTINDEX: position within data array to begin extraction
         %       ENDINDEX:   final grabbed position within data array
         %       DURATION:   matlab format time indicating duration of data to grab
         %       SAMPLES: the number of data points to grab.
         %
         %   the output waveform will have the new, appropriate start time.
         %   if the times are outside the range of the waveform object, then the
         %   output waveform will contain only the portion of the data that is
         %   appropriate.
         %
         %   *MULTIPLE EXTRACTIONS* can be received if the time values are vectors.
         %   Both starttime/startindex and endtime/endindex/endduration/samples must
         %   have the same number of elements.  In this case the output waveforms
         %   will be reshaped with each waveform represented by row, and each
         %   extracted time represented by column.  that is...
         %
         %  The output of this function, for multiple waveforms and times will be:
         %         t1   t2  t3 ... tn
         %    -----------------------
         %    w1 |
         %    w2 |
         %    w3 |
         %     . |
         %     . |
         %    wn |
         %
         %
         %%   examples:
         %       % say that Win is a waveform that starts 1/5/2007 04:00, and
         %       % contains 1 hour of data at 100 Hz (360000 samples)
         %
         %       % grab samples between 4:15 and 4:20
         %       Wout = extract(Win, 'TIME', '1/5/2007 4:15:00','1/5/2007 4:20:00');
         %
         %       % grab 3 minutes, starting at the 10000th sample
         %       Wout = extract(Win, 'INDEX&DURATION', 10000 , '0/0/0 00:03:00');
         %
         %
         %%     example of multiple extract:
         %  % declare the times we're interested in
         %         firstsnippet = datenum('6/20/2003 00:00:00');
         %         lastsnippet = datenum('6/20/2003 24:00:00');
         %
         %         % divide the day into 1-hour segments.
         %         % 25 pieces. equivelent to 0:1:24, including both midnights
         %         alltimes = linspace(firstsnippet, lastsnippet, 25);
         %         starttimes = alltimes(1:end-1);
         %         endtimes = alltimes(2:end);
         %
         %         % grab each hour of time, and shove it into wHours
         %         wHours = extract(wDay, 'time',starttimes, endtimes);
         %
         %         scaleFactor = 4 * std(double(wDay));
         %         wHours = wHours ./ scaleFactor;
         % %
         %          for n = 1:length(wHours)
         %            wHours(n) = -wHours(n) + n; %add offset for plotting
         %          end
         %          plot(wHours,'xunit','m','b'); %plot it in blue with at nm scaling
         %          axis ([0 60 1 25])
         %          set(gca,'ytick',[0:2:24],'xgrid', 'on','ydir','reverse');
         %          ylabel('Hour');
         %
         %   See also waveform/extract
         %% Set up condition variables, and ensure validity of input
         MULTIPLE_WAVES = ~isscalar(T);
         %if either of our times are strings, it's 'cause they're actually dates
         if ischar(startV)
            startV = datenum(startV);
         end
         if ischar(endV)
            endV = datenum(endV);
         end
         if numel(startV) ~= numel(endV)
            error('Waveform:extract:indexMismatch',...
               'Number of start times (or indexes) must equal number of end times')
         end
         % are we getting a series of extractions from each waveform?
         MULTIPLE_EXTRACTION = numel(endV) > 1;
         if MULTIPLE_WAVES && MULTIPLE_EXTRACTION
            T = T(:);
         end
         %%
         if numel(T)==0 || numel(startV) ==0
            warning('Waveform:extract:emptyWaveform','no waveforms to extract');
            return
         end
         outW(numel(T),numel(startV)) = SeismicTrace;
         for m = 1: numel(startV) %loop through the number of extractions
            for n=1:numel(T); %loop through the waveforms
               inW = T(n);
               myData = inW.data;
               switch lower(method)
                  case 'time'
                     % startV and endV are both matlab formated dates
                     %sampleTimes = get(inW,'timevector');
                     %   ensure the format of our times
                     if startV(m) > endV(m)
                        warning('Waveform:extract:reversedValues',...
                           'Start time prior to end time.  Flipping.');
                        [startV(m), endV(m)] = swap(startV(m), endV(m));
                     end
                     %if requested data is outside the existing waveform, change the
                     %start time, and clear out the data.
                     startsAfterWave = startV(m) > get(inW,'end') ;
                     endsBeforeWave = endV(m) < get(inW,'start');
                     if startsAfterWave || endsBeforeWave
                        myStart = startV(m);
                        myData = [];
                     else
                        %some aspect of this data must be represented by the waveform
                        [myStartI, myStartTime] = time2offset(inW,startV(m));
                        [myEndI] = time2offset(inW,endV(m)) - 1;
                        if isempty(myStartTime)
                           %waveform starts sometime after requested start
                           myStartTime = get(inW,'start');
                           myStartI = 1;
                        end
                        if myEndI > numel(myData)
                           myEndI = numel(myData);
                        end
                        myData = myData(myStartI:myEndI);
                        myStart = myStartTime;
                     end
                  case 'index'
                     %startV and endV are both indexes into the data
                     if startV(m) > numel(myData)
                        warning('Waveform:extract:noDataFound',...
                           'no data after start index');
                        return
                     end;
                     if endV(m) > numel(myData)
                        endV(m) = length(myData);
                        warning('Waveform:extract:truncatingData',...
                           'end index too long, truncating to match data');
                     end
                     if startV(m) > endV(m)
                        warning('Waveform:extract:reversedValues',...
                           'Start time prior to end time.  Flipping.');
                        [startV(m), endV(m)] = swap(startV(m), endV(m));
                     end
                     myData = myData(startV(m):endV(m));
                     sampTimes = inW.sampletimes; % grab individual sample times
                     myStart = sampTimes(startV(m));
                     %index&duration deprecated, since apparently never used
                  case 'time&samples'
                     % startV is a matlab date, while endV is an index into the data
                     sampTimes = get(inW,'timevector'); % grab individual sample times
                     index_to_times = sampTimes >= startV(m); %mask of valid times
                     goodTimes = find(index_to_times,endV(m));%first howevermany of these good times
                     myData = myData(goodTimes); % keep matching samples
                     try
                        myStart = sampTimes(goodTimes(1)); %first sample time is new waveform start
                     catch
                        warning('Waveform:extract:NoDataFound',...
                           'no data');
                        myStart = startV(1);
                     end
                  otherwise
                     error('Waveform:extract:unknownMethod','unknown method: %s', method);
               end
               if MULTIPLE_EXTRACTION
                  outW(n,m).start = myStart;
1000                   outW(n,m).data = myData;
1001                   %outW(n,m) = set(inW,'start',myStart, 'data', myData);
1002                else
1003                   outW(n).start = myStart;
1004                   outW(n).data = myData;
1005                   %outW(n) = set(inW,'start',myStart, 'data', myData);
1006                end
1007             end % n-loop (looping through waveforms)
1008          end % m-loop (looping through extractions)
1009
1010          function  [B,A] = swap(A,B)
1011             %do nothing, just flip inputs & outputs
1012          end
1013       end
1014
1015       %TODO: function ismember
1016
1017       %TODO: function calib_apply
1018       function obj = calibapply(obj)
1019          %calibapply   scale the data by the nominal calibration value
1020          %  scaledtraces = calibapply(traces)
1021          %
1022          %  because of the nature of floating-point operations, it is
1023          %  possible that repeated applications of calibapply and
1024          %  calibunapply would introduce rounding errors
1025          %
1026          %  See also calibunapply
1027          appliedIndex = false(numel(obj));
1028          for n=1:numel(obj)
1029             if ~obj(n).calib.applied
1030                obj(n).data = obj(n).data .* obj(n).calib.value;
1031                obj(n).calib.applied = true;
1032                appliedIndex(n) = true;
1033             else
1034                warning('SeismicTrace:calibapply:alreadyApplied','Calibratin already applied');
1035             end
1036          end
1037
1038          if any(~appliedIndex)
1039             %could use appliedIndex to give more details
1040             warning('SeismicTrace:calibapply:alreadyApplied','Calibration already applied');
1041          end
1042       end
1043       function obj = calibunapply(obj)
1044          %calibunapply  remove calibration from the data (divide by it)
1045          %  unscaledtraces = calibunapply(traces)
1046          %
1047          %  because of the nature of floating-point operations, it is
1048          %  possible that repeated applications of calibapply and
1049          %  calibunapply would introduce rounding errors
1050          %
1051          %  See also calibapply
1052          unapplied = false(numel(obj));
1053          for n=1:numel(obj)
1054             if obj(n).calib.applied
1055                obj(n).data = obj(n).data ./ obj(n).calib.value;
1056                obj(n).calib.applied = false;
1057                unapplied(n) = true;
1058             end
1059          end
1060          if any(~unapplied)
1061             %could use appliedIndex to give more details
1062             warning('SeismicTrace:calibunapply:notApplied','Calibration was not applied');
1063          end
1064       end
1065       %TODO: function calib_remove
1066
1067       %% history-related functions
1068       function T = addhistory(T, whathappened,varargin)
1069          %addhistory   function in charge of adding history to a waveform
1070          %   trace = trace.addhistory(whathappened);
1071          %   trace = trace.addhistory(formatString, [variables...])
1072          %
1073          %   The second way of using addhistory follows the syntax of fprintf
1074          %
1075          %   Input Arguments
1076          %       WAVEFORM: a SeismicTrace object
1077          %       WHATHAPPENED: absolutely anything.  Really.
1078          %
1079          %   AddHistory appends not only what happened, but also keeps track of WHEN
1080          %   it happened.
1081          %
1082          %   example
1083          %       T = SeismicTrace; %create a blank trace
1084          %       T = T.addhistory('the following procedures done by DoIt.m');
1085          %       N = 1; M = 'Today'
1086          %       T = T.addhistory('this is sample #%d date:%s',N,M);
1087          %       % what is actually added: "this is sample #1 date:Today"
1088          %
1089          % See also SeismicTrace.history, fprintf
1090
1091          if nargin > 2,
1092             whathappened = sprintf(whathappened, varargin{:});
1093          end
1094          modtime = now;
1095          for N = 1 : numel(T);
1096             %History is stored in a cell, the format of which is [WHAT, WHEN]
1097                T(N).history(end+1).what = whathappened;
1098                T(N).history(end).when = modtime;
1099          end
1100       end
1101       function T = clearhistory(T)
1102          %clearhistory   reset history of a waveform
1103          %   trace = trace.clearhistory
1104          %   clears the history, leaving it blank
1105          %
1106          % See also SeismicTrace.addhistory SeismicTrace.history.
1107          for N = 1: numel(T)
1108             T(N).history= T(N).history([]);
1109          end
1110       end
1111       function [myhist] = get.history(t)
1112          %history   retrieve the history of a waveform object
1113          %   myhist = trace.history
1114          %       returns a struct describing what's been done to this trace
1115          %   myhist = trace.history(N)
1116          %       get Nth element from the history.  End works,too!
1117          % See also SeismicTrace.addhistory, SeismicTrace.clearhistory
1118          myhist = t.history;
1119       end
1120
1121       %% display functions - contained in external files
1122       disp(T)
1123       varargout = plot(T, varargin)
1124       linkedplot(T, alignTraces)
1125       varargout = legend(T, varargin)
1126
1127       %% conversion functions
1128       function W = waveform(T)
1129          %waveform   convert SeismicTrace into waveform
1130          %   w = waveform(Trace) converts a SeismicTrace into a waveform.
1131          %
1132          %  See also waveform, SeismicTrace
1133
1134          W = repmat(waveform,size(T));
1135          for n=1:numel(T)
1136             W(n) = set(W(n),'channelinfo',T(n).channelinfo,...
1137                'freq', T(n).samplerate,...
1138                'data',T(n).data,...
1139                'units',T(n).units,...
1140                'start',T(n).firstsampletime);
1141             ufields = fieldnames(T(n).userdata);
1142             for z = 1:numel(ufields)
1143                W(n) = addfield(W(n), ufields{z}, T(n).userdata, T(n).userdata.(ufields{z}));
1144             end
1145          end
1146       end
1147       function CT = ChannelTag(T)
1148          %ChannelTag   Convert SeismicTrace into ChannelTag
1149          %   ct = ChannelTag(trace)
1150          %
1151          %   see also ChannelTag, SeismicTrace
1152          CT = reshape([T.channelinfo], size(T));
1153       end
1154    end
1155    methods(Static)
1156       function T = toTrace(item, itemlabel, conversionfunction)
1157          %toTrace   convert anything into traces
1158          % conversion functions exist outside SeismicTrace classdef so that
1159          % adding/removing/changing the conversion functions do not affect
1160          % this class
1161          % some envisioned examples
1162          % T = toTrace(X , 'fdsn_trace');
1163          % T = toTrace(X, 'fdsn_sac');
1164          % T = toTrace(X , 'winston');
1165          % T = toTrace(X , 'miniseed');
1166          % T = toTrace(X , 'seisan');
1167          % T = toTrace(X , 'seisan');
1168          % T = toTrace(X , 'waveform');
1169
1170          %TODO: either flesh this out, or remove it
1171
1172          persistent converters
1173          if isempty(converters)
1174             converters = [];
1175             %fill converters based on a directory/package
1176          end
1177       end
1178
1179       function T = syntheticdata(names, starts, ends, samplerate)
1180          %syntheticdata   Crates a SeismicTrace filled with synthetic data
1181          %   T = syntheticdata(names, starts, ends, samplerate)
1182          %
1183          %   See also: randn, sin, SeismicTrace
1184          if ~exist('names','var') || isempty(names)
1185             names = 'NT.STA.LO.CHA'; end
1186          if ~exist('starts','var') || isempty(starts)
1187             starts = datenum([2015 09 23 15 45 0]);
1188          end
1189          if ~exist('ends','var') || isempty(ends)
1190             ends = starts + datenum([0 0 0 0 10 0]); % 10 minutes of data
1191          end
1192          if ~exist('samplerate','var') || isempty(samplerate)
1193             samplerate = 20;
1194          end
1195          warning('Creating a SeismicTrace using a noisy sine wave');
1196          if ischar(names)
1197             names = {names};
1198          end
1199          if ~exist('starts','var')
1200             % build T from names
1201          else
1202             T = SeismicTrace;
1203             T.samplerate = samplerate;
1204             T = repmat(T, numel(names), numel(starts));
1205
1206             for n=1:numel(names)
1207                [T(n,:).name] = deal(names(n));
1208             end
1209             for n=1:numel(starts)
1210                [T(:,n).start] = deal(starts(n));
1211                nSeconds = (ends(n) - starts(n)) * 86400;
1212                nsamples = nSeconds * samplerate;
1213                D = sin((-nsamples: 2 : nsamples-1) / 600) * 10 + randn(size(-nsamples: 2 : nsamples-1));
1214                [T(:,n).data] = deal(D);
1215             end
1216             % now fill with bogus data
1217          end
1218       end
1219
1220       function T = retrieve(ds, names, starts, ends, miscfilters)
1221          %retrieve   Get a SeismicTrace from external data source
1222          %
1223          % UNDER CONSTRUCTION. for now, this is a wrapper around waveform.
1224          % it will use the waveform class to get data, and will then
1225          % convert to traces and pass that along.
1226          %
1227          % T = retrieve(datasouce, names, starts, ends, miscfilters)
1228          % names are channeltags OR N.S.L.C strings.
1229          % in future, this will be able to accept bulkdataselect (BDS)-type requests
1230          %    if BDS type, then starts, ends, miscfilters ignored.
1231          % for now
1232          % starts is either text, or array fo start times
1233          % find data pointed to by ds, names, starts, ends
1234          % convertToTraces
1235          % return the traces
1236
1237          if isa(names,'cell') || isa(names,'char')
1238             names = ChannelTag.array(names);
1239          end
1240          w = waveform(ds, names, starts, ends);
1241          T = SeismicTrace(w);
1242       end
1243    end %static methods
1244 end