Description of traceToWaveform
Home > GISMO > core > dev > +dataretrieval > @antelopesource > traceToWaveform.m
traceToWaveform
PURPOSE
traceToWaveform converts traceobjects to waveforms
SYNOPSIS
function allw = traceToWaveform(obj)
DESCRIPTION
traceToWaveform converts traceobjects to waveforms
    w = traceToWaveform(antelopesource)
 Note: this may return multiple waveform objects, depending upon
 how many segments and/or scnl's.
CROSS-REFERENCE INFORMATION
This function calls:
disp CATALOG.DISP Display Catalog object
get GET - Get correlation properties
set SET Set properties for correlation object
disp DISP Datasource disp overloaded operator
get
get GET: Get drumplot properties
set SET: Set drumplot properties
disp DISP - Filterobject disp overloaded operator
get GET - Get filterobject properties
set SET - Set filterobject properties
disp DISP - scnl disp overloaded operator
get GET for the scnl object
set SET - Set properties for scnlobject
disp DISP - spectralobject disp overloaded operator
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
disp DISP Display threecomp object
get GET Get threecomp object properties.
set SET inserts properties for threecomp object
abs ABS Absolute value for the waveform object
disp DISP Waveform disp overloaded operator
get GET Get waveform properties
set SET Set properties for waveform object(s)
setsamples setsamples replaces selected data samples with values.
segtype2units segtype2units retrieves unit and description based on the segtype code
disp CORRELATION/DISPLAY Command window display of a correlation object
get GET - Get correlation properties
set SET Set properties for correlation object
disp disp Display information about SeismicTrace(s)
disp DISP: Helicorder disp overloaded operator
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
load_antelope_old load a waveform from antelope
load_antelope_workaround load a waveform from antelope
antelopesource
SUBFUNCTIONS
function w = waveformMetadata(w, trpointer)
function spikes = findSpikes(trpointer)
function allw = applyCalibrationsToAll(trpointer, allw)
SOURCE CODE
function allw = traceToWaveform(obj)
   %traceToWaveform converts traceobjects to waveforms
   %    w = traceToWaveform(antelopesource)
   %
   % Note: this may return multiple waveform objects, depending upon
   % how many segments and/or scnl's.
   wBlank = antelopesource.blankWaveformWithCalib();
   try
      traceCount = dbnrecs(obj.trpointer);
      assert(traceCount > 0);
   catch er
      disp('traceToWaveform: No traces found to convert');
      allw = wBlank([]);
      return
   end
   % preallocations
   spikes(traceCount).mask = false; %used to track data spikes & inf values
   allw = repmat(wBlank,traceCount,1);
   % LOOP twice through segments represented by this trace object
   % 1st loop: find signal spikes, and get header info.
   for seg = 1:traceCount
      obj.trpointer.record = seg - 1;
      allw(seg) = waveformMetadata(wBlank, obj.trpointer);
      spikes(seg).mask = findSpikes(obj.trpointer);
   end
   allw = applyCalibrationsToAll(trpointer, allw);
   % 2nd loop: assign data to the waveforms.
   replaceWithNan = @(W,BAD) setsamples(W, BAD.mask, nan);
   for seg = 1:traceCount
      obj.trpointer.record = seg - 1;
      allw(seg) = set(allw(seg), 'data', trextract_data(obj.trpointer));
      allw(seg) = replaceWithNan(allw(seg), spikes(seg));
   end
end
function w = waveformMetadata(w, trpointer)
   s = db2struct(trpointer); %do once, get one for each segment
   [sunit, ~] = segtype2units(s.segtype);
   w = set(w, ...
      'station', s.sta, ...
      'channel', s.chan, ...
      'network', s.net, ...
      ...'location', s.loc, ... % unknown if 'loc' really is a field
      'start', datenum(epoch2str(s.time,'%Y-%m-%d %H:%M:%S.%s')), ...
      'freq', s.samprate, ...
      'units', sunit, ...
      'calib', s.calib);
end
function spikes = findSpikes(trpointer)
      % data spikes must be known PRIOR to applying calibration
      maxAllowableSignal = (realmax('single') * 1e-2);
      data = trextract_data(trpointer);
      spikes = (abs(data) >= maxAllowableSignal) | isinf(data);
end
function allw = applyCalibrationsToAll(trpointer, allw)
   % now, apply calibrations to all traces at once
   trapply_calib(trpointer);
   hasCalibs = get(allw,'calib') ~= 0;
   allw(hasCalibs) = set(allw(hasCalibs),'calibration_applied','YES');
end