Description of autoscale
Home > GISMO > core > dev > @TraceData > autoscale.m
autoscale
PURPOSE
autoscale automatically determine correct y-units for plotting
SYNOPSIS
function newunit = autoscale(axishandle, oldunit)
DESCRIPTION
autoscale   automatically determine correct y-units for plotting
  newunit = autoscale(axishandle, oldunit) autoscales the data in an
  axis by considering its range and units, then determines a new unit.
CROSS-REFERENCE INFORMATION
This function calls:
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
set SET Set properties for correlation object
get
get GET: Get drumplot properties
set SET: Set drumplot properties
get GET - Get filterobject properties
set SET - Set filterobject properties
get GET for the scnl object
ismember ISMEMBER for scnlobjects
set SET - Set properties for scnlobject
get GET - Get properties for spectralobject
set SET - Set properties for spectralobject
get GET Get threecomp object properties.
isempty ISEMPTY Display threecomp object
set SET inserts properties for threecomp object
abs ABS Absolute value for the waveform object
get GET Get waveform properties
isempty ISEMPTY returns TRUE if waveform contains no data
ismember ISMEMBER waveform implementation of ismember
max MIN Largest value of a waveform.
set SET Set properties for waveform object(s)
find INDEX = FIND(c,'CLUST',WHICH_CLUSTER)
get GET - Get correlation properties
set SET Set properties for correlation object
get GET: Get helicorder properties
set SET: Set helicorder properties
This function is called by:
TraceData
SUBFUNCTIONS
function [myunit, unitLength] = extractUnit(unit)
function v = unit2val(myunit)
function [unit, unitval] = val2unit(v)
SOURCE CODE
function newunit = autoscale(axishandle, oldunit)
   %autoscale   automatically determine correct y-units for plotting
   %  newunit = autoscale(axishandle, oldunit) autoscales the data in an
   %  axis by considering its range and units, then determines a new unit.
   %TODO: (maybe) make this TraceData dependent, and not axis dependent.
   if iscell(oldunit), oldunit = oldunit{1}; end;
   ah = axishandle;
   % yRange = @(ax) max(get(ax,'ydata')) - min(get(ax,'ydata'));
   % yMaxrange = max(arrayfun(yRange,ah)); % greatest data range from axis
   yFarthestFrom0 = @(ax) max(abs(get(ax,'ydata')));
   ydatamax = max(arrayfun(yFarthestFrom0, ah)); %overal maximum from axis
   [nominatorUnit, nominatorUnitLength] = extractUnit(oldunit);
   oldUnitVal = unit2val(nominatorUnit);
   if isempty(oldUnitVal),
      newunit= oldunit;
      return
   end
   trueScale = oldUnitVal .* ydatamax;  % ex. 1 mm == 0.001
   [newunit, newUnitVal] = val2unit(trueScale);
   oldunit(1:nominatorUnitLength) = [];
   newunit = [newunit, oldunit];
   set(ah,'ydata',get(ah,'ydata').*(oldUnitVal./newUnitVal));
   function [myunit, unitLength] = extractUnit(unit)
      unitLength = sum(isletter(unit(1:2)));
      myunit = unit(1:unitLength);
   end
   function v = unit2val(myunit)
      %unit2val   returns the associated multiplier for a unit
      %  unit2val('m') % returns 1
      %  unit2val('nm') % returns 1.0e-9
      % expects only the nominator unit eg. 'nm'
      knownunits = {'pm','nm', '\mum', 'mm','cm','m','km'};
      knownvals = 10.^[-12, -9, -6, -3, -2, 0, 3];
      whichunit = ismember(knownunits,myunit);
      if any(whichunit)
         v = knownvals(whichunit);
      else
         v = []; %not found!
      end
   end
   function [unit, unitval] = val2unit(v)
      %val2unit   returns the unit and multiplier for a value
      %  [a,b] = unit2val(0.0023) % a='mm', b=1.0e-3
      knownunits = {'pm','nm','\mum','mm','cm','m','km'};
      searchvals = 10.^[-inf, -9, -6, -3, -2, 0, 3]; % tweak this part if anything
      knownvals =  10.^[-12, -9, -6, -3, -2, 0, 3];
      whichunit = find((v - searchvals) >= 0, 1, 'last');
      unit = knownunits(whichunit);
      unitval = knownvals(whichunit);
   end
end